### ISSUE TITLE
Trezor with pin and passphrase enabled, login not possible

### ISSUE THREAD

**Issue by paulpw** [paritytech/parity#6883] opened 2017-10-24 22:23 UTC
> I'm running:
>Parity//v1.8.0-beta-9882902-20171015/x86_64-linux-gnu/rustc1.20.0
> - **Parity version**:   
> - **Operating system**: / ubuntu  16.10
>- installed via deb package
- Connect trezor, pin pad appears on parity and trezor screen.
- Enter correct pin, parity responds "wrong pin try again",  while on trezor screen 
"please enter your passphrase using computers's keyboard"
- enter passphrase but no response from parity.

I've tried entering an incorrect pin and I get the same response from parity(correctly) but
trezor screen responds correctly with random numbered keypad display and "please enter current pin"

**Comment by ncsolar** [comment] 2017-10-25 05:04
See #6784 passphrase not available last time i checked

**Comment by Office-Julia** [comment] 2017-10-28 07:39
Hello. Let me assist with your issue further.

Please note version 1.8.1 is not the latest one.
Our latest Beta release is 1.8.2,
and latest stable release is 1.7.8.
Please kindly let us know if you tried to install these versions and if the problem happens there again?

Reference: https://github.com/paritytech/parity/releases

**Comment by 5chdn** [comment] 2017-10-29 08:02
Duplicate of #6784

**Closed by 5chdn** 2017-10-29 08:02 UTC
Labels: F3-annoyance, M7-ui, P5-sometimesoon, Z0-duplicate
