### ISSUE TITLE
Crash after sleep mode on windows

### ISSUE THREAD

**Issue by Grix** [paritytech/parity#6230] opened 2017-08-04 10:47 UTC
The parity client consistently crashes after resuming windows from sleep mode. Often it crashes silently, but sometimes I get a message like this: 

![capture](https://user-images.githubusercontent.com/1517713/28965744-e713ac02-7912-11e7-8977-72b58eaf59bd.PNG)

I have windows 10 Pro 64-bit, Parity//v1.7.0-beta-5f2cabd-20170727/x86_64-windows-msvc/rustc1.18.0

**Comment by 5chdn** [comment] 2017-08-04 10:49
Could you open a command prompt (start -> `cmd`), and run parity.exe manually from within that prompt:

    cd "C:\Program Files\Ethcore\Parity\"
    parity.exe

And try to reproduce this issue and post the logs / screenshot here?

**Comment by Grix** [comment] 2017-08-04 10:55
Hi, it crashed without printing any errors to the console:

![capture](https://user-images.githubusercontent.com/1517713/28965947-e7e494ce-7913-11e7-8693-b88aa66b687c.PNG)

But I tried debugging it in VS from the message you see above, and the debug output said:
"The thread 0x10bc has exited with code 0 (0x0).
HEAP[parity.exe]: Invalid address specified to RtlValidateHeap( 000001896F1B0000, 0000018971488AC0 )
parity.exe has triggered a breakpoint."

**Comment by 5chdn** [comment] 2017-08-22 13:33
Do you mind disabling this "application stopped working" dialogue in Windows? Because the Parity process is still running in the background and Windows is preventing to show what's going on / or what's _not_.

**Comment by Grix** [comment] 2017-08-22 13:42
Ah, when I disable the error and try again, it shows this message:

`thread 'IO Worker #1' panicked at 'assertion failed: `(left == right)` (left: `1015`, right: `0`)', ethcore\src\miner\transaction_queue.rs:398`

**Comment by 5chdn** [comment] 2017-08-22 13:47
Interesting. Could you post the full back trace from the terminal?

**Comment by Grix** [comment] 2017-08-22 14:03
Excuse my ignorance, how do I do that?

**Comment by 5chdn** [comment] 2017-08-22 14:45
The message `thread 'IO Worker #1' panicked at ' ... ` should be followed by multiple lines of information. If you could just paste them all here, thanks :)

**Comment by Grix** [comment] 2017-08-22 15:06
That was the last line it printed... There was no other info relating to the crash.

And just now I tried multiple times to reproduce it, but I can't get that error to show again. I tried six times: two times I got the error message I screenshot in OP, and four times it crashed completely silently (or maybe the "stopped working" message would have been shown if I hadn't disabled it). So I apologize for not being able to give much info. All that happens consistently seems to be the actual crashing, but the error messages and logging that accompanies it is all over the place...

**Comment by DanielSel** [comment] 2017-11-07 00:19
I found the reason for the crash. It is cause by an overflow while parsing an invalid device path under windows.

See paritytech/libusb-sys#1

**Comment by 5chdn** [comment] 2017-11-13 10:36
Thanks.  I guess we need to see this merged into https://github.com/dcuddeback/libusb-sys first.

**Comment by arkpar** [comment] 2017-11-16 17:32
Our version is based on some obscure fork of libusb that supports windows hotplug. It is not really maintained anymore as far as I can tell. Bumping libusb in this repo should be enough to close this issue.

**Comment by folsen** [comment] 2018-05-19 08:38
@niklasad1 What's the status of the issue above, have we done anything that would affect this bug, i.e updated or removed libusb or anything else? I am inclined to just close this issue.

**Comment by Grix** [comment] 2018-05-30 11:19
It appears to maybe have been fixed. I tried two times to restart from sleep mode and parity resumed normally both times.

**Comment by folsen** [comment] 2018-05-30 11:44
@Grix Thanks, we've made quite a lot of changes over the past 6 months on stuff that this could be related to (like libusb) so hopefully it's fixed :) Closing.

**Closed by folsen** 2018-05-30 11:44 UTC
Labels: F1-panic, M4-core, P2-asap
