### ISSUE TITLE
App crashes using non-ascii path on windows

### ISSUE THREAD

**Issue by sant9ga** [paritytech/parity#2215] opened 2016-09-20 17:13 UTC
App closes in 1-2 sec after start. If start with .bat and pause, then I could see the error:
![image](https://cloud.githubusercontent.com/assets/11545131/18680966/8f1b8ca2-7f6e-11e6-9c34-d827271b291a.png)

**Comment by rphmeier** [comment] 2016-09-20 17:22
Probably unicode-related? Not sure if rocksdb can handle `UTF-8` paths.

**Comment by sant9ga** [comment] 2016-09-20 17:39
Maybe. May I manually lead it to another folder?

**Comment by rphmeier** [comment] 2016-09-20 18:34
@sant9ga Yeah, try running with `parity -d /path/to/ascii/folder` as a workaround.

**Comment by sant9ga** [comment] 2016-09-20 20:05
I've already renamed my username's folder into english, it helped!
But thanks for the responds!

**Comment by arkpar** [comment] 2016-09-21 04:41
The problem is that rocksdb uses non-unicode windows API. (`CreateFileA` but not `CreateFileW`) So all the paths and error messages need to be converted between utf-8 and local codepage with `MultiByteToWideChar` and friends

**Comment by 5chdn** [comment] 2017-05-09 11:03
This issue is labelled with _bug_: The client fails to follow expected behavior; and is inactive for more than 6 months. It's neither assigned nor linked to a milestone.

Please, decide on a deadline and assign this ticket to a developer within 7 days or close it if fixed otherwise.

**Comment by grbIzl** [comment] 2017-06-15 11:25
https://github.com/arkpar/rust-rocksdb/pull/10/ created in order to address the issue

**Comment by grbIzl** [comment] 2017-06-15 15:37
Sorry, correct PR is https://github.com/paritytech/rust-rocksdb/pull/7

**Comment by arkpar** [comment] 2017-06-22 13:33
Fixed by #5905

**Closed by arkpar** 2017-06-22 13:33 UTC
Labels: F2-bug, M4-core
