### ISSUE TITLE
State root not found for block #0

### ISSUE THREAD

**Issue by ipahomov** [paritytech/parity#6088] opened 2017-07-19 07:46 UTC
Parity 1.6.9
OS: Windows 10 x64, Kubuntu 16.04 x64
After installing parity, an exception is thrown when trying to start on Kovan:

```
parity --chain kovan
2017-07-19 09:35:49  Starting Parity/v1.6.9-stable-d44b008-20170716/x86_64-linux-gnu/rustc1.18.0
2017-07-19 09:35:49  State DB configuration: fast
2017-07-19 09:35:49  Operating mode: active
2017-07-19 09:35:49  Configured for Kovan using AuthorityRound engine
2017-07-19 09:35:50  State root not found for block #0 (a3c565fc15c7478862d50ccd6561e3c06b24cc509bf388941c25ea985ce32cb9)
thread 'main' panicked at 'State root of best block header always valid.: InvalidStateRoot(2480155b48a1cea17d67dbfdfaafe821c1d19cdd478c5358e8ec56dec24502b2)', /checkout/src/libcore/result.rs:859
stack backtrace:
   0: <unknown>
   1: <unknown>
   2: <unknown>
   ...
```
For example, with a 'ropsten' working fine.

Running only when adding command: --pruning archive

**Comment by euclidessilva** [comment] 2017-07-20 14:59
i have the same problem

**Comment by MicahZoltu** [comment] 2017-07-20 17:44
Parity Version: `Parity//v1.6.6-beta-8c6e3f3-20170411/x86_64-windows-msvc/rustc1.16.0`

`parity --chain=kovan`
```
2017-07-20 10:38:19  State root not found for block #0 (a3c565fc15c7478862d50ccd6561e3c06b24cc509bf388941c25ea985ce32cb9)
thread 'main' panicked at 'State root of best block header always valid.: InvalidStateRoot(2480155b48a1cea17d67dbfdfaafe821c1d19cdd478c5358e8ec56dec24502b2)', C:\bot\slave\stable-dist-rustc-win-msvc-64\build\src\libcore\result.rs:868
stack backtrace:
   0:     0x7ff72e286f58 - hid_error
   1:     0x7ff72e286464 - hid_error
   2:     0x7ff72e289e1d - hid_error
   3:     0x7ff72e289cb8 - hid_error
   4:     0x7ff72e289bd4 - hid_error
   5:     0x7ff72e289b69 - hid_error
   6:     0x7ff72e294077 - hid_error
   7:     0x7ff72dd7402a - <unknown>
   8:     0x7ff72de84ebc - hid_error
   9:     0x7ff72de8453a - hid_error
  10:     0x7ff72de8ea82 - hid_error
  11:     0x7ff72de9c450 - hid_error
  12:     0x7ff72de7cbcc - hid_error
  13:     0x7ff72de7830e - hid_error
  14:     0x7ff72de9d60a - hid_error
  15:     0x7ff72dc512b9 - <unknown>
  16:     0x7ff72dc4f09c - <unknown>
  17:     0x7ff72da78a79 - <unknown>
  18:     0x7ff72da97fc1 - <unknown>
  19:     0x7ff72da9eee7 - <unknown>
  20:     0x7ff72daa16c9 - <unknown>
  21:     0x7ff72e28b581 - hid_error
  22:      0x25f2517f63f - <unknown>
  23:  0x10001fab56a69d7 - <unknown>
  24: 0xfffffffffffffffd - <unknown>
  25:     0x7ff72daa03ee - <unknown>
  26:       0xe3a6b5febf - <unknown>
  27:     0x7ff72e28a40a - hid_error
  28:      0x25f0000001c - <unknown>
```

If I run `parity db kill --chain=kovan` and try again I get this error:
```
2017-07-20 10:39:22  Syncing snapshot 0/20        #0    2/ 3/25 peers     7 KiB db    7 KiB chain  0 bytes queue   10 KiB sync  RPC:  1 conn,  4 req/s,  35 µs
2017-07-20 10:39:27  Syncing snapshot 7/20        #0    2/ 3/25 peers     7 KiB db    7 KiB chain  0 bytes queue   10 KiB sync  RPC:  1 conn,  2 req/s,  40 µs
2017-07-20 10:39:32  Syncing snapshot 14/20        #0    2/ 3/25 peers     7 KiB db    7 KiB chain  0 bytes queue   10 KiB sync  RPC:  1 conn,  3 req/s,  37 µs
2017-07-20 10:39:36  Encountered error during block restoration: RlpExpectedToBeData
2017-07-20 10:39:38  Syncing snapshot 19/20        #0    0/ 3/25 peers     1 KiB db    7 KiB chain  0 bytes queue   10 KiB sync  RPC:  1 conn,  2 req/s,  38 µs
thread 'IO Worker #1' panicked at 'OpenBlock::new only fails if parent state root invalid; state root of best block's header is never invalid; qed: Trie(InvalidStateRoot(2480155b48a1cea17d67dbfdfaafe821c1d19cdd478c5358e8ec56dec24502b2))', C:\bot\slave\stable-dist-rustc-win-msvc-64\build\src\libcore\result.rs:868
stack backtrace:
   0:     0x7ff72e286f58 - hid_error
   1:     0x7ff72e286464 - hid_error
   2:     0x7ff72e289e1d - hid_error
   3:     0x7ff72e289cb8 - hid_error
   4:     0x7ff72e289bd4 - hid_error
   5:     0x7ff72e289b69 - hid_error
   6:     0x7ff72e294077 - hid_error
   7:     0x7ff72dd7417a - <unknown>
   8:     0x7ff72de9e46b - hid_error
   9:     0x7ff72decdf9b - hid_error
  10:     0x7ff72dedbbdb - hid_error
  11:     0x7ff72de55fad - <unknown>
  12:     0x7ff72de559fb - <unknown>
  13:     0x7ff72dd07d5f - <unknown>
  14:     0x7ff72e28b581 - hid_error
  15:      0x1dc9762322f - <unknown>
  16:  0x10000ffffffffff - <unknown>
  17: 0xfffffffffffffffd - <unknown>
  18:      0x1dc95a1e22f - <unknown>
  19:        0xf36affbbf - <unknown>
  20:     0x7ff72dd84c2a - <unknown>
  21:      0x1dc959a5a5f - <unknown>
  22:      0x1dc95a1df6f - <unknown>
```

**Comment by MicahZoltu** [comment] 2017-07-20 17:44
I can confirm that running with `--pruning archive` works around the issue.

**Comment by keorn** [comment] 2017-07-20 17:55
Last mentioned issue with `RlpExpectedToBeData` is duplicate of https://github.com/paritytech/parity/issues/6090

**Comment by euclidessilva** [comment] 2017-07-21 14:03
--pruning archive works for me

**Closed** 2017-07-21 15:24 UTC
Labels: F2-bug, M4-core
