### ISSUE TITLE
libssl1.0.2 not acceptable to 1.7.0 .deb package

### ISSUE THREAD

**Issue by stone212** [paritytech/parity#6528] opened 2017-09-16 06:40 UTC
_Before filing a new issue, please **provide the following information**._

> I'm running:
>
> - **Parity version**: 1.7.0
> - **Operating system**: Debian 9 stretch
> - **And installed**:  binaries

_Your issue description goes here below. Try to include **actual** vs. **expected behavior** and **steps to reproduce** the issue._

Failure running:

`# dpkg -i parity_1.7.0_amd64.deb`

Error: 

```
dpkg: dependency problems prevent configuration of parity:
 parity depends on libssl1.0.0 (>= 1.0.0); however:
  Package libssl1.0.0 is not installed.
```

The system does have libssl1.0.2 installed.  That is the default for Debian 9 stable.  But Parity does not know to look for it.

---

**Comment by 5chdn** [comment] 2017-09-17 08:04
Yeah, this needs to be fixed. Duplicate of #5893

cc @paritytech/ci

**Closed by 5chdn** 2017-09-17 08:04 UTC
