### ISSUE TITLE
Large disk space usage when syncing

### ISSUE THREAD

**Issue by gaoxiangxyz** [paritytech/parity#7156] opened 2017-11-28 09:55 UTC
> I'm running:
>
> - **Which Parity version?**: 1.8.2
> - **Which operating system?**: Windows
> - **How installed?**: via installer
> - **Are you fully synchronized?**: yes
> - **Did you try to restart the node?**: yes

The usage of disk space raise up to around 1TB after it syncing around 10 days and the parity occurs error because disk space is full. But after restart the node, the usage of disk space reduce to around 200GB. 

config file:
```
# This config should be placed in following path:
#   %AppData%\Parity\Ethereum\config.toml

[parity]
# Blockchain and settings will be stored in d:\parity\mainnet.
base_path = "D:\\deploy\\parity\\mainnet"
# Parity databases will be stored in d:\parity\mainnet\chains.
db_path = "D:\\deploy\\parity\\mainnet\\chains"
# Your encrypted mainnet keys will be stored in d:\parity\mainnet\keys.
keys_path = "D:\\deploy\\parity\\mainnet\\keys"
# You will be identified as 'mainnet' amongst other nodes..
identity = "ws_mainnet"

[ui]
# You will need to unlock accounts manually if Wallet is disabled.
disable = true

[network]
# Disable Warp Sync
no_warp = true

[ipc]
disable = true

[rpc]
# Only selected APIs will be exposed over this interface.
apis = ["web3", "eth", "net", "parity", "traces", "rpc", "personal", "parity_set"]

[websockets]
# UI won't work and WebSockets server will be not available.
disable = true

[secretstore]
# You won't be able to encrypt and decrypt secrets.
disable = true

[ipfs]
# You won't be able to hash-query blockchain data.
disable = true

[footprint]
# Keep all state trie data. No pruning.
pruning = "archive"
# Compute and Store tracing data. (Enables trace_* APIs).
tracing = "on"
# Increase performance on HDD.
db_compaction = "hdd"

[misc]
# Logs will be stored at d:\parity\mainnet\parity.log.
log_file = "D:\\deploy\\parity\\mainnet\\parity.log"
# Enables colors in logs.
color = false
```

**Comment by 5chdn** [comment] 2017-11-28 10:07
Duplicate of #6280 :)

**Closed by 5chdn** 2017-11-28 10:07 UTC
