### ISSUE TITLE
UX: "Export accounts" feature is no backup

### ISSUE THREAD

**Issue by 9798000** [paritytech/parity#6025] opened 2017-07-10 04:31 UTC
Hello all,

I deleted my account to test something if I can backup......, and now I only have a  JSON file name of accounts.json.
But when I Add account  ---> from JSON  FILE ........it failed....
It shows [-32023] Could not create account.
My json files edit as txt like this:

{
    "0x002cFfCFb906596ABC4d653bE202f7bB0fF841fD": {
        "name": "9798000",
        "uuid": "b********5-d363-75a9-c0d4-d**********7",
        "meta": {
            "passwordHint": "",
            "timestamp": 1***********0
        },
        "address": "0x002cFfCFb906596ABC4d653bE202f7bB0fF841fD"
    }
}

Can anyone help me? I can't find my accout again .......

Thanks
![help1](https://user-images.githubusercontent.com/30035397/28003194-55386cc6-656e-11e7-97b8-9d6a7644f9fc.png)

**Comment by MIGUELWAXX** [comment] 2017-07-10 04:32
mememe

**Comment by 9798000** [comment] 2017-07-10 04:39
@MIGUELWAXX Can you help me ,thanks a lot!!!

**Comment by 5chdn** [comment] 2017-07-10 05:55
@MIGUELWAXX The `accounts.json` file does not contain your keys. How did you delete your account? Do you have backups?

**Comment by 9798000** [comment] 2017-07-10 06:15
@5chdn 
Before  deleted,  I thought the json file  is the backups....it's seem I am wrong.
I had nothing now , just the json file,  my name, and my password.
It's mean I lost my account now????

**Comment by 5chdn** [comment] 2017-07-10 07:43
Did you write down your recovery phrase? You can only recover your account with the recovery phrase (11+ words) or the private key file (JSON). Did you use the 'delete' option in the wallet? Or did you manually remove the private keys? What system are you on?

Labeling with security as this is a serious usability issue.

**Comment by tomusdrw** [comment] 2017-07-10 07:51
@5chdn The issue is already addressed in 1.7 - "Export accounts" is gone and "Backup accounts" is introduced: #4824

**Comment by 5chdn** [comment] 2017-07-10 08:17
Fine.

**Closed** 2017-07-24 08:23 UTC
Labels: F3-annoyance, M7-ui
