### ISSUE TITLE
Installation fails

### ISSUE THREAD

**Issue by pannous** [paritytech/parity#4939] opened 2017-03-17 10:13 UTC
```
Unpacking parity (1.6.3) ...
dpkg: error processing archive /tmp/parity.deb (--install):
 trying to overwrite '/usr/bin/evm', which is also in package evm 1.5.9+build8841+xenial
dpkg-deb: error: subprocess paste was killed by signal (Broken pipe)
Errors were encountered while processing:
 /tmp/parity.deb
==> Parity is missing

==> Installation failed
```

As soon as your installation routine is more robust you should make this the first line in your documentation: 

Simple one-line installer for Mac and Ubuntu
bash <(curl https://get.parity.io -Lk)

**Comment by tomusdrw** [comment] 2017-03-17 10:18
Duplicate of #4904, fixed in latest master.
Solutions:
https://github.com/paritytech/parity/issues/4904#issuecomment-286425006

**Closed by tomusdrw** 2017-03-17 10:18 UTC
