### ISSUE TITLE
TxViewer Improvements

### ISSUE THREAD

**Issue by tomusdrw** [paritytech/parity#4798] opened 2017-03-07 09:26 UTC
- [ ] Dapp should propose to increase gas price (or do it automatically) when altering gas - otherwise the transaction won't be accepted to local queue.
- [ ] UI for modifying gas and gas price would need some more love (or remove it completely and rely on signer abilities) - Including buttons like: "Resubmit with higher gas price" and "Resubmit with lower gas" could also work.

**Comment by 5chdn** [comment] 2017-05-10 11:39
This issue is labelled with _annoyance_: The client behaves within expectations, however this "expected behaviour" itself is at issue. It's inactive since March, neither assigned nor linked to any milestone.

@paritytech/dapp-devs Please decide on a deadline and add an assignee within 7 days, thanks!

**Comment by debris** [comment] 2018-05-19 06:08
Closing, cause UI is being moved from this repo

**Closed by debris** 2018-05-19 06:08 UTC
Labels: F3-annoyance, M8-dapp, P7-nicetohave
