### ISSUE TITLE
Parity initial sync taking much longer than geth on same host.

### ISSUE THREAD

**Issue by OneOfMany07** [paritytech/parity#7300] opened 2017-12-15 18:26 UTC
I'm running:

- **Which Parity version?**: 1.8.4
- **Which operating system?**: Linux (Ubuntu 17.10 x64)
- **How installed?**: first did one liner install, then dpkg the newer deb file (bug filed that one liner old)
- **Are you fully synchronized?**: no
- **Did you try to restart the node?**: no

I initially installed and set up geth, and figured I might also let parity start its initial sync.  I think geth was at around the 1 million or billion mark (whatever the current max block is that is a 4 currently), and I started parity on the same host.  I have a Ryzen 1600x so plenty of CPU cores, and a good internet connection (150Mbps).  Geth finished syncing last night, and has continued to stay up to date overnight.  Parity is still on about 3 million (or billion or whatever) and has not finished syncing.

I have CPU cycles free to use.  And geth is using more network bandwidth in system monitor than parity.  Parity has lower peaks of network usage than geth.  Geth gets up to around 1.8MBps, but parity is usually stuck below 0.1 but peaks up to around 0.8.

Nothing else is using the network currently, but for a while last night I had some big downloads going.  After I noticed it taking up all my uplink I limited it to at least give about 30Mbps to this host.  No other users in the house.

**Comment by OneOfMany07** [comment] 2017-12-15 18:27
Oh, I did use a non-standard port (changed from 30303 to 30309) to allow both clients to run simultaneously.  Wonder if that put me into a lower priority pool, or do some clients not allow non-standard ports?  Meaning this could be an external cause, and not parity itself.

**Comment by OneOfMany07** [comment] 2017-12-17 19:52
I ran it for almost 2 days and it still wasn't sync'd, all the while geth was keeping current fine.  Something feels wrong there, but I'll ignore it and use geth for now.

**Comment by rphmeier** [comment] 2017-12-18 10:12
Most likely a duplicate of #6372 -- warp sync isn't kicking off, so your node is attempting a full sync.

**Closed** 2017-12-18 10:12 UTC
Labels: F7-optimisation, M4-core, Z0-duplicate

**Comment by 5chdn** [comment] 2018-01-03 13:44
Duplicate of #7436
