### ISSUE TITLE
Block import keeps failing at around block #78000

### ISSUE THREAD

**Issue by galkamax** [paritytech/parity#6899] opened 2017-10-26 02:23 UTC
I'm running:

- Parity version 1.8.1-beta
- Windows
- Installed via installer

When kick of the sync using these options:

> parity --no-warp --cache-size=2048 --port=3001

It runs fine for a while, and then it gives this error:

> 2017-10-25 19:20:01  Block import failed for #79022 (a3c9…5e91)
> Error: Execution(Internal("Database missing expected key: 08b5…71b0"))
> 2017-10-25 19:20:01  Imported #79021 80e4…7689 (0 txs, 0.00 Mgas, 21.02 ms, 0.53 KiB) + another 173 block(s) containing 57 tx(s)

Then it remains stuck trying to sync for a while and eventually exits, giving this error:

> stack backtrace:
>    0:     0x7ff7d89b96e4 - hid_error
>    1:     0x7ff7d89b9beb - hid_error
>    2:     0x7ff7d81dc6f4 - <no info>
>    3:     0x7ff7d8b32674 - hid_error
>    4:     0x7ff7d8b324e9 - hid_error
>    5:     0x7ff7d8b323c2 - hid_error
>    6:     0x7ff7d8b32330 - hid_error
>    7:     0x7ff7d8b3bc4f - hid_error
>    8:     0x7ff7d8b3bcc0 - hid_error
>    9:     0x7ff7d85ba968 - <no info>
>   10:     0x7ff7d84bfb44 - <no info>
>   11:     0x7ff7d84c8a53 - <no info>
>   12:     0x7ff7d84b255f - <no info>
>   13:     0x7ff7d84b3c90 - <no info>
>   14:     0x7ff7d843f709 - <no info>
>   15:     0x7ff7d831238b - <no info>
>   16:     0x7ff7d8317f7a - <no info>
>   17:     0x7ff7d8b33c22 - hid_error
>   18:     0x7ff7d836afb6 - <no info>
>   19:     0x7ff7d8b3075c - hid_error
>   20:     0x7ffe80d98364 - BaseThreadInitThunk
> 
> Thread 'IO Worker #3' panicked at 'nonce will return Some when given BlockId::Latest. nonce was given BlockId::Latest. Therefore nonce has returned Some; qed', src\libcore\option.rs:819

I've tried restarting the sync three times, and each time the same issue happens, but each time at slightly different blocks (79022, 76357, and 78622).

**Comment by Office-Julia** [comment] 2017-10-28 11:05
Hello. Let me assist you with this issue.
Could you please ask the following questions:

1. Have you uninstalled and installed Parity again?
2. Do you use any config file?
3. Do you experience any connection problem? Are you connected to any peers?
4. What's your time? Is it synchronized? time.is

Also please note version 1.8.1 is not the latest one.
Our latest Beta release is 1.8.2,
and latest stable release is 1.7.8.
Please kindly let us know if you tried to install these versions and if the problem happens there again?

Reference: https://github.com/paritytech/parity/releases

**Comment by Office-Julia** [comment] 2017-10-28 19:59
Could you please try to flush database and let us know if it solved your problem:

> parity db kill

**Comment by 5chdn** [comment] 2017-10-29 07:50
Duplicate of ##5968

**Closed by 5chdn** 2017-10-29 07:50 UTC
Labels: F1-panic, Z5-unconfirmed
