### ISSUE TITLE
Thread 'IO Worker #0' panicked at 'DB flush failed

### ISSUE THREAD

**Issue by lsgrep** [paritytech/parity#8045] opened 2018-03-03 16:07 UTC
> I'm running:
>
> - **Which Parity version?**:   docker parity/parity:nightly 
> - **Which operating system?**:  MacOS / Linux
> - **How installed?**:  via docker
> - **Are you fully synchronized?**:  yes
> - **Which network are you connected to?**:  kovan 
> - **Did you try to restart the node?**:  yes, and  it failed again

2018-03-03 14:49:40 UTC DB corrupted: Corruption: block checksum mismatch: expected 355184344, got 2324967102  in /root/.local/share/io.parity.ethereum/chains/kovan/db/9bf388941c25ea98/overlayrecent/db/014412.sst offset 38787337 size 10529. Repair will be triggered on next restart

====================

stack backtrace:
  0:     0x56085899470c - <no info>
  1:     0x560858993db2 - <no info>
  2:     0x560857e343c5 - <no info>

Thread 'IO Worker #0' panicked at 'DB flush failed.: Error(Msg("Corruption: block checksum mismatch: expected 355184344, got 2324967102  in /root/.local/share/io.parity.ethereum/chains/kovan/db/9bf388941c25ea98/overlayrecent/db/014412.sst offset 38787337 size 10529"), State { next_error: None, backtrace: None })', /checkout/src/libcore/result.rs:916

**Comment by 5chdn** [comment] 2018-03-23 10:32
Duplicate of #7748

**Closed by 5chdn** 2018-03-23 10:32 UTC
