### ISSUE TITLE
Parity doesn't return `removed` flag on filter changes

### ISSUE THREAD

**Issue by LogvinovLeon** [paritytech/parity#6880] opened 2017-10-24 15:27 UTC
> I'm running:
>
> - **Parity version**: 1.8.1
> - **Operating system**: Linux
> - **And installed**: docker images

---
I've installed a log filter and try to get filter changes.
[Standard defines](https://github.com/ethereum/wiki/wiki/JSON-RPC#returns-42), that every emited log shouls have a `removed` field, but the logs I'm getting miss this field.
```
        {
            "address": "0x71d271f8b14adef568f8f28f1587ce7271ac4ca5",
            "blockHash": "0xe8ed671b455103a24c9c0efc1204416687a2ba2af00c397c350c011202f4d75b",
            "blockNumber": "0x43772e",
            "data": "0x000000000000000000000000db790e1d4a5d7f71db60e55aa7b3af7cf9bbabf60000000000000000000000002013201070451a038d99cbbecedb879b7bdb73e8",
            "logIndex": "0x20",
            "topics": [
                "0x09e48df7857bd0c1e0d31bb8a85d42cf1874817895f171c917f6ee2cea73ec20"
            ],
            "transactionHash": "0x3ab0317c18848368581da767ce0518cac675630f722d1ef8dc385762d5c07c67",
            "transactionIndex": "0x35",
            "transactionLogIndex": "0x0",
            "type": "mined"
        }
```

**Comment by debris** [comment] 2017-12-29 13:12
it's **NOT** a bug.

it's caused by insidious [change in the specification](https://github.com/ethereum/wiki/wiki/JSON-RPC/_compare/677ad3a74a992a544c20e0485e43a39665ea187e...c248e86f1719f57f8546114eda88ae11dd6a84a5) on `18 Jul 2016` followed by the [commit](https://github.com/ethereum/go-ethereum/commit/f52a1ae849492480b6505ab7805305640518a568) in go-ethereum in Dec 2016.

**Comment by tomusdrw** [comment] 2017-12-29 13:28
> it's NOT a bug

That said, we are aiming for compatibility between clients, so it is important to implement that soonish.

@debris I don't agree that it's insubstantial, since we currently don't inform about removed log events at all - it requires quite significant change in filters logic to support that.

**Comment by 5chdn** [comment] 2018-01-03 13:59
Note, A-labels are for pull-requests and Q-labels for issues.

**Comment by sorpaas** [comment] 2018-04-23 13:51
Duplicate of #7994

**Comment by sorpaas** [comment] 2018-06-05 07:40
@folsen @debris @tomusdrw 

Right now we have `type` field in log, which will be set to `"removed"` if a log is removed in reorg. This is equivalent to, as in this issue, having a `removed` field set to `true`. If the goal for resolving the issue is to keep compatibility, then maybe we can support both `type` and `removed`?

**Comment by folsen** [comment] 2018-06-05 08:45
@sorpaas makes sense to me

**Comment by tomusdrw** [comment] 2018-06-05 13:04
@sorpaas yup, although I believe that filters never report removed log entries at all, so the fix is only for pubsub implementation. So #8796 doesn't fully address this issue I believe.

**Comment by sorpaas** [comment] 2018-06-05 13:07
@tomusdrw I think that one is fixed in https://github.com/paritytech/parity/pull/8463. So on the filter level removed logs should be returned as normal on master. :)

**Comment by tomusdrw** [comment] 2018-06-05 21:31
I think #8463 fixes the re-org messages, but only for pubsub. The regular RPC filters never had anything like that implemented (not even sure if it was ever speced), have a look here: https://github.com/paritytech/parity/blob/master/rpc/src/v1/impls/eth_filter.rs#L168-L206

**Closed** 2018-06-12 05:13 UTC
Labels: F3-annoyance, M6-rpcapi, P5-sometimesoon
