### ISSUE TITLE
Parity fires confirmation when state is not changed yet

### ISSUE THREAD

**Issue by xphoniex** [paritytech/parity#6663] opened 2017-10-06 09:17 UTC
~$ parity -v
    Parity/v1.7.0-beta-5f2cabd-20170727/x86_64-linux-gnu/rustc1.18.0

Already posted this question on [stackexchange](https://ethereum.stackexchange.com/questions/26976/occasionaly-web3-returns-contract-old-state-even-though-transaction-is-mined)

I'm running a single node private chain using ethash engine and try to reset `items` in my contract every time I start my dapp and immediately after I receive confirmation, I retrieve `items`. Weird thing is ~10% of time I receive original values instead of new ones and I don't know how to reproduce this consistently!

However Parity UI still shows the new values (which should be zeroes). Does anyone know what is wrong here?

**Comment by 5chdn** [comment] 2017-10-06 09:57
Are you calling RPC methods? Which? How?

**Comment by xphoniex** [comment] 2017-10-06 10:13
I connect to parity using ws and call the contract method : 

`contract.methods.reset().send({from: my_wallet})`

Here's also how I run parity : 

`parity --rpcapi 'eth,web3,personal' --ws-apis 'eth,web3,personal,pubsub' --chain chain.json --no-discovery --reserved-only --ws-origins all`

**Comment by rphmeier** [comment] 2017-10-06 10:23
How are you checking for confirmations? If it's by getting the block receipt, make sure the block number and hash are set. Otherwise, the receipt will be for the "pending" block.

**Comment by xphoniex** [comment] 2017-10-06 10:25
I wait for `confrimation` event to be fired : 

    contract.methods.reset().send({from: my_wallet})
    .on('confirmation', confirmation => {
        if (confirmation) return;
       for (var i = 0 ; i < 10 ; ++i) {
            (function(i){
                contract.methods.items(i).call()
                .then( res => console.log(i + " " + res) );
            }(i));
        }
    })

Am I doing anything wrong here?

**Comment by tomusdrw** [comment] 2017-10-06 11:53
My wild guess that `on('confirmation')` uses transaction receipt and Parity returns a receipt for pending transactions as well.
This can be resolved either by ignoring the first confirmation or by running in `--geth` compatibility mode.

**Comment by rphmeier** [comment] 2017-10-06 13:30
Duplicate of #5538 ?

**Comment by rphmeier** [comment] 2017-10-06 13:37
(workaround is to use `parity.js` for now, it doesn't have this broken behavior when waiting for confirmations)

**Comment by xphoniex** [comment] 2017-10-06 18:08
@tomusdrw I tried running with `--geth`, failure rate seems to have dropped a lot but it still fails occasionally. Regarding waiting for 1 confirmation, is it deterministic that the transaction is confirmed in one block?

@rphmeier are you talking about this ? https://github.com/paritytech/js-api

---

Guys, I've imported a wallet using it's json file from another chain (on parity). The wallet had a password there but in the new chain randomly it asks me for the pass and sometimes it doesn't! You might wanna look into that too!

**Comment by rphmeier** [comment] 2017-10-07 08:17
With Ethash there is no guarantee that the transaction is confirmed in one block or that once confirmed that it will stay confirmed. That's the purpose of waiting for a confirmation N blocks deep, to reduce probability of the transaction being reorganized out of the chain. Your code needs to handle that possibility.

**Comment by xphoniex** [comment] 2017-10-08 17:56
@rphmeier That's what I thought. Thanks for the clarification.

**Closed** 2017-10-09 13:10 UTC
Labels: Z0-question
