### ISSUE TITLE
Warp syncing not working at all on foundation network

### ISSUE THREAD

**Issue by GothicIII** [paritytech/parity#7352] opened 2017-12-21 00:12 UTC
_Before filing a new issue, please **provide the following information**._

> I'm running:
>
> - **Which Parity version?**: 1.8.4 Beta and 1.7.3 Stable
> - **Which operating system?**: Windows
> - **How installed?**: via installer / binaries 
> - **Are you fully synchronized?**: no 
> - **Did you try to restart the node?**: yes

Issue: Warp syncing broken on foundation network.

How to produce:
Install parity via installer/run binary without parameters. After a short while warp sync either won't even start or breaks at random points and start a normal sync.

Detailed description:
First time I started parity from command line. It started to sync with warp mode and the best I got was 40% snapshots downloaded. Then I get no error, even with high verbose level, the logfile output resets completly and parity just starts syncing blocks manually from block 0.

If I kill the deamon and delete all parity related config files ([...]\Appdata\Local\Parity and [...]\Appdata\Roaming\Parity) parity starts syncing at block 0 of 5m without even considering using warp. I don't know how to force warp sync again. It only kicked in twice out of 30 tries. 

"Workaround":
If I switch to a different network like kovan I have no problems. Syncing of 5m blocks was blazing fast. But this is not helpful.

System and environment:
Windows is installed on a SSD with a core i5 CPU@3.8Ghz (SingleThread boost) and 16gb RAM sitting at a 100mbit down and 40mbit up internet speed, so thats not an issue.

I hoped to get a faster alternative than geth, but I'm not willing to let my computer run for 48hours until all blocks are in sync. While writing this geth synced 4m blocks and should be finished soon.

EDIT: Today I tried it again without success. It got further to ~90% warp sync and then it just stops downloading the snapshots and starts again syncing from scratch at block #0.

**Comment by kirushik** [comment] 2017-12-21 16:12
Thanks for your report, @GothicIII! It's really detailed and seems to cover all the necessary info.

Yes, we're aware that warp sync has multiple problems and is currently not helping much. We hope to solve that for most usecases in the upcoming releases (but I can't give you any ETA on that, sorry).
There's already an issue #6372 for warp sync failing at arbitrary times, so I'm closing this one in favor of the older one.

If (after reading all the comments there) you think that this issue is somehow completely different — please post additional info here, and we'll reopen this one.

**Closed by kirushik** 2017-12-21 16:12 UTC

**Comment by 5chdn** [comment] 2018-01-03 13:04
Duplicate of #7436
