### ISSUE TITLE
Delete file associated with unix socket on startup (with warning)

### ISSUE THREAD

**Issue by NikVolf** [paritytech/parity#5300] opened 2017-03-27 17:35 UTC

**Comment by arkpar** [comment] 2017-03-27 18:05
Why not delete it automatically and inform if failed to delete/create?

**Comment by 5chdn** [comment] 2017-05-10 11:43
This issue is labelled with _annoyance_: The client behaves within expectations, however this "expected behaviour" itself is at issue. It's inactive since March, neither assigned nor linked to any milestone.

@paritytech/core-devs Please decide on a deadline and add an assignee within 7 days, thanks!

**Comment by tomusdrw** [comment] 2017-05-10 11:46
Fixed in https://github.com/paritytech/jsonrpc/issues/89

**Closed by tomusdrw** 2017-05-10 11:46 UTC
Labels: F3-annoyance, M4-core
