### ISSUE TITLE
Client Service Error: Client(Database("IO error: Failed to create dir: (...) No such file or directory

### ISSUE THREAD

**Issue by VojtechPistora** [paritytech/parity#5824] opened 2017-06-12 19:53 UTC
Hi all,

attempted to run Parity on Windows 10 for the first time and got the following. Deleting the folder where chains are supposed to be downloaded would not help. Thanks a lot for any answers

C:\WINDOWS\system32>chdir C:\Program Files\Ethcore\Parity

C:\Program Files\Ethcore\Parity>parity
2017-06-12 21:47:51  Starting Parity/v1.6.8-beta-c396229-20170608/x86_64-windows-msvc/rustc1.17.0
2017-06-12 21:47:51  State DB configuration: fast
2017-06-12 21:47:51  Operating mode: active
2017-06-12 21:47:52  Configured for Foundation using Ethash engine
2017-06-12 21:47:52  Updated conversion rate to Ξ1 = US$348.8 (341306240 wei/gas)
Client service error: Client(Database("IO error: Failed to create dir: C:\\Users\\Vojtěch\\AppData\\Local\\Parity\\Ethereum\\chains\\ethereum\\db\\906a34e69aec8c0d\\overlayrecent\\db: No such file or directory"))

![image](https://user-images.githubusercontent.com/9480686/27052273-78065a6c-4fb9-11e7-82ab-40871fff230a.png)

**Comment by arkpar** [comment] 2017-06-12 20:49
Duplicate of #2215. See linked issue for a workaround

**Closed by arkpar** 2017-06-12 20:49 UTC
