### ISSUE TITLE
restoring account 

### ISSUE THREAD

**Issue by roninkaizen** [paritytech/parity#6500] opened 2017-09-11 14:54 UTC
_Before filing a new issue, please **provide the following information**._

> I'm running:
>
> - **Parity version**: 1.7.0beta-5f2cabd-20170727/x86_64_linunx-gnu
> - **Operating system**: Linux
> - **And installed**: from source

_Your issue description goes here below. Try to include **actual** vs. **expected behavior** and **steps to reproduce** the issue._

![Image of error](https://files.gitter.im/roninkaizen/K8PE/error-cannot-create-account.PNG)
---

While testing to restore a wallet i was shown this error as visible.

**expected behavior:** account restauration after a short period of time (eta 90 sec.)

**actual behavior**: after filling the needed information, the note appeared, no navigation within the tabs nor any other parity navigation was "fulfilled"-only the navigation to the status page was possible after a long period of time (2-4 min) 

the node did not interact normally with the gui but kept synchronzing.
after a restart of the node, the restored account became visible and has the set.password.

**Comment by rphmeier** [comment] 2017-09-11 15:57
(tagged as ASAP since any bugs in the account recovery pipeline should be addressed quickly)

**Comment by tomusdrw** [comment] 2017-09-11 20:08
Can't reproduce on 1.7.2. What steps did you take? 
It seems that you are on the "Status" page while restoring the account how is it possible?

**Comment by 5chdn** [comment] 2017-09-12 06:11
Probably related to #6387. Can you retry with latest head of the beta branch?

**Comment by roninkaizen** [comment] 2017-09-12 20:15
@tomusdrw - completely right- some of the status page came up- and the error note-
way to come there
logged in, tried to recover- (got allmost no response) -> klicked status 
cause i wanted to see at which block the chain is- 
no further interaction possible.
node had to be restarted.

**Comment by 5chdn** [comment] 2017-09-27 09:56
Closing, probably cause by #6387, please report back if this still occurs with 1.7.2 or later.

**Closed by 5chdn** 2017-09-27 09:56 UTC
Labels: F2-bug, M7-ui, P2-asap, Z5-unconfirmed

**Comment by roninkaizen** [comment] 2018-03-02 13:02
not yet
