### ISSUE TITLE
Use of "Foundation" to refer to ETH chain on bottom corner of main parity wallet screen

### ISSUE THREAD

**Issue by bamos01** [paritytech/parity#6254] opened 2017-08-08 03:19 UTC
Seel also #6217 - This was closed without addressing my question: would you consider using the abbreviation "ETH" to refer to the  ETH chain instead of the confusing term "FOUNDATION"? .  The term "ETH" is unambiguous and avoids using terms like 'Ethereum' or 'Mainnet' that I understand may be problematic for you.  I believe that the term "FOUNDATION" is confusing to users (As no one else uses this term except in an insulting way), and furthermore "FOUNDATION" sounds like a consortium chain not a public blockchain.  Furthermore, as stated previously, many people use the term "Foundation chain" in a derogatory way to imply that the EF controls the mainchain and that it is not actually a dencentralized project.  I don't think that Parity intends it to be insulting, but names are important, and I think "ETH" is a much more neutral term that is unambiguous, will avoid user confusion, and will not sound like an insult to sensitive people.   Also - I note that you use the term "ETHEREUM CLASSIC" for the ETC chain.  This seems unfair that you would use their proper name but then refer to the ETH chain as "FOUNDATION" - please reconsider this policy - thank you!!

**Comment by 5chdn** [comment] 2017-08-08 07:30
duplicate of #6217

**Closed by 5chdn** 2017-08-08 07:30 UTC
Labels: Z0-duplicate
