### ISSUE TITLE
panicked at 'Expected to find transaction hash.'

### ISSUE THREAD

**Issue by gituser** [paritytech/parity#7309] opened 2017-12-17 08:44 UTC
_Before filing a new issue, please **provide the following information**._

> I'm running:
>
> - **Which Parity version?**: 1.7.10
> - **Which operating system?**: Linux
> - **How installed?**: from source
> - **Are you fully synchronized?**: yes
> - **Did you try to restart the node?**: yes

Parity just crashed:

```
2017-12-17 11:35:22  Verifier #7 INFO reorg  Reorg to #4747550 84e7…2639 (406d…a2f7 #4747548 5320…5875 e068…52ee)
thread '<unnamed>' panicked at 'Expected to find transaction hash. Database is probably corrupted', /checkout/src/libcore/option.rs:823
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
stack backtrace:
   0: std::sys::imp::backtrace::tracing::imp::unwind_backtrace
             at ./checkout/src/libstd/sys/unix/backtrace/tracing/gcc_s.rs:49
   1: std::sys_common::backtrace::_print
             at ./checkout/src/libstd/sys_common/backtrace.rs:71
   2: std::panicking::default_hook::{{closure}}
             at ./checkout/src/libstd/sys_common/backtrace.rs:60
             at ./checkout/src/libstd/panicking.rs:355
   3: std::panicking::default_hook
             at ./checkout/src/libstd/panicking.rs:371
   4: std::panicking::rust_panic_with_hook
             at ./checkout/src/libstd/panicking.rs:549
   5: std::panicking::begin_panic
             at ./checkout/src/libstd/panicking.rs:511
   6: std::panicking::begin_panic_fmt
             at ./checkout/src/libstd/panicking.rs:495
   7: rust_begin_unwind
             at ./checkout/src/libstd/panicking.rs:471
   8: core::panicking::panic_fmt
             at ./checkout/src/libcore/panicking.rs:69
   9: core::option::expect_failed
             at ./checkout/src/libcore/option.rs:823
  10: <core::iter::FlatMap<I, U, F> as core::iter::iterator::Iterator>::next
  11: <core::iter::FlatMap<I, U, F> as core::iter::iterator::Iterator>::next
  12: <ethcore::client::client::Client as ethcore::client::traits::BlockChainClient>::filter_traces
  13: <jsonrpc_macros::delegates::DelegateMethod<T, F> as jsonrpc_core::calls::RpcMethod<M>>::call
  14: <futures::future::then::Then<A, B, F> as futures::future::Future>::poll
  15: <futures::future::map::Map<A, F> as futures::future::Future>::poll
  16: <futures::future::either::Either<A, B> as futures::future::Future>::poll
  17: <futures::future::map::Map<A, F> as futures::future::Future>::poll
  18: <futures::future::map::Map<A, F> as futures::future::Future>::poll
  19: tokio_core::reactor::Core::poll
```
Parity version:

```
Parity
  version Parity/v1.7.10-unstable-3931713-20171211/x86_64-linux-gnu/rustc1.19.0
Copyright 2015, 2016, 2017 Parity Technologies (UK) Ltd
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>.
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.

By Wood/Paronyan/Kotewicz/Drwięga/Volf
   Habermeier/Czaban/Greeff/Gotchac/Redmann
```

Had to rollback to `v1.7.8` for now.

**Comment by alfatop** [comment] 2017-12-18 13:53
anyone?

**Comment by gituser** [comment] 2017-12-18 13:54
ping @5chdn @tomusdrw

**Comment by tomusdrw** [comment] 2017-12-20 22:10
Most likely a race condition caused by the re-org. @0x7CFE another reason to disallow non-hash-based quering inside client.

@gituser Are you able to reproduce the issue? From my interpretation this can only happen in case there is a pending query and a specific re-org happens causing some transactions to be removed from DB.

**Comment by gituser** [comment] 2017-12-23 13:37
@tomusdrw no I wasn't able to re-produce the issue yet.

But I think the issue is still there most likely occurs under high load or some race condition as you've mentioned.

I've upgraded for now to `1.8.4` and will see how it goes.

**Comment by folsen** [comment] 2018-05-21 02:15
Closing as Unreproducible.

**Closed by folsen** 2018-05-21 02:15 UTC
Labels: F1-panic, M4-core, P2-asap
