### ISSUE TITLE
1.8.9 on Ubuntu 16.04 --> libssl.so.1.1 error

### ISSUE THREAD

**Issue by stone212** [paritytech/parity#7826] opened 2018-02-07 11:13 UTC
> I'm running:
>
> - **Which Parity version?**: 1.8.9
> - **Which operating system?**: Ubuntu 16.04
> - **How installed?**: via binaries 

Upgrading from 1.8.8 to 1.8.9 on Ubuntu 16.04 breaks Parity.  The problem is that libssl.so.1.1 does not exist for Ubuntu 16.04 (see https://packages.ubuntu.com/search?keywords=libssl&suite=default&section=all&arch=any&searchon=names)

However parity_1.8.9_amd64.deb package installs with no error.  Also libssl.so.1.1 is not in the changelog for 1.8.9.

Then you run Parity and you see:

> parity: error while loading shared libraries: libssl.so.1.1: cannot open shared object file: No such file or directory

**Comment by 5chdn** [comment] 2018-02-07 11:16
Please use the linux binary not the debian binary! 

duplicate of #7792

**Closed by 5chdn** 2018-02-07 11:16 UTC

**Comment by stone212** [comment] 2018-02-07 11:33
@5chdn 

I specified this in the original Issue post.  I am using parity_1.8.9_amd64.deb, not parity_1.8.9_debian.deb.

**Comment by 5chdn** [comment] 2018-02-08 08:01
What's the sha256sum of that file?

**Comment by stone212** [comment] 2018-02-10 03:30
Good question.  I tried this upgrade again from the beginning and it worked.  So maybe you are correct that I used the wrong file accidentally?  Not sure.  Issue closed.
