### ISSUE TITLE
Ethash "sealFields" should return RLP decoded values

### ISSUE THREAD

**Issue by keorn** [paritytech/parity#6123] opened 2017-07-21 22:05 UTC
Values in `"sealFields"` should be equal to `"mixHash"` and `"nonce"` fields.
Before someone looks at poor https://github.com/ethereum/EIPs/issues/95

**Comment by feynmanliang** [comment] 2017-07-21 22:26
I'd like to work on this. Is the related code under `rpc/src/v1/{types,impl}`?

**Comment by keorn** [comment] 2017-07-24 09:29
Yep and `ethcore/src/ethereum/ethash.rs` in `fn extra_info`

**Comment by tomusdrw** [comment] 2017-10-30 09:18
Duplicate of #1090

**Closed by tomusdrw** 2017-10-30 09:18 UTC
Labels: F8-enhancement, good first issue, hacktoberfest, help wanted, M4-core, P7-nicetohave, Q2-easy
