### ISSUE TITLE
Verifier #1 panicked

### ISSUE THREAD

**Issue by bdrehmer** [paritytech/parity#8197] opened 2018-03-23 02:44 UTC
> I'm running:
>
> - **Which Parity version?**: 1.9.4
> - **Which operating system?**: Ubuntu 16.04 x64
> - **How installed?**: via binaries
> - **Are you fully synchronized?**: yes
> - **Which network are you connected to?**: ethereum

stack backtrace:
   0:     0x55ad5a5738dc - <no info>

Thread 'Verifier #1' panicked at 'DB flush failed.: Error(Msg("Corruption: block checksum mismatch: expected 3110324462, got 2294949896  in ~/.local/share/io.parity.ethereum/chains/ethereum/db/906a34e69aec8c0d/overlayrecent/db/895296.sst offset 53253 size 25483"), State { next_error: None, backtrace: None })', /checkout/src/libcore/result.rs:916

This is a bug. Please report it

**Comment by 5chdn** [comment] 2018-03-23 10:33
Duplicate of #7748

**Closed by 5chdn** 2018-03-23 10:33 UTC
