### ISSUE TITLE
block invalid timestamp

### ISSUE THREAD

**Issue by bilbma** [paritytech/parity#6892] opened 2017-10-25 10:35 UTC
-
![2017-10-25 12 01 05 stage 1 block verification failed for c121 4354 block invalidtimestamp outofbounds min none max some 1508925695 found 1508925714](https://user-images.githubusercontent.com/4594919/31994418-e0529eec-b980-11e7-8e7e-42438230d72b.png)

**Comment by ngotchac** [comment] 2017-10-25 14:53
Duplicate of #6893

**Closed by ngotchac** 2017-10-25 14:53 UTC
