### ISSUE TITLE
Thread 'IO Worker #0' panicked at 'DB flush failed.

### ISSUE THREAD

**Issue by sgehrman** [paritytech/parity#7029] opened 2017-11-12 23:16 UTC
ubuntu, 

just did: $ bash <(curl https://get.parity.io -kL)
then: $ parity

Got this:

====================

stack backtrace:
   0:     0x556d6e35c6cc - <no info>

Thread 'IO Worker #0' panicked at 'DB flush failed.: "Corruption: block checksum mismatch"', /checkout/src/libcore/result.rs:906

This is a bug. Please report it at:

    https://github.com/paritytech/parity/issues/new

Aborted (core dumped)

$ parity -v

Parity
  version Parity/v1.8.2-beta-1b6588c-20171025/x86_64-linux-gnu/rustc1.21.0
Copyright 2015, 2016, 2017 Parity Technologies (UK) Ltd
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>.
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.

By Wood/Paronyan/Kotewicz/Drwięga/Volf
   Habermeier/Czaban/Greeff/Gotchac/Redmann

**Comment by 5chdn** [comment] 2017-11-13 10:50
Your database is corrupted. You can reset it with `parity db kill`

Duplicate of #6974

Duplicate of #6960

Duplicate of #6905

Duplicate of #6798

Duplicate of #6790

Duplicate of #6670

Duplicate of #6506

Duplicate of #6501

Duplicate of #5837

Duplicate of #3634

Duplicate of #3432

Duplicate of #2830

Duplicate of #2640

Duplicate of #2603

Duplicate of #763

**Closed by 5chdn** 2017-11-13 10:50 UTC

**Comment by magum** [comment] 2017-11-23 08:52
You need to open this issue back. Because after killing DB it repeated again 

Loading config file from /home/magum/.local/share/io.parity.ethereum/config.toml
2017-11-22 23:13:11  Starting Parity/v1.7.9-stable-12940e4-20171113/x86_64-linux-gnu/rustc1.21.0
2017-11-22 23:13:11  Keys path /home/magum/.local/share/io.parity.ethereum/keys/Foundation
2017-11-22 23:13:11  DB path /home/magum/.local/share/io.parity.ethereum/chains/ethereum/db/906a34e69aec8c0d
2017-11-22 23:13:11  Path to dapps /home/magum/.local/share/io.parity.ethereum/dapps
2017-11-22 23:13:11  State DB configuration: fast
2017-11-22 23:13:11  Operating mode: active
2017-11-22 23:13:12  Configured for Foundation using Ethash engine
2017-11-22 23:13:15  Removed existing file '/home/magum/.local/share/io.parity.ethereum/jsonrpc.ipc'.
2017-11-22 23:13:20  Public node URL: enode://6be5d9a5b7e78475f04cb2cfbac62ad7cd399fbaaa51a7072f5106caf0096b16144d733866acd2cd987deaa6de9f0872afb088d4695deccfa7e9a2b18455b364@192.168.88.241:30303
2017-11-22 23:13:50  Syncing #4601679 e1c4…abff     0 blk/s    0 tx/s   0 Mgas/s      0+    0 Qed  #4601679    2/25 peers   86 KiB chain 66 MiB db 0 bytes queue 10 KiB sync  RPC:  0 conn,  0 req/s,   0 µs
2017-11-22 23:14:00  Syncing #4601730 b805…3ad6     5 blk/s  394 tx/s  19 Mgas/s      0+   74 Qed  #4601806    4/25 peers   1 MiB chain 68 MiB db 6 MiB queue 322 KiB sync  RPC:  0 conn,  0 req/s,   0 µs
2017-11-22 23:14:10  Syncing #4601834 90ea…d023    10 blk/s  829 tx/s  41 Mgas/s      0+  224 Qed  #4602060    3/25 peers   3 MiB chain 69 MiB db 18 MiB queue 304 KiB sync  RPC:  0 conn,  0 req/s,   0 µs
2017-11-22 23:14:21  Syncing #4601932 bff4…9249     9 blk/s  791 tx/s  39 Mgas/s      0+  378 Qed  #4602314    4/25 peers   5 MiB chain 71 MiB db 31 MiB queue 1018 KiB sync  RPC:  0 conn,  0 req/s,   0 µs
2017-11-22 23:14:30  Syncing #4602036 4901…1c80    10 blk/s  800 tx/s  42 Mgas/s      0+  466 Qed  #4602506    4/25 peers   5 MiB chain 72 MiB db 40 MiB queue 1 MiB sync  RPC:  0 conn,  0 req/s,   0 µs
2017-11-22 23:14:40  Syncing #4602112 be93…0928     7 blk/s  705 tx/s  36 Mgas/s      0+  577 Qed  #4602693    7/25 peers   4 MiB chain 73 MiB db 48 MiB queue 261 KiB sync  RPC:  0 conn,  0 req/s,   0 µs
2017-11-22 23:14:50  Syncing #4602191 56d4…0c00     7 blk/s  623 tx/s  34 Mgas/s      0+  501 Qed  #4602693    8/25 peers   6 MiB chain 75 MiB db 42 MiB queue 261 KiB sync  RPC:  0 conn,  0 req/s,   0 µs
2017-11-22 23:15:00  Syncing #4602277 30e1…0f7b     8 blk/s  642 tx/s  33 Mgas/s      0+  414 Qed  #4602694    8/25 peers   7 MiB chain 75 MiB db 35 MiB queue 261 KiB sync  RPC:  0 conn,  0 req/s,   0 µs
2017-11-22 23:15:10  Syncing #4602360 e472…c10a     8 blk/s  735 tx/s  37 Mgas/s      0+  330 Qed  #4602694    7/25 peers   7 MiB chain 76 MiB db 28 MiB queue 261 KiB sync  RPC:  0 conn,  0 req/s,   0 µs
2017-11-22 23:15:20  Syncing #4602452 4d67…af31     9 blk/s  791 tx/s  55 Mgas/s      0+  240 Qed  #4602695    7/25 peers   6 MiB chain 77 MiB db 21 MiB queue 261 KiB sync  RPC:  0 conn,  0 req/s,   0 µs
2017-11-22 23:15:30  Syncing #4602518 3db0…80bc     6 blk/s  620 tx/s  32 Mgas/s      0+  177 Qed  #4602696    7/25 peers   6 MiB chain 78 MiB db 15 MiB queue 261 KiB sync  RPC:  0 conn,  0 req/s,   0 µs
2017-11-22 23:15:40  Syncing #4602589 29df…654a     7 blk/s  578 tx/s  28 Mgas/s      0+  105 Qed  #4602696    7/25 peers   6 MiB chain 79 MiB db 9 MiB queue 261 KiB sync  RPC:  0 conn,  0 req/s,   0 µs
thread 'IO Worker #1' panicked at 'DB flush failed.: "Corruption: block checksum mismatch"', /checkout/src/libcore/result.rs:906:4
stack backtrace:
   0: <unknown>
   1: <unknown>
   2: <unknown>
   3: <unknown>
   4: <unknown>
   5: <unknown>
   6: <unknown>
   7: <unknown>
   8: <unknown>
   9: <unknown>
  10: <unknown>
  11: <unknown>
  12: <unknown>
  13: <unknown>
^C^C^C^C^C

[1]    8788 abort (core dumped)  parity --warp
parity --warp  162,88s user 77,30s system 102% cpu 3:55,18 total

~ % 
~ % 
~ % 
~ % parity --warp
Loading config file from /home/magum/.local/share/io.parity.ethereum/config.toml
Option '--warp' does nothing. It's on by default.
2017-11-22 23:17:11  Starting Parity/v1.8.3-beta-b49c44a-20171114/x86_64-linux-gnu/rustc1.21.0
2017-11-22 23:17:11  Keys path /home/magum/.local/share/io.parity.ethereum/keys/Foundation
2017-11-22 23:17:11  DB path /home/magum/.local/share/io.parity.ethereum/chains/ethereum/db/906a34e69aec8c0d
2017-11-22 23:17:11  Path to dapps /home/magum/.local/share/io.parity.ethereum/dapps
2017-11-22 23:17:11  State DB configuration: fast
2017-11-22 23:17:11  Operating mode: active
2017-11-22 23:17:11  Configured for Foundation using Ethash engine
2017-11-22 23:17:12  Updated conversion rate to Ξ1 = US$368.42 (323130140 wei/gas)
2017-11-22 23:17:14  Removed existing file '/home/magum/.local/share/io.parity.ethereum/jsonrpc.ipc'.
2017-11-22 23:17:19  Public node URL: enode://6be5d9a5b7e78475f04cb2cfbac62ad7cd399fbaaa51a7072f5106caf0096b16144d733866acd2cd987deaa6de9f0872afb088d4695deccfa7e9a2b18455b364@192.168.88.241:30303
2017-11-22 23:17:29  Syncing #4602592 93db…7dc8     0 blk/s    0 tx/s   0 Mgas/s      0+    0 Qed  #4602592    1/25 peers   82 KiB chain 64 MiB db 0 bytes queue 119 KiB sync  RPC:  0 conn,  0 req/s,   0 µs

====================

stack backtrace:
   0:     0x55b62011608c - <no info>

Thread 'Verifier #0' panicked at 'DB flush failed.: "Corruption: block checksum mismatch"', /checkout/src/libcore/result.rs:906

This is a bug. Please report it at:

    https://github.com/paritytech/parity/issues/new

[1]    9087 abort (core dumped)  parity --warp
parity --warp  13,70s user 4,88s system 93% cpu 19,904 total
~ % cd /home/magum/.local/share/io.parity.ethereum/chains/ethereum/db/906a34e69aec8c0d
..um/chains/ethereum/db/906a34e69aec8c0d % 
..um/chains/ethereum/db/906a34e69aec8c0d % mc


===============================
after killing DB
===============================



..um/chains/ethereum/db/906a34e69aec8c0d % parity --warp                                                                     
..um/chains/ethereum/db/906a34e69aec8c0d % cd -
~
~ % parity --warp                                                                     
Loading config file from /home/magum/.local/share/io.parity.ethereum/config.toml
Option '--warp' does nothing. It's on by default.
2017-11-22 23:18:32  Starting Parity/v1.8.3-beta-b49c44a-20171114/x86_64-linux-gnu/rustc1.21.0
2017-11-22 23:18:32  Keys path /home/magum/.local/share/io.parity.ethereum/keys/Foundation
2017-11-22 23:18:32  DB path /home/magum/.local/share/io.parity.ethereum/chains/ethereum/db/906a34e69aec8c0d
2017-11-22 23:18:32  Path to dapps /home/magum/.local/share/io.parity.ethereum/dapps
2017-11-22 23:18:32  State DB configuration: fast
2017-11-22 23:18:32  Operating mode: active
2017-11-22 23:18:32  Configured for Foundation using Ethash engine
2017-11-22 23:18:32  Updated conversion rate to Ξ1 = US$368.42 (323130140 wei/gas)
2017-11-22 23:18:32  Removed existing file '/home/magum/.local/share/io.parity.ethereum/jsonrpc.ipc'.
2017-11-22 23:18:38  Public node URL: enode://6be5d9a5b7e78475f04cb2cfbac62ad7cd399fbaaa51a7072f5106caf0096b16144d733866acd2cd987deaa6de9f0872afb088d4695deccfa7e9a2b18455b364@192.168.88.241:30303
2017-11-22 23:19:07     0/25 peers   8 KiB chain 3 MiB db 0 bytes queue 10 KiB sync  RPC:  0 conn,  0 req/s,   0 µs
2017-11-22 23:19:17  Syncing     #254 47e6…0bb6    25 blk/s    0 tx/s   0 Mgas/s      0+    0 Qed      #254    1/25 peers   271 KiB chain 4 MiB db 0 bytes queue 95 KiB sync  RPC:  0 conn,  0 req/s,   0 µs
2017-11-22 23:19:22  Syncing     #638 d9ef…87e2    76 blk/s    0 tx/s   0 Mgas/s      0+    0 Qed      #638    1/25 peers   742 KiB chain 8 MiB db 0 bytes queue 211 KiB sync  RPC:  0 conn,  0 req/s,   0 µs
2017-11-22 23:19:32  Syncing    #2540 2cce…39b5   190 blk/s    0 tx/s   0 Mgas/s      0+    0 Qed     #2540    2/25 peers   3 MiB chain 14 MiB db 0 bytes queue 799 KiB sync  RPC:  0 conn,  0 req/s,   0 µs
2017-11-22 23:19:42  Syncing    #6097 7b6c…20bb   355 blk/s    0 tx/s   0 Mgas/s      0+    0 Qed     #6097    2/25 peers   6 MiB chain 29 MiB db 0 bytes queue 997 KiB sync  RPC:  0 conn,  0 req/s,   0 µs
2017-11-22 23:19:52  Syncing    #8522 f8b0…4e8e   242 blk/s    0 tx/s   0 Mgas/s      0+    0 Qed     #8522    3/25 peers   7 MiB chain 47 MiB db 0 bytes queue 2 MiB sync  RPC:  0 conn,  0 req/s,   0 µs
2017-11-22 23:20:02  Syncing   #13720 153d…2b13   520 blk/s    0 tx/s   0 Mgas/s      0+    0 Qed    #13720    3/25 peers   7 MiB chain 61 MiB db 0 bytes queue 2 MiB sync  RPC:  0 conn,  0 req/s,   0 µs
2017-11-22 23:20:12  Syncing   #16891 ddc7…8cfa   317 blk/s    0 tx/s   0 Mgas/s      0+    0 Qed    #16891    4/25 peers   6 MiB chain 72 MiB db 0 bytes queue 4 MiB sync  RPC:  0 conn,  0 req/s,   0 µs
2017-11-22 23:20:22  Syncing   #22098 dc24…d321   521 blk/s    0 tx/s   0 Mgas/s      0+    0 Qed    #22098    5/25 peers   6 MiB chain 73 MiB db 0 bytes queue 4 MiB sync  RPC:  0 conn,  0 req/s,   0 µs
2017-11-22 23:20:32  Syncing   #26816 f97a…61a4   472 blk/s    0 tx/s   0 Mgas/s      0+    0 Qed    #26816    4/25 peers   6 MiB chain 73 MiB db 0 bytes queue 3 MiB sync  RPC:  0 conn,  0 req/s,   0 µs
2017-11-22 23:20:38  Syncing   #27273 6be2…27ee    82 blk/s    0 tx/s   0 Mgas/s     14+ 2166 Qed    #29464    5/25 peers   6 MiB chain 73 MiB db 4 MiB queue 3 MiB sync  RPC:  0 conn,  0 req/s,   0 µs
2017-11-22 23:20:47  Syncing   #31750 8bf5…f2e0   473 blk/s    0 tx/s   0 Mgas/s      0+    0 Qed    #31750    5/25 peers   6 MiB chain 73 MiB db 0 bytes queue 5 MiB sync  RPC:  0 conn,  0 req/s,   0 µs
2017-11-22 23:20:57  Syncing   #34165 0833…e09d   241 blk/s    0 tx/s   0 Mgas/s      0+    0 Qed    #34165    3/25 peers   6 MiB chain 73 MiB db 0 bytes queue 5 MiB sync  RPC:  0 conn,  0 req/s,   0 µs
2017-11-22 23:21:07  Syncing   #37211 d51c…00a5   304 blk/s    0 tx/s   0 Mgas/s      0+    0 Qed    #37211    2/25 peers   6 MiB chain 73 MiB db 0 bytes queue 5 MiB sync  RPC:  0 conn,  0 req/s,   0 µs
2017-11-22 23:21:17  Syncing   #38231 29c0…594d   102 blk/s    0 tx/s   0 Mgas/s      0+    0 Qed    #38231    4/25 peers   5 MiB chain 73 MiB db 0 bytes queue 6 MiB sync  RPC:  0 conn,  0 req/s,   0 µs
2017-11-22 23:21:27  Syncing   #41275 eede…3ad0   304 blk/s    0 tx/s   0 Mgas/s      0+    0 Qed    #41275    4/25 peers   6 MiB chain 73 MiB db 0 bytes queue 6 MiB sync  RPC:  0 conn,  0 req/s,   0 µs
2017-11-22 23:21:37  Syncing   #44069 d168…52b6   279 blk/s    0 tx/s   0 Mgas/s      0+    0 Qed    #44069    4/25 peers   6 MiB chain 73 MiB db 0 bytes queue 6 MiB sync  RPC:  0 conn,  0 req/s,   0 µs
2017-11-22 23:21:47  Syncing   #47879 844d…8071   381 blk/s   79 tx/s   1 Mgas/s      0+    0 Qed    #47879    4/25 peers   6 MiB chain 73 MiB db 0 bytes queue 5 MiB sync  RPC:  0 conn,  0 req/s,   0 µs
2017-11-22 23:21:57  Syncing   #49149 efa7…0a1c   127 blk/s   71 tx/s   1 Mgas/s      0+    0 Qed    #49149    4/25 peers   6 MiB chain 73 MiB db 0 bytes queue 5 MiB sync  RPC:  0 conn,  0 req/s,   0 µs
2017-11-22 23:22:07  Syncing   #52578 b87d…d287   343 blk/s  192 tx/s  14 Mgas/s      0+    0 Qed    #52578    6/25 peers   6 MiB chain 72 MiB db 0 bytes queue 5 MiB sync  RPC:  0 conn,  0 req/s,   0 µs
2017-11-22 23:22:17  Syncing   #56388 2d48…35e1   381 blk/s  181 tx/s  25 Mgas/s      0+    0 Qed    

===============
cut syncing 
===============

2017-11-23 04:46:58  Syncing #2495823 a01f…8867   222 blk/s  971 tx/s  29 Mgas/s      0+ 3703 Qed  #2499530   24/25 peers   6 MiB chain 258 MiB db 40 MiB queue 15 MiB sync  RPC:  0 conn,  0 req/s,   0 µs
2017-11-23 04:47:08  Syncing #2497623 a62c…ac80   180 blk/s 1377 tx/s  39 Mgas/s      0+ 4108 Qed  #2501735   24/25 peers   6 MiB chain 258 MiB db 40 MiB queue 16 MiB sync  RPC:  0 conn,  0 req/s,   0 µs
2017-11-23 04:47:18  Syncing #2498828 118b…c71f   118 blk/s 1399 tx/s  46 Mgas/s      0+ 4798 Qed  #2503629   25/25 peers   5 MiB chain 258 MiB db 40 MiB queue 16 MiB sync  RPC:  0 conn,  0 req/s,   0 µs

====================

stack backtrace:
   0:     0x5615430c408c - <no info>

Thread 'IO Worker #1' panicked at 'DB flush failed.: "Corruption: block checksum mismatch"', /checkout/src/libcore/result.rs:906

This is a bug. Please report it at:

    https://github.com/paritytech/parity/issues/new


====================

**Comment by 5chdn** [comment] 2017-11-23 15:07
If this repeatedly occurs: this indicates a corrupted disk.
