### ISSUE TITLE
Stage 4 block verification failed  kovan network

### ISSUE THREAD

**Issue by israelstox** [paritytech/parity#7649] opened 2018-01-21 11:27 UTC
I'm running:
parity:v1.7.12 
operating system: Linux
How installed:from source
Fully synchronized: yes
connected to: kovan
try to restart the node: yes

Stage 4 block verification failed for #5470476 (0bc5…e8bf)
Error: Block(TemporarilyInvalid(OutOfBounds { min: None, max: Some(1516430008), found: 1516430012 }))
Stage 4 block verification failed for #5487271 (c478…f29c)
Error: Block(TemporarilyInvalid(OutOfBounds { min: None, max: Some(1516517128), found: 1516517132 }))

**Comment by pgrzesik** [comment] 2018-01-22 09:59
I'm having similar issue, more details: https://github.com/paritytech/parity/issues/7659

**Comment by 5chdn** [comment] 2018-01-22 10:12
Duplicate of #7527 

Please downgrade to 1.8.5 or wait for 1.9.0

**Closed by 5chdn** 2018-01-22 10:12 UTC
