### ISSUE TITLE
Spec json is invalid: missing field `gasLimitBoundDivisor` at line 23 column 4

### ISSUE THREAD

**Issue by stone212** [paritytech/parity#6939] opened 2017-10-31 06:53 UTC
_Before filing a new issue, please **provide the following information**._

> I'm running:
>
> - **Parity version**: 1.7.8
> - **Operating system**: Linux
> - **And installed**: via binaries 

I am creating a private chain spec file for a private network.  I see that the chain spec file for mainnet has "gasLimitBoundDivisor" in the "params" section:
https://github.com/paritytech/parity/blob/master/ethcore/res/ethereum/foundation.json

So I attempt to duplicate that, and I also place mine in the same section.  But when I do, I get this error:

> Spec json is invalid: missing field `gasLimitBoundDivisor` at line 23 column 4

If I add the gasLimitBoundDivisor to the "engine" section (under its *params*) the error goes away.  That matches the example on this page:
https://github.com/paritytech/parity/wiki/Pluggable-Consensus

But it does not match the official mainnet chain spec file linked to above.

**Comment by sparshprogrammer** [comment] 2017-10-31 08:01
"gasLimitBoundDivisor":"0x0400"
add this on that line

**Comment by stone212** [comment] 2017-10-31 23:08
@sparshprogrammer 

Thank you but I already did that, as I said in my initial comment:

> If I add the gasLimitBoundDivisor to the "engine" section (under its params) the error goes away.

But the *issue*  that I opened regards the conflicting documentation.

**Comment by 5chdn** [comment] 2017-11-01 21:55
Duplicate of #6916

https://github.com/paritytech/parity/blob/master/CHANGELOG.md#parity-v180-2017-10-15

> Further, users upgrading from 1.7 should acknowledge the following changes:
>
> -The chain-engine was further abstracted and chain-specs need to be upgraded. #6134 #6591

Move `registrar`, `gasLimitBoundDivisor`, and `eip155Transition` from engine (Ethash/AuthorityRound/etc.) to general params section.

**Closed** 2017-11-01 21:56 UTC
Labels: M2-config, Z0-duplicate, Z0-question

**Comment by 5chdn** [comment] 2017-11-01 21:59
Sorry, fat-fingered this issue too quickly, thanks for reporting, I updated the docs.
