### ISSUE TITLE
Thread 'main' panicked

### ISSUE THREAD

**Issue by brianharness** [paritytech/parity#6985] opened 2017-11-04 21:53 UTC
> I'm running:
>
> - **Parity version**: v1.8.2-beta-1b6588c-20171025/x86_64-linux-gnu/rustc1.21.0
> - **Operating system**: Ubuntu 17.10
> - **And installed**:   .deb  package
I run Parity from command line. I was running 1.7.6 with no problems. With 1.8.2 nothing works. I've tried some different options, but that does not help. It returns 
stack backtrace:
   0:     0x5648c5ecd34c - <no info>

Thread 'main' panicked at 'called `Option::unwrap()` on a `None` value', /checkout/src/libcore/option.rs:335

This is a bug. Please report it at:

    https://github.com/paritytech/parity/issues/new

Aborted (core dumped)

---

**Comment by 5chdn** [comment] 2017-11-06 14:04
Can you share the full stack backtrace, please?

Do you use any configuration?

**Comment by palkeo** [comment] 2017-11-26 20:35
Hijacking this issue as I have the same problem (running a docker container with the nightly build):
parity_1  | ====================
parity_1  |
parity_1  | stack backtrace:
parity_1  |    0:     0x56500eb61b2c - <no info>
parity_1  |    1:     0x56500eb61b62 - <no info>
parity_1  |    2:     0x56500e1b34f8 - <no info>
parity_1  |    3:     0x56500edf9336 - <no info>
parity_1  |    4:     0x56500edf91c4 - <no info>
parity_1  |    5:     0x56500edf90c9 - <no info>
parity_1  |    6:     0x56500edf905a - <no info>
parity_1  |    7:     0x56500ee327b0 - <no info>
parity_1  |    8:     0x56500ee326e6 - <no info>
parity_1  |    9:     0x56500e73a3e0 - <no info>
parity_1  |   10:     0x56500e5c02ad - <no info>
parity_1  |   11:     0x56500e66b68b - <no info>
parity_1  |   12:     0x56500e0efc36 - <no info>
parity_1  |   13:     0x56500e10ad96 - <no info>
parity_1  |   14:     0x56500e110e41 - <no info>
parity_1  |   15:     0x56500e114495 - <no info>
parity_1  |   16:     0x56500edffd1b - <no info>
parity_1  |
parity_1  | Thread 'main' panicked at 'called `Option::unwrap()` on a `None` value', /checkout/src/libcore/option.rs:335
parity_1  |
parity_1  | This is a bug. Please report it at:
parity_1  |
parity_1  |     https://github.com/paritytech/parity/issues/new
parity_1  |

It is probably because of the database, and I may have ran of disk space because the DB got so big (with tracing on, and fat DB), when syncing.

**Comment by palkeo** [comment] 2017-11-26 23:18
I managed to reproduce on a debug build:
stack backtrace:
   0:     0x56454766e4b4 - backtrace::backtrace::libunwind::trace
                        at /home/palkeo/.cargo/registry/src/github.com-1ecc6299db9ec823/backtrace-0.3.3/src/backtrace/libunwind.rs:53
                         - backtrace::backtrace::trace<closure>
                        at /home/palkeo/.cargo/registry/src/github.com-1ecc6299db9ec823/backtrace-0.3.3/src/backtrace/mod.rs:42
   1:     0x56454766e91f - backtrace::capture::{{impl}}::new_unresolved
                        at /home/palkeo/.cargo/registry/src/github.com-1ecc6299db9ec823/backtrace-0.3.3/src/capture.rs:88
   2:     0x56454766e87e - backtrace::capture::{{impl}}::new
                        at /home/palkeo/.cargo/registry/src/github.com-1ecc6299db9ec823/backtrace-0.3.3/src/capture.rs:63
   3:     0x564544e82803 - panic_hook::panic_hook
                        at panic_hook/src/lib.rs:53
   4:     0x564544e80938 - core::ops::function::Fn::call<fn(&std::panicking::PanicInfo),(&std::panicking::PanicInfo)>
                        at /build/rust/src/rustc-1.21.0-src/src/libcore/ops/function.rs:73
   5:     0x564547eb293a - std::panicking::rust_panic_with_hook::he320c96b10174bc7
   6:     0x564547eb27f4 - std::panicking::begin_panic::hccaa67383af9c783
   7:     0x564547eb26f1 - std::panicking::begin_panic_fmt::h8e4e43ea19ab9416
   8:     0x564547eb267a - rust_begin_unwind
   9:     0x564547f112c0 - core::panicking::panic_fmt::h83ccad0ec79d6328
  10:     0x564547f111b6 - core::panicking::panic::he5a13be5d7e7e9fb
  11:     0x564545cdeef7 - core::option::{{impl}}::unwrap<ethcore::encoded::Block>
                        at /build/rust/src/rustc-1.21.0-src/src/libcore/macros.rs:32
  12:     0x5645465381c9 - ethcore::blockchain::blockchain::{{impl}}::new
                        at ethcore/src/blockchain/blockchain.rs:553
  13:     0x5645463498c0 - ethcore::client::client::{{impl}}::new
                        at ethcore/src/client/client.rs:209
  14:     0x5645463f35d7 - ethcore::service::{{impl}}::start
                        at ethcore/src/service.rs:98
  15:     0x564544c74b64 - parity::run::execute
                        at parity/run.rs:583
  16:     0x564544c8ce33 - parity::execute
                        at parity/main.rs:163
  17:     0x564544c8e69f - parity::start
                        at parity/main.rs:189
  18:     0x564544c8f497 - parity::main_direct
                        at parity/main.rs:284
  19:     0x564544c909f0 - parity::main
                        at parity/main.rs:365
  20:     0x564547ed4eab - __rust_maybe_catch_panic

**Comment by calvintam236** [comment] 2017-11-30 04:48
I am on v1.7.9, and I encounter the same bug. It is running inside the Docker container as well. Image using https://github.com/calvintam236/docker_parity.

```bash
2017-11-30 02:30:31 UTC Starting Parity/v1.7.9-stable-12940e4-20171113/aarch64-linux-gnu/rustc1.21.0
2017-11-30 02:30:31 UTC Keys path /parity/keys/Foundation
2017-11-30 02:30:31 UTC DB path /parity/chains/ethereum/db/906a34e69aec8c0d
2017-11-30 02:30:31 UTC Path to dapps /parity/dapps
2017-11-30 02:30:31 UTC State DB configuration: fast
2017-11-30 02:30:31 UTC Operating mode: active
2017-11-30 02:30:31 UTC Configured for Foundation using Ethash engine
thread 'main' panicked at 'called `Option::unwrap()` on a `None` value', /checkout/src/libcore/option.rs:335:20
stack backtrace:
   0: <unknown>
   1: <unknown>
   2: <unknown>
   3: <unknown>
   4: <unknown>
   5: <unknown>
   6: <unknown>
   7: <unknown>
   8: <unknown>
   9: <unknown>
  10: <unknown>
  11: <unknown>
  12: <unknown>
  13: <unknown>
  14: <unknown>
  15: <unknown>
  16: <unknown>
  17: <unknown>
```

**Comment by 5chdn** [comment] 2018-01-03 13:18
Duplicate of #7340

**Closed by 5chdn** 2018-01-03 13:18 UTC
Labels: F1-panic, M4-core, P2-asap
