### ISSUE TITLE
Releasing with md5 in 2017?

### ISSUE THREAD

**Issue by WyseNynja** [paritytech/parity#6473] opened 2017-09-06 05:45 UTC
I went to download parity and noticed that the release section lists md5 sums. Why is a secure hashing algorithm not being used? Why not use signatures with a tool like https://jedisct1.github.io/minisign/?

**Comment by 5chdn** [comment] 2017-09-06 05:56
Duplicate of #4672

Starting with 1.7.1 we switched to Sha256. However, due to a bug, we had to pull 1.7.1, please wait for 1.7.2.

**Comment by 5chdn** [comment] 2017-09-06 05:57
Regarding signatures, see #3574

**Closed by 5chdn** 2017-09-06 05:56 UTC
