### ISSUE TITLE
Parity falls out of sync frequently; peer count low

### ISSUE THREAD

**Issue by ksedgwic** [paritytech/parity#7992] opened 2018-02-23 20:58 UTC
_Before filing a new issue, please **provide the following information**._

> I'm running:
>
> - **Which Parity version?**: version Parity/v1.10.0-unstable-0a643a9-20180129/x86_64-linux-gnu/rustc1.22.1.
> - **Which operating system?**: Linux; CentOS Linux release 7.4.1708 (Core)
> - **How installed?**: built from source
> - **Are you fully synchronized? Expect to stay syncd, failing to stay syncd.
> - **Which network are you connected to?**: ethereum.  Second copy connected to ropsten stays syncd.
> - **Did you try to restart the node?**: yes, multiple times.  Often temporarily fixes the problem

My parity instance has trouble staying synced.
* instance is running on EC2 node provisioned w/ 2TB of SSD.
* peer count seems low, often between 0 and 5.

**Comment by 5chdn** [comment] 2018-02-25 11:23
Duplicate of #7531

**Closed by 5chdn** 2018-02-25 11:23 UTC
