### ISSUE TITLE
eth_getBlockByNumber gives null results for some blocks

### ISSUE THREAD

**Issue by saulbein** [paritytech/parity#6410] opened 2017-08-29 10:04 UTC
> I'm running:
>
> - **Parity version**: 1.6.10
> - **Operating system**: Ubuntu 16.04.3 LTS
> - **And installed**: via dpkg

Parity consistently (same blocks) gives JSON response to `eth_getBlockByNumber` with `"result": null`.

The node is confirmed to have the ancient blocks available and is ahead of them (so far it has only been encountered with ancient ones).

The issue persists after restart with the same exact blocks returning `null` response.

The issue just popped up at some point seemingly without any trigger (although it wasn't monitored, so maybe it was just missed).

Command line arguments:
`--jsonrpc-apis web3,eth,net,parity,rpc,personal --no-dapps --cache-size 2048 --jsonrpc-interface xxx.xxx.x.xxx --jsonrpc-hosts all --log-file /var/log/parity.log --logging debug`

Log sample:
![img_29082017_105428_0](https://user-images.githubusercontent.com/28628020/29815408-2dd3e9cc-8cb9-11e7-90e5-01f4cbe3a270.png)

Request:
```
{
    "jsonrpc":"2.0",
    "method":"eth_getBlockByNumber",
    "params": ["0x3D5971", true],
    "id":1
}
```

Response:
```
{
   "jsonrpc": "2.0",
   "result": null,
   "id": 1
}
```

**Comment by debris** [comment] 2018-05-09 11:38
I can't reproduce this issue. It's quite old and there were a lot of changes since then. I'm closing it, but please reopen if it still occurs

**Closed by debris** 2018-05-09 11:38 UTC
Labels: F2-bug, M6-rpcapi, P5-sometimesoon

**Comment by saulbein** [comment] 2018-05-09 13:07
I haven't encountered this again, so it doesn't seem to be relevant anymore.
