### ISSUE TITLE
DB corrupted: Corruption: block checksum mismatch: expected 190745535

### ISSUE THREAD

**Issue by bizhua** [paritytech/parity#8766] opened 2018-06-02 10:33 UTC
I'm running:

Which Parity version?: 1.10.4
Which operating system?: ubuntu 16.04 and 18。04
How installed?: via installer
Are you fully synchronized?: no
Which network are you connected to?: ethereum
Did you try to restart the node?: yes

```
DB corrupted: Corruption: block checksum mismatch: expected 190745535, got 1131197072  in /home/bjfm/paritylz/chains/ethereum/db/906a34e69aec8c0d/overlayrecent/db/167632.sst offset 7254809 size 16271. Repair will be triggered on next restart

stack backtrace:
   0:     0x55dee69f3dbc - <no info>

Thread 'IO Worker #0' panicked at 'DB flush failed.: Error(Msg("Corruption: block checksum mismatch: expected 190745535, got 1131197072  in /home/bjfm/paritylz/chains/ethereum/db/906a34e69aec8c0d/overlayrecent/db/167632.sst offset 7254809 size 16271"), State { next_error: None, backtrace: None })', libcore/result.rs:945
```

**Comment by roninkaizen** [comment] 2018-06-03 00:42
try a parity db kill,
had exact the same and for sure to warp&sync again,
never came up again with this version ;-)

**Comment by AntoniosHadji** [comment] 2018-06-03 21:29
I had the same issue with Parity 1.10.4 on Ubuntu 16.04 installed via deb package. Node was fully synced to mainnet.  I had parityJS shell dapp wallet open but I was not using it when the crash occurred.
 
```
Jun  3 15:14:26 hadji parity[2508]: 2018-06-03 15:14:26  Verifier #2 WARN kvdb_rocksdb  DB corrupted: Corruption: block checksum mismatch: expected 1269784933, got 1574034133  in /mnt/blockchain/ethereum/io.parity.ethereum/chains/ethereum/db/906a34e69aec8c0d/overlayrecent/db/2686758.sst offset 27841324 size 16365. Repair will be triggered on next restart
Jun  3 15:14:26 hadji parity[2508]: ====================
Jun  3 15:14:26 hadji parity[2508]: stack backtrace:
Jun  3 15:14:26 hadji parity[2508]:    0:     0x5611be7d7dbc - <no info>
Jun  3 15:14:26 hadji parity[2508]: Thread 'Verifier #2' panicked at 'DB flush failed.: Error(Msg("Corruption: block checksum mismatch: expected 1269784933, got 1574034133  in /mnt/blockchain/ethereum/io.parity.ethereum/chains/ethereum/db/906a34e69aec8c0d/overlayrecent/db/2686758.sst offset 27841324 size 16365"), State { next_error: None, backtrace: None })', libcore/result.rs:945
Jun  3 15:14:26 hadji parity[2508]: This is a bug. Please report it at:
Jun  3 15:14:26 hadji parity[2508]:     https://github.com/paritytech/parity/issues/new
```
I restarted node.
```
Jun  3 15:19:57 hadji parity[14422]: 2018-06-03 15:19:57  main WARN kvdb_rocksdb  DB has been previously marked as corrupted, attempting repair
Jun  3 15:19:57 hadji parity[14422]: 2018-06-03 15:19:57   INFO miner  Updated conversion rate to Ξ1 = US$609.61 (7811396 wei/gas)
Jun  3 15:35:36 hadji parity[14422]: 2018-06-03 15:35:36  main WARN kvdb_rocksdb  DB corrupted: Invalid argument: You have to open all column families. Column families not opened: col5, col4, col6, col3, col2, col0, col1, attempting repair
Jun  3 15:51:20 hadji parity[14422]: Client service error: Client(Database(Error(Msg("Received null column family handle from DB."), State { next_error: None, backtrace: None })))
```
 
I executed ```parity db kill``` using 1.10.4
I upgraded to 1.11.1 beta.  I had to empty cache and snapshot folders before the chain would start syncing.

**Comment by Tbaut** [comment] 2018-06-04 10:08
This is a duplicate of https://github.com/paritytech/parity/issues/7748 Please follow this thread.

**Closed by Tbaut** 2018-06-04 10:08 UTC
Labels: M4-core, Z7-duplicate
