### ISSUE TITLE
Parity Crashes during sync

### ISSUE THREAD

**Issue by nicholasfoden** [paritytech/parity#7095] opened 2017-11-20 07:59 UTC
_Before filing a new issue, please **provide the following information**._

> I'm running:
>
> - **Parity version**: v1.8.3-beta-b49c44a-20171114
> - **Operating system**: Windows 10 x64
> - **And installed**: via installer 

During warp restore, 
Also happens immediately when --no-warp is set

Thread 'IO Worker #2' panicked at 'nonce will return Some when given BlockId::Latest. nonce was given BlockId::Latest. Therefore nonce has returned Some; qed', src\libcore\option.rs:819

stack backtrace:
   0:     0x7ff6a6c12054 - hid_error
   1:     0x7ff6a6c1255b - hid_error
   2:     0x7ff6a6431134 - <no info>
   3:     0x7ff6a6d8b564 - hid_error
   4:     0x7ff6a6d8b3d9 - hid_error
   5:     0x7ff6a6d8b2b2 - hid_error
   6:     0x7ff6a6d8b220 - hid_error
   7:     0x7ff6a6d94b0f - hid_error
   8:     0x7ff6a6d94b80 - hid_error
   9:     0x7ff6a6810798 - <no info>
  10:     0x7ff6a67155c4 - <no info>
  11:     0x7ff6a671e4d3 - <no info>
  12:     0x7ff6a6707fdf - <no info>
  13:     0x7ff6a6709710 - <no info>
  14:     0x7ff6a6695509 - <no info>
  15:     0x7ff6a65688fb - <no info>
  16:     0x7ff6a656ec6a - <no info>
  17:     0x7ff6a6d8cb12 - hid_error
  18:     0x7ff6a65c20c6 - <no info>
  19:     0x7ff6a6d8964c - hid_error
  20:     0x7ffa79512774 - BaseThreadInitThunk

**Comment by 5chdn** [comment] 2017-11-20 11:54
Duplicate of #5968

Duplicate of #6503

Duplicate of #6899

**Closed by 5chdn** 2017-11-20 11:54 UTC
