### ISSUE TITLE
Parity can't generate token for UI and fails with obscure UTF-8 message

### ISSUE THREAD

**Issue by pietervdvn** [paritytech/parity#5617] opened 2017-05-14 17:35 UTC
Suddenly, the parity client would not load the ui anymore, syncing works fine though (running parity without ui)

Full error message when running `parity ui`:

      Error generating token: Error { repr: Custom(Custom { kind: InvalidData, error: StringError("stream did not contain valid UTF-8") }) }

version Parity/v1.6.6-beta-8c6e3f3-20170411/x86_64-linux-gnu/rustc1.16.

If you guys want some files or debug output, please provide instructions. (I tried to get somewhat more verbose output with `-l=trace` and equivalents, but that didn't seem to do anything)

**Comment by tomusdrw** [comment] 2017-05-15 08:12
Could you check if this file: `~/.local/share/io.parity.ethereum/signer/authcodes` is a valid text file?
Does removing (please make a backup) the file fix the problem?

**Comment by 5chdn** [comment] 2017-05-15 10:19
You need to tell which module should be logged, i.e., `-lsigner=trace`. (This said, I'm not sure whether this is a signer issue.)

**Comment by pietervdvn** [comment] 2017-05-15 11:22
@tomusdrw : Spot on: it is not a valid text file, it contains garbage. Removing authcodes indeed fixes the UI, and I can (again) access my wallet. I still have a copy of it, if you want it, I can send it to you in PM to debug.

@5chdn : Yes, I know, but even enabling each module did not give any output. I saw [your post on stackexchange](https://ethereum.stackexchange.com/questions/3331/how-to-make-parity-write-logs) and tried -levery,module,ever=trace, but this _still_ didn't give any extra output.

**Comment by tomusdrw** [comment] 2017-05-15 11:26
@pietervdvn Yes, please send me a copy. Is it possible that your disk got corrupted?
Closing since the issue is solved, I double checked the code and it's not possible to generate a non-text file, so it must be caused by some external software.

**Closed by tomusdrw** 2017-05-15 11:26 UTC
Labels: Z5-unconfirmed
