### ISSUE TITLE
trezor hardware wallet will not authorize transactions

### ISSUE THREAD

**Issue by davethefixer** [paritytech/parity#7995] opened 2018-02-23 22:07 UTC
_Before filing a new issue, please **provide the following information**._

> I'm running:  windows 10  Microsoft edge 41.16299.248.0
>
> - **Which Parity version?**Parity v1.9.0-20180125 beta

: > - **Which operating system?**: Windows 
> - **How installed?**: via installer
> - **Are you fully synchronized?**: / yes
> - **Which network are you connected to?**: ethereum
> - **Did you try to restart the node?**: yes

_Your issue description goes here below. Try to include **actual** vs. **expected behavior** and **steps to reproduce** the issue._
trezor hardware wallet will not authorize transactions
when attempting to send eth/tokens everythings good until "parity signer" page.
when the "confirm request" button is pressed a small red banner at the bottom of the screen appears 
saying "[-32602] Invalid params: invalid type: null, expected a string."

nothing happens on the trezor hardware wallet  
so it would appear that the signer is not passing info to the trezor hardware device.

![2018-02-23](https://user-images.githubusercontent.com/10480142/36619176-c72d657c-18e5-11e8-8129-7e9c3315e399.png)

**Comment by 5chdn** [comment] 2018-02-28 14:46
Can you try if it works with 1.8.10?

**Comment by davethefixer** [comment] 2018-03-01 21:05
hi
  yes Trezor works perfectly on 1.8.10

**Comment by ghettodev** [comment] 2018-03-02 02:54
I'm having this issue on all versions of Parity after 1.8.10, including betas.

This issue duplicates #7852

> Which Parity version?:  > Parity/v1.8.10
> Which operating system?: Ubuntu 17.10
> How installed?: parity_*_ubuntu.deb
> Are you fully synchronized?: Yes
> Which network are you connected to?: Ethereum Foundation
> Did you try to restart the node?: Yes

**Comment by 5chdn** [comment] 2018-03-29 11:04
Duplicate of #7852

**Closed by 5chdn** 2018-03-29 11:04 UTC
Labels: F2-bug, M7-ui, P5-sometimesoon
