### ISSUE TITLE
Parity Archive Mode memory consumption

### ISSUE THREAD

**Issue by abrahamchaibi** [paritytech/parity#8195] opened 2018-03-22 18:18 UTC
_Before filing a new issue, please **provide the following information**._

> I'm running:
>
> - **Which Parity version? v1.9.5-unstable-2acfdfc-20180314
> - **Which operating system? Linux
> - **How installed?**: from source
> - **Are you fully synchronized?**: yes
> - **Which network are you connected to?**: ethereum
> - **Did you try to restart the node?**: yes

_Your issue description goes here below. Try to include **actual** vs. **expected behavior** and **steps to reproduce** the issue._

```2018-03-22 07:01:41  Imported #5301507 7dc0…5494 (115 txs, 7.97 Mgas, 183.73 ms, 17.97 KiB)
2018-03-22 07:02:00  Imported #5301508 2857…6367 (14 txs, 0.69 Mgas, 20.65 ms, 2.93 KiB)

====================

stack backtrace:
   0:     0x55b9721ef54c - backtrace::backtrace::trace::h7fe757c5a8cb7109
   1:     0x55b9721eebf2 - backtrace::capture::Backtrace::new::hd7f0642352dfc6dd
   2:     0x55b9718c58e5 - panic_hook::panic_hook::h0724e12d078acbd2

Thread 'Verifier #1' panicked at 'DB flush failed.: Error(Msg("IO error: No space left on deviceWhile appending to file: /home/dexterity/.local/share/io.parity.ethereum/chains/ethereum/db/906a34e69aec8c0d/archive/db/449871.sst: No space left on device"), State { next_error: None, backtrace: None })', /checkout/src/libcore/result.rs:916

This is a bug. Please report it at:

    https://github.com/paritytech/parity/issues/new
```

My node just ran out of memory. It is running on a 1tb ssd and df -h returns the following:

```dexterity@dexterityOffice:~/parity$ df -h
Filesystem      Size  Used Avail Use% Mounted on
udev            7.8G     0  7.8G   0% /dev
tmpfs           1.6G  158M  1.4G  10% /run
/dev/nvme0n1p2  923G  875G  1.6G 100% /
tmpfs           7.8G   12M  7.8G   1% /dev/shm
tmpfs           5.0M  4.0K  5.0M   1% /run/lock
tmpfs           7.8G     0  7.8G   0% /sys/fs/cgroup
/dev/nvme0n1p1  511M  3.5M  508M   1% /boot/efi
tmpfs           1.6G   72K  1.6G   1% /run/user/1000```

Appears that as of today parity can no longer be run in archive mode on a 1 tb ssd? Just want to make sure I am not doing anything grossly stupid and unfortunately I do not know anyone else running an archive node.

Actual behaviour: node crashes (out of memory)
Expected behaviour: node does not crash (uses < 1tb memory)

**Comment by 5chdn** [comment] 2018-03-23 10:28
Can confirm, our archive nodes also hit that threshold. It's no. 1 on our priority list.

Duplicate of #7967

For now, get a 2TB SSD to survive another 3 months :)

**Closed by 5chdn** 2018-03-23 10:28 UTC
Labels: M2-config, Z0-question
