### ISSUE TITLE
Multi-sig wallet not correctly setting an unlimited withdrawal rate during creation in Parity desktop client

### ISSUE THREAD

**Issue by pyskell** [paritytech/parity#6279] opened 2017-08-10 18:30 UTC
> I'm running:
>
> - **Parity version**: Parity//v1.7.0-beta-5f2cabd-20170727/x86_64-windows-msvc/rustc1.18.0
> - **Operating system**: Windows 7
> - **And installed**: via installer
---
Expected behavior: Unticking the box next to "wallet daily limit" when creating a multi-sig contract should result in a contract with a very large withdrawal limit (effectively unlimited).

![image](https://user-images.githubusercontent.com/9665963/29185559-9979adce-7dd7-11e7-9a17-4f7992c8bd0e.png)

Actual behavior: Unticking that box results in a contract that has a daily withdrawal limit of 1 ETH.

Workaround: Leave the box ticked and manually specify a very large withdrawal limit.

Example: ![image](https://user-images.githubusercontent.com/9665963/29185651-dcbb9688-7dd7-11e7-9e1e-907b7982b488.png)

Two live ETC network examples because the first time I thought I had made a mistake :smile:: 
1. http://gastracker.io/contract/0x136d2ac8a59727176d1bc577f19ff9507d60571e
2. http://gastracker.io/contract/0x75490e07954b2d8843184785ae68a6af3dd4f040

I know I can have other owners make a function call to change it, but in this case it was just easier to redeploy. So I haven't tested making that same change from the Parity desktop client, it probably warrants checking as well.

**Comment by 5chdn** [comment] 2017-08-11 07:15
Duplicate of #5433. This is a usability issue, I acknowledge that. The switch on the left is not enabling or disabling the daily withdrawal limit, but it switches between ETH and Wei (or ETC and Wei in this case).

1000000000000000000 means 1 ETH. If you want to disable the daily limit, set it to 0.

**Closed** 2017-08-11 07:15 UTC
Labels: Z0-duplicate
