### ISSUE TITLE
Bug during Sync

### ISSUE THREAD

**Issue by ja-weber** [paritytech/parity#7833] opened 2018-02-07 15:58 UTC
Hello,

I want to report a bug.

Parity version 1.9.2
Call: docker run -d -p 8545:8545 parity/parity:v1.9.2 --rpcaddr=0.0.0.0 --rpcport=8545 --mode active --light

====================

stack backtrace:
   0:     0x55b5d68a1cec - <no info>
   1:     0x55b5d68a1d22 - <no info>
   2:     0x55b5d68a0d89 - <no info>

Thread '<unnamed>' panicked at 'all back-references to answered requests have been filled; qed: NoSuchOutput', /checkout/src/libcore/result.rs:906

It happens during syncing this block:

2018-02-07 15:41:05 UTC Syncing  #686361 0995…6b74   674 hdr/s  30057+    0 Qed   #686361   25/50 peers     10 MiB cache   25 MiB queue  RPC:  0 conn,  0 req/s, 130 µs
2018-02-07 15:41:10 UTC Syncing  #689662 ab9f…eb64   660 hdr/s  26882+    0 Qed   #689662   25/50 peers     10 MiB cache   23 MiB queue  RPC:  0 conn,  7 req/s, 130 µs
2018-02-07 15:41:15 UTC Syncing  #691059 f0d0…df11   279 hdr/s  27280+    0 Qed   #691059   19/50 peers     10 MiB cache   23 MiB queue  RPC:  0 conn,  4 req/s, 130 µs

**Comment by 5chdn** [comment] 2018-02-09 09:45
Duplicate of #7416

**Comment by 5chdn** [comment] 2018-02-09 09:45
Try nightly (1.10)

**Closed by 5chdn** 2018-02-09 09:45 UTC
