### ISSUE TITLE
eth.getBlock("X") starts to return null for a given block

### ISSUE THREAD

**Issue by gitsparty** [paritytech/parity#8079] opened 2018-03-09 00:47 UTC
> I'm running:
>
> - **Which Parity version?**: 1.8.9
> - **Which operating system?**: Windows
> - **How installed?**: via installer
> - **Are you fully synchronized?**: yes
> - **Which network are you connected to?**: ropsten
> - **Did you try to restart the node?**: no

**Actual**
I started syncing ropsten network. Side-by-side, I could lookup a block X, in the console, by doing eth.getBlock("X"). However, after a few minutes, the lookup stopped working. 

**Expected**
I understand that older blocks may not have been synced. But, why would a block that was query-able once disappear?

In addition, i don't understand how the following could be true. Sync is complete/not running, and I can't query a block. 

```
> eth.syncing
false
> eth.getBlock("2699220")
null
```
**steps to reproduce**
Unknown

**Comment by rphmeier** [comment] 2018-03-09 15:51
@gitsparty did your node warp sync in the meantime? it will actually discard downloaded blocks when it does that (although we are already working on fixing that -- #6350

**Comment by gitsparty** [comment] 2018-03-10 03:49
It was downloading snapshot when ```eth.getBlock("X")``` was working. Sometime after the snapshot restore was complete, ```eth.getBlock("X")``` stopped working. **Note:** I had not specified ```--warp``` in the cmdline.

**Comment by rphmeier** [comment] 2018-03-11 15:37
@gitsparty ok, going to close as a duplicate of #6350 then

**Closed by rphmeier** 2018-03-11 15:37 UTC
