### ISSUE TITLE
Thread '<unnamed>' panicked at 'index out of bounds: the len is 0 but the index is 1', ethcore/src/ethereum/ethash.rs:537

### ISSUE THREAD

**Issue by stone212** [paritytech/parity#6385] opened 2017-08-26 06:01 UTC
_Before filing a new issue, please **provide the following information**._

> I'm running:
>
> - **Parity version**: 1.8.0
> - **Operating system**: Linux
> - **And installed**: from source

_Your issue description goes here below. Try to include **actual** vs. **expected behavior** and **steps to reproduce** the issue._

---

Parity starts up fine on a custom genesis file.  Then I invoke open-ethereum-pool (https://github.com/sammy007/open-ethereum-pool) and Parity instantly crashes.  This is the output from Parity:

```
stack backtrace:
   0:     0x55d7d7934d9c - backtrace::backtrace::trace::h18b17b72e62d3e01

Thread '<unnamed>' panicked at 'index out of bounds: the len is 0 but the index is 1', ethcore/src/ethereum/ethash.rs:537

This is a bug. Please report it at:

    https://github.com/paritytech/parity/issues/new
```

I am reporting the bug as requested.

**Comment by 5chdn** [comment] 2017-08-26 17:49
Duplicate of #6239

**Closed by 5chdn** 2017-08-26 17:49 UTC
