### ISSUE TITLE
Parity/Raspbian - terminate called after throwing an instance of 'std::bad_alloc'

### ISSUE THREAD

**Issue by alaflam** [paritytech/parity#6496] opened 2017-09-11 13:13 UTC
> I'm running:
>
> - **Parity version**: v1.6.8-beta-c396229-20170608
> - **Operating system**: Linux ARM Raspberry Pi3
> - **And installed**: via installer all in one Raspbian (lite) and Parity ([https://github.com/diglos/pi-gen])

I tried for more than 8 days 24h/24 h to sync a node on my Raspberry and arrive after multiple failures only to 2418000 block on Homestead.
I also installed VNC server to connect to my raspberry to check the progress of the process and it seems like the process was sleeping or failed each time before I re-connect to VNC.
I analysed the logs and I see that I often get "full memory error".  
Thinking that it could be caused by the warp recovery (never reaching 100%), I tried with no-warp and it seems more stable except I got very often this error: 
parity[11158]: terminate called after throwing an instance of 'std::bad_alloc'
parity[11158]: what():  std::bad_alloc
systemd[1]: parity.service: main process exited, code=killed, status=6/ABRT
systemd[1]: Unit parity.service entered failed state.

Has someone succeed in achieving blockchain synchronization with Parity on Raspberry and how ?
I'm about to give away.

**Comment by rphmeier** [comment] 2017-09-11 13:16
@alaflam this indicates that the Pi has run out of memory. The blocks you're reaching were part of last fall's attacks and contain very resource-heavy transactions. Given the current volume of the Ethereum chain, I don't think it's reasonable to expect to run a full node on a raspberry pi. You could try running a light client on the Pi, though.

**Comment by rphmeier** [comment] 2017-09-11 13:17
(More generally, this is a duplicate of other memory-related footprint issues)

**Closed by rphmeier** 2017-09-11 13:16 UTC
Labels: M4-core, Z0-question

**Comment by arkpar** [comment] 2017-09-13 12:57
parity 1.7.0 uses less memory by default and should run fine on a Raspberry Pi
