### ISSUE TITLE
[enhancement] Cache password for parity

### ISSUE THREAD

**Issue by adrianbrink** [paritytech/parity#4948] opened 2017-03-17 14:13 UTC
I'm deploying and calling numerous contracts and it is very tedious to always have to copy & paste my password to unlock my account. (Yeah, I am using a super secure password :) )

It would be cool to have the option to unlock the account for a period of time or generally always leave the account in an unlocked state. 

Of course this shouldn't be default behaviour and should probably be mutually exclusive with the ability to listen on all network interfaces. However I do think there is value behind allowing this when the parity node is listening on the local network interfaces.

**Comment by rphmeier** [comment] 2017-03-19 20:06
Duplicate of https://github.com/paritytech/parity/issues/4574

**Closed by rphmeier** 2017-03-19 20:06 UTC
Labels: F8-enhancement, M6-rpcapi
