### ISSUE TITLE
most recent warp snapshot too old 

### ISSUE THREAD

**Issue by SnowLeopard71** [paritytech/parity#7561] opened 2018-01-15 07:44 UTC
> - **Which Parity version?**:  v1.8.5-beta-54bae9a-20171228
> - **Which operating system?**: Windows 7 64-bit
> - **How installed?**: via installer 
> - **Are you fully synchronized?**: no 
> - **Which network are you connected to?**: ethereum 
> - **Did you try to restart the node?**: no 

Long-story short, old ssd was too small, now on new bigger and restarting from scratch.
The "warp" appears to have worked okay, taking only 22 minutes from 0/671 to 668/671 before going into "Synching" mode from block 4230000.
So far though, it has gone up to only 4244269 after 35 minutes (just over 400 blocks per min), and the latest block is 4911426, so 667157 blocks to go, which will take over 27 hours to catch up completely.
Is there a way to get the warp snapshot to deliver blocks up to at least the current week instead of from several months ago?
Is there any other way to speed up the synching or is how it will be for all new users?  (Quite a welcome to have to wait 24 hours for software to install and become usable.)

2018-01-15 01:35:29  Syncing snapshot 0/671        #0    1/25 peers      8 KiB chain    3 MiB db  0 bytes queue   10 KiB sync  RPC:  0 conn,  0 re                                                                      q/s,   0 µs
2018-01-15 01:57:50  Syncing snapshot 668/671        #0   24/25 peers      8 KiB chain    3 MiB db  0 bytes queue   10 KiB sync  RPC:  0 conn,  0 req/s, 335 µs
2018-01-15 01:57:55  Syncing #4230000 ffaa…3016     0 blk/s    0 tx/s   0 Mgas/s      0+    0 Qed        #0   24/25 peers     20 KiB chain    1 KiB db  0 bytes queue   10 KiB sync  RPC                                :  0 conn,  0 req/s, 335 µs
2018-01-15 02:33:09  Syncing #4244269 67e2…4c82     2 blk/s  375 tx/s  14 Mgas/s    211+ 1383 Qed  #4245874   25/25 peers      6 MiB chain   78 MiB db  167 MiB queue   66 MiB sync  RPC:  1 conn, 21 req/s, 246830 µs

**Comment by 5chdn** [comment] 2018-01-16 10:23
Yeah, annoying. Please remove your nodes.json and try again.

Duplicate of #7436

**Closed by 5chdn** 2018-01-16 10:23 UTC

**Comment by SnowLeopard71** [comment] 2018-01-16 17:04
Will that speed anything up?
Maybe you should put a warning about it taking 24-48 hours to become usuable?
Is there a less retarded wallet for Ethereum that does not take so long to get working?

**Comment by 5chdn** [comment] 2018-01-17 11:45
> Will that speed anything up?

Yes!

> Is there a less retarded wallet for Ethereum that does not take so long to get working?

Sure, https://wallet.parity.io :)
