### ISSUE TITLE
dockerhub ethcore/parity:v1.6.8 contains version 1.7.0 nightly

### ISSUE THREAD

**Issue by vincentserpoul** [paritytech/parity#5845] opened 2017-06-15 06:50 UTC
tags mismatch

**Comment by 5chdn** [comment] 2017-06-15 08:45
duplicate of #5435

FYI, we are moving the repository to parity/parity. You can test this by getting it via:

    $ docker run parity/parity:v1.6.8

This already fetches the correct version.

**Closed** 2017-06-15 08:45 UTC
Labels: Z0-duplicate
