### ISSUE TITLE
Bug: Crash - Corruption: block checksum mismatch

### ISSUE THREAD

**Issue by metanoid** [paritytech/parity#7927] opened 2018-02-17 21:12 UTC
> I'm running:
>
> - **Which Parity version?**:  v1.9.0-20180125 beta
> - **Which operating system?**: Windows 
> - **How installed?**: via installer
> - **Are you fully synchronized?**: no
> - **Which network are you connected to?**: ethereum 
> - **Did you try to restart the node?**: yes

_Your issue description goes here below. Try to include **actual** vs. **expected behavior** and **steps to reproduce** the issue._

Running parity from command line gives the below output:

```
stack backtrace:
   0:     0x7ff62cfa3afa - hid_error
   1:     0x7ff62cfa3f93 - hid_error
   2:     0x7ff62c813da6 - <no info>
   3:     0x7ff62d1cd3f3 - hid_error
   4:     0x7ff62d1cd271 - hid_error
   5:     0x7ff62d1cd152 - hid_error
   6:     0x7ff62d1cd0c5 - hid_error
   7:     0x7ff62d1d5e6f - hid_error
   8:     0x7ff62cbe52d9 - <no info>
   9:     0x7ff62cc8bba2 - <no info>
  10:     0x7ff62cb9908c - <no info>
  11:     0x7ff62cba2aea - <no info>
  12:     0x7ff62d1ce812 - hid_error
  13:     0x7ff62cbe5c11 - <no info>
  14:     0x7ff62d1cb37c - hid_error
  15:     0x7ff828301fe4 - BaseThreadInitThunk

Thread 'IO Worker #1' panicked at 'DB flush failed.: Error(Msg("Corruption: block checksum mismatch: expected 3921887865, got 3339666307  in D:\\Ethereum\\chains\\ethereum\\db\\906a34e69aec8c0d\\overlayrecent\\db/002164.sst offset 195170642 size 51896"), State { next_error: None, backtrace: None })', src\libcore\result.rs:906

This is a bug. Please report it at:

    https://github.com/paritytech/parity/issues/new
```

**Comment by 5chdn** [comment] 2018-02-19 11:23
Duplicate of #7766

**Closed by 5chdn** 2018-02-19 11:23 UTC
Labels: M4-core, Z0-duplicate
