### ISSUE TITLE
eth_getTransactionCount returns wrong value for Morden testnet

### ISSUE THREAD

**Issue by gagarin55** [paritytech/parity#7002] opened 2017-11-08 09:33 UTC
> I'm running:
>
> - **Parity version**: Parity 1.8.2-beta
> - **Operating system**: Linux
> - **And installed**: via binaries

Being running as `parity --chain=morden` on `eth_getTransactionCount` RPC call it returns **0x100000** for addresses never used before.

According [Ethereum JSON-RPC specification](https://github.com/ethereum/wiki/wiki/JSON-RPC#eth_gettransactioncount) this method should returns _number of transactions sent from address_.
For new address it is **0x00**

---

**Comment by Office-Julia** [comment] 2017-11-09 13:50
Hello. 
Let me assist you in resolving your question.

First of all, Morden is very old chain, it is advised not to use it anymore and give a preference to Ropsten or Kovan test chains.

You can still use Morden at your own risk - though you need to be aware of the fact that that transaction count (& nonce) has been offset from the start for replay protection, so it is not a bug, it is by design.

Regards,
Julia.

**Comment by Office-Julia** [comment] 2017-11-09 13:52
Please confirm are you using ETC or ETH?

**Comment by 5chdn** [comment] 2017-11-13 11:07
It sounds like some messy nonce-handling.

Should it always return 0x0 on main net or on all networks?

**Comment by tomusdrw** [comment] 2017-11-13 11:20
We were explicitly fixing that to return a network `nonce` (so `start_nonce + no_of_transactions_sent`; see https://github.com/paritytech/parity/issues/1825), please cross check with geth implementation if that's the *actual* behaviour on their client, maybe just documentation needs updating.

**Closed** 2017-11-13 11:21 UTC
Labels: M6-rpcapi, Z0-question

**Comment by gagarin55** [comment] 2017-11-14 21:15
But why? Really, you have method with name **get transaction count** which returns something else, why ?

**Comment by tomusdrw** [comment] 2017-11-14 21:35
When `morden` network was started there was no replay protection scheme implemented. To prevent replay protection though, `account_start_nonce` was introduced, which technically can be described as introducing `account_start_nonce` dummy transactions that were sent from that particular account.

I'm all in for returning a correct value, but we should also maintain compatibility with other implementations, that's why I suggested checking what geth is returning on morden (cause I remember we were compatible with that at some point in the past).

If both implementations return `nonce` we should update the docs (possibly even consider renaming the method) otherwise feel free to re-open that bug and we will fix it.
