### ISSUE TITLE
Thread 'main' panicked at 'called `Option::unwrap()` on a `None` value', src\libcore\option.rs:335

### ISSUE THREAD

**Issue by Quantenkosmos** [paritytech/parity#7429] opened 2018-01-02 21:30 UTC
_Before filing a new issue, please **provide the following information**._

> I'm running:
>
> - Starting Parity/v1.8.5-beta-54bae9a-20171228/x86_64-windows-msvc/rustc1.22.1
> - Win 10, 64
> - via installer 
> - **Are you fully synchronized?**: no
> - **Did you try to restart the node?**: yes

starting with follwoing config.toml

[parity]
mode = "last"
mode_timeout = 600
mode_alarm = 3600
auto_update = "none"
release_track = "current"
public_node = false
no_download = false
no_consensus = false
no_persistent_txqueue = false

[footprint]
tracing = "auto"
pruning = "auto"
pruning_history = 64
pruning_memory = 5000
cache_size_db = 1024
cache_size_blocks = 80
cache_size_queue = 100
cache_size_state = 150
cache_size = 4096 # Overrides above caches with total size
fast_and_loose = false
db_compaction = "ssd"
fat_db = "auto"
scale_verifiers = true
num_verifiers = 3

chain = "homestead"

base_path = "D:/crypto/ETH/Ethereum"

[network]
port = 30303
min_peers = 25
max_peers = 150
nat = "any"
id = 1
bootnodes = []
discovery = true
warp = true
allow_ips = "all"
snapshot_peers = 20
max_pending_peers = 64
no_serve_light = false

reserved_only = false

---------

stack backtrace:
   0:     0x7ff746e24612 - hid_error
   1:     0x7ff746e24af3 - hid_error
   2:     0x7ff74665b634 - <no info>
   3:     0x7ff746f950e4 - hid_error
   4:     0x7ff746f94f59 - hid_error
   5:     0x7ff746f94e32 - hid_error
   6:     0x7ff746f94da0 - hid_error
   7:     0x7ff746f9e39f - hid_error
   8:     0x7ff746f9e2cf - hid_error
   9:     0x7ff746a1f09a - <no info>
  10:     0x7ff7468a75c2 - <no info>
  11:     0x7ff746953985 - <no info>
  12:     0x7ff7464133aa - <no info>
  13:     0x7ff74642dbe7 - <no info>
  14:     0x7ff74643353a - <no info>
  15:     0x7ff746436a87 - <no info>
  16:     0x7ff746f96572 - hid_error
  17:     0x7ff746f958e2 - hid_error
  18:     0x7ff747190279 - hid_write
  19:     0x7ffb09771fe4 - BaseThreadInitThunk

Thread 'main' panicked at 'called `Option::unwrap()` on a `None` value', src\libcore\option.rs:335

This is a bug. Please report it at:

    https://github.com/paritytech/parity/issues/new

**Comment by 5chdn** [comment] 2018-01-03 13:17
Duplicate of #7340

**Closed by 5chdn** 2018-01-03 13:17 UTC
