### ISSUE TITLE
Crash on RPC call

### ISSUE THREAD

**Issue by kondratovich** [paritytech/parity#6381] opened 2017-08-25 11:40 UTC
> I'm running:
>
> - **Parity version**: version Parity/v1.8.0-nightly-e7a7bd6-20170808/x86_64-macos/rustc1.18.0
> - **Operating system**: MacOS
> - **And installed**: via homebrew

Spam this RPC request for a while.

```
curl --data '{"method":"eth_getBlockByNumber","params":["pending",false],"id":1,"jsonrpc":"2.0"}' -H "Content-Type: application/json" -X POST localhost:8545
```

```
...
2017-08-25 14:36:49  Imported #4202214 8623…8e43 (117 txs, 6.05 Mgas, 170.85 ms, 21.50 KiB)
2017-08-25 14:36:51  Imported #4202215 fd91…54b1 (111 txs, 3.07 Mgas, 142.53 ms, 14.20 KiB)

====================

stack backtrace:

Thread '<unnamed>' panicked at 'index out of bounds: the len is 0 but the index is 1', ethcore/src/ethereum/ethash.rs:537
```

**Comment by 5chdn** [comment] 2017-08-26 09:44
Can you update to latest master?

At what rate are you spamming this call, and why?

**Comment by kondratovich** [comment] 2017-08-26 16:18
I can confirm that last nightly build (Parity/v1.8.0-nightly-5c0f9f1-20170824/x86_64-macos/rustc1.19.0) cashes too.

It's easy reproducible for me, I send requests by hand in console using curl. Sometimes it's enough one request, sometimes 4-5.

I'm not sure, but seems crash happens just after new block.

**Comment by 5chdn** [comment] 2017-08-26 17:48
Duplicate of #6239

**Closed by 5chdn** 2017-08-26 17:48 UTC
Labels: F2-bug, M4-core, M6-rpcapi, Z5-unconfirmed
