### ISSUE TITLE
Parity crashes on wifi reconnect.

### ISSUE THREAD

**Issue by russdirks** [paritytech/parity#5458] opened 2017-04-15 05:43 UTC
I've been running Parity on Windows 10 for about 3-4 months now, and it crashes every 5-10 days, more or less.  Up until about 3 weeks ago I was running an old version of Parity (1.4 I think), but for the last 3 weeks I've been running 1.6.5.  It has crashed 3 times since then.  Here is the latest crash dump:

```
Faulting application name: parity.exe, version: 0.0.0.0, time stamp: 0x58da29f9
Faulting module name: ntdll.dll, version: 10.0.14393.479, time stamp: 0x5825887f
Exception code: 0xc0000374
Fault offset: 0x00000000000f8283
Faulting process id: 0x2cc
Faulting application start time: 0x01d2b3d51af74e1c
Faulting application path: C:\Program Files\Ethereum\Parity\parity.exe
Faulting module path: C:\WINDOWS\SYSTEM32\ntdll.dll
Report Id: 95ab31e1-d6c3-4da7-9cc3-cec171e63a55
Faulting package full name: 
Faulting package-relative application ID:
```

I've used MemTest to test my memory and everything checks out ok.   I tried monitoring RAM useage, and didn't see anything abnormal ... no increased memory useage that I could see.

 My command line is as follows : `--chain=classic --jsonrpc-interface all --jsonrpc-hosts all --jsonrpc-port 8545 --author 0x....`

My .toml file is as follows:
```
chain = "classic"

[rpc]
port = 8545
interface = "all"
hosts = ["all"]

[mining]
author = "0x...."

[network]
bootnodes = ["enode://7ff0a073bf2ee9e94fae86de914eca0c0266c0b7051f4592ff0e9820706a085919ea667459897cde4efe3f0465f608cf402bde861983ce6ae3f9185df371aea7
```

Let me know if you want me to run any diagnostics and special logging.

**Comment by 5chdn** [comment] 2017-05-09 12:29
This issue is labelled with _panic_: The client panics and exits without proper error handling. It's inactive for one month and neither assigned nor linked to a milestone.

@paritytech/core-devs Please, assign a developer to this issue and decided on a deadline within 7 days.

**Comment by russdirks** [comment] 2017-05-09 14:27
Just thought I would mention, since I reported this issue (24 days ago), it has not crashed once.

**Comment by arkpar** [comment] 2017-05-10 12:44
@russdirks Have you been running the same 1.6.5 version all this time?

**Comment by russdirks** [comment] 2017-05-10 14:31
I have been running 1.6.5 since about 3 weeks prior to reporting this issue all the way until now.  In those 3 weeks prior it crashed 3 times.

**Comment by russdirks** [comment] 2017-05-11 19:20
I think I'll close this.  If the problem starts reappearing I'll re-open or file a new issue.

**Comment by russdirks** [comment] 2017-05-28 20:05
I figured out how to  repo the issue ... just kill the wifi connection.  I can make parity crash pretty reliably this way.  Probably what was happening in the past was my wifi connection was dropping out occasionally.  If you can't repo on a test machine let me know how to configure logging and I'll upload.  Just a reminder, this is on Windows 10.

**Comment by 5chdn** [comment] 2017-05-29 09:17
Could you run parity.exe from a command prompt and see what the exact panic message will be?

**Comment by russdirks** [comment] 2017-05-29 16:00
There's no specific error message, just the standard Windows popup saying the program stopped working.

![capture](https://cloud.githubusercontent.com/assets/7891737/26556026/f047ed24-444c-11e7-8be1-b2f5f83d6fe3.PNG)

I checked Windows Event viewer and found this:
```
Faulting application name: parity.exe, version: 0.0.0.0, time stamp: 0x58da29f9
Faulting module name: parity.exe, version: 0.0.0.0, time stamp: 0x58da29f9
Exception code: 0xc0000005
Fault offset: 0x0000000000b51cd0
Faulting process id: 0x374
Faulting application start time: 0x01d2d88d6a0f91ad
Faulting application path: C:\Program Files\Ethereum\Parity\parity.exe
Faulting module path: C:\Program Files\Ethereum\Parity\parity.exe
Report Id: 950ce372-2635-4c0c-a1a6-bea26e1f9e4a
Faulting package full name: 
Faulting package-relative application ID: 
```

**Comment by russdirks** [comment] 2017-06-23 01:46
Just wondering if there has been any progress on this?  Any chance we will see something in the next release?

**Comment by arkpar** [comment] 2017-06-23 08:29
We  could not reproduce this exact issue, but a possible fix has been added to 1.6.8. Could you please check if it still crashes with the latest version?

**Comment by russdirks** [comment] 2017-06-23 18:48
Ok, I just upgraded to 1.6.8, did a complete re-synch, but I am still able to make Parity crash by cutting the wifi connection.

**Comment by brson** [comment] 2018-02-02 21:41
I can't reproduce this on master, commit 0ea1c4157310fbc823359ed769d0dc27ad0cb210, whereas I can on 1.9.0, both built from source.

**Comment by 5chdn** [comment] 2018-02-05 10:55
Thanks for confirming!

**Closed by 5chdn** 2018-02-05 10:55 UTC
Labels: F1-panic, M4-core, P2-asap
