### ISSUE TITLE
Syncing stuck after Stage 4 block verification failed, peers dropping to 0

### ISSUE THREAD

**Issue by pgrzesik** [paritytech/parity#7659] opened 2018-01-22 09:55 UTC
_Before filing a new issue, please **provide the following information**._

> I'm running:
>
> - **Which Parity version?**: 1.7.12
> - **Which operating system?**: Amazon Linux + Docker version 17.06.2-ce, build 3dfb8343b139d6342acfd9975d7f1068b5b1c3d3
> - **How installed?**: Docker
> - **Are you fully synchronized?**: hard to answer, sometimes it's able to fully synchronise but gets stuck after a while
> - **Which network are you connected to?**: kovan
> - **Did you try to restart the node?**: yes

_Your issue description goes here below. Try to include **actual** vs. **expected behavior** and **steps to reproduce** the issue._

Hello,
I'm running setup as in the description above, very often, synchronisation of my kovan parity node gets stuck after getting this:
```2018-01-22 09:36:51 UTC Stage 4 block verification failed for #5505913 (ea49…ebe8)
Error: Block(TemporarilyInvalid(OutOfBounds { min: None, max: Some(1516613808), found: 1516613812 }))
2018-01-22 09:36:57 UTC    0/25 peers      4 MiB chain   69 MiB db  0 bytes queue   54 KiB sync  RPC:  0 conn,  0 req/s,   0 µs
```
After that, peers drop to 0 and there's nothing I can do other than restart machine which sometimes helps, but that's only a temporary solution.

If it will be of any help, here's config that I'm using for running parity:
```
 "--testnet",
        "--jsonrpc-apis", "web3,eth,personal,net",
        "--jsonrpc-hosts", "all",
        "--jsonrpc-interface", "all",
        "--warp",
        "--mode", "active",
        "--tracing", "off",
        "--pruning", "fast",
        "--db-compaction", "ssd"
```

**Comment by 5chdn** [comment] 2018-01-22 10:12
Duplicate of #7527 

Please downgrade to 1.8.5 or wait for 1.9.0

**Closed by 5chdn** 2018-01-22 10:12 UTC

**Comment by rstormsf** [comment] 2018-01-27 02:33
@5chdn it still doesn't work even in 1.9.0
