### ISSUE TITLE
Server Shutdown Parity is Scanning Private network

### ISSUE THREAD

**Issue by ydaniels** [paritytech/parity#7379] opened 2017-12-25 11:10 UTC
_Before filing a new issue, please **provide the following information**._

> I'm running:
>
> - **Which Parity version?**: 1.8.0
> - **Which operating system?**:  Linux
> - **How installed?**: via installer 
> - **Are you fully synchronized?**: no  (JUST syncing)
> - **Did you try to restart the node?**: no  

_
I just started installing parity on another server  but  after a few hours my server was suspended for netscan abuse . Mostly scanning these ips 10.0.0.0,100.64.0.0, 192.168.0.0 port 30303. 
This problem seems to occur with ethereum software nodes including geth

why is parity scanning local networks for other nodes, can running parity in default mode without much flags be made less aggressive. 
Am sure that's what most people would do at first especially if you just want to get it up and running fast for development purpose.

 _

**Comment by tomusdrw** [comment] 2017-12-27 10:19
Please run with `--allow-ips public`. Duplicate of #2478, #7364

**Closed by tomusdrw** 2017-12-27 10:19 UTC
Labels: Z0-duplicate
