### ISSUE TITLE
help-Parity 1.7.10 & 1.7.11 not warping correctly-warping only until block height around 200,000

### ISSUE THREAD

**Issue by zumbatan** [paritytech/parity#7449] opened 2018-01-04 07:47 UTC
_Before filing a new issue, please **provide the following information**._

> I'm running:
>
> - **Which Parity version?**: 1.7.10 / 1.7.11
> - **Which operating system?**: Windows 
> - **How installed?**: via installer 
> - **Are you fully synchronized?**: no 

Expected:  after installing Parity, warping is done relatively fast and then syncing begins and ends in couple hours

Actual:  after installing both parity clients several times deinstalling, re-installing, still no correct warping (warping is being finished while still at block heights around 150,000 till 450,000). This means, Parity starts syncing from 150,000 which is obviuously totally flawed. Warping should bring the client as close as possible to the most current block.

What can be the issue here?

**Comment by 5chdn** [comment] 2018-01-04 09:59
Duplicate of #6372 :(

**Closed by 5chdn** 2018-01-04 09:59 UTC
