### ISSUE TITLE
Parity stopped syncing

### ISSUE THREAD

**Issue by luckymf** [paritytech/parity#6371] opened 2017-08-24 15:14 UTC
> I'm running:
>
> - **Parity version**: 1.7.0-beta
> - **Operating system**: Windows 64-bit
> - **And installed**: via installer

Hi, I have downloaded from https://parity.io/ and installed Windows Parity wallet about 5 days ago, followed the instructions and setup an account "LUCKYMF" (uuid: 71c9ef0a-b2e1-8477-5ff9-7965c0296cef). I needed to withdraw my ETH tokens from Bittrex.com. So I made a withdrawal request and it suceeded. Thansaction was successful and confirmed soon afterwards (check here https://etherscan.io/tx/0x60dfe8126b93b435ca67fbc454deaac64ef786dcb17e7a98f4aa2985e7e504d5). All these days passed and my Parity account ballance is still empty. The first 2 or 3 days I was noticing that syncing was working, slowly but working. But the last 24 hours I watched the "status" page  and the best block got stuck on #2,398,524 out of more then 4 million. I tried to restart the application, refresh Parity page, restarted my PC several times, but it wouldn't move. The application was installed on a system "C" drive, and it shows only around 8GB of free disk space, maybe that is the reason? I really need the ETH funds which I have sent as fast as possible. Can you help me out in this situation? 
![parityscr1](https://user-images.githubusercontent.com/31316078/29673351-a43b55fc-88f7-11e7-9e4f-db22ef9e4341.png)

**Comment by 5chdn** [comment] 2017-08-25 08:12
You are not synchronized. Could you scroll down on the status page to the bottom, enable the logs and paste them here?

**Comment by luckymf** [comment] 2017-08-25 10:20
[25.08.2017, 13:19:03]Syncing snapshot 1/400 #2399226 7/25 peers 5 MiB
chain 61 MiB db 0 bytes queue 10 KiB sync RPC: 1 conn, 8 req/s, 137 µs

[25.08.2017, 13:18:53]Syncing snapshot 1/400 #2399226 6/25 peers 5 MiB
chain 61 MiB db 0 bytes queue 10 KiB sync RPC: 1 conn, 7 req/s, 138 µs

[25.08.2017, 13:18:43]Syncing snapshot 1/400 #2399226 6/25 peers 5 MiB
chain 61 MiB db 0 bytes queue 10 KiB sync RPC: 1 conn, 9 req/s, 310 µs

[25.08.2017, 13:18:33]Syncing snapshot 1/400 #2399226 6/25 peers 5 MiB
chain 61 MiB db 0 bytes queue 10 KiB sync RPC: 1 conn, 8 req/s, 243 µs

[25.08.2017, 13:18:23]Syncing snapshot 1/400 #2399226 4/25 peers 5 MiB
chain 61 MiB db 0 bytes queue 10 KiB sync RPC: 1 conn, 8 req/s, 154 µs

[25.08.2017, 13:18:13]Syncing snapshot 1/400 #2399226 5/25 peers 4 MiB
chain 61 MiB db 0 bytes queue 10 KiB sync RPC: 1 conn, 8 req/s, 281 µs

[25.08.2017, 13:18:03]Syncing snapshot 1/400 #2399226 4/25 peers 4 MiB
chain 61 MiB db 0 bytes queue 10 KiB sync RPC: 1 conn, 7 req/s, 135 µs

[25.08.2017, 13:17:53]Syncing snapshot 0/400 #2399226 4/25 peers 4 MiB
chain 61 MiB db 0 bytes queue 10 KiB sync RPC: 1 conn, 6 req/s, 129 µs

[25.08.2017, 13:17:43]Syncing snapshot 0/400 #2399226 4/25 peers 4 MiB
chain 61 MiB db 0 bytes queue 10 KiB sync RPC: 1 conn, 5 req/s, 116 µs

[25.08.2017, 13:17:33]Syncing snapshot 0/400 #2399226 3/25 peers 4 MiB
chain 61 MiB db 0 bytes queue 10 KiB sync RPC: 1 conn, 9 req/s, 383 µs

[25.08.2017, 13:17:28]Public node URL: enode://
df8e086c142326702294d9d7fc152155f16044ed1fcb1924d6b3066223747292dc240af4bb60dac08be32149921ef4f8641519ee77ea321ee3fa66e21cfd1ff5@127.0.0.1:30303

[25.08.2017, 13:17:19]Updated conversion rate to Ξ1 = US$331.12 (359530140
wei/gas)

[25.08.2017, 13:17:18]Configured for Foundation using Ethash engine

[25.08.2017, 13:17:18]Operating mode: passive

[25.08.2017, 13:17:18]State DB configuration: fast

[25.08.2017, 13:17:18]Path to dapps
C:\Users\LUCKY\AppData\Roaming\Parity\Ethereum\dapps

[25.08.2017, 13:17:18]DB path
C:\Users\LUCKY\AppData\Local\Parity\Ethereum\chains\ethereum\db\906a34e69aec8c0d

[25.08.2017, 13:17:18]Keys path
C:\Users\LUCKY\AppData\Roaming\Parity\Ethereum\keys\Foundation

[25.08.2017, 13:17:18]Starting
Parity/v1.7.0-beta-5f2cabd-20170727/x86_64-windows-msvc/rustc1.18.0

2017-08-25 11:12 GMT+03:00 Afri <notifications@github.com>:

**Comment by 5chdn** [comment] 2017-08-25 10:29
Log shows the warp sync just started. Keep it running like that. If the issue persists, please come back with new logs. :)

**Comment by luckymf** [comment] 2017-08-26 13:57
Now got stuck again on block #2,423,899 (not changing more then 30 hrs), the line"Syncing snapshot 166/445 #2423835" is not changing for more then 7  hours. By the way I noticed that every time when my PC goes into sleep mode, parity program stops running and in the morning when I wake up my PC the parity icon dissappears from taskbar. So I have to start over the program, and it starts syncing snapshots. As you can see from logs it has 445 snapshots to sync, but it always gets stuck and never reaches "445/445" value. As far as I understand, block history will not go on syncing before warp restore is completed. What do I do?
Here are the last logs:
[26.08.2017, 16:53:00] Syncing snapshot 166/445 #2423835 17/25 peers 5 MiB chain 103 MiB db 0 bytes queue 21 KiB sync RPC: 1 conn, 8 req/s, 656 µs
[26.08.2017, 16:52:50] 16/25 peers 5 MiB chain 103 MiB db 0 bytes queue 21 KiB sync RPC: 1 conn, 7 req/s, 163 µs
[26.08.2017, 16:52:40] 18/25 peers 5 MiB chain 103 MiB db 0 bytes queue 21 KiB sync RPC: 1 conn, 4 req/s, 180 µs
[26.08.2017, 16:52:30] Syncing snapshot 166/445 #2423835 18/25 peers 5 MiB chain 103 MiB db 0 bytes queue 21 KiB sync RPC: 1 conn, 6 req/s, 180 µs
[26.08.2017, 16:52:20] Syncing snapshot 166/445 #2423835 17/25 peers 5 MiB chain 103 MiB db 0 bytes queue 21 KiB sync RPC: 1 conn, 5 req/s, 127 µs
[26.08.2017, 16:52:10] 16/25 peers 5 MiB chain 103 MiB db 0 bytes queue 21 KiB sync RPC: 1 conn, 4 req/s, 106 µs
[26.08.2017, 16:52:00] 16/25 peers 5 MiB chain 103 MiB db 0 bytes queue 21 KiB sync RPC: 1 conn, 5 req/s, 225 µs
[26.08.2017, 16:51:50] 16/25 peers 6 MiB chain 103 MiB db 0 bytes queue 21 KiB sync RPC: 1 conn, 3 req/s, 148 µs
[26.08.2017, 16:51:40] 16/25 peers 6 MiB chain 103 MiB db 0 bytes queue 21 KiB sync RPC: 1 conn, 3 req/s, 115 µs
[26.08.2017, 16:51:30] 16/25 peers 6 MiB chain 103 MiB db 0 bytes queue 21 KiB sync RPC: 1 conn, 4 req/s, 343 µs
[26.08.2017, 16:51:20] 17/25 peers 6 MiB chain 103 MiB db 0 bytes queue 21 KiB sync RPC: 1 conn, 3 req/s, 94 µs
[26.08.2017, 16:51:10] 18/25 peers 5 MiB chain 103 MiB db 0 bytes queue 21 KiB sync RPC: 1 conn, 3 req/s, 119 µs
[26.08.2017, 16:51:00] 17/25 peers 6 MiB chain 103 MiB db 0 bytes queue 21 KiB sync RPC: 1 conn, 4 req/s, 149 µs
[26.08.2017, 16:50:50] Syncing snapshot 166/445 #2423835 18/25 peers 6 MiB chain 103 MiB db 0 bytes queue 21 KiB sync RPC: 1 conn, 7 req/s, 191 µs
[26.08.2017, 16:50:40] 17/25 peers 6 MiB chain 103 MiB db 0 bytes queue 21 KiB sync RPC: 1 conn, 4 req/s, 192 µs
[26.08.2017, 16:50:30] 18/25 peers 6 MiB chain 103 MiB db 0 bytes queue 21 KiB sync RPC: 1 conn, 6 req/s, 136 µs
[26.08.2017, 16:50:20] 19/25 peers 6 MiB chain 103 MiB db 0 bytes queue 21 KiB sync RPC: 1 conn, 7 req/s, 185 µs
[26.08.2017, 16:50:10] Syncing snapshot 166/445 #2423835 19/25 peers 6 MiB chain 103 MiB db 0 bytes queue 21 KiB sync RPC: 1 conn, 4 req/s, 105 µs
[26.08.2017, 16:50:00] Syncing snapshot 166/445 #2423835 18/25 peers 6 MiB chain 103 MiB db 0 bytes queue 21 KiB sync RPC: 1 conn, 4 req/s, 133 µs
[26.08.2017, 16:49:50] 17/25 peers 6 MiB chain 103 MiB db 0 bytes queue 21 KiB sync RPC: 1 conn, 5 req/s, 205 µs
[26.08.2017, 16:49:40] Syncing snapshot 166/445 #2423835 19/25 peers 6 MiB chain 103 MiB db 0 bytes queue 21 KiB sync RPC: 1 conn, 3 req/s, 113 µs
[26.08.2017, 16:49:31] 18/25 peers 5 MiB chain 103 MiB db 0 bytes queue 21 KiB sync RPC: 1 conn, 4 req/s, 176 µs
[26.08.2017, 16:49:20] 19/25 peers 5 MiB chain 103 MiB db 0 bytes queue 21 KiB sync RPC: 1 conn, 5 req/s, 219 µs
[26.08.2017, 16:49:10] 18/25 peers 5 MiB chain 103 MiB db 0 bytes queue 21 KiB sync RPC: 1 conn, 4 req/s, 122 µs
[26.08.2017, 16:49:00] Syncing snapshot 166/445 #2423835 17/25 peers 5 MiB chain 103 MiB db 0 bytes queue 21 KiB sync RPC: 1 conn, 4 req/s, 128 µs

**Comment by 5chdn** [comment] 2017-08-26 17:53
Duplicate of #6372

**Comment by 5chdn** [comment] 2017-08-26 17:53
You are not alone with these kind of issues, let's track them in #6372 if you don't mind.

**Closed by 5chdn** 2017-08-26 17:53 UTC
Labels: Z0-duplicate
