### ISSUE TITLE
Compilation issues with Mist and parity running in geth compatibility mode

### ISSUE THREAD

**Issue by D-Nice** [paritytech/parity#1968] opened 2016-08-19 19:32 UTC
Cross-referencing this issue at request of @luclu

https://github.com/ethereum/mist/issues/1082

I was informed previously that Mist support may be abandoned, although it would be preferable to stay and quirks be sorted out.

**Comment by 5chdn** [comment] 2017-05-10 09:57
This issue is labelled with _annoyance_: The client behaves within expectations, however this "expected behaviour" itself is at issue. It's inactive since last year, neither assigned nor linked to any milestone.

@paritytech/core-devs Are we keeping geth and mist compatibilty or are we going to drop it at some point? Please, decide within 7 days on a deadline and add an assignee or close it otherwise. Thanks.

**Comment by luclu** [comment] 2017-05-10 10:13
Hi there, we are currently refactoring the IPC endpoint selection in Mist the be node agnostic.

Once merged any node added to Mist's [clientBinaries.json](https://github.com/ethereum/mist/pull/2093/files#diff-e33487aa70598f95497e969cdd109b0a) will be recognized with any arbitrary dataDir/ipc-socket/etc specified in the JSON file.

**Closed** 2017-06-22 10:16 UTC
Labels: F3-annoyance, M4-core, P9-somedaymaybe, Q9-epic
