### ISSUE TITLE
Parity crashes at startup

### ISSUE THREAD

**Issue by UGatgithub** [paritytech/parity#8207] opened 2018-03-23 19:42 UTC
Hi, my parity crashes at startup. PC restart uninstall and reinstall Parity did not help.
I had to reset my home network this week and don't know if it is related to that.

> I'm running:
>
> - **Which Parity version?**: v1.9.5-stable-ff821daf1-20180321/x86_64-windows-msvc/rustc1.24.1
> - **Which operating system?**: Windows
> - **How installed?**: via installer
> - **Are you fully synchronized?**: no not anymore
> - **Which network are you connected to?**: Ethereum
> - **Did you try to restart the node?**: yes, crashes at startup

_Your issue description goes here below. Try to include **actual** vs. **expected behavior** and **steps to reproduce** the issue._

2018-03-23 20:35:57  Starting Parity/v1.9.5-stable-ff821daf1-20180321/x86_64-windows-msvc/rustc1.24.1
2018-03-23 20:35:57  Keys path C:\Users\user\AppData\Roaming\Parity\Ethereum\keys\Foundation
2018-03-23 20:35:57  DB path C:\Users\userAppData\Local\Parity\Ethereum\chains\ethereum\db\906a34e69aec8c0d
2018-03-23 20:35:57  Path to dapps C:\Users\user\AppData\Roaming\Parity\Ethereum\dapps
2018-03-23 20:35:57  State DB configuration: fast
2018-03-23 20:35:57  Operating mode: passive
2018-03-23 20:35:57  Configured for Foundation using Ethash engine
2018-03-23 20:35:58  Updated conversion rate to Ξ1 = US$527.08 (225862530 wei/gas)

====================

stack backtrace:
   0:     0x7ff6a9a9bbf3 - <no info>
   1:     0x7ff6a9a9b3d3 - <no info>
   2:     0x7ff6a94d6f0d - <no info>
   3:     0x7ff6a9d14114 - hid_error
   4:     0x7ff6a9d13f01 - hid_error
   5:     0x7ff6a9d13e52 - hid_error
   6:     0x7ff6a9d13dca - hid_error
   7:     0x7ff6a9d2b7ed - hid_error
   8:     0x7ff6a9d2b71f - hid_error
   9:     0x7ff6a97ce478 - <no info>
  10:     0x7ff6a9654593 - <no info>
  11:     0x7ff6a971f201 - <no info>
  12:     0x7ff6a8f221f6 - <no info>
  13:     0x7ff6a8f29450 - <no info>
  14:     0x7ff6a915450d - <no info>
  15:     0x7ff6a9159e52 - <no info>
  16:     0x7ff6a915bfe9 - <no info>
  17:     0x7ff6a911eac6 - <no info>
  18:     0x7ff6a9d13cfd - hid_error
  19:     0x7ff6a9d28722 - hid_error
  20:     0x7ff6a9cfdd13 - hid_error
  21:     0x7ff6a916bfea - <no info>
  22:              0x3ae - <no info>
  23:              0x3af - <no info>
  24:     0x7ff6aa0489b0 - hid_write
  25:     0x7ff6aa048980 - hid_write
  26:     0x7ff6a915a9af - <no info>
  27:     0x7ff6aa00db5c - hid_write
  28:     0x7ffbff1f1fe4 - BaseThreadInitThunk

Thread 'main' panicked at 'called `Option::unwrap()` on a `None` value', src\libcore\option.rs:335

This is a bug. Please report it at: https://github.com/paritytech/parity/issues/new

**Comment by UGatgithub** [comment] 2018-03-23 20:06
Did a test and renamed c:\Users\r-u-g\AppData\Local\Parity\Ethereum\ to c:\Users\r-u-g\AppData\Local\Parity\Ethereum.bak\, tried to restart and now Partity works again and started to resync.

**Comment by UGatgithub** [comment] 2018-03-25 10:04
I found a solution for myself but not sure i fyi should close this now.

**Comment by niklasad1** [comment] 2018-03-26 12:18
@UGatgithub 

Hi, can you verify if you get these errors running parity without hardware-wallet:
```
parity.exe --no-hardware-wallets
```

If that works then run parity with hardware wallet and provide the logs please:
```bash
parity.exe -l hardware_wallet=trace
```

**Comment by 5chdn** [comment] 2018-03-26 13:56
Duplicate of #7340

**Closed by 5chdn** 2018-03-26 13:56 UTC
Labels: F2-bug, M4-core, P5-sometimesoon
