### ISSUE TITLE
Corruption: block checksum mismatch

### ISSUE THREAD

**Issue by mpolci** [paritytech/parity#7552] opened 2018-01-14 09:49 UTC
Parity version: Parity/v1.8.6-beta-2d051e4-20180109/x86_64-linux-gnu/rustc1.22.1
OS: linux (ubuntu 14.04)
Installed from official deb package 
Are you fully synchronized? yes
Which network are you connected to? ethereum 
Did you try to restart the node?  yes, I get the same error after few blocks

```
stack backtrace:
   0:     0x55577c4972fc - <no info>

Thread 'IO Worker #1' panicked at 'DB flush failed.: "Corruption: block checksum mismatch: expected 2858477624, got 299572259  in /home/user/.local/share/io.parity.ethereum/chains/ethereum/db/906a34e69aec8c0d/overlayrecent/db/141692.sst offset 25597147 size 6319"', /checkout/src/libcore/result.rs:906

This is a bug. Please report it at:

    https://github.com/paritytech/parity/issues/new

Aborted (core dumped)

```

**Comment by 5chdn** [comment] 2018-01-16 10:30
Duplicate of #7334

**Closed by 5chdn** 2018-01-16 10:30 UTC
