### ISSUE TITLE
no matching package named `ring` found (required by `multihash`) version required: ~0.6.2 versions found: 0.9.7, 0.9.6, 0.9.5, ...

### ISSUE THREAD

**Issue by drandreaskrueger** [paritytech/parity#5783] opened 2017-06-07 08:46 UTC
Apart from the fact that this needed almost 4 hours ... it failed:

```

date; cargo install --git https://github.com/paritytech/parity.git parity; date

Tue  6 Jun 17:49:12 BST 2017

    Updating git repository `https://github.com/paritytech/parity.git`
  Installing parity v1.7.0 (https://github.com/paritytech/parity.git#99bfef28)
    Updating registry `https://github.com/rust-lang/crates.io-index`
    Updating git repository `https://github.com/paritytech/rust-ctrlc.git`
    Updating git repository `https://github.com/paritytech/jsonrpc.git`
    Updating git repository `https://github.com/paritytech/nanomsg.rs.git`
    Updating git repository `https://github.com/paritytech/js-precompiled.git`
    Updating git repository `https://github.com/paritytech/hyper`
    Updating git repository `https://github.com/tailhook/rotor`
    Updating git repository `https://github.com/paritytech/rust-secp256k1`
    Updating git repository `https://github.com/paritytech/rust-rocksdb`
    Updating git repository `https://github.com/paritytech/bn`
    Updating git repository `https://github.com/tomusdrw/tokio-proto`
    Updating git repository `https://github.com/tomusdrw/tokio-minihttp`
    Updating git repository `https://github.com/nikvolf/parity-tokio-ipc`
    Updating git repository `https://github.com/tomusdrw/ws-rs`
    Updating git repository `https://github.com/alexcrichton/mio-named-pipes`
    Updating git repository `https://github.com/nikvolf/tokio-named-pipes`
    Updating git repository `https://github.com/paritytech/libusb-rs`
    Updating git repository `https://github.com/paritytech/hidapi-rs`
    Updating git repository `https://github.com/paritytech/libusb-sys`
error: failed to compile `parity v1.7.0 (https://github.com/paritytech/parity.git#99bfef28)`, intermediate artifacts can be found at `/tmp/cargo-install.X8OUPaXeZE4M`

Caused by:
  no matching package named `ring` found (required by `multihash`)
location searched: registry https://github.com/rust-lang/crates.io-index
version required: ~0.6.2
versions found: 0.9.7, 0.9.6, 0.9.5, ...

Tue  6 Jun 21:32:27 BST 2017
```

and `/tmp/cargo-install.X8OUPaXeZE4M` is empty.

In my second attempt, as a preparation, I had wiped everything before:

```
rm .cargo -rf
curl https://sh.rustup.rs -sSf | sh
source $HOME/.cargo/env

rustc --version
    rustc 1.17.0 (56124baa9 2017-04-24)

rustc --version
    cargo 0.18.0 (fe7b0cdcf 2017-04-24)
```

**Comment by 5chdn** [comment] 2017-06-07 08:58
Might be related to / duplicate of https://github.com/paritytech/parity/issues/5704 and https://github.com/rust-lang/cargo/issues/4108

**Comment by tomusdrw** [comment] 2017-06-07 09:04
The updated `cid` package PR has been made 21 days ago, but it wasn't released yet.
https://github.com/ipld/rust-cid/pull/6
If it is not released today I'll fork the repo and use the fork instead.

**Comment by drandreaskrueger** [comment] 2017-06-07 09:10
What if instead of the failing

    cargo install --git https://github.com/paritytech/parity.git

I'd simply go back to a (presumably working) [v1.6.7](https://github.com/paritytech/parity/releases/tag/v1.6.7)?  Let's see how this goes:

    date; cargo install --git https://github.com/paritytech/parity --tag v1.6.7 parity; date

**Comment by tomusdrw** [comment] 2017-06-07 09:22
The problem is that `ring-0.6` has been removed from `crates.io` registry.

**Closed** 2017-06-07 09:30 UTC
Labels: Z0-duplicate

**Comment by drandreaskrueger** [comment] 2017-06-07 11:44
You closing this issue means that the problem is completely resolved?

**Comment by drandreaskrueger** [comment] 2017-06-07 11:46
I am now waiting almost 2 hours already - or does parity always need that long?

```
rm .cargo -rf
curl https://sh.rustup.rs -sSf | sh
source $HOME/.cargo/env

date; cargo install --git https://github.com/paritytech/parity parity; date

Wed  7 Jun 10:57:47 BST 2017

    Updating git repository `https://github.com/paritytech/parity`
  Installing parity v1.7.0 (https://github.com/paritytech/parity#19f01194)
    Updating registry `https://github.com/rust-lang/crates.io-index`
    Updating git repository `https://github.com/paritytech/rust-ctrlc.git`
    Updating git repository `https://github.com/paritytech/jsonrpc.git`
    Updating git repository `https://github.com/paritytech/rust-rocksdb`
    Updating git repository `https://github.com/paritytech/rust-secp256k1`
    Updating git repository `https://github.com/paritytech/bn`
    Updating git repository `https://github.com/paritytech/hyper`
    Updating git repository `https://github.com/paritytech/nanomsg.rs.git`
    Updating git repository `https://github.com/tailhook/rotor`
    Updating git repository `https://github.com/tomusdrw/ws-rs`
    Updating git repository `https://github.com/nikvolf/parity-tokio-ipc`
    Updating git repository `https://github.com/alexcrichton/mio-named-pipes`
    Updating git repository `https://github.com/nikvolf/tokio-named-pipes`
    Updating git repository `https://github.com/tomusdrw/tokio-proto`
    Updating git repository `https://github.com/tomusdrw/tokio-minihttp`
    Updating git repository `https://github.com/paritytech/js-precompiled.git`
    Updating git repository `https://github.com/paritytech/libusb-rs`
    Updating git repository `https://github.com/paritytech/hidapi-rs`
    Updating git repository `https://github.com/paritytech/libusb-sys`

```
stuck there.

**Comment by drandreaskrueger** [comment] 2017-06-07 12:47
3 hours. I get the impression this is perhaps not yet fixed ...?

**Comment by tomusdrw** [comment] 2017-06-07 12:53
It looks it's trying to fetch all the dependencies. What internet connection do you have?

**Comment by drandreaskrueger** [comment] 2017-06-07 13:12
> What internet connection do you have?

88.92 Mbps, just measured for you.   
87.04 Mbps upload.

**Comment by tomusdrw** [comment] 2017-06-07 13:17
That's weird what kind of CPU / disk?
The process looks normal, compiling Parity from scratch should not take longer than 20 minutes on a decent machine when all dependencies are already fetched.

I just realized that now you might be experiencing the issues linked by @5chdn https://github.com/rust-lang/cargo/issues/4108

**Comment by 5chdn** [comment] 2017-06-07 14:22
Yes I closed it because it#s tracked in the two other tickets above and a fix is available in #5785. This does not mean I do not endorse this discussion.

**Comment by drandreaskrueger** [comment] 2017-06-07 16:04
> CPU 
i5-6500 CPU @ 3.20GHz

> disk?
SSD 

> should not take longer than 20 minutes 
The last attempt is already 6 hours old now. And still running.

**Comment by drandreaskrueger** [comment] 2017-06-07 16:06
> and a fix is available in #5785
Great. How exactly can I use that fix ?

thanks.

**Comment by drandreaskrueger** [comment] 2017-06-07 16:14
@alexcrichton said [here](https://github.com/rust-lang/cargo/issues/4066#issuecomment-306735417):

"ah yeah unfortunately that's this issue :("

**Comment by 5chdn** [comment] 2017-06-08 12:33
> > you might be experiencing the issues linked by @5chdn rust-lang/cargo#4108
> 
> "alexcrichton closed this 8 days ago"

This one is the correct ticket https://github.com/rust-lang/cargo/issues/4066

> Great. How exactly can I use that fix ?

Try to build latest master or beta:

    cargo install --git https://github.com/paritytech/parity parity
