### ISSUE TITLE
Light client sync stuck on Kovan 

### ISSUE THREAD

**Issue by Tbaut** [paritytech/parity#8383] opened 2018-04-12 12:24 UTC
_Before filing a new issue, please **provide the following information**._

> I'm running:
>
> - **Which Parity version?**: Parity/v1.11.0-unstable-8348147-20180410/x86_64-linux-gnu/rustc1.25.0
> - **Which operating system?**: Linux
> - **How installed?**:  from source
> - **Are you fully synchronized?**: no
> - **Which network are you connected to?**:  kovan
> - **Did you try to restart the node?**: yes

My node starts syncing using `parity --chain kovan --light` but gets stuck at random block height.
[Here is a sync trace where the client gets stuck at block 1460487](https://gist.github.com/Tbaut/a27405011826da70370211e6a0e53d0b)
Relaunching the client makes it sync further for a couple minutes but gets stuck again some blocks higher.
In the console without trace it looks like this:
```
2018-04-12 12:20:20  Starting Parity/v1.11.0-unstable-8348147-20180410/x86_64-linux-gnu/rustc1.25.0
2018-04-12 12:20:20  Keys path /home/thib/.local/share/io.parity.ethereum/keys/Kovan
2018-04-12 12:20:20  DB path /home/thib/.local/share/io.parity.ethereum/chains/kovan/db/9bf388941c25ea98
2018-04-12 12:20:20  Path to dapps /home/thib/.local/share/io.parity.ethereum/dapps
2018-04-12 12:20:20  Running in experimental Light Client mode.
...
4/50 peers   10 MiB cache 23 MiB queue  RPC:  0 conn,  0 req/s,   0 µs
2018-04-12 12:32:01  Syncing #2563032 0xecab…24c0   470 hdr/s      0+28817 Qed  #2563032    3/50 peers   10 MiB cache 23 MiB queue  RPC:  0 conn,  0 req/s,   0 µs
2018-04-12 12:32:06  Syncing #2565482 0xca7e…f541   490 hdr/s      0+27025 Qed  #2565482    7/50 peers   10 MiB cache 22 MiB queue  RPC:  0 conn,  0 req/s,   0 µs
2018-04-12 12:32:11  Syncing #2567908 0x7e5f…7591   485 hdr/s      0+28975 Qed  #2567908    3/50 peers   10 MiB cache 23 MiB queue  RPC:  0 conn,  0 req/s,   0 µs
2018-04-12 12:32:21  Syncing #2572700 0x4e7e…95a6   479 hdr/s      0+25903 Qed  #2572700    4/50 peers   10 MiB cache 21 MiB queue  RPC:  0 conn,  0 req/s,   0 µs
2018-04-12 12:32:31  Syncing #2577371 0x433f…23b6   467 hdr/s      0+25415 Qed  #2577371    3/50 peers   10 MiB cache 21 MiB queue  RPC:  0 conn,  0 req/s,   0 µs
2018-04-12 12:32:36  Syncing #2579401 0x4c14…c8db   406 hdr/s      0+23367 Qed  #2579401    2/50 peers   10 MiB cache 19 MiB queue  RPC:  0 conn,  0 req/s,   0 µs
2018-04-12 12:32:46  Syncing #2584292 0x562a…31dd   489 hdr/s      0+23942 Qed  #2584292    2/50 peers   10 MiB cache 19 MiB queue  RPC:  0 conn,  0 req/s,   0 µs
2018-04-12 12:32:56  Syncing #2585560 0x6976…3a80   126 hdr/s      0+    0 Qed  #2585560    7/50 peers   10 MiB cache 0 bytes queue  RPC:  0 conn,  0 req/s,   0 µs
2018-04-12 12:33:06  Syncing #2585560 0x6976…3a80     0 hdr/s      0+    0 Qed  #2585560    6/50 peers   10 MiB cache 0 bytes queue  RPC:  0 conn,  0 req/s,   0 µs
2018-04-12 12:33:16  Syncing #2585560 0x6976…3a80     0 hdr/s      0+    0 Qed  #2585560    5/50 peers   10 MiB cache 0 bytes queue  RPC:  0 conn,  0 req/s,   0 µs
2018-04-12 12:33:26  Syncing #2585560 0x6976…3a80     0 hdr/s      0+    0 Qed  #2585560    6/50 peers   10 MiB cache 0 bytes queue  RPC:  0 conn,  0 req/s,   0 µs
2018-04-12 12:33:36  Syncing #2585560 0x6976…3a80     0 hdr/s      0+    0 Qed  #2585560    6/50 peers   10 MiB cache 0 bytes queue  RPC:  0 conn,  0 req/s,   0 µs
2018-04-12 12:33:46  Syncing #2585560 0x6976…3a80     0 hdr/s      0+    0 Qed  #2585560    7/50 peers   10 MiB cache 0 bytes queue  RPC:  0 conn,  0 req/s,   0 µs
...
2018-04-12 13:55:16  Syncing #2585560 0x6976…3a80     0 hdr/s      0+    0 Qed  #2585560    8/50 peers   10 MiB cache 0 bytes queue  RPC:  0 conn,  0 req/s,   0 µs
2018-04-12 13:55:26  Syncing #2585560 0x6976…3a80     0 hdr/s      0+    0 Qed  #2585560   11/50 peers   10 MiB cache 0 bytes queue  RPC:  0 conn,  0 req/s,   0 µs
2018-04-12 13:55:36  Syncing #2585560 0x6976…3a80     0 hdr/s      0+    0 Qed  #2585560    9/50 peers   10 MiB cache 0 bytes queue  RPC:  0 conn,  0 req/s,   0 µs
2018-04-12 13:55:41  Syncing #2585560 0x6976…3a80     0 hdr/s      0+    0 Qed  #2585560   15/50 peers   10 MiB cache 0 bytes queue  RPC:  0 conn,  0 req/s,   0 µs
2018-04-12 13:55:51  Syncing #2585560 0x6976…3a80     0 hdr/s      0+    0 Qed  #2585560   14/50 peers   10 MiB cache 0 bytes queue  RPC:  0 conn,  0 req/s,   0 µs
2018-04-12 13:56:01  Syncing #2585560 0x6976…3a80     0 hdr/s      0+    0 Qed  #2585560   13/50 peers   10 MiB cache 0 bytes queue  RPC:  0 conn,  0 req/s,   0 µs
2018-04-12 13:56:11  Syncing #2585560 0x6976…3a80     0 hdr/s      0+    0 Qed  #2585560   14/50 peers   10 MiB cache 0 bytes queue  RPC:  0 conn,  0 req/s,   0 µs

```

**Comment by folsen** [comment] 2018-04-12 12:31
@tomaka @rphmeier this is one of the "sync gets stuck" causes that I found when I was investigating as well, and appears it's not fixed. Although I have no real idea what's causing it, it's the one of the 3 i didn't fully investigate. Somehow it gets stuck in a loop doing a common ancestor search.

**Comment by 5chdn** [comment] 2018-04-12 13:13
Duplicate of #6319 ?

**Closed as completed** 2018-04-12 13:19 UTC
Labels: Z7-duplicate 🖨, M4-core ⛓

**Comment by 5chdn** [comment] 2018-04-12 18:33
I'm happy with splitting up but I don't see any differences yet other than one reports Kovan and the other Foundation.
