### ISSUE TITLE
Error: "Events not supported"

### ISSUE THREAD

**Issue by lfrickel** [paritytech/parity#5572] opened 2017-05-07 11:39 UTC
I take an example from the "Events" section of the OFFICIAL guide to Solidity (http://solidity.readthedocs.io/en/develop/contracts.html?highlight=event#events):
```
pragma solidity ^0.4.11;

contract ClientReceipt {
    event Deposit(address indexed _from, bytes32 indexed _id, uint _value);

    function deposit(bytes32 _id) {
        // Any call to this function (even deeply nested) can
        // be detected from the JavaScript API by filtering
        // for `Deposit` to be called.
        Deposit(msg.sender, _id, msg.value);
    }
}
```
I compile this through the Parity editor and get a number of errors:
```
"msg.value" used in non-payable function. Do you want to add the "payable" modifier to this function?
        Deposit(msg.sender, _id, msg.value);
                                 ^-------^
**9: 34
Events not supported.
    event Deposit(address indexed _from, bytes32 indexed _id, uint _value);
    ^---------------------------------------------------------------------^**
3: 5
Parameter type "bytes32" not supported.
    function deposit(bytes32 _id) {
                     ^---------^
5: 22
Only internal function calls supported.
        Deposit(msg.sender, _id, msg.value);
        ^---------------------------------^
9: 9
Not supported.
        Deposit(msg.sender, _id, msg.value);
        ^-----^
9: 9
Member access: Only call and array length supported.
        Deposit(msg.sender, _id, msg.value);
                ^--------^
9: 17
Member access: Only call and array length supported.
        Deposit(msg.sender, _id, msg.value);
                                 ^-------^
```

Someone can explain to me: HOW CAN IT BE?

**I MUST have events for my contract!**

Thankful in advance for the answer!

**Comment by rphmeier** [comment] 2017-05-07 16:30
@ngotchac aren't these just warnings from the static analyzer as opposed to the solidity compilation  itself?

**Comment by 5chdn** [comment] 2017-05-08 08:27
Duplicate of #5409

**Closed by 5chdn** 2017-05-08 08:27 UTC
Labels: M7-ui, Z0-question

**Comment by ngotchac** [comment] 2017-05-08 09:21
@rphmeier You are right. Maybe the static analyser messages should be hidden by default (could be/is misleading)

**Comment by lfrickel** [comment] 2017-05-10 17:37
First, thanks to @rphmeier, @5chdn and @raingloom for the comments.
Secondly, it seems strange to me that the validator, the compiler and the official manual have three different and conflicting opinions, based on such basic functions as events.
Thirdly, I, of course, immediately checked the work of this example, regardless of the messages of the validator.
Result: Parity writes me "No events has been sent from this contract." (Although the function "deposit" was sent and Parity confirmed this fact), and the web3j-filter does not see any events.

**Comment by ngotchac** [comment] 2017-05-11 15:45
Hey @lfrickel I tried the code you posted here web3j/web3j#85
and I could see the events getting logged in the Parity Wallet (in the Contract view).

![image](https://cloud.githubusercontent.com/assets/2864519/25958616/66b23152-3671-11e7-85c9-da04e8dbe812.png)

Can you confirm that 
```
pragma solidity ^0.4.11;
contract EventTest {                
  event NumberEvent(uint indexed number);   

  function triggerEvent(uint val) returns (uint) { 
    NumberEvent(val);
    return 123;
  }                                 
}
```

doesn't work when you try to deploy and execute `triggerEvent`?

**Comment by lfrickel** [comment] 2017-05-12 09:37
Hey @ngotchac. Thank you again for your attention. I can confirm that

```
pragma solidity ^0.4.11;

contract ClientReceipt {
    event Deposit(address indexed _from, bytes32 indexed _id, uint _value);

    function deposit(bytes32 _id) {
        Deposit(msg.sender, _id, msg.value);
    }
}
```

doesn't work when I try to deploy and execute `triggerEvent`.

```
pragma solidity ^0.4.11;
contract EventTest {                
  event NumberEvent(uint indexed number);   

  function triggerEvent(uint val) returns (uint) { 
    NumberEvent(val);
    return 123;
  }                                 
}
```
I checked with TestRPC. I do not see a fundamental difference between these examples, but since you insist, then I tried to check through Kovan / Parity this example too. Now I have another problem: deployment.

![1](https://cloud.githubusercontent.com/assets/28390130/25991800/4592b022-370d-11e7-9f1a-0b1f9b4b3e55.png)

then:

![2](https://cloud.githubusercontent.com/assets/28390130/25992003/f0356100-370d-11e7-90fa-7b11f7862e6c.png)

then:

![3](https://cloud.githubusercontent.com/assets/28390130/25992186/7aa3fbee-370e-11e7-92af-cc1687a7d656.png)

then:

![4](https://cloud.githubusercontent.com/assets/28390130/25992389/007142f4-370f-11e7-8db2-4899fc49dfea.png)

then:

![5](https://cloud.githubusercontent.com/assets/28390130/25992473/48f6eae2-370f-11e7-9cc4-45be4c176259.png)

And so many hours without end. Tried to stop and start - the same result. On other days, all passed in a few minutes! While I wait.

**Comment by ngotchac** [comment] 2017-05-12 10:36
@lfrickel This is very strange... Could you try to run with `-lown_tx=trace` CLI flag, and send the logs when this transaction hanging happens. Also if you see anything in the JS console it would be useful.

**Comment by tomusdrw** [comment] 2017-05-12 10:37
@lfrickel Could you also check if the transaction is visible on https://kovan.etherscan.io/txsPending after you send it?

**Comment by lfrickel** [comment] 2017-05-12 16:36
To @tomusdrw : "Unable to locate Transaction entry"

**Comment by lfrickel** [comment] 2017-05-12 16:45
@ngotchac Is this the information that you had in mind?

![6](https://cloud.githubusercontent.com/assets/28390130/26007935/5be145d0-374b-11e7-8de9-33a9b6263c99.png)

**Comment by tomusdrw** [comment] 2017-05-12 18:30
Can you try to increase `gas_price` of your transaction? You're using 10Gwei, and it seems that every transaction on Kovan is using 20Gwei. Did you set it manually or was it proposed by Parity?

**Comment by lfrickel** [comment] 2017-05-13 07:55
@tomusdrw I increased the price from 130K to 3M. Unfortunately, it did not get better.

![3](https://cloud.githubusercontent.com/assets/28390130/26023689/a2d4fa7a-37ca-11e7-834a-c8ac4e7a3729.png)

**Comment by lfrickel** [comment] 2017-05-13 08:12
@ngotchac I found that a few days ago in the test network Kovan I was already deploying this contract. 

```
pragma solidity ^0.4.11;
contract EventTest {                
  event NumberEvent(uint indexed number);   

  function triggerEvent(uint val) returns (uint) { 
    NumberEvent(val);
    return 123;
  }                                 
}
```

Here is his address: `0xF45e5FebD63E5f6225a1b08429FC332f3B231826` You can check the functionality of events.

![1](https://cloud.githubusercontent.com/assets/28390130/26023794/f1e3aeca-37cc-11e7-80e8-6dd2cc940ee9.png)

**Comment by ngotchac** [comment] 2017-05-15 08:17
@lfrickel It seems that you nevers actually sent a transaction to the contract : https://kovan.etherscan.io/address/0xf45e5febd63e5f6225a1b08429fc332f3b231826 

The only transaction received it the one I just made to test. Again it might be the gas price you send the transaction with that is too low. Whenever you send a transaction, you can go check its status on `https://kovan.etherscan.io/tx/<txhash>` to see if it was broadcasted, with which gas & gas price and when it is mined.

**Comment by lfrickel** [comment] 2017-05-15 18:10
@ngotchac Thanks for the advice, but, unfortunately, this did not work.

I increased the gas price from 27K to 1M in my transaction.

![1](https://cloud.githubusercontent.com/assets/28390130/26071996/aef668a4-39b2-11e7-8b5e-7b6847da7ccc.png)

Then:

![2](https://cloud.githubusercontent.com/assets/28390130/26072006/bc66af6c-39b2-11e7-9c91-edf87c680dbf.png)

Then:

![3](https://cloud.githubusercontent.com/assets/28390130/26072019/c5a164c8-39b2-11e7-8c55-c7a1ca903821.png)

Then:

![4](https://cloud.githubusercontent.com/assets/28390130/26072027/cbbc134e-39b2-11e7-8980-a1c7d1d376bc.png)

Then:

![5](https://cloud.githubusercontent.com/assets/28390130/26072032/d050d8fe-39b2-11e7-921f-97227b04629d.png)

Then:

![6](https://cloud.githubusercontent.com/assets/28390130/26072047/dc7c662a-39b2-11e7-94b0-0f21a98d7057.png)

**Comment by tomusdrw** [comment] 2017-05-16 06:17
Please try to increase `gas price` (second input) not `gas` (first input), also make sure your time is exact: `https://time.is`

**Comment by lfrickel** [comment] 2017-05-16 07:42
@tomusdrw The time difference is 0.5 seconds.

**Comment by lfrickel** [comment] 2017-05-16 08:02
@tomusdrw, @ngotchac  I increased the price of gas 7 times!

![1](https://cloud.githubusercontent.com/assets/28390130/26095291/bad4669e-3a25-11e7-8ecc-97dfceaba6ef.png)
![2](https://cloud.githubusercontent.com/assets/28390130/26095299/c01be334-3a25-11e7-95ce-22037d7304f6.png)
![4](https://cloud.githubusercontent.com/assets/28390130/26095323/d17728be-3a25-11e7-8217-cb3f5e5556c1.png)

Now for 30 minutes I see this screen:

![3](https://cloud.githubusercontent.com/assets/28390130/26095524/a24b605e-3a26-11e7-84e2-50f67a756bdc.png)

Transaction Information (0x71a47b3e95319d33dcfa7b1bac04f27bd0995d0266819058df20ed78fc22f831):

![5](https://cloud.githubusercontent.com/assets/28390130/26095610/df9c8fdc-3a26-11e7-8c39-b95b9cdc59e0.png)

**Comment by lfrickel** [comment] 2017-05-17 09:12
@tomusdrw, @ngotchac Thank you for participating.
I found this problem. This was in the test chain KOVAN and in TestRPC. The same actions on the main chain caused a successful result.
I did not want to burden the main chain with test contracts, but I had to.
Thank you all again!

The contrakt: 0x2783318E7C1c6d1Aab46F0773264f74Fd0a8313d
