### ISSUE TITLE
1.7.0 OS X installer can't install over 1.6.8

### ISSUE THREAD

**Issue by PLPeeters** [paritytech/parity#6220] opened 2017-08-03 11:05 UTC
When installing version 1.7.0 on OS X (using the installer) over version 1.6.8 (that was installed using the installer as well), everything goes fine, but Parity isn't getting updated; it still shows 1.6.8 in the Parity interface when the installer relaunches it.

After deleting the Parity Ethereum app from my Applications folder and running the installer again, it installed version 1.7.0 properly.

**Comment by karljohns0n** [comment] 2017-08-07 14:31
I have the same issue.

**Comment by 5chdn** [comment] 2017-08-08 07:32
Duplicate of #6219.

**Closed by 5chdn** 2017-08-08 07:32 UTC
Labels: Z0-duplicate
