### ISSUE TITLE
Allow extension install via UI settings

### ISSUE THREAD

**Issue by jacogr** [paritytech/parity#4444] opened 2017-02-06 10:57 UTC
As there is an explanation on how to setup the Proxy, there should be a tab in the Settings panel to add the Chrome Extension (if applicable, ie. on Chrome when the extension is not already installed)

**Comment by tomusdrw** [comment] 2017-06-28 17:16
Duplicate of #5493 (there are more details there)

**Closed by tomusdrw** 2017-06-28 17:16 UTC
Labels: F8-enhancement, M7-ui
