### ISSUE TITLE
Thread 'Verifier #0' panicked at 'DB flush failed.: "Corruption: block checksum mismatch"'

### ISSUE THREAD

**Issue by morelazers** [paritytech/parity#7279] opened 2017-12-14 01:05 UTC
_Before filing a new issue, please **provide the following information**._

> I'm running:
>
> - **Which Parity version?**: 1.8.2
> - **Which operating system?**: Linux
> - **How installed?**: via one-line installer
> - **Are you fully synchronized?**: no
> - **Did you try to restart the node?**: yes

_Your issue description goes here below. Try to include **actual** vs. **expected behavior** and **steps to reproduce** the issue._

Trying to sync from approximately block 4710000, this has happened a few times. Starts syncing successfully and then throws this error after ~30 mins.

stack backtrace:
   0:     0x55a8af0666cc - <no info>

Thread 'Verifier #0' panicked at 'DB flush failed.: "Corruption: block checksum mismatch"', /checkout/src/libcore/result.rs:906

**Comment by 5chdn** [comment] 2017-12-14 17:03
Please, reset your database with `parity db kill` in your command prompt.

Duplicate of #7088

Duplicate of #7087

Duplicate of #7029

Duplicate of #6974

Duplicate of #6960

Duplicate of #6905

Duplicate of #6798

Duplicate of #6790

Duplicate of #6670

Duplicate of #6506

Duplicate of #6501

Duplicate of #5837

Duplicate of #3634

Duplicate of #3432

Duplicate of #2830

Duplicate of #2640

Duplicate of #2603

Duplicate of #763

**Closed by 5chdn** 2017-12-14 17:03 UTC
