### ISSUE TITLE
Unexpected crash during DB flush

### ISSUE THREAD

**Issue by vn-linescode** [paritytech/parity#7622] opened 2018-01-18 15:42 UTC
> I'm running:
>
> - **Which Parity version?**: 1.8.6-stable
> - **Which operating system?**: Linux (Ubuntu 16.04)
> - **How installed?**: via deb package
> - **Are you fully synchronized?**: yes
> - **Which network are you connected to?**: kovan
> - **Did you try to restart the node?**: yes (it keeps to crash)

Hello i'm having this issue, parity keeps to crash few second after the start. I'm using it since 2 days, i'm having the issue just now.

This the stacktrace that i got:
```
stack backtrace:
  0:     0x5622f99c626c - <no info>

Thread 'Verifier #0' panicked at 'DB flush failed.: "Corruption: block checksum mismatch: expected 1844570858, got 1982577653  in /home/crypto/.local/share/io.parity.ethereum/chains/kovan/db/9bf388941c25ea98/overlayrecent/db/037895.sst offset 408533 size 16317"', /checkout/src/libcore/result.rs:906
```
I just made few eWallet and some transaction via RPC. I don't have an exact procedure to replicate the issue.
Thank you all.

**Comment by 5chdn** [comment] 2018-01-18 16:16
Duplicate of #7334

**Closed by 5chdn** 2018-01-18 16:16 UTC
