### ISSUE TITLE
Allow finding of text in the Parity app's contract develop section.

### ISSUE THREAD

**Issue by chuacw** [paritytech/parity#6623] opened 2017-10-03 08:24 UTC
> I'm running:
>
> - **Parity version**: version Parity/v1.7.2-beta-9f47909-20170918/x86_64-windows-msvc/rustc1.19.0
> - **Operating system**: Windows 2008 R2

Unable to find text in contract section when developing.
Implement a find text feature, so that text can be found.

1.  Start the Parity app, so that it opens up a browser window to browse the parity app.
2.  Go to the contracts section.
3.  Click on Develop. Enter a lot of text into the editor.
4.  Now, try to find any text you've entered.
---

**Comment by 5chdn** [comment] 2017-10-04 09:33
Thanks for your heads-up.

Duplicate of #5483

**Closed by 5chdn** 2017-10-04 09:33 UTC
Labels: Z0-duplicate
