### ISSUE TITLE
Event Log links to Etherscan don't work

### ISSUE THREAD

**Issue by belgacoin** [paritytech/parity#5441] opened 2017-04-11 09:51 UTC
In Parity//v1.5.11-stable-f067f12-20170314/x86_64-macos/rustc1.15.1
when clicking "Registry" you'll get a new window with the Event Log.
when clicking on a Ether address, the link to etherscan.io has a double https:// in front so it doesn't work properly.

**Comment by 5chdn** [comment] 2017-04-11 10:06
duplicate of #4941 #5377 and should be fixed in #4984 with 52c81fe4eeed111d5f6e1ce6debcafa2960f6e0d on master

@ngotchac this needs backporting, does it?

**Closed by 5chdn** 2017-04-11 10:06 UTC
Labels: Z0-duplicate

**Comment by ngotchac** [comment] 2017-04-11 22:57
@5chdn Yes it does indeed !
