### ISSUE TITLE
Parity PoA authorities are not syncing

### ISSUE THREAD

**Issue by fatihATtargens** [paritytech/parity#7441] opened 2018-01-03 17:00 UTC
_**Authority sync not work correct**._

I'm running a private parity poa network with verion 1.7.7 stable.
The following issue I get:

> Stage 1 block verification failed for b4e8…ee34: Block(DifficultyOutOfBounds(OutOfBounds { min: None, max: Some(340282366920938463463374607431768211455), found: 340282366920938463463374607431768211456 }))

and after that the two atuhorities are not able to sync again correct.
In the following screenshot you can see that on of the authorities imports higher blocknumbers and than back again lower blocknumber (the lower numbers are the same like at the other authority and the hash values are correct too). But it never stops to do add first the wrong blocknumber and then the correct one. So my app doesn't work correct!
"wrong authority"
![image](https://user-images.githubusercontent.com/35073662/34530555-cc9a058c-f0af-11e7-9cd3-fe25cdaa4e48.png)

"working authority"
![image](https://user-images.githubusercontent.com/35073662/34530567-d5961c20-f0af-11e7-8afc-671a295ca2f8.png)

All other none authority nodes got the same blocknumber as in the second pic.

Thank you in advance for some help!

Best

Fatih

**Comment by debris** [comment] 2018-01-03 17:22
@tomusdrw can you confirm that this is fixed in #7343 ?

**Comment by fatihATtargens** [comment] 2018-01-03 18:22
Sorry but i'm not able to change the version of parity.

**Comment by tomusdrw** [comment] 2018-01-04 08:20
@debris It's a similar bug that was fixed in previous release, but the cause is a bit different. We have identified it and working on a fix.

**Comment by fatihATtargens** [comment] 2018-01-04 09:00
If you know the bug and the causes is there a workaround for it?

**Comment by tomusdrw** [comment] 2018-01-04 09:02
@fatihATtargens Restart both nodes and they should reorganize. Also make sure that the time on both authorities are properly synchronized.

**Comment by fatihATtargens** [comment] 2018-01-04 09:10
@tomusdrw thanks a lot! I'll give that a try and let you know if that works!

**Comment by fatihATtargens** [comment] 2018-01-04 14:44
@tomusdrw the workaround doesn't work! The same error occures.

**Closed** 2018-01-08 13:46 UTC
Labels: B0-patch, F2-bug, M4-core, P2-asap
