### ISSUE TITLE
Default Account for Parity Browser Extension overlay lists only a single account.

### ISSUE THREAD

**Issue by NiklasKunkel** [paritytech/parity#5627] opened 2017-05-16 02:16 UTC
I have several accounts under my accounts tab in the parity UI.  For example, if via the cli I type 'parity accounts list' I see all of my public keys. When I try to access a dapp using the parity browser extension it connects using one of my accounts. However now I want the parity extension to use a different account when interacting with a dapp. Clicking on the browser overlay box a popup appears that contains the one account that is currently being used, with no other accounts displayed. 

Why aren't my other accounts listed. Am I not supposed to be able to select an account through the popup?

Similarly when interacting through the parity javascript console, a web3.eth.accounts returns only the single account that the parity browser extension is using, not any of the others.

**Comment by rstormsf** [comment] 2017-05-16 04:53
click on a avatar when you are in Dapp, and switch an account

**Comment by NiklasKunkel** [comment] 2017-05-16 04:55
I'm saying that clicking on the avatar only shows my current account and not any of the others.

**Comment by rstormsf** [comment] 2017-05-16 05:13
do you see your account in the UI too?

**Comment by NiklasKunkel** [comment] 2017-05-16 05:13
> I have several accounts under my accounts tab in the parity UI.

yes.

**Comment by NiklasKunkel** [comment] 2017-05-16 05:23
Found something interesting.

When I use parity on kovan and access a dapp I can click on the avatar and change to a different account. It works!

When I use parity on mainnet, I don't see any other accounts when I click on the avatar except the one that it defaults to.

**Comment by rstormsf** [comment] 2017-05-16 05:56
make sure you have valid accounts on mainnet, and you are able to see them in Parity UI.

**Comment by NiklasKunkel** [comment] 2017-05-16 05:58
They're valid on the mainnet, I can transfer ETH and other tokens from them no problem through the parity UI. They just don't show up in the browser extension avatar UI.

**Comment by rstormsf** [comment] 2017-05-16 06:00
What is your `parity -v` ?

I just checked on 
` version Parity/v1.6.6-beta-8c6e3f3-20170411/x86_64-windows-msvc/rustc1.16.0` 
and it works fine on mainnet

**Comment by tomusdrw** [comment] 2017-05-16 06:01
Try goint to `Applications -> Permissions` and enable all accounts there. Duplicate of #5468

**Comment by NiklasKunkel** [comment] 2017-05-16 06:01
version Parity/v1.6.6-unstable/x86_64-macos/rustc1.17.0

**Closed by tomusdrw** 2017-05-16 06:01 UTC
Labels: Z0-duplicate
