### ISSUE TITLE
Installer does not work

### ISSUE THREAD

**Issue by TheOneFreeMan1** [paritytech/parity#7708] opened 2018-01-27 17:22 UTC
_Before filing a new issue, please **provide the following information**._

> I'm running:
>
> - **Which Parity version?**: N/A won't install/unknown
> - **Which operating system?**: Windows 
> - **How installed?**: via installer 
> - **Are you fully synchronized?**: no
> - **Which network are you connected to?**: none
> - **Did you try to restart the node?**: n/a

_Your issue description goes here below. Try to include **actual** vs. **expected behavior** and **steps to reproduce** the issue._

I clicked on the installation file and got an error message. It would not install.
![photo](https://user-images.githubusercontent.com/26447002/35474473-b02e6a72-035c-11e8-8312-edbe3a5990e1.jpeg)

**Comment by ddorgan** [comment] 2018-01-27 19:24
Can you try this binary instead: https://d1h4xl4cr1h0mo.cloudfront.net/beta-release/x86_64-pc-windows-msvc/parity_1.9.0_installer.exe

Need to get the link corrected.

**Comment by 5chdn** [comment] 2018-01-29 11:52
Duplicate of #7678

**Closed by 5chdn** 2018-01-29 11:52 UTC
