### ISSUE TITLE
Parity account action icons lack tooltip and/or labels

### ISSUE THREAD

**Issue by miohtama** [paritytech/parity#5443] opened 2017-04-11 21:21 UTC
It is unclear what these icons mean - only way to find out is to dare to click them 

<img width="880" alt="image" src="https://cloud.githubusercontent.com/assets/49922/24931414/d33ee234-1f15-11e7-9ed0-4241a6992c78.png">

**Comment by 5chdn** [comment] 2017-04-12 07:31
which version?

**Comment by tomusdrw** [comment] 2017-04-12 07:32
That's what it looks like on smaller screens I suppose. Are you zoomed in? Is your window maximized?
That said I think it would be good to add at least some tooltips on small screens.

**Comment by miohtama** [comment] 2017-04-12 08:20
This is OSX / Firefox / 1024 px window.

**Comment by 5chdn** [comment] 2017-05-09 12:05
This issue is labelled with _bug_: The client fails to follow expected behavior. It's assigned to @ngotchac but not linked to a milestone.

Since there's a patch available, I added it to the 1.7 milestone. Please, don't forget to close it once #5562 is merged. Please, also check if #5432 is a duplicate of this issue.

**Closed** 2017-05-10 14:19 UTC
Labels: F2-bug, M7-ui
