### ISSUE TITLE
Multiple issues with health and time

### ISSUE THREAD

**Issue by 5chdn** [paritytech/parity#6130] opened 2017-07-24 12:43 UTC
Trying to collect my observations in a single ticket.

- [x] the time displayed on status tab is not the offset between real time and machine time but 
also includes latency of whatever api is used (always in the range between 200 to 4000 ms). when I visit time.is, it just tells me it's rather 7ms.
- [x] the time sync is checked like once per minute. I guess it's safe to assume that a sync'd clock doesn't need a check more often than once per hour (unless the check failed).
- [x] api requests keep failing randomly, can't really tell why. but this should be handled with some kind of grey icon instead of yellow, maybe it's worth to introduce a 4th (unknown) state, which will be handled differently 
![screenshot at 2017-07-24 12-40-17](https://user-images.githubusercontent.com/15729797/28523691-daac397c-707d-11e7-8a9e-fa818e1199b1.png)
- [x] while using dapps, this keeps producing warning overlays. this is a drastic measure and should only be used for more fatal error messages, most users will probably not care whether an NPT request failed or not.
![screenshot at 2017-07-24 14-33-07](https://user-images.githubusercontent.com/15729797/28523739-074e794a-707e-11e7-87a9-f08f7c5cb38f.png)

**Comment by 5chdn** [comment] 2017-07-24 12:44
This is 1.7.0 on Linux.

**Comment by tomusdrw** [comment] 2017-08-10 13:09
The issues should be addressed by #6173 
Issue 1 is indeed weird and is caused by asymmetric latency between request and response. I was doing some tests and it doesn't matter what kind of network I have the time to send a packet is always higher then the time required to get a response, that cause this skew. I think it might either be an issue with the ntp library we're using (or underlying rust apis) or the load balancing server of pool.ntp.org

**Closed** 2017-08-10 13:13 UTC
Labels: F3-annoyance, M7-ui

**Comment by 3esmit** [comment] 2017-09-18 01:43
How to configure ntp server?
