### ISSUE TITLE
Core dump while syncing node

### ISSUE THREAD

**Issue by figitaki** [paritytech/parity#7748] opened 2018-01-31 01:54 UTC
> **Version** Parity/v1.9.0-beta-53ec114-20180125/x86_64-linux-gnu/rustc1.23.0
> **Operating System** Ubuntu 17.10
> **Installation method** via bash script installer
> **Fully synchronized?** no
> **Network** Foundation
> **Attempted restart**: yes

I had just upgraded my parity node from 1.8.0-beta and I started the client trying to sync the node. It had been a few months since I had touched this node so it'd been sitting around for a while. During the sync process, the process crashed and reported the following error message.

I'm not sure if this was just a one time problem, or if it's repeatable. I haven't encountered the issue again since restarting the node.

```
2018-01-30 17:38:43  Syncing #4420934 e081…c89a     0 blk/s    0 tx/s   0 Mgas/s      0+  814 Qed  #4421751   22/25 peers   11 MiB chain 66 MiB db 68 MiB queue 983 KiB sync  RPC:  0 conn,  0 req/s,  49 µs

====================

stack backtrace:
   0:     0x5622bd45e9ac - <no info>

Thread 'IO Worker #2' panicked at 'Low level database error. Some issue with disk?: Error(Msg("Corruption: block checksum mismatch: expected 514266003, got 1386451055  in /home/figitaki/.local/share/io.parity.ethereum/chains/ethereum/db/906a34e69aec8c0d/overlayrecent/db/100569.sst offset 973628716 size 7522819"), State { next_error: None, backtrace: None })', /checkout/src/libcore/result.rs:906

This is a bug. Please report it at:

    https://github.com/paritytech/parity/issues/new

[1]    5403 abort (core dumped)  parity --mode active --cache-size 2048 --pruning fast --db-compaction hdd
```

**Comment by 5chdn** [comment] 2018-01-31 09:18
Could you run a health check on your disk? just to make sure it's not a disk issue?

Are you on SSD or HDD?

**Comment by figitaki** [comment] 2018-01-31 18:38
I'm using an 1TB HDD, particularly a Seagate ST1000LM024 HN-M.  Upon running a health check, the drive seems to be in working condition. I also got the same error message a little bit later down the line, at block `#4427586` so not sure if that gives any more direction.

**Comment by andresilva** [comment] 2018-02-19 00:09
Can you run a memtest?

**Comment by jamesray1** [comment] 2018-03-23 12:52
![img_20180323_234924](https://user-images.githubusercontent.com/16969914/37829969-e50aa956-2e98-11e8-8003-e5304eef0fbe.jpg)
I had the same issue (but not now), and have no memtest.

**Comment by folsen** [comment] 2018-04-30 10:55
Closing as it's probably an issue with the memory on the client machine.

**Closed by folsen** 2018-04-30 10:55 UTC
Labels: F1-panic, M4-core, P2-asap

**Comment by andresilva** [comment] 2018-04-30 10:58
@unixfox Thanks a lot for running the memtest! 👍 

For anyone else still having this issue please run some hardware tests, I posted some general tips on a duplicate issue:

> memtest is a bootable image that you can use to check your RAM for issues. It's available here: https://www.memtest86.com/download.htm. For checking your disk I would say to use `smartctl` on Linux, something like this: `smartctl -t long /dev/sdX`.

**Comment by jamesray1** [comment] 2018-05-01 11:47
The test passed with no errors.

![img_20180501_214523](https://user-images.githubusercontent.com/16969914/39471893-508d467e-4d35-11e8-8ef4-99c9016299d9.jpg)

![img_20180501_213230](https://user-images.githubusercontent.com/16969914/39471924-6d29dbbc-4d35-11e8-8ec5-f77f76236af7.jpg)

**Comment by jamesray1** [comment] 2018-05-01 23:59
![img_20180502_095615](https://user-images.githubusercontent.com/16969914/39499111-97295daa-4d9b-11e8-9bf7-2eec41d52c5a.jpg)

The laptop also tested fine. The CPU config was round robin, switch CPU after each test.

**Comment by jamesray1** [comment] 2018-05-02 00:39
`smartctl -t long /dev/sdb4` tested fine on the desktop:

![screenshot from 2018-05-02 10-37-33](https://user-images.githubusercontent.com/16969914/39500013-f75fbe54-4df4-11e8-977d-2b2a49817590.png)

**Comment by andresilva** [comment] 2018-05-02 10:56
@jamesray1 Thanks for taking the time to run these tests, it seems no hardware errors have been found. Are you getting DB corruption issues constantly or is this something that only happened once for you?

**Comment by jamesray1** [comment] 2018-05-03 05:41
Yeah sorry, forgot to mention, it only happened once.

**Comment by NoviceF** [comment] 2018-05-07 05:44
I having the same issue (Corruption: block checksum mismatch).

![memory1](https://user-images.githubusercontent.com/2798499/39686228-80a97130-51d0-11e8-85c2-0f28fdfaccef.jpg)

![memory2](https://user-images.githubusercontent.com/2798499/39686235-88c99fa2-51d0-11e8-9b30-404c47b50f2e.jpg)

![hdd1](https://user-images.githubusercontent.com/2798499/39686324-16316c3a-51d1-11e8-811c-1c9577702fc4.png)

I getting error every time, when I try to sync db (from scratch), reproduction chance is 100%.

Ubuntu 16.04 x64.

I trying to use ubuntu repo version of patity, then I compile some of them from github (at the moment I have version Parity/v1.10.1-unstable-45c29a2-20180413/x86_64-linux-gnu/rustc1.25.0

**Comment by fanatid** [comment] 2018-05-28 07:04
Same issue. Memtest86 says that memory is fine. New SSD was not helpful. Receive error with `1.9.6`, `1.10.4`. Interesting that on another laptop I was able to run Parity without problems on same system (Fedora28, kernel 4.16.3).

**Comment by xtien** [comment] 2019-01-12 14:39
How is this issue closed if there is no fix?

**Comment by joshua-mir** [comment] 2019-01-12 14:42
@xtien this issue is outside parity-ethereum's control, if you are seeing this error, it means your hard drive or memory is failing, and the fix would be to replace your failing hardware.

**Comment by olegabr** [comment] 2019-10-17 01:59
Looks like you really do not want to fix it :-)

In my case base was corrupted after the parity process was killed by the system with `Out of memory` error:

```
# dmesg|grep 'Out of memory'
[14855308.005974] Out of memory: Kill process 3407 (parity) score 221 or sacrifice child
```

And now in logs I see:

```
2019-10-17 03:51:50  Starting Parity-Ethereum/v2.6.2-beta-25936ae-20190829/x86_64-linux-gnu/rustc1.36.0
2019-10-17 03:51:50  Keys path ./morden/keys/rinkeby
2019-10-17 03:51:50  DB path ./morden/chains/rinkeby/db/0d824504e4fa37a7
2019-10-17 03:51:50  State DB configuration: archive +Trace
2019-10-17 03:51:50  Operating mode: active
2019-10-17 03:51:50  DB corrupted: Invalid argument: You have to open all column families. Column families not opened: col6, col1, col3, col0, col4, col2, col5, attempting repair
```
