### ISSUE TITLE
DB corrupted

### ISSUE THREAD

**Issue by jennazenk** [paritytech/parity#8224] opened 2018-03-26 13:00 UTC
> I'm running:
>
> - **Which Parity version?**: Parity/v1.9.4-beta-6f21a32-20180228/x86_64-macos/rustc1.24.0
> - **Which operating system?**: MacOS
> - **Are you fully synchronized?**:yes
> - **Which network are you connected to?**: kovan
> - **Did you try to restart the node?**: yes

When I run `parity --chain kovan`, I get the following error message. 

 ```
 DB corrupted: Corruption: block checksum mismatch: expected 1299283320, got 1190243125  in /Users/jennazenk/Library/Application Support/io.parity.ethereum/chains/kovan/db/9bf388941c25ea98/overlayrecent/db/015974.sst offset 13047410 size 5113. Repair will be triggered on next restart

====================

stack backtrace:

Thread 'main' panicked at 'failed to update version: Error(Msg("Corruption: block checksum mismatch: expected 1299283320, got 1190243125  in /Users/jennazenk/Library/Application Support/io.parity.ethereum/chains/kovan/db/9bf388941c25ea98/overlayrecent/db/015974.sst offset 13047410 size 5113"), State { next_error: None, backtrace: None })', src/libcore/result.rs:916
```

If I try to restart I get: 

```
DB has been previously marked as corrupted, attempting repair
2018-03-26 14:55:03  DB corrupted: Invalid argument: You have to open all column families. Column families not opened: col4, col6, col1, col2, col3, col5, col0, attempting repair
Client service error: Client(Database(Error(Msg("Received null column family handle from DB."), State { next_error: None, backtrace: None })))
```

**Comment by 5chdn** [comment] 2018-03-26 13:52
Duplicate of #7748

**Comment by 5chdn** [comment] 2018-03-26 13:53
Duplicate of #7766

**Closed by 5chdn** 2018-03-26 13:52 UTC
Labels: M4-core, Z0-duplicate

**Comment by dinganc** [comment] 2019-11-06 19:29
I had this same issue for days. I fixed the issue by removing 1 stick of my ram. Now my laptop has only 1 stick of 8GB DDR3 installed, and Parity syncs without an issue. Wish this helps!
