### ISSUE TITLE
IO Worker panicked, 'DB flush failed ... Corruption: block checksum mismatch'

### ISSUE THREAD

**Issue by Dar13** [paritytech/parity#8142] opened 2018-03-17 00:31 UTC
I'm running:

 - **Which Parity version?**: 1.9.4
 - **Which operating system?**: Linux
 - **How installed?**: from source
 - **Are you fully synchronized?**: no
 - **Which network are you connected to?**: ethereum
 - **Did you try to restart the node?**: yes, DB is attempting repair

Process dumped core, error messages told me to post an issue here.

Full log:
```
Mar 16 19:05:45 parity[5582]: 2018-03-16 19:05:45  Syncing #5265548 7de3…eef0     1 blk/s  231 tx/s  10 Mgas/s      0+ 1653 Qed  #5267204   24/25 peers      5 MiB chain  110 MiB db  181 MiB queue   19 MiB sync  RPC:  0 conn,  0 req/s,   0 µs
Mar 16 19:05:55 parity[5582]: 2018-03-16 19:05:55  Syncing #5265572 c305…3a14     2 blk/s  234 tx/s  12 Mgas/s      0+ 1629 Qed  #5267204   24/25 peers      6 MiB chain  109 MiB db  178 MiB queue   19 MiB sync  RPC:  0 conn,  0 req/s,   0 µs
Mar 16 19:06:05 parity[5582]: 2018-03-16 19:06:05  Syncing #5265590 86cb…bca5     1 blk/s  243 tx/s  11 Mgas/s      0+ 1613 Qed  #5267204   24/25 peers      6 MiB chain  109 MiB db  176 MiB queue   19 MiB sync  RPC:  0 conn,  0 req/s,   0 µs
Mar 16 19:06:15 parity[5582]: 2018-03-16 19:06:15  Syncing #5265608 4507…3cfc     1 blk/s  182 tx/s   9 Mgas/s      0+ 1593 Qed  #5267204   24/25 peers      6 MiB chain  105 MiB db  174 MiB queue   19 MiB sync  RPC:  0 conn,  0 req/s,   0 µs
Mar 16 19:06:25 parity[5582]: 2018-03-16 19:06:25  Syncing #5265618 c660…90a5     1 blk/s  136 tx/s   6 Mgas/s      0+ 1585 Qed  #5267204   24/25 peers      6 MiB chain  106 MiB db  173 MiB queue   19 MiB sync  RPC:  0 conn,  0 req/s,   0 µs
Mar 16 19:06:35 parity[5582]: 2018-03-16 19:06:35  Syncing #5265631 6bfb…6ff8     1 blk/s  149 tx/s   7 Mgas/s      0+ 1569 Qed  #5267204   24/25 peers      6 MiB chain  108 MiB db  171 MiB queue   19 MiB sync  RPC:  0 conn,  0 req/s,   0 µs
Mar 16 19:06:45 parity[5582]: 2018-03-16 19:06:45  Syncing #5265646 feca…db9f     1 blk/s  141 tx/s   8 Mgas/s      0+ 1557 Qed  #5267204   24/25 peers      6 MiB chain  107 MiB db  170 MiB queue   19 MiB sync  RPC:  0 conn,  0 req/s,   0 µs
Mar 16 19:06:45 parity[5582]: 2018-03-16 19:06:45  DB corrupted: Corruption: block checksum mismatch: expected 2905577788, got 434147501  in /storage/<user>/parity/chains/ethereum/db/906a34e69aec8c0d/overlayrecent/db/427774.sst offset 1180025 size 16336. Repair will be triggered on next restart
Mar 16 19:06:45 parity[5582]: ====================
Mar 16 19:06:45 parity[5582]: stack backtrace:
Mar 16 19:06:45 parity[5582]:    0:     0x55fa1e3cbe4c - backtrace::backtrace::trace::hd0ea503b4c2b54bb
Mar 16 19:06:45 parity[5582]:    1:     0x55fa1e3cb4f2 - backtrace::capture::Backtrace::new::h654638660bebf6f1
Mar 16 19:06:45 parity[5582]:    2:     0x55fa1da9b1b5 - panic_hook::panic_hook::hbc4bf42a40533cb7
Mar 16 19:06:45 parity[5582]: Thread 'IO Worker #3' panicked at 'DB flush failed.: Error(Msg("Corruption: block checksum mismatch: expected 2905577788, got 434147501  in /storage/<user>/parity/chains/ethereum/db/906a34e69aec8c0d/overlayrecent/db/427774.sst offset 1180025 size 16336"), State { next_error: None, backtrace: None })>
Mar 16 19:06:45 parity[5582]: This is a bug. Please report it at:
Mar 16 19:06:45 parity[5582]:     https://github.com/paritytech/parity/issues/new
Mar 16 19:06:46 systemd[1]: Created slice system-systemd\x2dcoredump.slice.
Mar 16 19:06:46 systemd[1]: Started Process Core Dump (PID 6957/UID 0).
Mar 16 19:06:47 systemd[5576]: parity.service: Main process exited, code=killed, status=6/ABRT
Mar 16 19:06:47 systemd[5576]: parity.service: Failed with result 'signal'.
Mar 16 19:06:50 systemd-coredump[6958]: Process 5582 (parity) of user 1000 dumped core.
                                                    
                                                    Stack trace of thread 5652:
                                                    #0  0x00007fdf56df6860 raise (libc.so.6)
                                                    #1  0x00007fdf56df7ec9 abort (libc.so.6)
                                                    #2  0x000055fa1e6b2e79 n/a (/home/<user>/.cargo/bin/parity)
                                                    #3  0x000055fa1e6a113d n/a (/home/<user>/.cargo/bin/parity)
                                                    #4  0x000055fa1e6a1118 n/a (/home/<user>/.cargo/bin/parity)
                                                    #5  0x000055fa1e6a0ecf n/a (/home/<user>/.cargo/bin/parity)
                                                    #6  0x000055fa1e6a0e3a n/a (/home/<user>/.cargo/bin/parity)
                                                    #7  0x000055fa1e6a0dc3 n/a (/home/<user>/.cargo/bin/parity)
                                                    #8  0x000055fa1e6fda21 n/a (/home/<user>/.cargo/bin/parity)
                                                    #9  0x000055fa1e08f8a3 n/a (/home/<user>/.cargo/bin/parity)
```

**Comment by Dar13** [comment] 2018-03-17 00:38
After restarting the node this was printed to my journal:
```
Mar 16 20:32:54 parity[8050]: 2018-03-16 20:32:54  DB corrupted: Invalid argument: You have to open all column families. Column families not opened: col5, col0, col2, col3, col1, col4, col6, attempt>
```

**Comment by 5chdn** [comment] 2018-03-23 10:31
Duplicate of #7748

**Closed by 5chdn** 2018-03-23 10:31 UTC
