### ISSUE TITLE
 Thread 'Verifier #0' panicked at 'DB flush failed.: "Corruption: block checksum mismatch"', /checkout/src/libcore/result.rs:860

### ISSUE THREAD

**Issue by Beasta** [paritytech/parity#6974] opened 2017-11-02 23:39 UTC
_Before filing a new issue, please **provide the following information**._

> I'm running:
>
> - **Parity version**: v1.8.0
> - **Operating system**: Linux
> - **And installed**: cant remember

_Your issue description goes here below. Try to include **actual** vs. **expected behavior** and **steps to reproduce** the issue._

---
I'm running on digital ocean with Ubuntu. Using an external volume for storage.
got this:
2017-11-02 23:10:55 UTC Syncing #4464890 8a22…5001     0 blk/s   20 tx/s   1 Mgas/s   1162+    0 Qed  #4466053    2/25 peers    329 KiB chain   68 MiB db   41 MiB queue  419 KiB sync  RPC:  0 conn,  0 req/s,   0 µs
2017-11-02 23:11:05 UTC Syncing #4464893 033f…4d39     0 blk/s   34 tx/s   1 Mgas/s   1159+    0 Qed  #4466053    3/25 peers    447 KiB chain   67 MiB db   40 MiB queue  419 KiB sync  RPC:  0 conn,  0 req/s,   0 µs

====================

stack backtrace:
   0:     0x55f115e2717c - <no info>

Thread 'Verifier #0' panicked at 'DB flush failed.: "Corruption: block checksum mismatch"', /checkout/src/libcore/result.rs:860

This is a bug. Please report it at:

    https://github.com/paritytech/parity/issues/new

**Comment by 5chdn** [comment] 2017-11-04 13:15
Your database is corrupted. You can reset it with `parity db kill`

Duplicate of #6974

Duplicate of #6960

Duplicate of #6905

Duplicate of #6798

Duplicate of #6790

Duplicate of #6670

Duplicate of #6506

Duplicate of #6501

Duplicate of #5837

Duplicate of #3634

Duplicate of #3432

Duplicate of #2830

Duplicate of #2640

Duplicate of #2603

Duplicate of #763

**Closed by 5chdn** 2017-11-04 13:15 UTC
Labels: M4-core, Z0-question
