### ISSUE TITLE
Parity v1.9.0-unstable freezes with Unexpected rpl Error...

### ISSUE THREAD

**Issue by jfriedhead** [paritytech/parity#6823] opened 2017-10-18 18:05 UTC
_Before filing a new issue, please **provide the following information**._

> I'm running:
>
> - **Parity version**: 1.9.0-unstable-98d0ef3ff-20171016/
> - **Operating system**: Debian GNU/Linux Stretch (Stable)
> - **And installed**: via cargo source code

_Your issue description goes here below. Try to include **actual** vs. **expected behavior** and **steps to reproduce** the issue._

---

I was running Parity version v1.8.0-unstable-492da38d6-20171004 up until it stopped syncing at the hard fork on block number 4,370,000

I then compiled the binary for 1.9.0-unstable to see if it fixes the problem, but when I run the Parity command it gives me the Unexpected rpl Error message below:

stack backtrace:
   0:     0x55dd6ae79a2c - backtrace::backtrace::trace::h3d7946faa2473996
   1:     0x55dd6ae79a6b - backtrace::capture::Backtrace::new::hbeb31b9a68424764
   2:     0x55dd6ae78928 - panic_hook::panic_hook::he41fad7943307f94
   3:     0x55dd6aeac176 - std::panicking::rust_panic_with_hook
                        at /checkout/src/libstd/panicking.rs:612
   4:     0x55dd6aeac004 - std::panicking::begin_panic_new<alloc::string::String>
                        at /checkout/src/libstd/panicking.rs:553
   5:     0x55dd6aeabf09 - std::panicking::begin_panic_fmt
                        at /checkout/src/libstd/panicking.rs:521
   6:     0x55dd6aeabe9a - std::panicking::rust_begin_panic
                        at /checkout/src/libstd/panicking.rs:497
   7:     0x55dd6aeda380 - core::panicking::panic_fmt
                        at /checkout/src/libcore/panicking.rs:92
   8:     0x55dd6a60f606 - core::result::unwrap_failed::h3d1569c811e856ea
   9:     0x55dd6a709997 - <KVDB as ethcore::db::Readable>::read::hf05cdd7a0f9dbe96
  10:     0x55dd6a850f23 - ethcore::blockchain::blockchain::BlockChain::epoch_transition::hc91e4c937f8a8561
  11:     0x55dd6a6d5a20 - ethcore::client::client::Client::new::h8aeb6ba31677d24e
  12:     0x55dd6a77f02b - ethcore::service::ClientService::start::h48945109204c904f
  13:     0x55dd6a190c50 - parity::run::execute::h15d7bf25f0ceb5c5
  14:     0x55dd6a1a8e13 - parity::execute::h1c44d6a91437713e
  15:     0x55dd6a1aee2f - parity::main_direct::h710edebd0fbf28dc
  16:     0x55dd6a1b3163 - parity::main::ha9bc2dedec8224f4
  17:     0x55dd6aeb2c7b - panic_abort::__rust_maybe_catch_panic
                        at /checkout/src/libpanic_abort/lib.rs:40

Thread 'main' panicked at 'Unexpected rlp error: RlpExpectedToBeData', /checkout/src/libcore/result.rs:860

**Comment by 5chdn** [comment] 2017-10-19 11:01
`parity db kill` is your friend.

Fixed in #6665

Duplicate of #6659 #6749 #6786 #6802

**Closed by 5chdn** 2017-10-19 11:01 UTC
