### ISSUE TITLE
Node constantly falls out of sync

### ISSUE THREAD

**Issue by ButteryGuitars** [paritytech/parity#9594] opened 2018-09-19 13:25 UTC
_Before filing a new issue, please **provide the following information**._

- **Parity Ethereum version**: 2.0.5
- **Operating system**: Windows
- **Installation**: one-line installer
- **Fully synchronized**: no / yes
- **Network**: ethereum
- **Restarted**:yes

_Your issue description goes here below. Try to include **actual** vs. **expected behavior** and **steps to reproduce** the issue._

I'm having the same issues in v2.0.5 I've been battling issues keeping Parity in sync for at least a few weeks. I took the plunge to v1.11.8 a few weeks ago and have been battling a behavior where Parity will momentarily fall out of sync then come back. This has persisted from that version to v1.11.10, v1.11.11 and now v2.0.5.

After each subsequent upgrade I've wiped out the cache, db, and nodes.json and warp restored from scratch to isolate out any potential db issues. Same behavior of momentarily falling out of sync, flashing red, then coming back.

I've tweaked all of my config settings I can manage. Tried various cache sizes ranging from 8GB down to 2GB and it doesn't necessarily make much of a difference. I have tracing = off, db_compaction = "ssd", pruning ="fast". I've tried peer counts from 10 up to 150. FWIW, I'm running on a machine with 8 cores, 16GB of memory and an SSD. There isn't anymore hardware or network I can throw at this issue and it appears to be a fundamental flaw in Parity versions starting with v1.11

I've proved out this identical behavior on 3 different workstations.
[parity-v2.0.5-09182018-run-#1.log](https://github.com/paritytech/parity-ethereum/files/2397221/parity-v2.0.5-09182018-run-.1.log)

"2018-09-18 15:49:51 IO Worker #0 DEBUG sync Unexpected packet 4 from unregistered peer: 8:Parity/v1.11.8-stable-c754a02-20180725/x86_64-linux-gnu/rustc1.27.2"

**Comment by joshua-mir** [comment] 2018-09-19 13:56
It's probably not helpful to mention the unexpected packet; it is not the cause of your issue; I only see it once near the beginning of the logs you have provided.

It is unclear whether falling in and out of sync is an issue unless it prevents you from achieving sync at all.

**Comment by joshua-mir** [comment] 2018-09-20 08:55
@ButteryGuitars can you try the 2.1.1/beta and see whether this is still an issue? what kind of peer numbers do you have when this happens?

**Comment by 5chdn** [comment] 2018-09-20 09:03
Duplicate of #9528

**Closed as completed by 5chdn** 2018-09-20 09:03 UTC
Labels: Z7-duplicate 🖨, M4-core ⛓

**Comment by ButteryGuitars** [comment] 2018-09-20 16:56
@joshua-mir will try today. thanks for the response
