### ISSUE TITLE
Cannot start parity as daemon

### ISSUE THREAD

**Issue by kissarat** [paritytech/parity#6906] opened 2017-10-26 23:22 UTC
It happened a couple of hours ago, and I do not know why, I did not do anything with the server. After detecting the error, I updated the parity 1.8.1 -> 1.8.2 beta, but nothing has changed. No aliases exists for parity command

<img width="893" alt="screen shot 2017-10-26 at 10 40 29 pm" src="https://user-images.githubusercontent.com/1538346/32081209-9ec8ba82-babc-11e7-95ee-4c9d2ecbf115.png">

There no error when I run parity not as daemon. Removing `~/.local/share/io.parity.ethereum/config.toml` changes nothing

I'm running:
- **Parity version**: 1.8.1
- **Operating system**: Ubuntu 16.04 Linux 4.4.0 x86_64
- **And installed**: binaries

**Comment by AyushyaChitransh** [comment] 2017-10-27 18:13
Running parity inside a screen might prove to be a helpful alternative to daemon.

Create a new screen using `screen -S parityNode`. Start parity in this screen, and then exit the screen using `CTRL+A and CTRL+D`. To return to that screen, use `screen -r parityNode`.

This is just an alternative to daemon that I use and I think that it might be helpful to you too.

**Comment by kissarat** [comment] 2017-10-29 04:20
@AyushyaChitransh
Is parity runs the same as `parity > parity.log &` ? As I guess `screen` is more convenient way to running in background (only)?

**Comment by 5chdn** [comment] 2017-10-29 07:36
Is this reproducible? What's the content of your config file? Can you try running with `--no--config` ?

**Comment by AyushyaChitransh** [comment] 2017-10-29 07:39
I had no config file, not even in the default location. It was a new server with a fresh installation of parity. But I'll try reproducing it with `--no-config` option.

**Comment by 5chdn** [comment] 2017-10-29 07:40
@AyushyaChitransh do you experience the same issue?

**Comment by AyushyaChitransh** [comment] 2017-10-29 07:41
Pardon me! I confused it with another issue.

**Comment by axelchalon** [comment] 2017-10-30 11:00
This is due to https://github.com/paritytech/parity/blob/f9e588dd7ba3987150e3ff476a2f314413179586/parity/main.rs#L260-L262

The `--can-restart` flag is passed at the end of the flags where it should be passed as first flag (global arguments need to come before subcommands since https://github.com/paritytech/parity/pull/6356) ; will make a PR.

**Comment by axelchalon** [comment] 2017-11-10 10:08
fixed with https://github.com/paritytech/parity/pull/7004

**Closed by axelchalon** 2017-11-10 10:08 UTC
Labels: F2-bug, Z5-unconfirmed

**Comment by LordOfBongo** [comment] 2018-01-21 00:30
Im running parity on w10. Need to generate a new token. Im a total noob and don't know much about coding. So this is what it looks like. Any easy way for a noob like me to get this fixed?
![parity signer new-token](https://user-images.githubusercontent.com/35643950/35189424-87171ba0-fe4a-11e7-8790-93fa0427efe3.png)
![parity](https://user-images.githubusercontent.com/35643950/35189427-8ea780a8-fe4a-11e7-85d0-028665460b15.png)

**Comment by 5chdn** [comment] 2018-01-22 09:57
@LordOfBongo hey, this has been fixed for a while, please upgrade to 1.8.6 :)
