### ISSUE TITLE
Parity Taking Up All My C: Drive. HELP!

### ISSUE THREAD

**Issue by rbranston** [paritytech/parity#7419] opened 2018-01-02 00:54 UTC
_Before filing a new issue, please **provide the following information**._

> I'm running: Window 10
>
> - **Which Parity version?**: 1.7.8

> - **Which operating system?**: Windows
> - **How installed?**: via installer
> - **Are you fully synchronized?**: yes
> - **Did you try to restart the node?**: no

_Your issue description goes here below. Try to include **actual** vs. **expected behavior** and **steps to reproduce** the issue._

Hi,

My C drive says it is full. Under C:\User\myname\AppData\Parity\Ethereum\chains\ethereum\db
I see tons and tons of gigabyte files here. Can I delete all these? I there a simple way to copy and paste all these chains to my D Drive? What is the most efficient/safe way to fix this problem?

Thank you in advance.

**Comment by 5chdn** [comment] 2018-01-02 11:20
Please upgrade to 1.7.11-stable or 1.8.5-beta and reset your database with:

    parity.exe db kill

**Comment by 5chdn** [comment] 2018-01-02 11:21
Duplicate of #6280

**Closed by 5chdn** 2018-01-02 11:20 UTC

**Comment by rbranston** [comment] 2018-01-03 03:07
Where can I preform this upgrade?

**Comment by rbranston** [comment] 2018-01-03 04:20
I figured it out.

Im switching my parity wallet to chrome instead of firefox because i was told its better. Its asking me for a new token now though. Do I just get that from this page?
![image](https://user-images.githubusercontent.com/35016027/34509032-904638d6-f013-11e7-97c4-ff334f84c97e.png)

**Comment by 5chdn** [comment] 2018-01-03 12:54
Wait until your client is fully synchronized.

Your issue will be fixed in 1.8.6 coming up this week.

**Comment by rbranston** [comment] 2018-01-04 01:43
Ok, 

I did a parity kill and my chain is resyncing now.

I was also told to do this cmd: parity.exe --min-peers 100 --max-peers 500 --log-file=parity.log

is that ok?

**Comment by 5chdn** [comment] 2018-01-04 09:55
looks good.

**Comment by rbranston** [comment] 2018-01-04 17:25
Will I keep having to delete my parity chains every few weeks though to keep my C drive from filling up again?

**Comment by 5chdn** [comment] 2018-01-04 20:54
No. Not once we released 1.8.6 :)

Stay tuned :)
