### ISSUE TITLE
Tokens not showing up in Parity

### ISSUE THREAD

**Issue by ShaggyDogDog** [paritytech/parity#6599] opened 2017-09-27 05:26 UTC
_Before filing a new issue, please **provide the following information**._

> I'm running: 
>
> - **Parity version**: 1.7
> - **Operating system**: Windows 
> - **And installed**: via installer 

Purchased some tokens from a well know platform. Withdrew those token to my parity wallet. 29 hours has elapsed and they (tokens) have still not shown up.  I have purchase token (the same token) at least 7 times from this platform and transferred them to my parity wallet each time without issue.  I can see the transaction on the blockchain and my parity wallet address is correct. I only haw a few ETH in the parity wallet but hold a lot of these particular tokens. I have never had an issue in the past and the transfers usually shows in a few minutes. The Tx has is 0xe5bdc448d2c01b73d7dc07bfba1f9d8fd67e7c3c2aec44906efae041853bf95d from EthScan - and all seems ok yet no token in the wallet.  Any suggestions?

---

**Comment by 5chdn** [comment] 2017-09-27 08:17
Are you on 1.7.0 or 1.7.2?

Probably duplicate of #6549

**Closed** 2017-09-27 08:17 UTC
Labels: Z0-duplicate

**Comment by ShaggyDogDog** [comment] 2017-09-27 08:59
if i go to home in the parity wallet is state 1.7. Is there a more thorough
way to confirm version?

Thanks

Dan

**Comment by 5chdn** [comment] 2017-09-27 09:34
After launching parity it says

    2017-09-27 11:33:26  Starting Parity/v1.7.2-beta-9f47909ed-20170918/x86_64-linux-gnu/rustc1.20.0

Or in the wallet you can find the version in the footer like this
 
    Parity//v1.7.2-beta-9f47909ed-20170918/x86_64-linux-gnu/rustc1.20.0

**Comment by ShaggyDogDog** [comment] 2017-09-28 07:56
thanks they finally showed up - not sure why the significant delay. Thanks
for your input.

**Comment by thommeredith** [comment] 2018-01-19 02:33
I am having this issue as well

I'm running:

Parity version: 1.8.6
Operating system: MacOS
And installed: via installer

https://etherscan.io/tx/0xa09909aa6c3b3b1527fc8ce8803083a51e5ada03eb62160da9d53cb04a5e3cab

https://www.dropbox.com/s/myo7jfaknmuj98n/Screenshot%202018-01-18%2018.32.01.PNG?dl=0

**Comment by 5chdn** [comment] 2018-01-19 09:13
I clearly see your token, @thommeredith
