### ISSUE TITLE
ethkey.exe crash upon launch

### ISSUE THREAD

**Issue by Toobis** [paritytech/parity#7785] opened 2018-02-02 00:38 UTC
> I'm running: Windows 10 
>
> - **Which Parity version?**: 0.0.0
> - **Which operating system?**: Windows 10
> - **How installed?**: via installer 
> - **Are you fully synchronized?**: no
> - **Which network are you connected to?**: n/a
> - **Did you try to restart the node?**: no

_Your issue description goes here below. Try to include **actual** vs. **expected behavior** and **steps to reproduce** the issue._

Program crashes upon launch. Not able to change any settings. Reporting as requested.

![image](https://user-images.githubusercontent.com/8886151/35710753-ff8c8c60-076d-11e8-94cc-f8c21ce889df.png)

**Comment by 5chdn** [comment] 2018-02-02 07:58
Duplicate of #7772 

Please do not use ethkey.exe on Windows. Download the Parity installer.

**Closed by 5chdn** 2018-02-02 07:58 UTC

**Comment by JamesX88** [comment] 2018-02-02 11:23
You realize the website downloads that file on parity.io? It's not our problem, it's a website problem. I found the release here on Github but the website should be linking people there.

**Comment by JamesX88** [comment] 2018-02-02 11:24
When you goto parity.io and click "Download for windows" button, it downloads this:
https://d1h4xl4cr1h0mo.cloudfront.net/stable/x86_64-pc-windows-msvc/ethkey.exe

**Comment by maciejhirsz** [comment] 2018-02-02 11:58
@Toobis @JamesX88 this should now be resolved, can you confirm?

**Comment by JamesX88** [comment] 2018-02-02 12:03
@maciejhirsz fixed now. cheers!
