### ISSUE TITLE
Unable to sign transactions with Ledger

### ISSUE THREAD

**Issue by bamos01** [paritytech/parity#7786] opened 2018-02-02 03:13 UTC
_Before filing a new issue, please **provide the following information**._

> I'm running:
>
> - **Which Parity version?**: 0.9.1
> - **Which operating system?**: Mac Os
> - **How installed?**: via installer 
> - **Are you fully synchronized?**: yes
> - **Which network are you connected to?**: ethereum 
> - **Did you try to restart the node?**: yes

_Your issue description goes here below. Try to include **actual** vs. **expected behavior** and **steps to reproduce** the issue._

My ledger wallet is recognized but when i click the button on the parity transaction signer to confirm on ledger - i receive the following error on the parity signer window:
[-32602] Invalid params: invalid type: null, expected a string.

And no transaction data appears to be sent to the ledger

It seemed to be working fine before 0.9.0

**Comment by troncmp** [comment] 2018-02-02 23:11
i am having the same issue as described above?  my non ledger wallets sign transactions no problem...but my ledger wallet spits out [-32602] Invalid params: invalid type: null, expected a string.close when trying to sign

**Comment by fifinger** [comment] 2018-02-05 03:28
It seems the original poster mistyped version 0.9.0 and meant to type 1.9.0

I am also experiencing the same problem which only started occuring after upgrading from 1.8.2 to 1.9.0. Clearly this is a bug in parity 1.9.0 because everything used to work just fine in 1.8.x

I have been able to replicate this error (see below) when trying to sign smart contract requests or when signing transfers - so this doesn´t seem to be a contract related issue. Any thoughts would be greatly apprecaited.

[-32602] Invalid params: invalid type: null, expected a string.

**Comment by fifinger** [comment] 2018-02-05 06:05
This can be fixed by quitting the parity service, then moving the parity ethereum app in the applications folder to the trash bin and finally downloading the latest **stable** release of the 1.8.8 pkg installer from the parity.io website. This seems to be a problem that only occurs in the beta of 1.9.

**Comment by 5chdn** [comment] 2018-02-05 09:40
Please use 1.8.9 stable! Thanks!

**Closed by 5chdn** 2018-02-05 09:40 UTC

**Comment by troncmp** [comment] 2018-02-05 16:55
hey Afri thanks for the response..

yes but then if i use 1.8.9 stable, the erc20 tokens dont show up..that is why i upgraded to 1.9.1 so the erc20 tokens would show up

**Comment by 5chdn** [comment] 2018-02-06 11:06
1.8.9 should show tokens.

**Comment by sillytuna** [comment] 2018-02-07 14:21
Same problem with all 1.9.x builds.

**Comment by Sofoca** [comment] 2018-02-13 10:24
Maybe reference as duplicate to #7820?

**Comment by 5chdn** [comment] 2018-02-13 10:58
Yes thank you.

**Comment by 5chdn** [comment] 2018-02-13 10:58
Duplicate of #7820
