### ISSUE TITLE
Contract deployment in signer doesn't display value

### ISSUE THREAD

**Issue by tomusdrw** [paritytech/parity#4393] opened 2017-02-02 08:23 UTC
You need to go to the details to actually see how much value is being transfered with contract creation,
would be good to have this information displayed more explicitly cause it seems important.

![screenshot from 2017-02-02 00-26-13](https://cloud.githubusercontent.com/assets/581548/22541823/1967b8a8-e929-11e6-85d1-3c261ef66d04.png)

(Perhaps it's more of a bug, cause in the description it says "for a total of transaction value of ..." but displays only fees)

**Comment by 5chdn** [comment] 2017-05-10 11:13
This issue is labelled with _annoyance_: The client behaves within expectations, however this "expected behaviour" itself is at issue. It's inactive since February, neither assigned nor linked to any milestone.

@paritytech/ui-devs Please decide on a deadline and add an assignee within 7 days, thanks!

**Comment by ngotchac** [comment] 2017-05-10 11:39
This is fixed in the current Wallet version.

**Closed by ngotchac** 2017-05-10 11:39 UTC
Labels: F3-annoyance, M7-ui
