### ISSUE TITLE
New account cannot be created using chain and keys-path options for Parity 1.8.2

### ISSUE THREAD

**Issue by Ochir** [paritytech/parity#6943] opened 2017-10-31 11:10 UTC
> I'm running:
>
> - **Parity version**: 1.8.2
> - **Operating system**:  Linux/Ubuntu 16.04
> - **And installed**: via installer

_Your issue description goes here below. Try to include **actual** vs. **expected behavior** and **steps to reproduce** the issue._

When I ran version 1.7.x I was able to create a new account by running command 
"parity account new --chain morden.json --keys-path eth/keys"

With version 1.8.2 I get the error message for the same command: 
"error: Found argument '--chain' which wasn't expected, or isn't valid in this context"

Account can be created with password option but it is not clear where account is created.

**Comment by axelchalon** [comment] 2017-11-01 10:14
Hi, "global" arguments need to come before the subcommand now: `parity --chain morden.json --keys-path eth/keys account new`

**Comment by Ochir** [comment] 2017-11-01 10:34
alright, then the hint should be fixed. Right now it shows previous variant.

**Comment by Office-Julia** [comment] 2017-11-01 12:12
@axelchalon if I not mistake in older version of Parity order didn't matter.
Actually I am not sure why order of arguments play role here. Sounds like a bug to me.
So "bug" for now.

**Comment by axelchalon** [comment] 2017-11-01 12:15
@Office-Julia yes you're right, in older versions it didn't matter; but since https://github.com/paritytech/parity/pull/6356 "global" options need to be passed before the command

**Comment by 5chdn** [comment] 2017-11-01 21:53
Closing as intended behavior. Maybe needs some more explicit docs / usage instructions.

**Closed by 5chdn** 2017-11-01 21:53 UTC
Labels: M4-core, Z0-intended
