### ISSUE TITLE
export import core dump

### ISSUE THREAD

**Issue by ng0177** [paritytech/parity#7329] opened 2017-12-19 06:05 UTC
017-12-19 06:25:34  Syncing #3687844 d908…3694    93 blk/s 1911 tx/s  81 Mgas/s      0+ 2705 Qed     7 MiB chain 78 MiB db 41 MiB queue  
2017-12-19 06:25:44  Syncing #3688933 e933…d188   110 blk/s 2385 tx/s  92 Mgas/s      0+ 2790 Qed     7 MiB chain 78 MiB db 39 MiB queue  
2017-12-19 06:25:54  Syncing #3689964 de1b…0117    96 blk/s 1833 tx/s  89 Mgas/s      0+ 2700 Qed     8 MiB chain 78 MiB db 40 MiB queue  
2017-12-19 06:26:04  Syncing #3690993 3226…153a   110 blk/s 2297 tx/s 106 Mgas/s      0+ 2728 Qed     13 MiB chain 78 MiB db 39 MiB queue  
2017-12-19 06:26:04  Stage 2 block verification failed for 3913…e13e: Block(MismatchedH256SealElement(Mismatch { expected: 3bbb39a8bf646b35b6318a68d7db325d8917801c6eb6b33a1102a2341208372f, found: 9dcad3110fbfdfecc317bd8fd8c9991fe7c15177a465aa0ec1ac769ab3049953 }))
Cannot import block: Import(KnownBad)
[th6mas@freckle ~]$ parity import /run/media/th6mas/BLOCKCHAIN/ethereum/chain/ethereum-chain-backup.rlp
2017-12-19 06:32:14  Configured for Foundation using Ethash engine
2017-12-19 06:32:50       10 KiB chain 60 MiB db 0 bytes queue  
2017-12-19 06:33:15  Syncing #3691386 85e0…4c39     1 blk/s   27 tx/s   1 Mgas/s   1974+  400 Qed     171 KiB chain 60 MiB db 13 MiB queue  
2017-12-19 06:33:25  Syncing #3692346 e06f…bea9    96 blk/s 2148 tx/s  85 Mgas/s      0+ 5716 Qed     4 MiB chain 64 MiB db 79 MiB queue  
2017-12-19 06:33:36  Syncing #3693639 6ea5…a709   123 blk/s 2278 tx/s 108 Mgas/s      0+ 4424 Qed     8 MiB chain 69 MiB db 61 MiB queue  
2017-12-19 06:33:45  Syncing #3694579 9322…8c87    98 blk/s 1808 tx/s  92 Mgas/s      0+ 3484 Qed     7 MiB chain 71 MiB db 49 MiB queue  
2017-12-19 06:33:55  Syncing #3695738 3f23…122b   115 blk/s 2286 tx/s 126 Mgas/s      0+ 2878 Qed     7 MiB chain 74 MiB db 41 MiB queue  
2017-12-19 06:34:05  Syncing #3696908 6770…897d   117 blk/s 1975 tx/s 101 Mgas/s      0+ 2753 Qed     8 MiB chain 76 MiB db 40 MiB queue  
2017-12-19 06:34:16  Syncing #3697998 d44c…d782   107 blk/s 2197 tx/s  98 Mgas/s      0+ 3084 Qed     8 MiB chain 78 MiB db 41 MiB queue  
2017-12-19 06:34:25  Syncing #3699236 6f2a…fcde   125 blk/s 2441 tx/s 112 Mgas/s      0+ 3155 Qed     8 MiB chain 78 MiB db 39 MiB queue  
2017-12-19 06:34:31  Syncing #3699805 28d6…db56   108 blk/s 1830 tx/s  88 Mgas/s      0+ 3218 Qed     8 MiB chain 78 MiB db 40 MiB queue  
2017-12-19 06:34:40  Syncing #3700811 6500…2c06   103 blk/s 1673 tx/s  89 Mgas/s      0+ 3186 Qed     8 MiB chain 78 MiB db 42 MiB queue  
2017-12-19 06:34:50  Syncing #3701944 68df…f834   113 blk/s 1916 tx/s 108 Mgas/s      0+ 2906 Qed     8 MiB chain 78 MiB db 41 MiB queue  
2017-12-19 06:35:00  Syncing #3703107 6ad0…1d75   116 blk/s 2070 tx/s 102 Mgas/s      0+ 2815 Qed     8 MiB chain 77 MiB db 39 MiB queue  
2017-12-19 06:35:10  Syncing #3704022 7bd3…d0ff    91 blk/s 1945 tx/s  86 Mgas/s      0+ 3056 Qed     8 MiB chain 77 MiB db 42 MiB queue  
2017-12-19 06:35:20  Syncing #3705148 ed9b…34c9   112 blk/s 2051 tx/s 109 Mgas/s    231+ 2962 Qed     8 MiB chain 78 MiB db 41 MiB queue  
2017-12-19 06:35:30  Syncing #3706323 3ff9…72e3   117 blk/s 1985 tx/s 100 Mgas/s      0+ 2814 Qed     8 MiB chain 78 MiB db 41 MiB queue  
2017-12-19 06:35:40  Syncing #3707254 7412…9cf8    93 blk/s 1991 tx/s 101 Mgas/s      0+ 2477 Qed     8 MiB chain 77 MiB db 39 MiB queue  

====================

stack backtrace:
   0:     0x55fd4591858c - backtrace::backtrace::trace::h834b76b8e250796e
   1:     0x55fd459186e2 - backtrace::capture::Backtrace::new::hfd9a5edc2b89174a
   2:     0x55fd44fb78a8 - panic_hook::panic_hook::h1e1f15be4ae4fb73
   3:     0x55fd45a292e5 - std::panicking::rust_panic_with_hook::he3f5d1b3fe35e66c
   4:     0x55fd45a290f4 - std::panicking::begin_panic::h51f448984789a85b
   5:     0x55fd45a29069 - std::panicking::begin_panic_fmt::hfe4f00f98044189d
   6:     0x55fd45a28ffa - rust_begin_unwind
   7:     0x55fd45a37c70 - core::panicking::panic_fmt::h9927bd7bca5c28d9
   8:     0x55fd452117d2 - core::result::unwrap_failed::hf7c718e3287adf85
   9:     0x55fd452e130a - ethcore::client::client::Client::import_verified_blocks::hcda1b4ecb15c8f5a
  10:     0x55fd451a9782 - std::sys_common::backtrace::__rust_begin_short_backtrace::h4c508b7de3d752ce
  11:     0x55fd451addd6 - std::panicking::try::do_call::h15d375bb3c33c5b4
  12:     0x55fd45a2fd6b - __rust_maybe_catch_panic

Thread 'IO Worker #3' panicked at 'DB flush failed.: Error(Msg("Corruption: block checksum mismatch"), State { next_error: None, backtrace: None })', src/libcore/result.rs:906

This is a bug. Please report it at:

    https://github.com/paritytech/parity/issues/new

====================

stack backtrace:
   0:     0x55fd4591858c - backtrace::backtrace::trace::h834b76b8e250796e
   1: Aborted (core dumped)

I use Fedora 27 [th6mas@freckle ~]$ parity --version
Parity
  version Parity/v1.9.0-unstable-5cb53ddd8-20171218/x86_64-linux-gnu/rustc1.21.0
Copyright 2015, 2016, 2017 Parity Technologies (UK) Ltd
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>.
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.

By Wood/Paronyan/Kotewicz/Drwięga/Volf
   Habermeier/Czaban/Greeff/Gotchac/Redmann

**Comment by 5chdn** [comment] 2018-01-02 14:35
Duplicate of #7334

**Closed by 5chdn** 2018-01-02 14:35 UTC
Labels: M4-core, Z5-unconfirmed
