### ISSUE TITLE
parity  failing with core dump.

### ISSUE THREAD

**Issue by Gaurang10** [paritytech/parity#7580] opened 2018-01-16 12:41 UTC
_Before filing a new issue, please **provide the following information**._

> I'm running: parity for syncing ethereum main net but getting core dump. 
>
> - **Which Parity version?**: 0.0.0
 version Parity/v1.8.6-beta-2d051e4-20180109/x86_64-linux-gnu/rustc1.22.1

> - **Which operating system?**: Windows / MacOS / Linux
lsb_release -a
No LSB modules are available.
Distributor ID:	Ubuntu
Description:	Ubuntu 16.04.3 LTS
Release:	16.04
Codename:	xenial

> - **How installed?**: via installer / homebrew / binaries / from source
installer

> - **Are you fully synchronized?**: no / yes
no.

> - **Which network are you connected to?**: ethereum / ropsten / kovan / ...
ethereum

> - **Did you try to restart the node?**: no / yes
yes, twice

_Your issue description goes here below. Try to include **actual** vs. **expected behavior** and **steps to reproduce** the issue._
Just try to sync the main net to use JSON - RPC for reading event data.

**Comment by 5chdn** [comment] 2018-01-16 14:02
Hi, your issue description is missing the critical part: The issue description :)

What did you do? What did you expect? What did happen? Please also share your configuration and some logs, thanks!

**Comment by 5chdn** [comment] 2018-01-17 12:22
Thanks for your detailed report! Please follow progress in this issue: #7536

**Comment by 5chdn** [comment] 2018-01-17 12:22
Duplicate of #7536

**Closed by 5chdn** 2018-01-17 12:22 UTC
Labels: M4-core, Z0-question
