### ISSUE TITLE
Compiling evm v0.1.0  error[E0308]: match arms have incompatible types

### ISSUE THREAD

**Issue by drandreaskrueger** [paritytech/parity#6611] opened 2017-09-29 15:26 UTC
Error during `cargo` install of `parity v1.7.2` on `arch linux`:
```
Compiling evm v0.1.0  error[E0308]: match arms have incompatible types
```

details:
```
cargo install --tag v1.7.2 --git https://github.com/paritytech/parity.git parity
    Updating git repository `https://github.com/paritytech/parity.git`
  Installing parity v1.7.2 (https://github.com/paritytech/parity.git?tag=v1.7.2#9f47909e)
    Updating registry `https://github.com/rust-lang/crates.io-index`
[...]
   Compiling common-types v0.1.0 (https://github.com/paritytech/parity.git?tag=v1.7.2#9f47909e)
   Compiling evm v0.1.0 (https://github.com/paritytech/parity.git?tag=v1.7.2#9f47909e)
error[E0308]: match arms have incompatible types
  --> .cargo/git/checkouts/parity-dc9825eb65b3adf1/9f47909/ethcore/evm/src/wasm/mod.rs:90:4
   |
90 | / 			elements::Module::deserialize(
91 | | 				&mut cursor
92 | | 			).map_err(|err| {
93 | | 				evm::Error::Wasm(format!("Error deserializing contract code ({:?})", err))
94 | | 			})?
   | |______^ expected struct `parity_wasm::elements::module::Module`, found struct `parity_wasm::elements::Module`
   |
   = note: expected type `parity_wasm::elements::module::Module`
              found type `parity_wasm::elements::Module`
note: match arm with an incompatible type
  --> .cargo/git/checkouts/parity-dc9825eb65b3adf1/9f47909/ethcore/evm/src/wasm/mod.rs:90:4
   |
90 | / 			elements::Module::deserialize(
91 | | 				&mut cursor
92 | | 			).map_err(|err| {
93 | | 				evm::Error::Wasm(format!("Error deserializing contract code ({:?})", err))
94 | | 			})?
   | |______^
note: Perhaps two different versions of crate `parity_wasm` are bCompiling evm v0.1.0  error[E0308]: match arms have incompatible typeseing used?
  --> .cargo/git/checkouts/parity-dc9825eb65b3adf1/9f47909/ethcore/evm/src/wasm/mod.rs:90:4
   |
90 | / 			elements::Module::deserialize(
91 | | 				&mut cursor
92 | | 			).map_err(|err| {
93 | | 				evm::Error::Wasm(format!("Error deserializing contract code ({:?})", err))
94 | | 			})?
   | |______^

error[E0308]: mismatched types
   --> .cargo/git/checkouts/parity-dc9825eb65b3adf1/9f47909/ethcore/evm/src/wasm/mod.rs:119:62
    |
119 | 			let module_instance = self.program.add_module("contract", contract_module, Some(&execution_params.externals))
    | 			                                                          ^^^^^^^^^^^^^^^ expected struct `parity_wasm::elements::Module`, found struct `parity_wasm::elements::module::Module`
    |
    = note: expected type `parity_wasm::elements::Module`
               found type `parity_wasm::elements::module::Module`
note: Perhaps two different versions of crate `parity_wasm` are bCompiling evm v0.1.0  error[E0308]: match arms have incompatible typesCompiling evm v0.1.0  error[E0308]: match arms have incompatible typesCompiling evm v0.1.0  error[E0308]: match arms have incompatible typeseing used?
   --> .cargo/git/checkouts/parity-dc9825eb65b3adf1/9f47909/ethcore/evm/src/wasm/mod.rs:119:62
    |
119 | 			let module_instance = self.program.add_module("contract", contract_module, Some(&execution_params.externals))
    | 			                                                          ^^^^^^^^^^^^^^^

error: aborting due to 2 previous errors

error: Could not compile `evm`.
warning: build failed, waiting for other jobs to finish...
error: failed to compile `parity v1.7.2 (https://github.com/paritytech/parity.git?tag=v1.7.2#9f47909e)`, intermediate artifacts can be found at `/tmp/cargo-install.vs2zVVskVsYB`

Caused by:
  build failed
```

I'm running:

```
rustup --version; rustc --version; cargo --version; uname -a; 
rustup 1.6.0
rustc 1.20.0 (f3d6973f4 2017-08-27)
cargo 0.21.0 (5b4b8b2ae 2017-08-12)
Linux .... 4.11.5-1-ARCH #1 SMP PREEMPT Wed Jun 14 16:19:27 CEST 2017 x86_64 GNU/Linux
```

Installed via cargo:

```
sudo pacman -R rust cargo rustup
sudo pacman -R rustup
rm .cargo -rf

sudo pacman -Sy rustup
rustup default stable

cargo install --tag v1.7.2 --git https://github.com/paritytech/parity.git parity
```

**Comment by tomusdrw** [comment] 2017-09-29 16:18
`cargo install` is broken (doesn't respect the `Cargo.lock` file). Please clone the repo and build manually.

**Comment by drandreaskrueger** [comment] 2017-09-29 17:28
Thanks a lot. 

This now worked indeed:

```
git clone https://github.com/paritytech/parity
cd parity
git checkout tags/v1.7.2
git submodule update --init

cargo build --release

sudo ln -s ~/parity/target/release/parity /usr/local/bin/
parity --version
```

> version Parity/v1.7.2-unstable-9f47909ed-20170918/x86_64-linux-gnu/rustc1.19.0


thank you very much.

**Comment by tomusdrw** [comment] 2017-09-29 18:06
Closing as a duplicate of #6007

**Closed by tomusdrw** 2017-09-29 18:07 UTC
