### ISSUE TITLE
database broken

### ISSUE THREAD

**Issue by xtien** [paritytech/parity#7623] opened 2018-01-18 16:35 UTC
> I'm running:
>
> - **Which Parity version?**: 1.8.5
> - **Which operating system?**:  Linux
> - **How installed?**: via installer
> - **Are you fully synchronized?**: no / yes
> - **Which network are you connected to?**: ethereum 

I was fully synchronized. Then Ubuntu needed to restart my computer, I stopped Parity, I rebooted, I started "parity ui", it started, but it was out of sync, so it started syncing all right. But after a while, before it was fully synced, it slowed down and hung up my computer. I tried all kinds of things, I ended up rebooting my computer again. Then, when I started parity, I got this:

Client(Database("Invalid argument: You have to open all column families. Column families not opened: col7, col6, col5, col4, col3, col2, col1, col0"))

I deleted the database, then parity had to sync. After syncing for about 20 hours, it had come to October 2016, it hung up my computer again. I managed to stop all processes, to stop parity properly (letting it finish its work so I wouldn't get a corrupted database) but I still get this error again:

Client(Database("Invalid argument: You have to open all column families. Column families not opened: col7, col6, col5, col4, col3, col2, col1, col0"))

What can I do without deleting the database? 
I have a couple of ethers that I access via parity, without having a synced db I don't know how to get the coins back. I know I can, but I do want to get the chain back on my computer.

Should I kill the db and sync for another six days, or is there something else I can do?

**Comment by xtien** [comment] 2018-01-18 17:14
I have killed the database, I have upgraded Parity to the latest version. It started doing "syncing snapshot", but that stopped half way, so normal syncing started at zero. I have never ever seen "syncing snapshot" work.

**Comment by roninkaizen** [comment] 2018-01-19 00:57
i had this behavior with single-head-cpu usage at 1 GB RAM on various intel systems with various linux installations, ubuntu and debian show same behaviour.
my "fix" was to built in more RAM,
best with 4 GB, after having that, 
setting up additionally a SWAP-Space and activate it
and you will be able to operate a stable running node.
otherwise you can meet me at gitter at
https://gitter.im/paritytech/parity

**Comment by xtien** [comment] 2018-01-19 11:50
My computer has 16Gb of RAM. 
Syncing is now at 4888135, speed is about the same speed that blocks are created. Which means I'll never catch up.

**Comment by kirushik** [comment] 2018-01-19 12:02
@xtien Current `foundation` block speed is about one block per 15 seconds (https://stats.parity.io/).
Are you sure your sync is that slow? I've never seen a sync so slow, actually.
Also, your initial post says that you're running Parity `1.8.5`, can you plase make sure you've upgraded to 1.8.6?

**Comment by winsvega** [comment] 2018-01-19 20:44
got the same issue after copying the database from one machine to another.

**Comment by xtien** [comment] 2018-01-20 16:20
I have parity 1.8.6 now. I use an hdd, I have ordered an ssd and I'll move the database to the ssd. For now, sync speed is about one block per five seconds. As one new block is created ever 15 seconds, the sync speed is two blocks per 15 seconds. Parity managed to do one snapshot sync, which brought me to 4.3M, but most snapshot syncs just don't finish as if the snapshots are incomplete. 

I am at 4922815 now, I expect syncing to take at least another day and a half. 

There is another issue: parity gradually hangs up my computer when syncing. When the computer is hung up, I can't just reboot, because that corrupts the database and I need to resync from scratch. Happened twice in the last month. 
I'll keep syncing until I can see my coins again (bought one last Wednesday), then backup the parity db so I don't have to sync all of it again.

**Comment by winsvega** [comment] 2018-01-20 17:39
syncing on ssd - 2/3 blocks per second.
on hdd is like not going anywhere. but I could hear that it's killing the drive.

**Comment by 5chdn** [comment] 2018-01-22 11:06
Duplicate of #7334

**Closed by 5chdn** 2018-01-22 11:06 UTC
