### ISSUE TITLE
Parity windows service and max_peers configuration

### ISSUE THREAD

**Issue by jeffallen6767** [paritytech/parity#7577] opened 2018-01-16 10:55 UTC
1st thanks for the windows installer, it made getting up-and-running with Parity a breeze!

> I'm running:
>
> - **Which Parity version?**: Parity/1.8.5/1.22.1/windows
> - **Which operating system?**: Windows 10 Home
> - **How installed?**: via installer
> - **Are you fully synchronized?**: yes
> - **Which network are you connected to?**: ethereum ( main chain says "Foundation" )
> - **Did you try to restart the node?**: yes

The parity.exe service along with ptray start automatically when I boot my system and log into Windows 10.  I currently use the parity service as a back-end for mining with a different application.

I'm able to use the config generator at: https://paritytech.github.io/parity-config-generator/ to generate a config.toml file which is located properly at: %UserProfile%\AppData\Roaming\Parity\Ethereum\config.toml 

My configuration follows:

> [rpc]
> cors = "local"
> 
> [mining]
> author = "<redacted>" ( I can provide this if necessary )
> extra_data = "some msg that works"
> 
> [network]
> max_peers = 16
> max_pending_peers = 16
> no_serve_light = true

I'm able to configure some properties such as cors, author, and extra_data, but none of the [network] values seem to be picked-up and used, my connections as viewed in the web-client are usually 0/25/25 and I'm using quite a bit more network bandwidth than I'm comfortable with... ( I'm capped to 1024 GB / Month by my provider, and I'm using at least that much by my calculations 1/2 way into the month so far... )

Please help me limit my bandwidth usage.

Thanks,
Jeff Allen

**Comment by 5chdn** [comment] 2018-01-16 11:00
Duplicate of #7576

**Comment by 5chdn** [comment] 2018-01-16 11:01
Default min peers is 25, you need to reduce this to get less than this.

**Closed by 5chdn** 2018-01-16 11:00 UTC
