### ISSUE TITLE
dependancy not supported

### ISSUE THREAD

**Issue by oeneme** [paritytech/parity#7314] opened 2017-12-17 17:02 UTC
libssl1.0.2 not supported (but libssl1.0.0 is) making it uninstallable on the current stable release branch of Debian

Parity 1.7.10-stable
Debian 9
installed from command line (x86_64 | parity_1.7.10_amd64.deb)

**Comment by NikVolf** [comment] 2017-12-18 09:16
duplicate of https://github.com/paritytech/parity/issues/5893

**Closed by NikVolf** 2017-12-18 09:16 UTC
Labels: M0-build
