### ISSUE TITLE
pure virtual method called

### ISSUE THREAD

**Issue by tom-seddon** [paritytech/parity#6762] opened 2017-10-14 21:41 UTC
_Before filing a new issue, please **provide the following information**._

> I'm running:
>
> - **Parity version**: Parity/v1.7.6-stable-1953533-20171013/x86_64-linux-gnu/rustc1.20.0
> - **Operating system**: Linux VM (`Linux parity-vbox 4.10.0-37-generic #41~16.04.1-Ubuntu SMP Fri Oct 6 22:42:59 UTC 2017 x86_64 x86_64 x86_64 GNU/Linux`)
> - **And installed**: via installer 

---

After running Parity, and hitting Ctrl+C to make it stop, I get a `pure virtual method called` error followed by a core dump. Here's the output from an example run, minus the enode URL that I removed:

```
tom@parity-vbox:~$ parity
2017-10-14 22:36:03  Starting Parity/v1.7.6-stable-1953533-20171013/x86_64-linux-gnu/rustc1.20.0
2017-10-14 22:36:03  Keys path /home/tom/.local/share/io.parity.ethereum/keys/Foundation
2017-10-14 22:36:03  DB path /home/tom/.local/share/io.parity.ethereum/chains/ethereum/db/906a34e69aec8c0d
2017-10-14 22:36:03  Path to dapps /home/tom/.local/share/io.parity.ethereum/dapps
2017-10-14 22:36:03  State DB configuration: fast
2017-10-14 22:36:03  Operating mode: active
2017-10-14 22:36:03  Configured for Foundation using Ethash engine
2017-10-14 22:36:12  Public node URL: ........
2017-10-14 22:36:27  Imported #4366128 4536…00c7 (85 txs, 6.70 Mgas, 3879.72 ms, 18.12 KiB)
2017-10-14 22:36:32  Syncing #4366128 4536…00c7     0 blk/s    0 tx/s   0 Mgas/s      0+    0 Qed  #4366128    3/25 peers   670 KiB chain 65 MiB db 0 bytes queue 339 KiB sync  RPC:  0 conn,  0 req/s,   0 µs
2017-10-14 22:36:35  Imported #4366129 a45b…42e2 (11 txs, 0.69 Mgas, 283.07 ms, 2.06 KiB)
2017-10-14 22:36:42  Imported #4366130 74b5…b4cd (184 txs, 6.69 Mgas, 851.03 ms, 25.00 KiB)
^C2017-10-14 22:36:45  Finishing work, please wait...
pure virtual method called
terminate called without an active exception

Aborted (core dumped)
```

It's done this several times, both when run as `parity` and when run as `parity ui`.

Thanks,

--Tom

**Comment by 5chdn** [comment] 2017-10-16 08:29
duplicate of #6213

**Closed by 5chdn** 2017-10-16 08:29 UTC
