### ISSUE TITLE
Signing via hardware wallets is not supported

### ISSUE THREAD

**Issue by banteg** [paritytech/parity#6717] opened 2017-10-12 00:49 UTC
> I'm running:
>
> - **Parity version**: Parity//v1.8.0-nightly-e3fa460-20171010/x86_64-macos/rustc1.20.0
> - **Operating system**: MacOS
> - **And installed**: homebrew `--master`

---

Signing with Ledger Nano S doesn't work.

I'm trying:
```python
web3.eth.sign(web3.eth.accounts[0], 'Please take my Ether and try to build Polkadot.')
```
When I click "Confirm Request", I immediately get an error:
```
[-32000] Signing via hardware wallets is not supported.
```

I've digged into this a bit and successfully signed a message with `eth.signPersonalMessage_async` from [ledger-node-js-api](https://github.com/LedgerHQ/ledger-node-js-api#using-with-ethereum) (see example at the very bottom). Maybe it could help somehow.

**Comment by tomusdrw** [comment] 2017-10-12 07:30
The sign support has been added recently to ledeger and it was not yet implemented in Parity.
Duplicate of #6083

**Closed by tomusdrw** 2017-10-12 07:30 UTC
Labels: Z0-duplicate
