### ISSUE TITLE
1.9.4 Not showing wallet list under accounts.

### ISSUE THREAD

**Issue by Flazky** [paritytech/parity#8077] opened 2018-03-08 19:00 UTC
> I'm running:
>
> - **Which Parity version?**: 1.9.4
> - **Which operating system?**: Windows
> - **How installed?**: via installer 
> - **Are you fully synchronized?**: yes
> - **Which network are you connected to?**: ethereum
> - **Did you try to restart the node?**:yes

_Your issue description goes here below. Try to include **actual** vs. **expected behavior** and **steps to reproduce** the issue._

Opened Parity Wallet App/Accounts but does not show any of my wallets. However, I can see accounts on the status toolbar above. 

Also, Parity Apps periodically either work, or get stuck on the loading screen (white with parity logo in the middle).

**Comment by Tbaut** [comment] 2018-03-12 15:06
@Flazky it sometimes takes time for the accounts to appear on the wallet page. Did you manage to see the account once you refreshed / relaunched Parity ?
If not, could you please post a screenshot of your browser console (Ctrl + Shift + i ) > "Console tab" while you are on the Account page ?

**Comment by pohng** [comment] 2018-03-13 02:38
Same issue. 

Mac Os

![image](https://user-images.githubusercontent.com/2709202/37319504-f64007aa-2634-11e8-933f-5ae91cbcca47.png)

![image](https://user-images.githubusercontent.com/2709202/37319526-0a552bbc-2635-11e8-999a-3e32154bbe0c.png)

![image](https://user-images.githubusercontent.com/2709202/37319536-17b9d4ce-2635-11e8-8388-54540d3f340c.png)

Tried refresh, restart, reinstall. Also tried restoring from json backup. It seemed to work (complete successfully) but still no accounts/wallets show up.

**Comment by pohng** [comment] 2018-03-13 02:39
Also, left machine on with parity running full 24 hours now, no change.

**Comment by Flazky** [comment] 2018-03-13 06:12
@Tbaut Ive tried multiple fresh installs, refreshes, relaunches etc..but still not working. Ive sinced reinstalled an older ver 1.8.11 stable ver and it works now

**Comment by chevdor** [comment] 2018-03-13 16:15
The issue should be fixed in master by now since #8066 
If you wait long enough (like long....) they will appear. The problem is that your machine is kept busy by a very high CPU usage and the UI (incl. what you report) is VERY slow.

I´d recommend using another version and/or waiting until the regression is removed in the 1.9x branch. A version before 18.02 should be ok.

**Comment by AntoniosHadji** [comment] 2018-03-24 20:47
I'm seeing  the same behavior on v1.9.5.  just upgraded from 1.8.10 a few hours ago.

**Comment by AntoniosHadji** [comment] 2018-03-25 19:53
I'm seeing this message in the console:
```
Content Security Policy: The page’s settings blocked the loading of a resource at self (“script-src”). Source: ;!function(){var t=0,e=function(t,e){ret....
127.0.0.1:8180:1
Content Security Policy: The page’s settings blocked the loading of a resource at self (“script-src”). Source: ;!function(){var t=0,e=function(t,e){ret....
v1:1
```

**Comment by Tbaut** [comment] 2018-03-26 08:38
@AntoniosHadji could you please upgrade to [v1.10](https://github.com/paritytech/parity/releases/tag/v1.10.0) (notice the changes in [accessing Parity Wallet](https://wiki.parity.io/Parity-Wallet) ) and report back the errors in parity console and web console (ctrl+shift+i in Parity UI app)

**Comment by 5chdn** [comment] 2018-03-26 14:06
Should be tracked here: https://github.com/Parity-JS/dapp-wallet/issues

**Comment by AntoniosHadji** [comment] 2018-03-27 01:42
@Tbaut in v1.10 I can access the built-in Dapp and it appears to be working normally.  There are web console errors. I'm not seeing any errors in the parity logs.  
As suggested by @5chdn, I reported console errors here: https://github.com/Parity-JS/dapp-wallet/issues/6

**Comment by AntoniosHadji** [comment] 2018-03-27 10:05
This morning, my accounts are not showing again in the wallet dapp.  I suspect this has to do with the signer token being changed.

**Closed** 2018-03-27 10:44 UTC
Labels: F2-bug, M7-ui, P5-sometimesoon
