### ISSUE TITLE
Corruption: block checksum mismatch: expected 4229381128, got 93859409

### ISSUE THREAD

**Issue by cleanunicorn** [paritytech/parity#7581] opened 2018-01-16 13:15 UTC
_Before filing a new issue, please **provide the following information**._

> I'm running:
>
> - **Which Parity version?**: 1.8.6
> - **Which operating system?**: Linux
> - **How installed?**: binaries
> - **Are you fully synchronized?**: no
> - **Which network are you connected to?**: ethereum
> - **Did you try to restart the node?**: yes

Tried to sync the node a few times. I get this and crash. The db is corrupted after that. It happens at different blocks.

```
2018-01-16 00:14:13  Syncing #4889009 8277…88b5     2 blk/s  646 tx/s  17 Mgas/s   1026+ 1103 Qed  #4891144   99/100 peers   6 MiB chain 83 MiB db 281 MiB queue 200 MiB sync  RPC:  0 conn,  0 req/s,   0 µs
2018-01-16 00:14:13  Syncing #4889009 8277…88b5     0 blk/s    0 tx/s   0 Mgas/s   1026+ 1103 Qed  #4891144   99/100 peers   6 MiB chain 83 MiB db 281 MiB queue 200 MiB sync  RPC:  0 conn,  0 req/s,   0 µs

====================                                       

stack backtrace:                                           
   0:     0x55dfda76e2fc - <no info>                       

Thread 'IO Worker #3' panicked at 'DB flush failed.: "Corruption: block checksum mismatch: expected 4229381128, got 93859409  in .//chains/ethereum/db/906a34e69aec8c0d/overlayrecent/db/010146.sst offset 1727765 size 13885"', /checkout/src/libcore/result.rs:906

```

**Comment by 5chdn** [comment] 2018-01-16 14:00
Duplicate of #7334

**Closed** 2018-01-16 14:13 UTC
Labels: M4-core, Z0-duplicate
