### ISSUE TITLE
DB flush failed. IO error

### ISSUE THREAD

**Issue by iFA88** [paritytech/parity#7501] opened 2018-01-08 20:54 UTC
I run `Parity/v1.8.4-beta-c74c8c1-20171211/x86_64-linux-gnu/rustc1.22.1` with `--no-periodic-snapshot --no-warp --tracing on --pruning archive` parameters.

What I expected is that the client exits daily many times because has no more space to write the DB. After the client crash there is no more free space on the disk. When I restart the client then makes 350GB free space again. The disk size is 1 TB, DB folder size is 602 GB.
Is there any solution to prevent write more data as available or maybe deleting the old data what not needed?

I use `--pruning archive` because I need older data from storage.

Some logs:
http://fusionsolutions.io/parity_eth_2018-01-07_19-17.log
http://fusionsolutions.io/parity_eth_2018-01-08_06-26.log
http://fusionsolutions.io/parity_eth_2018-01-08_12-13.log
http://fusionsolutions.io/parity_eth_2018-01-08_13-31.log
http://fusionsolutions.io/parity_eth_2018-01-08_16-56.log

**Comment by andresilva** [comment] 2018-01-10 01:18
Please try the latest beta (https://github.com/paritytech/parity/releases/tag/v1.8.6), it includes a fix for this.

**Comment by iFA88** [comment] 2018-01-10 09:38
Alright, I started using that. The sync seems pretty slow, they imports one block in 1-3 second. Here is some log:
http://fusionsolutions.io/parity_eth_2018-01-10_08-23.log
http://fusionsolutions.io/parity_eth_2018-01-10_09-57.log

I will report after few days.

**Comment by andresilva** [comment] 2018-01-10 09:46
Yes, that's expected. Due to the changes we made, RocksDB requires a full compaction which will take some time (and degrade performance temporarily). It should go back to normal eventually (although I'm not sure whether it may be faster to just sync from scratch on a fresh db).

**Comment by iFA88** [comment] 2018-01-10 09:52
I think that is almost done, as you see in the first log file i have send SIGTERM and waited ~14 min's about that the parity and his database has closed. I have now full sync and in the rocksdb *.log / *.sst nothing happens until the next block, then a little work and stops again.

**Comment by andresilva** [comment] 2018-01-10 16:34
It will still do a lot more compactions than on a fresh database (and block other threads). Could you try temporarily increasing `--cache-size`. Maybe something like `--cache-size 2048`, depending on how much RAM you have available on your system.

**Comment by petejkim** [comment] 2018-01-11 23:55
Hmm.. one of the two nodes that I run (v1.8.6) had runaway disk usage issue today.

```
~/.local/share/io.parity.ethereum/chains/ethereum# du -hd 3 .
2.3G    ./db/906a34e69aec8c0d/snapshot
34G     ./db/906a34e69aec8c0d/overlayrecent
36G     ./db/906a34e69aec8c0d
36G     ./db
28K     ./network
```

Exact same config on another instance:

```
~/.local/share/io.parity.ethereum/chains/ethereum# du -hd 3
2.3G    ./db/906a34e69aec8c0d/snapshot
19G     ./db/906a34e69aec8c0d/overlayrecent
21G     ./db/906a34e69aec8c0d
21G     ./db
2.7M    ./network
21G     .
```

**Comment by 5chdn** [comment] 2018-01-16 10:57
Duplicate of #6280

**Closed** 2018-01-16 10:57 UTC

**Comment by iFA88** [comment] 2018-01-16 11:10
Thanks for the support.
I have do a full resync with `--cache-size 4096`. Here is my log:
http://fusionsolutions.io/parity_eth_2018-01-10_19-28.log
http://fusionsolutions.io/parity_eth_2018-01-12_01-12.log

Disk usage statistics from the beginning:
![kep](https://user-images.githubusercontent.com/18205395/34985904-efa70920-fab5-11e7-9a55-64a03ab05600.png)

Full sync takes 6 days. The 0-1block/s with 2-10 Mgas/s is terrible :(

**Comment by 5chdn** [comment] 2018-01-16 13:59
That's a nice result.
