### ISSUE TITLE
``parity account list`` and ``personal.listAccounts`` are different.

### ISSUE THREAD

**Issue by yihuang** [paritytech/parity#8394] opened 2018-04-13 08:23 UTC
_Before filing a new issue, please **provide the following information**._

> I'm running:
>
> - **Which Parity version?**: Parity/v1.10.0-beta-0a9d41e-20180320/x86_64-linux-gnu/rustc1.24.1
> - **Which operating system?**: Linux
> - **How installed?**: via installer
> - **Are you fully synchronized?**: yes
> - **Which network are you connected to?**: ethereum
> - **Did you try to restart the node?**: yes

_Your issue description goes here below. Try to include **actual** vs. **expected behavior** and **steps to reproduce** the issue._

I use ``parity account import`` to import account from geth's keystore. 
The import is successful, and ``parity account list`` shows the account. But ``web3.personal.listAccounts`` is still empty.
I'm using web3py. parity is run with ``--geth --jsonrpc-apis=all``
And when I try to sign transaction with this account, it complains "Account password is invalid or account does not exist".

**Comment by Tbaut** [comment] 2018-04-13 16:09
I just tried and could not reproduce your issue.
`parity account list` and an RPC call to `personal_listAccounts` return the same.

Beware of being connected to the same network. For instance, I imported my account to Ropsten with `parity account import /path/to/geth/keystore` --chain ropsten`, then making the RPC call while my node is also connected to Ropsten.

```
$ parity account list --chain ropsten
0x001c5233e5718ad4da89f2b54bc30fe470272a68
0x00a2084f84ce3760b7f4e97033a604ceb3ea65ea

$ curl --data '{"method":"personal_listAccounts","params":[],"id":1,"jsonrpc":"2.0"}' -H "Content-Type: application/json" -X POST localhost:8545
{"jsonrpc":"2.0","result":["0x004702bdcc3c7dbffd943136107e70b827028600","0x3d6e2725ce175d948e45deaef0e314fccf2ca8f4"],"id":1}
```

**Comment by yihuang** [comment] 2018-04-14 00:02
```
$ sudo parity account list --chain mainnet
address1
$ curl --data '{"method":"personal_listAccounts","params":[],"id":1,"jsonrpc":"2.0"}' -H "Content-Type: application/json" -X POST localhost:8357
{"jsonrpc":"2.0","result":["address2"],"id":1}
```

address1 is imported with ``parity account import``, address2 is created with personal json-rpc api.

**Comment by Tbaut** [comment] 2018-04-14 14:55
I still can't reproduce...

```
parity --chain ropsten --jsonrpc-apis personal
```

In another shell :
```
$ curl --data '{"method":"personal_listAccounts","params":[],"id":1,"jsonrpc":"2.0"}' -H "Content-Type: application/json" -X POST localhost:8545
{"jsonrpc":"2.0","result":["0x001c5233e5718ad4da89f2b54bc30fe470272a68","0x00a2084f84ce3760b7f4e97033a604ceb3ea65ea"],"id":1}

$ parity account list --chain ropsten
0x001c5233e5718ad4da89f2b54bc30fe470272a68
0x00a2084f84ce3760b7f4e97033a604ceb3ea65ea

$ curl --data '{"method":"personal_newAccount","params":["password_for_new_account"],"id":1,"jsonrpc":"2.0"}' -H "Content-Type: application/json" -X POST localhost:8545
{"jsonrpc":"2.0","result":"0xf78e8af9b43960e052cfa47a6ca8e9ffc35289aa","id":1}

$ parity account list --chain ropsten
0x001c5233e5718ad4da89f2b54bc30fe470272a68
0x00a2084f84ce3760b7f4e97033a604ceb3ea65ea
0xf78e8af9b43960e052cfa47a6ca8e9ffc35289aa

$ curl --data '{"method":"personal_listAccounts","params":[],"id":1,"jsonrpc":"2.0"}' -H "Content-Type: application/json" -X POST localhost:8545
{"jsonrpc":"2.0","result":["0x001c5233e5718ad4da89f2b54bc30fe470272a68","0x00a2084f84ce3760b7f4e97033a604ceb3ea65ea","0xf78e8af9b43960e052cfa47a6ca8e9ffc35289aa"],"id":1}
```

Please provide clear steps for me to reproduce.

**Comment by yihuang** [comment] 2018-04-25 09:10
``/usr/bin/parity --rpcport=8357 --port=30305 --jsonrpc-apis=all --cache-size=2048 --geth --mode=active --min-peers=50 --max-peers=100 --db-compaction=ssd``

This is the current full running command, run with root user. Currently there are several addresses created with rpc api, but ``sudo parity account list`` still only shows one.

The content of file ``/root/.local/share/io.parity.ethereum/keys/ethereum/address_book.json`` is ``{}``

**Comment by yihuang** [comment] 2018-04-25 15:01
```
$ sudo cat /root/.local/share/io.parity.ethereum/keys/ethereum/address_book.json
{}
$ sudo cat /root/.local/share/io.parity.ethereum/keys/ethereum/dapps_history.json
{"":{"last_accessed":1523662170}}
$ sudo ls -1 /root/.local/share/io.parity.ethereum/keys/ethereum/
address_book.json
dapps_history.json
UTC--2018-04-13T08-50-54Z--b735d61b-8209-081d-f6ec-13e9aceaee6a
UTC--2018-04-14T00-38-07Z--2933e7c8-967e-eb61-6b71-4ec56ed5fb73
UTC--2018-04-19T07-44-35Z--6d7db7b5-85c9-dd3f-0c66-2f929f3e9819
UTC--2018-04-20T07-19-32Z--508f1677-0df8-d3f5-0ba1-4f9d74acb614
UTC--2018-04-25T09-29-29Z--ee682e47-e203-fc29-eb89-1ca45e69217c
UTC--2018-04-25T13-21-53Z--c0e774a2-7079-76d5-97a2-d67520ae007d
```

**Comment by tomusdrw** [comment] 2018-04-25 15:03
@yihuang are you using a config file?

**Comment by yihuang** [comment] 2018-04-25 15:07
@tomusdrw No, below is full supervisor configuration I used to run parity. There are no other arguments.

```
[program:parity]
direcotry=/home/huangyi/parity
command=/usr/bin/parity --rpcport=8357 --port=30305 --jsonrpc-apis=all --cache-size=2048 --geth --mode=active --min-peers=50 --max-peers=100 --db-compaction=ssd
autorestart=true
stdout_logfile=/home/huangyi/parity/stdout.log
stderr_logfile=/home/huangyi/parity/stderr.log
```

**Comment by tomusdrw** [comment] 2018-04-30 06:07
@yihuang let me get this straight, are you running `parity list accounts` on the host machine, but the RPC-queries parity is inside docker container?

If so it will print completely different results.

**Comment by yihuang** [comment] 2018-05-02 01:45
@tomusdrw No, they are running in same machine, by supervisor I mean http://supervisord.org, just a process manager, not a container.

**Comment by tomusdrw** [comment] 2018-05-02 06:59
@yihuang Do you run it by the same users? You are showing us content of `/root/.local` and then supervisor config showing `/home/huangyi`. Please run a following test on the same machine with the same user:
```
# List existing accounts (should be none)
$ parity --no-config --base-path /tmp/test account list
# Run parity
$ parity --no-config --base-path /tmp/test --jsonrpc-apis personal

# In a separate terminal (but as the same user)
$ curl --data '{"method":"personal_listAccounts","params":[],"id":1,"jsonrpc":"2.0"}' -H "Content-Type: application/json" -X POST localhost:8545
{"jsonrpc":"2.0","result":[],"id":1}

$ curl --data '{"method":"personal_newAccount","params":["password_for_new_account"],"id":1,"jsonrpc":"2.0"}' -H "Content-Type: application/json" -X POST localhost:8545
{"jsonrpc":"2.0","result":"0xf78e8af9b43960e052cfa47a6ca8e9ffc35289aa","id":1}

$ parity --no-config --base-path /tmp/test  account list
0xf78e8af9b43960e052cfa47a6ca8e9ffc35289aa

$ curl --data '{"method":"personal_listAccounts","params":[],"id":1,"jsonrpc":"2.0"}' -H "Content-Type: application/json" -X POST localhost:8545
{"jsonrpc":"2.0","result":["0xf78e8af9b43960e052cfa47a6ca8e9ffc35289aa"],"id":1}

```

**Comment by folsen** [comment] 2018-05-21 09:46
Closing as a misconfiguration, please reopen if the comment above did not resolve the issue.

**Closed by folsen** 2018-05-21 09:46 UTC
Labels: M6-rpcapi, Z1-question
