### ISSUE TITLE
[Chrome Extension] Signer bar can't be moved

### ISSUE THREAD

**Issue by bjornwgnr** [paritytech/parity#4886] opened 2017-03-13 16:48 UTC
Signer bar seems to be fixed to the bottom right unlike the drag&drop solution in the parity browser.

**Comment by tomusdrw** [comment] 2017-03-14 09:17
The difficulty is that the signer bar is in an iframe, so the process will be a bit complicated:
1. On mousedown generates the event to upper frame that iframe should be expanded to entire viewport
2. Moving the sidebar is allowed now (within the iframe)
3. On mouseup generates another event to fix the position of the iframe (after the animation is done)

**Comment by ngotchac** [comment] 2017-03-15 13:07
Couldn't it be (a bit hacky) : two states for the iframe : open & close
Open should take the whole viewport. When closing, just check with JS the position and dimensions of the content and then style the iframe accordingly.

**Comment by tomusdrw** [comment] 2017-03-15 14:15
@ngotchac Could you elaborate? I'm not sure if I understand this.
What would happen if we want to re-position the signer bar (let's assume it's minimized (closed state?)) and user starts to drag it?

**Comment by ngotchac** [comment] 2017-03-15 14:35
So the idea would be : 

- The Signer Bar would emit two events : `expand` and `shrink`
These events would be emitted when the user starts dragging the Signer Bar, when the Signer opens to sign transactions, when the user wants to change the default account, etc...
- The iframe handler would respond to the `expand` event by giving the iframe full width and full height
- The iframe handler would respond to the `shrink` event by waiting for let's say 200ms for the Signer Bar to shrink to its correct width/height and move to the wanted position (while the iframe is still with full width and height). Then the iframe handler would query the position and the sizes of the iframe's content, and set the iframe position and size accordingly.

**Comment by tomusdrw** [comment] 2017-03-15 15:07
So the problem is that if iframe is expanded to full width and height you cannot click anything on the website. We currently emit those events when signer bar is being opened/closed - but they are just expanding the iframe to required size.
So my proposal is re-using the old events and also adds some new ones
1. On events: `signer_bar::open` & `signer_bar::close` set the size to "large" and "small" in cradle
2. On events `signer_bar::drag_start` & `signer_bar::position` & `signer_bar::drag_stop`: maximize iframe, remember new position of an iframe, set iframe size & position to "small".

**Comment by ngotchac** [comment] 2017-03-15 15:37
That would work but seems a bit complicated no ? Is it a big issue if the website cannot get interactions from the user when the Signer Bar is expanded ? It's more like when you open a modal, you cannot interact with the background. This would be the same, and would make this easier to implement and maintain.

**Comment by tomusdrw** [comment] 2017-03-15 21:20
Just checked and actually we have an overlay on the whole website anyway (I think date & time modals/selectors were causing some issues otherwise), so it should be enough to have those two events and another event to indicate a docked position.

**Comment by ngotchac** [comment] 2017-05-05 13:26
This is done.

**Closed by ngotchac** 2017-05-05 13:26 UTC
Labels: F3-annoyance, M7-ui
