### ISSUE TITLE
Can't broadcast transactions to queue

### ISSUE THREAD

**Issue by madnadyka** [paritytech/parity#8702] opened 2018-05-24 06:02 UTC
> I'm running:
>
> - **Which Parity version?**: 1.11.0
> - **Which operating system?**: Linux
> - **How installed?**: binaries 
> - **Are you fully synchronized?**: no 
> - **Which network are you connected to?**: ethereum 
> - **Did you try to restart the node?**: yes

I'm having problem with transactions broadcasting to the node, such message is appeared :
>There are too many transactions in the queue. Your transaction was dropped due to limit. Try increasing the fee.

If I increase the gas price it still gives this error. If I restart node I can broadcast transactions but only for a small time -  I have this error again after maybe 5 mins.

**Comment by dvdplm** [comment] 2018-05-24 07:41
The queue limit is 50 transactions. Is it possible that the transactions you are enqueueing are not getting processed properly?

Can you help us reproduce the problem please? How do you start parity and what config options are you using? Are you running a miner?

Thanks!

**Comment by madnadyka** [comment] 2018-05-24 08:46
I send to queue maximum 1-2 transaction and there are no other pending transactions in queue.
Everything was ok with the previous version and I don’t make changes in my program code. 
I send transaction throw RPC API - eth_sendRawTransaction.

Parity config:

parity --no-warp --pruning fast  --pruning-memory 1024 --db-path /mnt/parity_data_1024/ --port 30336 --jsonrpc-port 18560 --jsonrpc-interface "0.0.0.0" --jsonrpc-apis «all» --ws-port 18561 --ws-interface "0.0.0.0"  --ws-apis "all" --tracing on --no-ui --min-peers=25 --cache-size 4096 --mode active --tx-queue-size 500 --no-persistent-txqueue --tx-queue-mem-limit=0

I’m not running a miner

**Comment by Tbaut** [comment] 2018-05-24 13:47
This is a duplicate of https://github.com/paritytech/parity/issues/8679 A fix has been merged and will be introduced in the next minor version.

**Closed by Tbaut** 2018-05-24 13:47 UTC
Labels: F3-annoyance, M4-core, Z7-duplicate
