### ISSUE TITLE
Disk I/O use 100%

### ISSUE THREAD

**Issue by seriouslylost** [paritytech/parity#6020] opened 2017-07-08 12:06 UTC
Hi,

I use Parity 1.6 on a PC with Windows 10 Home.
Turning on Parity (excellent software btw) causes Disk usage to reach 100% resulting in a slow computer.
I have doublechecked this several times.

**Comment by 5chdn** [comment] 2017-07-10 03:26
You can use the `--db-path` flag to prevent Parity from filling your primaty disk by pointing the database to another location. Usually a fresh parity installation should not fill up more than 10GB. How much does your instance require?

**Comment by arkpar** [comment] 2017-07-10 11:12
Also, after the initial sync it takes a few hours to download and import the blockchain in the background. During this process time high CPU/disk usage is to be expected.

**Comment by seriouslylost** [comment] 2017-07-10 14:00
Never happens on my other computer using Windows 7.


Helge


________________________________

**Comment by seriouslylost** [comment] 2017-07-10 14:02
The problem is not the size, I have plenty hd space.

The problem is that the computer is running slow.


Helge


________________________________

**Comment by tomusdrw** [comment] 2017-07-10 14:09
How much RAM do you have? Maybe it's just the SWAP file starting to be used?

**Comment by 5chdn** [comment] 2017-07-11 10:47
Now, understanding that we are talking not about disk usage but high disk I/O I can confirm this on all of my machines running parity. Systems often become unresponsive while parity syncs and it's not CPU or RAM but super high disk I/O (using iotop to monitor).

**Comment by seriouslylost** [comment] 2017-07-20 21:05
@tomusdrw I have 8GB RAM. All the time when Parity is running disk usage is at 100%.

**Comment by Vurich** [comment] 2017-07-25 09:41
The best way to fix this on Linux is to use [`ionice`](https://linux.die.net/man/1/ionice), but the equivalent for Windows is more complicated. There's [this StackOverflow answer](https://superuser.com/questions/136021/how-to-change-i-o-priority-of-a-process-or-thread-in-win7) that has some answers, plus [this project on GitHub](https://github.com/giampaolo/psutil/) includes a shim to emulate `ionice`. I don't think this is our responsibility, although it might be nice to document it.

**Comment by 5chdn** [comment] 2017-07-25 11:02
Didn't know about `ionice(1)` yet. Just tested with

    ionice -c 3 -t parity

I could add some useful information to the FAQ.

**Comment by Vurich** [comment] 2017-07-25 11:05
I just added it to the FAQ

**Comment by 5chdn** [comment] 2017-07-25 11:10
Probably not much more we can do here. Regarding Windows: It's not clear whether process priority does affect I/O.

**Comment by Vurich** [comment] 2017-07-25 15:09
The flavour text for low process priority mentions both CPU and IO on one of the versions of Windows that I saw a screenshot of, but I don't know if that's still true. Certainly at one time it affected IO priority.

**Comment by 5chdn** [comment] 2017-07-26 10:52
Can confirm `ionice -c3` (lowest priority: "idle") does not solve this issue. just doing a full sync of ropsten and my browser and other apps keep freezing.

**Comment by 5chdn** [comment] 2017-08-26 09:52
I would like to close this as duplicate of #6280 - let's keep this in one place.

**Closed by 5chdn** 2017-08-26 09:52 UTC
Labels: F3-annoyance, F7-footprint, M4-core
