### ISSUE TITLE
"Web Applications" section has links out of order

### ISSUE THREAD

**Issue by douros** [paritytech/parity#6246] opened 2017-08-06 19:51 UTC
![parity_bug](https://user-images.githubusercontent.com/12970274/29006462-9720abe0-7aad-11e7-992b-362a374385d4.jpg)

The link targets under "Web Applications" do not match the URL displayed. The attached screenshot shows three buttons that should link to etherdelta.github.io, etheroll.com, and registrar.ens.domains. Instead of linking to those sites in that order, they instead link to (respectively): etheroll.com, etherdelta.github.io, and etheroll.com. The link appears to change depending on where I click in the box, but so far I haven't been able to get a box to link to the site that it's supposed to.

This is Parity version 1.7.0.

**Comment by tomusdrw** [comment] 2017-08-06 21:57
Duplicate of #6199

**Closed by tomusdrw** 2017-08-06 21:57 UTC
Labels: Z0-duplicate
