### ISSUE TITLE
web3.personal.newAccount() fails with 'method not found'

### ISSUE THREAD

**Issue by 5chdn** [paritytech/parity#4980] opened 2017-03-21 13:03 UTC
Running with `--jsonrpc-api "web3,eth,personal,parity_accounts"` fails to create a new account in the parity web3 console application (via UI):

![screenshot at 2017-03-21 14-01-16](https://cloud.githubusercontent.com/assets/15729797/24148407/efafda00-0e3e-11e7-9cea-42834a033f80.png)

Reproduced with 1.6.3 on kovan and homestead. However, accessing this via web3 nodejs console, works as expected.

**Comment by tomusdrw** [comment] 2017-03-21 13:06
JS console dapp uses `:8080` webserver which is not affected by `--jsonrpc-api` (only `:8545` is). You can have enable all apis using `--dapps-apis-all`

It will be addressed by #4474 for now it works as intended.

**Closed** 2017-03-21 14:17 UTC
Labels: F2-bug, M6-rpcapi

**Comment by karthik2883** [comment] 2017-08-22 06:02
start your geth with  --rpcapi "eth,net,web3,personal"
