### ISSUE TITLE
When 1.8.6 is running, other web browsing/apps can't connect online, though node syncs fine

### ISSUE THREAD

**Issue by cryptogineer** [paritytech/parity#7529] opened 2018-01-10 23:37 UTC
> I'm running:
>
> - **Which Parity version?**: 1.8.6
> - **Which operating system?**: MacOS
> - **How installed?**: via installer
> - **Are you fully synchronized?**: yes
> - **Which network are you connected to?**: ethereum
> - **Did you try to restart the node?**: yes

I just upgraded from 1.8.5 to 1.8.6. When the node is running, I cannot browse the web and other apps can't connect, though wifi is connected and the node is continuing to sync.  Once I quit parity, all other web browsing and connections work again.  This only occurred right after upgrading to 1.8.6.

**Comment by 5chdn** [comment] 2018-01-16 14:31
Duplicate of #6157

**Comment by 5chdn** [comment] 2018-01-16 14:32
> You router or your ISP can't handle high connection rate. Try running parity with `--max-pending-peers 8`

**Closed by 5chdn** 2018-01-16 14:31 UTC
