### ISSUE TITLE
Sysc disrupt

### ISSUE THREAD

**Issue by wangcheng714** [paritytech/parity#7645] opened 2018-01-21 01:48 UTC
stack backtrace:

ocalhost:~ wangcheng$ parity --db-path /Volumes/Samsung_T5/parity_data/ --mode active --db-compaction ssd --cache-size 4096 --snapshot-peers=25 --max-peers=100 --min-peers=50 --base-path /Users/wangcheng/Library/Application\ Support/io.parity.ethereum
2018-01-21 10:13:42  Starting Parity/v1.8.6-beta-2d051e4-20180109/x86_64-macos/rustc1.22.1
2018-01-21 10:13:42  Keys path /Users/wangcheng/Library/Application Support/io.parity.ethereum/keys/Foundation
2018-01-21 10:13:42  DB path /Volumes/Samsung_T5/parity_data/ethereum/db/906a34e69aec8c0d
2018-01-21 10:13:42  Path to dapps /Users/wangcheng/Library/Application Support/io.parity.ethereum/dapps
2018-01-21 10:13:42  State DB configuration: fast
2018-01-21 10:13:42  Operating mode: active
2018-01-21 10:13:42  Configured for Foundation using Ethash engine

====================

stack backtrace:

Thread 'main' panicked at 'called `Option::unwrap()` on a `None` value', src/libcore/option.rs:335

This is a bug. Please report it at:

    https://github.com/paritytech/parity/issues/new

Abort trap: 6

> I'm running:
>parity --db-path /Volumes/Samsung_T5/parity_data/ --db-compaction ssd --cache-size 4096 --jsonrpc-hosts all --jsonrpc-interface all --snapshot-peers=25 --max-peers=100 --min-peers=50
> - **Which Parity version?**: 1.8.6
> - **Which operating system?**:  MacOS 
> - **How installed?**: via  homebrew 
> - **Are you fully synchronized?**: no
> - **Which network are you connected to?**: ethereum 
> - **Did you try to restart the node?**: yes

_Your issue description goes here below.

Actual is  : 

ocalhost:~ wangcheng$ parity --db-path /Volumes/Samsung_T5/parity_data/ --mode active --db-compaction ssd --cache-size 4096 --snapshot-peers=25 --max-peers=100 --min-peers=50 --base-path /Users/wangcheng/Library/Application\ Support/io.parity.ethereum
2018-01-21 10:13:42  Starting Parity/v1.8.6-beta-2d051e4-20180109/x86_64-macos/rustc1.22.1
2018-01-21 10:13:42  Keys path /Users/wangcheng/Library/Application Support/io.parity.ethereum/keys/Foundation
2018-01-21 10:13:42  DB path /Volumes/Samsung_T5/parity_data/ethereum/db/906a34e69aec8c0d
2018-01-21 10:13:42  Path to dapps /Users/wangcheng/Library/Application Support/io.parity.ethereum/dapps
2018-01-21 10:13:42  State DB configuration: fast
2018-01-21 10:13:42  Operating mode: active
2018-01-21 10:13:42  Configured for Foundation using Ethash engine

====================

stack backtrace:

Thread 'main' panicked at 'called `Option::unwrap()` on a `None` value', src/libcore/option.rs:335

This is a bug. Please report it at:

    https://github.com/paritytech/parity/issues/new

Abort trap: 6

expected is  : 

sync the database . 

i also have to try other way : 

try to restart the sync program , nothing work .

try to add --base-path , nothing work

**Comment by 5chdn** [comment] 2018-01-22 11:04
Duplicate of #7340

**Closed by 5chdn** 2018-01-22 11:04 UTC
