### ISSUE TITLE
Corrupt DB while restarting a sync

### ISSUE THREAD

**Issue by DWAK-ATTK** [paritytech/parity#7898] opened 2018-02-14 19:52 UTC
_Before filing a new issue, please **provide the following information**._

> I'm running:
>
> - **Which Parity version?**: 0.0.0

Parity
  version Parity/v1.9.2-beta-0feb0bb-20180201/x86_64-linux-gnu/rustc1.23.0
Copyright 2015, 2016, 2017, 2018 Parity Technologies (UK) Ltd
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>.
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.

By Wood/Paronyan/Kotewicz/Drwięga/Volf
   Habermeier/Czaban/Greeff/Gotchac/Redmann

> - **Which operating system?**: Windows / MacOS / Linux

Ubuntu 16.04 LTS

> - **How installed?**: via installer / homebrew / binaries / from source

the curl command from the web site (apt-get)

> - **Are you fully synchronized?**: no / yes

no, I'm trying to sync.

> - **Which network are you connected to?**: ethereum / ropsten / kovan / ...

ethereum / FOUNDATION

> - **Did you try to restart the node?**: no / yes

not yet

_Your issue description goes here below. Try to include **actual** vs. **expected behavior** and **steps to reproduce** the issue._

2018-02-14 10:46:11  Syncing #2429409 c5f8…a04b     4 blk/s   17 tx/s   0 Mgas/s   1410+    1 Qed  #2430821    2/25 peers   3 MiB chain 192 MiB db 5 MiB queue 1 MiB sync  RPC:  1 conn,  6 req/s,  69 µs
2018-02-14 10:46:11  DB corrupted: Corruption: block checksum mismatch: expected 953194794, got 865771633  in /home/parallels/.local/share/io.parity.ethereum/chains/ethereum/db/906a34e69aec8c0d/overlayrecent/db/172448.sst offset 14641052 size 9936. Repair will be triggered on next restart

====================

stack backtrace:
   0:     0x560baf245efc - <no info>

Thread 'Verifier #1' panicked at 'DB flush failed.: Error(Msg("Corruption: block checksum mismatch: expected 953194794, got 865771633  in /home/parallels/.local/share/io.parity.ethereum/chains/ethereum/db/906a34e69aec8c0d/overlayrecent/db/172448.sst offset 14641052 size 9936"), State { next_error: None, backtrace: None })', /checkout/src/libcore/result.rs:906

This is a bug. Please report it at:

    https://github.com/paritytech/parity/issues/new

Aborted (core dumped)

*restart parity*

2018-02-14 10:53:37  DB corrupted: Invalid argument: You have to open all column families. Column families not opened: col5, col4, col6, col1, col3, col0, col2, attempting repair
Client service error: Client(Database(Error(Msg("Received null column family handle from DB."), State { next_error: None, backtrace: None })))

*Same error on next restart.*

**Comment by Aggour** [comment] 2018-02-16 13:20
Had the same issue, had to clear the blockchain files and start sync from scratch.
Can you please tell us how did you restart the node? If it wasn't restarted properly this is more likely to happen.

**Comment by DWAK-ATTK** [comment] 2018-02-16 23:07
I restarted the node by pressing CTRL-C and waiting for the command prompt to appear.

**Comment by dunnomattic** [comment] 2018-02-17 01:07
I am in the same boat, I've hit this bug about 6 times today on a fresh install of 1.9.2-beta, ubuntu server 16.04.3 -- I get to thought the snapshots, then this happens after an indeterminate number of block syncs: 

2018-02-16 19:41:40  Syncing #4888403 c0a0…11c8     2 blk/s  554 tx/s  19 Mgas/s      0+  865 Qed  #4889270   48/50 peers   6 MiB chain 122 MiB db 179 MiB queue 103 MiB sync  RPC:  0 conn,  0 req/s,   0 µs
2018-02-16 19:41:50  Syncing #4888432 10b5…d857     2 blk/s  676 tx/s  20 Mgas/s      0+  837 Qed  #4889270   48/50 peers   6 MiB chain 125 MiB db 173 MiB queue 103 MiB sync  RPC:  0 conn,  0 req/s,   0 µs
2018-02-16 19:42:00  Syncing #4888459 7260…b731     2 blk/s  582 tx/s  21 Mgas/s      0+  809 Qed  #4889270   47/50 peers   6 MiB chain 127 MiB db 168 MiB queue 103 MiB sync  RPC:  0 conn,  0 req/s,   0 µs
2018-02-16 19:42:10  Syncing #4888480 2f95…6e7f     2 blk/s  477 tx/s  15 Mgas/s      0+  789 Qed  #4889270   48/50 peers   6 MiB chain 132 MiB db 164 MiB queue 103 MiB sync  RPC:  0 conn,  0 req/s,   0 µs
2018-02-16 19:42:20  DB corrupted: Corruption: block checksum mismatch: expected 2411514650, got 3817568159  in /home/matt/.local/share/io.parity.ethereum/chains/ethereum/db/906a34e69aec8c0d/overlayrecent/db/010
922.sst offset 5496680 size 13237. Repair will be triggered on next restart

====================

stack backtrace:
   0:     0x55f784bc4efc - <no info>

Thread 'IO Worker #2' panicked at 'DB flush failed.: Error(Msg("Corruption: block checksum mismatch: expected 2411514650, got 3817568159  in /home/matt/.local/share/io.parity.ethereum/chains/ethereum/db/906a34e6
9aec8c0d/overlayrecent/db/010922.sst offset 5496680 size 13237"), State { next_error: None, backtrace: None })', /checkout/src/libcore/result.rs:906

This is a bug. Please report it at:

    https://github.com/paritytech/parity/issues/new

Aborted (core dumped)

**Comment by 5chdn** [comment] 2018-02-19 11:33
Duplicate of #7766

**Closed by 5chdn** 2018-02-19 11:33 UTC
Labels: M4-core, Z0-question

**Comment by dinganc** [comment] 2019-11-06 19:29
I had this same issue for days. I fixed the issue by removing 1 stick of my ram. Now my laptop has only 1 stick of 8GB DDR3 installed, and Parity syncs without an issue. Wish this helps!
