### ISSUE TITLE
musicoin unable to sync

### ISSUE THREAD

**Issue by ktmine** [paritytech/parity#8279] opened 2018-03-30 21:55 UTC
> I'm running:
>
> - **Which Parity version?**: 1.10.0-20180320 beta
> - **Which operating system?**: Linux
> - **How installed?**: via installer 
> - **Are you fully synchronized?**: no
> - **Which network are you connected to?**: musicoin
> - **Did you try to restart the node?**: yes

I would like to sync to the musicoin network.  I used to run a node for mining on the network, and have not turned it on for a while.  Recently I attempted to restart it to mine again.  I updated my copy of parity to 1.10 and started it up.  It would get 1-2 peers for a few seconds and then go to 0 peers.  I shut parity down and deleted my nodes.json file and restarted. same thing happened.  After letting it run for a few hours and not getting anymore than 1-2 peers and then they would be none.  I then did db kill.  I started it back up and let it begin to re-install the block chain. I got an average of 20 or so peers now.  I then let it run overnight to get synced up.  when I logged back on I found that it had no peers again and was stuck at block 2,222,221 now as best block.  Will not sync to more than 2,222,221 and no peers.

Does anyone have any advice/instruction for me to go from here. I'm at the end of my knowledge about this.

Edit:
I created a brand new virtual box with a new install of ubuntu to try it clean. I installed a new copy of parity 1.10.0.... beta.  I started parity on the musicoin chain and it warped synced. I got a few peers but it stopped syncing at block 2,222,221 again.  
here are some of the logs.
Syncing #2222221 254f…eefe 0 blk/s 0 tx/s 0 Mgas/s 8994+ 0 Qed #2246937 6/25 peers 7 MiB chain 67 MiB db 17 MiB queue 7 MiB sync RPC: 1 conn, 1 req/s, 170 µs
[2018-03-31 22:47:11]
 Syncing #2222221 254f…eefe 0 blk/s 0 tx/s 0 Mgas/s 10508+ 0 Qed #2246937 7/25 peers 6 MiB chain 67 MiB db 19 MiB queue 7 MiB sync RPC: 1 conn, 1 req/s, 154 µs
[2018-03-31 22:47:01]
 Syncing #2222221 254f…eefe 0 blk/s 0 tx/s 0 Mgas/s 12513+ 0 Qed #2246936 6/25 peers 5 MiB chain 67 MiB db 23 MiB queue 7 MiB sync RPC: 1 conn, 1 req/s, 154 µs
[2018-03-31 22:46:51]
 Syncing #2222221 254f…eefe 0 blk/s 0 tx/s 0 Mgas/s 14864+ 0 Qed #2246930 6/25 peers 6 MiB chain 67 MiB db 27 MiB queue 7 MiB sync RPC: 1 conn, 0 req/s, 154 µs
[2018-03-31 22:46:41]
 Syncing #2222221 254f…eefe 0 blk/s 0 tx/s 0 Mgas/s 13876+ 0 Qed #2243557 6/25 peers 6 MiB chain 67 MiB db 26 MiB queue 7 MiB sync RPC: 1 conn, 0 req/s, 154 µs
[2018-03-31 22:46:31]
 Syncing #2222221 254f…eefe 0 blk/s 0 tx/s 0 Mgas/s 7454+ 0 Qed #2235177 6/25 peers 6 MiB chain 67 MiB db 14 MiB queue 6 MiB sync RPC: 1 conn, 0 req/s, 133 µs
[2018-03-31 22:46:26]
 Syncing #2222221 254f…eefe 0 blk/s 0 tx/s 0 Mgas/s 4671+ 0 Qed #2231241 6/25 peers 5 MiB chain 67 MiB db 9 MiB queue 6 MiB sync RPC: 1 conn, 0 req/s, 135 µs
[2018-03-31 22:46:16]
 Syncing #2222221 254f…eefe 0 blk/s 0 tx/s 0 Mgas/s 1360+ 0 Qed #2225650 5/25 peers 4 MiB chain 67 MiB db 3 MiB queue 5 MiB sync RPC: 1 conn, 12 req/s, 150 µs
[2018-03-31 22:46:06]
 #154305 6/25 peers 5 MiB chain 67 MiB db 0 bytes queue 5 MiB sync RPC: 1 conn, 12 req/s, 150 µs
[2018-03-31 22:45:31]
 #130811 5/25 peers 7 MiB chain 67 MiB db 0 bytes queue 5 MiB sync RPC: 1 conn, 10 req/s, 166 µs
[2018-03-31 22:45:01]
 #110363 3/25 peers 6 MiB chain 67 MiB db 0 bytes queue 2 MiB sync RPC: 1 conn, 9 req/s, 172 µs
[2018-03-31 22:44:26]
 #86868 3/25 peers 5 MiB chain 67 MiB db 0 bytes queue 7 MiB sync RPC: 1 conn, 9 req/s, 151 µs
[2018-03-31 22:43:56]
 #65812 3/25 peers 7 MiB chain 67 MiB db 0 bytes queue 6 MiB sync RPC: 1 conn, 7 req/s, 151 µs
[2018-03-31 22:43:26]
 #42294 3/25 peers 5 MiB chain 67 MiB db 0 bytes queue 6 MiB sync RPC: 1 conn, 6 req/s, 240 µs
[2018-03-31 22:42:56]
 #26417 3/25 peers 6 MiB chain 67 MiB db 0 bytes queue 5 MiB sync RPC: 1 conn, 5 req/s, 143 µs
[2018-03-31 22:42:26]
 Syncing #2222221 254f…eefe 0 blk/s 0 tx/s 0 Mgas/s 567+ 0 Qed #2247897 3/25 peers 5 MiB chain 67 MiB db 3 MiB queue 3 MiB sync RPC: 1 conn, 4 req/s, 154 µs
[2018-03-31 22:42:16]
 Syncing #2222221 254f…eefe 0 blk/s 0 tx/s 0 Mgas/s 2537+ 0 Qed #2247897 2/25 peers 7 MiB chain 67 MiB db 14 MiB queue 3 MiB sync RPC: 1 conn, 3 req/s, 154 µs
[2018-03-31 22:42:06]
 Syncing #2222221 254f…eefe 0 blk/s 0 tx/s 0 Mgas/s 4597+ 0 Qed #2247897 2/25 peers 7 MiB chain 67 MiB db 28 MiB queue 3 MiB sync RPC: 1 conn, 3 req/s, 154 µs
[2018-03-31 22:42:01]
 Syncing #2222221 254f…eefe 0 blk/s 0 tx/s 0 Mgas/s 5671+ 0 Qed #2247897 2/25 peers 6 MiB chain 67 MiB db 34 MiB queue 3 MiB sync RPC: 1 conn, 3 req/s, 154 µs
[2018-03-31 22:41:51]
 Syncing #2222221 254f…eefe 0 blk/s 0 tx/s 0 Mgas/s 6696+ 0 Qed #2246829 2/25 peers 5 MiB chain 67 MiB db 40 MiB queue 3 MiB sync RPC: 1 conn, 2 req/s, 293 µs
[2018-03-31 22:41:41]
 Syncing #2222221 254f…eefe 0 blk/s 0 tx/s 0 Mgas/s 6656+ 0 Qed #2244638 2/25 peers 5 MiB chain 67 MiB db 40 MiB queue 3 MiB sync RPC: 1 conn, 2 req/s, 293 µs
[2018-03-31 22:41:31]
 Syncing #2222221 254f…eefe 0 blk/s 0 tx/s 0 Mgas/s 6508+ 0 Qed #2242225 2/25 peers 5 MiB chain 67 MiB db 40 MiB queue 3 MiB sync RPC: 1 conn, 2 req/s, 177 µs
[2018-03-31 22:41:21]
 Syncing #2222221 254f…eefe 0 blk/s 0 tx/s 0 Mgas/s 6463+ 0 Qed #2239812 2/25 peers 5 MiB chain 67 MiB db 39 MiB queue 3 MiB sync RPC: 1 conn, 1 req/s, 195 µs
[2018-03-31 22:41:11]
 Syncing #2222221 254f…eefe 0 blk/s 0 tx/s 0 Mgas/s 6441+ 0 Qed #2237496 2/25 peers 5 MiB chain 67 MiB db 40 MiB queue 3 MiB sync RPC: 1 conn, 1 req/s, 177 µs
[2018-03-31 22:41:01]

**Comment by r0ck3r** [comment] 2018-04-02 08:00
Have this bug too! Stopped to sync at block 2,254,594.
Need help.
Parity 1.9.5, previous was 1.9.2

**Comment by 5chdn** [comment] 2018-04-03 11:38
Duplicate of #8246

**Closed by 5chdn** 2018-04-03 11:38 UTC
