### ISSUE TITLE
Thread 'main' panicked at 'Unexpected rlp error: RlpExpectedToBeData', /checkout/src/libcore/result.rs:860

### ISSUE THREAD

**Issue by philip-bl** [paritytech/parity#7202] opened 2017-12-05 04:30 UTC
_Before filing a new issue, please **provide the following information**._

> I'm running:
>
> - **Which Parity version?**: 0.0.0
Parity version Parity/v1.9.0-unstable-e85c98e09-20171204/x86_64-linux-gnu/rustc1.20.0
> - **Which operating system?**: Windows / MacOS / Linux
Linux, Debian Stretch
> - **How installed?**: from this github, `cargo build --release`
> - **Are you fully synchronized?**: no

_Your issue description goes here below. Try to include **actual** vs. **expected behavior** and **steps to reproduce** the issue._

What I did:

```
$ cargo clean && cargo clean --release
$ git pull
$ cargo build --jobs 9 --release
$ cd target/release
$ ./parity
```

What I got when trying to run parity:
```
2017-12-05 07:03:51  Starting Parity/v1.9.0-unstable-e85c98e09-20171204/x86_64-linux-gnu/rustc1.20.0
2017-12-05 07:03:51  Keys path /home/shibbiry/.local/share/io.parity.ethereum/keys/Foundation
2017-12-05 07:03:51  DB path /home/shibbiry/.local/share/io.parity.ethereum/chains/ethereum/db/906a34e69aec8c0d
2017-12-05 07:03:51  Path to dapps /home/shibbiry/.local/share/io.parity.ethereum/dapps
2017-12-05 07:03:51  State DB configuration: fast
2017-12-05 07:03:51  Operating mode: active
2017-12-05 07:03:51  Configured for Foundation using Ethash engine
2017-12-05 07:03:51  Updated conversion rate to Ξ1 = US$464.94 (256049400 wei/gas)

====================

stack backtrace:
   0:     0x557e7c221e7c - backtrace::backtrace::trace::h3d7946faa2473996
   1:     0x557e7c221ebb - backtrace::capture::Backtrace::new::hbeb31b9a68424764
   2:     0x557e7b813f28 - panic_hook::panic_hook::ha4d516298410acae
   3:     0x557e7c3d3876 - std::panicking::rust_panic_with_hook
                        at /checkout/src/libstd/panicking.rs:612
   4:     0x557e7c3d3704 - std::panicking::begin_panic_new<alloc::string::String>
                        at /checkout/src/libstd/panicking.rs:553
   5:     0x557e7c3d3609 - std::panicking::begin_panic_fmt
                        at /checkout/src/libstd/panicking.rs:521
   6:     0x557e7c3d359a - std::panicking::rust_begin_panic
                        at /checkout/src/libstd/panicking.rs:497
   7:     0x557e7c401a80 - core::panicking::panic_fmt
                        at /checkout/src/libcore/panicking.rs:92
   8:     0x557e7bb7f826 - core::result::unwrap_failed::hbab804723bd3d338
   9:     0x557e7bc759b7 - <KVDB as ethcore::db::Readable>::read::h18609d7f0cee6b0c
  10:     0x557e7bdbd6a3 - ethcore::blockchain::blockchain::BlockChain::epoch_transition::hee48a5b3fddd30f5
  11:     0x557e7bc41a80 - ethcore::client::client::Client::new::h8bab635b61026e17
  12:     0x557e7bceb3cb - ethcore::service::ClientService::start::h4543979e56ed0580
  13:     0x557e7b691998 - parity::run::execute::h930697fcd2ed512a
  14:     0x557e7b6aa013 - parity::execute::hff4cc0562c9fb8f1
  15:     0x557e7b6b00b7 - parity::main_direct::h389389e89deacdf3
  16:     0x557e7b6b4423 - parity::main::h7c6f7f4e09e08f2f
  17:     0x557e7c3da37b - panic_abort::__rust_maybe_catch_panic
                        at /checkout/src/libpanic_abort/lib.rs:40

Thread 'main' panicked at 'Unexpected rlp error: RlpExpectedToBeData', /checkout/src/libcore/result.rs:860

This is a bug. Please report it at:

    https://github.com/paritytech/parity/issues/new

Aborted
```

**Comment by 5chdn** [comment] 2017-12-06 14:14
Duplicate of #7188

**Closed by 5chdn** 2017-12-06 14:14 UTC
