### ISSUE TITLE
panicked at 'State root of best block header always valid.: InvalidStateRoot

### ISSUE THREAD

**Issue by gpuri** [paritytech/parity#7652] opened 2018-01-21 16:25 UTC
I'm running:

 - **Which Parity version?**: 1.10.0
 - **Which operating system?**: Windows
 - **How installed?**: via installer
 - **Are you fully synchronized?**: no 
 - **Which network are you connected to?**: ropsten 
 - **Did you try to restart the node?**: yes 

_Your issue description goes here below. Try to include **actual** vs. **expected behavior** and **steps to reproduce** the issue._

While synchronizing I am getting the following error 

====================

stack backtrace:
   0:     0x7ff668177cca - hid_error
   1:     0x7ff668178163 - hid_error
   2:     0x7ff66782be06 - <no info>
   3:     0x7ff66819f073 - hid_error
   4:     0x7ff66819eef1 - hid_error
   5:     0x7ff66819edd2 - hid_error
   6:     0x7ff66819ed45 - hid_error
   7:     0x7ff6681a7bff - hid_error
   8:     0x7ff667b355e9 - <no info>
   9:     0x7ff667bbf4c0 - <no info>
  10:     0x7ff667bbea27 - <no info>
  11:     0x7ff667bcef30 - <no info>
  12:     0x7ff667500275 - <no info>
  13:     0x7ff667524584 - <no info>
  14:     0x7ff6674573ea - <no info>
  15:     0x7ff66771808a - <no info>
  16:     0x7ff667678d50 - <no info>
  17:     0x7ff6675742a6 - <no info>
  18:     0x7ff6681a0492 - hid_error
  19:     0x7ff66752711b - <no info>
  20:     0x7ff667fd4088 - hid_error
  21:     0x7ff667e59bb6 - <no info>
  22:     0x7ff6681a0492 - hid_error
  23:     0x7ff667e5b9b1 - <no info>
  24:     0x7ff66819cfec - hid_error
  25:     0x7fffecd01fe4 - BaseThreadInitThunk

Thread '<unnamed>' panicked at 'State root of best block header always valid.: InvalidStateRoot(7b8c16988f8fd3c41d5539aa945f60bb3cb7437a3bd3e0836303a4d5788d827d)', src\libcore\result.rs:906

**Comment by 5chdn** [comment] 2018-01-22 10:41
Duplicate of #7447

**Closed by 5chdn** 2018-01-22 10:41 UTC
