### ISSUE TITLE
Syncing via light client stucks

### ISSUE THREAD

**Issue by loebelch** [paritytech/parity#6242] opened 2017-08-06 08:55 UTC
There seems to be an issue with light client (parity --light):
When syncing mainnet the syncing stucks at a block. Then also after hours the same block will be synced again and again:

```
2017-08-06 08:50:38 UTC Syncing #1110246 b6fb…3246     0 hdr/s      0+    0 Qed  #1110246    5/50 peers   816 KiB cache 0 bytes queue  RPC:  0 conn,  0 req/s,   0 µs
2017-08-06 08:50:43 UTC Syncing #1110246 b6fb…3246     0 hdr/s      0+    0 Qed  #1110246    5/50 peers   816 KiB cache 0 bytes queue  RPC:  0 conn,  0 req/s,   0 µs
2017-08-06 08:50:48 UTC Syncing #1110246 b6fb…3246     0 hdr/s      0+    0 Qed  #1110246    5/50 peers   816 KiB cache 0 bytes queue  RPC:  0 conn,  0 req/s,   0 µs
2017-08-06 08:50:53 UTC Syncing #1110246 b6fb…3246     0 hdr/s      0+    0 Qed  #1110246    5/50 peers   816 KiB cache 0 bytes queue  RPC:  0 conn,  0 req/s,   0 µs

```

Current version:
Parity/v1.7.0-beta-5f2cabd-20170727/arm-linux-gnu/rustc1.18.0
(based on this release: http://parity-downloads-mirror.parity.io/v1.7.0/armv7-unknown-linux-gnueabihf/parity_1.7.0_armhf.deb)

**Comment by 5chdn** [comment] 2017-08-22 13:35
Duplicate of #6319

**Closed by 5chdn** 2017-08-22 13:35 UTC
Labels: F2-bug, M4-core
