### ISSUE TITLE
UI: first auto-compilation of contract fails in Contracts/Develop mode

### ISSUE THREAD

**Issue by svyatonik** [paritytech/parity#7278] opened 2017-12-13 13:24 UTC
By @jacogr request - logging the issue here.

> I'm running:
>
> - **Which Parity version?**: master @ 053c009cdb149f274b6158433b731e4f063121ff
> - **Which operating system?**: Linux
> - **How installed?**: from source (`cargo build` without any features)
> - **Are you fully synchronized?**: yes
> - **Did you try to restart the node?**: yes

Steps to reproduce:
1) open UI/Parity Wallet/Contracts/Develop
2) previously developed Solidity contract is auto-loaded
3) since auto-compilation is on by default, it starts compiling

Actual behavior:
text in compilation results window is changing from "Loading Solidity 0.4.19"
..to "Compiling..."
..and finally to "An error occurred with the following description
Error: Maximum call stack size exceeded"

Expected behavior:
compilation completes without an error

Workaround:
simply click "Compile" button again && compilation completes successfully. So it is not a big issue.

**Comment by debris** [comment] 2017-12-29 12:56
duplicate of #6082

**Closed by debris** 2017-12-29 12:56 UTC
Labels: F3-annoyance, M7-ui, P5-sometimesoon
