### ISSUE TITLE
stack backtrace: Ubuntu 17.04 

### ISSUE THREAD

**Issue by nickhill** [paritytech/parity#7493] opened 2018-01-08 08:03 UTC
_Before filing a new issue, please **provide the following information**._

> I'm running:
>
> - **Which Parity version?**: 0.0.0
> - **Which operating system?**: Windows / MacOS / Linux
> - **How installed?**: via installer / homebrew / binaries / from source
> - **Are you fully synchronized?**: no / yes
> - **Did you try to restart the node?**: no / yes

_Your issue description goes here below. Try to include **actual** vs. **expected behavior** and **steps to reproduce** the issue._
<user>@machine:~/src/ethereum/parity/parity$ target/release/parity 
2018-01-07 22:54:41  Starting Parity/v1.9.0-unstable-c37a87e49-20180105/x86_64-linux-gnu/rustc1.23.0
2018-01-07 22:54:41  Keys path /home/<user>/.local/share/io.parity.ethereum/keys/Foundation
2018-01-07 22:54:41  DB path /home/<user>/.local/share/io.parity.ethereum/chains/ethereum/db/906a34e69aec8c0d
2018-01-07 22:54:41  Path to dapps /home/<user>/.local/share/io.parity.ethereum/dapps
2018-01-07 22:54:41  State DB configuration: fast
2018-01-07 22:54:41  Operating mode: active
2018-01-07 22:54:41  Configured for Foundation using Ethash engine
2018-01-07 22:54:41  Updated conversion rate to Ξ1 = US$1214.10 (98054216 wei/gas)

====================

stack backtrace:
   0:     0x561dbf20dc8c - backtrace::backtrace::trace::h88dff4dc401d81d6
   1:     0x561dbf20dcc2 - backtrace::capture::Backtrace::new::hc1bdbce336b16eca
   2:     0x561dbe6a0f89 - panic_hook::panic_hook::ha4f6f84d07d9cbbd

Thread 'main' panicked at 'Unexpected rlp error: RlpExpectedToBeData', /checkout/src/libcore/result.rs:906

This is a bug. Please report it at:

    https://github.com/paritytech/parity/issues/new

====================

restarts have identical results but for stack addresses:

<user>@machine:~/src/ethereum/parity/parity$ target/release/parity 
2018-01-07 23:28:14  Starting Parity/v1.9.0-unstable-c37a87e49-20180105/x86_64-linux-gnu/rustc1.23.0
2018-01-07 23:28:14  Keys path /home/<user>/.local/share/io.parity.ethereum/keys/Foundation
2018-01-07 23:28:14  DB path /home/<user>/.local/share/io.parity.ethereum/chains/ethereum/db/906a34e69aec8c0d
2018-01-07 23:28:14  Path to dapps /home/<user>/.local/share/io.parity.ethereum/dapps
2018-01-07 23:28:14  State DB configuration: fast
2018-01-07 23:28:14  Operating mode: active
2018-01-07 23:28:14  Configured for Foundation using Ethash engine
2018-01-07 23:28:14  Updated conversion rate to Ξ1 = US$1213.48 (98104300 wei/gas)

====================

stack backtrace:
   0:     0x558b71d3bc8c - backtrace::backtrace::trace::h88dff4dc401d81d6
   1:     0x558b71d3bcc2 - backtrace::capture::Backtrace::new::hc1bdbce336b16eca
   2:     0x558b711cef89 - panic_hook::panic_hook::ha4f6f84d07d9cbbd

Thread 'main' panicked at 'Unexpected rlp error: RlpExpectedToBeData', /checkout/src/libcore/result.rs:906

This is a bug. Please report it at:

    https://github.com/paritytech/parity/issues/new

Aborted

====================  CONFIGURATIONS ====================  

> lsb_release -a
LSB Version:	core-9.20160110ubuntu5-amd64:core-9.20160110ubuntu5-noarch:security-9.20160110ubuntu5-amd64:security-9.20160110ubuntu5-noarch
Distributor ID:	Ubuntu
Description:	Ubuntu 17.04
Release:	17.04
Codename:	zesty

====================

installation via git, likley > 1 year ago

> git status
On branch master
Your branch is up-to-date with 'origin/master'.
nothing to commit, working tree clean

====================

<user>@machine:~/src/ethereum/parity/parity$ rustup -V
rustup 1.9.0 (57fc3c087 2018-01-04)

<user>@machine:~/src/ethereum/parity/parity$ rustc -V
rustc 1.23.0 (766bd11c8 2018-01-01)

====================

I am NOT synchronized, likely 3-4 months behind. 

====================  NOTES ====================  

My system lacked this directory:
/home/<user>/.local/share/io.parity.ethereum/keys/Foundation

creating it made no difference. 

====================  SUBOPTIMAL SOLUTION ====================  

Removal of  /home/<user>/.local/share/io.parity.ethereum
and restarting resulted in apparent success, peers were found and parity began
pulling in the chain. 

Thereafter, replacing the newly created /home/<user>/.local/share/io.parity.ethereum
directory with the pre-existing one again resulted in the rlp error.
So the issue seems to be caused by something therein, something about
older builds.

**Comment by lght** [comment] 2018-01-12 19:27
Am I understanding correctly that the panic happened using the latest build from master on a data directory (`.local/share/io.parity.ethereum`) that was created from another git build from >1 year ago?

Can you provide a tar file of the manifest files and a few of the sst file from your old database directory `.local/share/io.parity.ethereum/chains/ethereum/db`?

**Comment by nickhill** [comment] 2018-01-13 05:35
**_Am I understanding correctly that the panic happened using the latest build from master on a data directory (.local/share/io.parity.ethereum) that was created from another git build from >1 year ago?_**
 
Yes, correct.

**_Can you provide a tar file of the manifest files and a few of the sst file from your old database directory .local/share/io.parity.ethereum/chains/ethereum/db?_**

Yes, but the upload limit here is 10MB, even via `xz` the file size is too great to include even the second .sst. Also, the github selector does not accept `.xz` files, so I `mv issue-7493_db-sample.tar.{xz,zip}` . Please advise as to another method and I will provide all 150 .sst files if need be.   Compression was performed as you indicated, `tar --xz -cf issue-7493_db-sample.tar.xz CURRENT MANIFEST-204941 OPTIONS* 000860.sst`
[issue-7493_db-sample.tar.zip](https://github.com/paritytech/parity/files/1628095/issue-7493_db-sample.tar.zip)


**_Could you also please provide your old data directory structure?_**
Yes, included
[issue-7493_data_directory_structure.txt](https://github.com/paritytech/parity/files/1628094/issue-7493_data_directory_structure.txt)

**Comment by nickhill** [comment] 2018-01-15 06:32
Also - identical behavior for classic chain, similarly out of sync

**Comment by nickhill** [comment] 2018-01-15 07:53
starting from scratch, to an SSD, full sync was achieved with today's build `Parity/v1.10.0-unstable-24a40af5b-20180115/x86_64-linux-gnu/rustc1.23.0`   in 1hour, 13 minutes. Very nice

**Comment by 5chdn** [comment] 2018-01-16 10:21
Duplicate of #7188

**Closed by 5chdn** 2018-01-16 10:21 UTC

**Comment by lght** [comment] 2018-01-17 00:57
@nickhill thank you for the database sample, and directory structure. Since this issue has been marked as a duplicate, please follow progress of #7188 if still interested.

**Comment by nickhill** [comment] 2018-01-17 01:13
understood, thank you
