### ISSUE TITLE
Parity 1.8.8 creates .parity directory

### ISSUE THREAD

**Issue by stone212** [paritytech/parity#7800] opened 2018-02-03 05:25 UTC
> - **Which Parity version?**: 1.8.8
> - **Which operating system?**: Ubuntu 16.04
> - **How installed?**: via binary (amd64)
> - **Are you fully synchronized?**: yes
> - **Which network are you connected to?**: private blockchain
> - **Did you try to restart the node?**: yes

When invoking 1.8.8 on a system with an existing .local/share/io.parity.ethereum directory, Parity ignores this directory and creates a new .parity directory with a new network key.  A symlink is an effective workaround like so:

`$~ ln -s .local/share/io.parity.ethereum .parity`

This is similar to and may be a duplicate of my Issue at https://github.com/paritytech/parity/issues/7575.  I post this separately because I can confirm it also affects 1.8.8-stable.

**Comment by 5chdn** [comment] 2018-02-05 11:33
Thanks for confirming!

**Comment by 5chdn** [comment] 2018-02-05 11:33
Duplicate of #7575

**Closed by 5chdn** 2018-02-05 11:33 UTC
Labels: M4-core, Z0-duplicate
