### ISSUE TITLE
This bug just cost someone 500 ETH

### ISSUE THREAD

**Issue by adam-szabo** [paritytech/parity#5691] opened 2017-05-24 22:41 UTC
Quote from [Reddit](https://www.reddit.com/r/ethereum/comments/6cixvy/psa_if_your_account_shows_address/):

> This applies primarily to users of Parity. The account with this address corresponds to the key you get if you use Parity's recovery phrase option in the Parity wallet without specifying any recovery phrase (i.e. just leaving the field blank). No warnings are given in the current version of Parity (though I believe they plan to change this) and it will just look like you have created a normal account. However everyone who does this will always get the same key, meaning that someone else can (and will!) take your funds as soon as you deposit them.

Look at [Etherscan](https://etherscan.io/address/0x00a329c0648769A73afAc7F9381E08FB43dBEA72), somebody just lost 500 ETH because of this. 36 seconds after the transfer, it was picked up (probably by a script) and forwarded.

Edit: it looks like it did cost 4000 ETH for someone else earlier!

**Comment by emansipater** [comment] 2017-05-26 03:33
I would strongly recommend that a check be put in as soon as possible to notify users who already have this wallet loaded of the dangers, not just blocking new creations of it.  It almost looks like the number of deposits are actually increasing over time despite the new version blocking creation.

**Comment by 5chdn** [comment] 2017-05-26 14:35
This was already fixed in 1.6.7 https://github.com/paritytech/parity/releases/tag/v1.6.7

See also https://blog.parity.io/restoring-blank-seed-phrase/

**Closed by 5chdn** 2017-05-26 14:35 UTC
Labels: Z0-duplicate

**Comment by 5chdn** [comment] 2017-05-26 14:44
Duplicate of #5495
