### ISSUE TITLE
Clean start up of parity can not restore from snapshot and trying to sync from block 0?

### ISSUE THREAD

**Issue by ulion** [paritytech/parity#7030] opened 2017-11-12 23:50 UTC
_Before filing a new issue, please **provide the following information**._

> I'm running:
>
> - **Parity version**: 1.8.2
> - **Operating system**: Linux
> - **And installed**: via the bash command line

my disk was full, so I tried to restart parity from clean state, I deleted the .local/share folder, then re-run parity, to make it re-sync, but, it trying to sync from block 0 after download (some) snapshot??

here is the key log lines related:

2017-11-12 23:22:24 UTC Syncing snapshot 188/404        #0   25/25 peers   8 KiB chain 3 MiB db 0 bytes queue 10 KiB sync  RPC:  0 conn,  0 req/s,   0 µs
2017-11-12 23:22:29 UTC Syncing snapshot 190/404        #0   25/25 peers   8 KiB chain 3 MiB db 0 bytes queue 10 KiB sync  RPC:  0 conn,  0 req/s,   0 µs
2017-11-12 23:22:44 UTC Syncing       #0 d4e5…8fa3     0 blk/s    0 tx/s   0 Mgas/s    637+    0 Qed      #638   23/25 peers   8 KiB chain 3 MiB db 1 MiB queue 6 MiB sync  RPC:  0 conn,  0 req/s,   0 µs
2017-11-12 23:22:49 UTC Syncing     #190 d707…a3d6    38 blk/s    0 tx/s   0 Mgas/s   7429+    0 Qed     #7620   23/25 peers   185 KiB chain 4 MiB db 13 MiB queue 7 MiB sync  RPC:  0 conn,  0 req/s,   0 µs

so did I miss something or did something wrong? I tried twice, it still does like this.

---

**Comment by ulion** [comment] 2017-11-13 07:17
just now the other attempt finally got the snapshot correctly, not sure whether previously it failed in the half.

**Comment by 5chdn** [comment] 2017-11-13 10:49
Duplicate of #6372 - I hope we can see this fixed in 1.9.0

**Closed by 5chdn** 2017-11-13 10:49 UTC

**Comment by ulion** [comment] 2017-11-14 03:21
although it can startup now, but the sync cost much more disk space (more than 34G at least) and time. so is this expected too?
