### ISSUE TITLE
Parity mainnet sync stuck.

### ISSUE THREAD

**Issue by miningpoolhub** [paritytech/parity#6593] opened 2017-09-26 00:23 UTC
I'm running Parity/v1.7.0-unstable-5f2cabd-20170727/x86_64-linux-gnu/rustc1.19.0
Ubuntu
installed from source.

I run several parity instances and one of them stuck

```
2017-09-26 00:10:35 UTC Syncing #4234806 46dbâ€¦5806     0 blk/s    0 tx/s   0 Mgas/s      0+    0 Qed  #4233783    2/25 peers      2 MiB chain   65 MiB db  0 bytes queue   10 KiB sync  RPC:  0 conn,  0 req/s,   0 Âµs
2017-09-26 00:10:50 UTC Syncing #4234806 46dbâ€¦5806     0 blk/s    0 tx/s   0 Mgas/s      0+    0 Qed  #4233783    4/25 peers      6 MiB chain   65 MiB db  0 bytes queue   11 KiB sync  RPC:  0 conn,  0 req/s,   0 Âµs
2017-09-26 00:11:05 UTC Syncing #4234806 46dbâ€¦5806     0 blk/s    0 tx/s   0 Mgas/s      0+    0 Qed  #4233783    7/25 peers     96 KiB chain   65 MiB db  0 bytes queue   11 KiB sync  RPC:  0 conn,  0 req/s,   0 Âµs
2017-09-26 00:11:15 UTC Syncing #4234806 46dbâ€¦5806     0 blk/s    0 tx/s   0 Mgas/s      0+    0 Qed  #4233783   11/25 peers    143 KiB chain   65 MiB db  0 bytes queue   11 KiB sync  RPC:  0 conn,  0 req/s,   0 Âµs
2017-09-26 00:11:20 UTC Syncing #4234806 46dbâ€¦5806     0 blk/s    0 tx/s   0 Mgas/s      0+    0 Qed  #4233783   12/25 peers    377 KiB chain   65 MiB db  0 bytes queue   11 KiB sync  RPC:  0 conn,  0 req/s,   0 Âµs
2017-09-26 00:11:35 UTC Syncing #4234806 46dbâ€¦5806     0 blk/s    0 tx/s   0 Mgas/s      0+    0 Qed  #4233783   13/25 peers    269 KiB chain   65 MiB db  0 bytes queue   11 KiB sync  RPC:  0 conn,  0 req/s,   0 Âµs
2017-09-26 00:11:45 UTC Syncing #4234806 46dbâ€¦5806     0 blk/s    0 tx/s   0 Mgas/s      0+    0 Qed  #4233783   15/25 peers    898 KiB chain   65 MiB db  0 bytes queue   11 KiB sync  RPC:  0 conn,  0 req/s,   0 Âµs
2017-09-26 00:11:55 UTC Syncing #4234806 46dbâ€¦5806     0 blk/s    0 tx/s   0 Mgas/s      0+    0 Qed  #4233783   15/25 peers      2 MiB chain   65 MiB db  0 bytes queue   11 KiB sync  RPC:  0 conn,  0 req/s,   0 Âµs
2017-09-26 00:12:00 UTC Syncing #4234806 46dbâ€¦5806     0 blk/s    0 tx/s   0 Mgas/s      0+    0 Qed  #4233783   15/25 peers    772 KiB chain   65 MiB db  0 bytes queue   11 KiB sync  RPC:  0 conn,  0 req/s,   0 Âµs
2017-09-26 00:12:30 UTC   16/25 peers      4 MiB chain   65 MiB db  0 bytes queue   11 KiB sync  RPC:  0 conn,  0 req/s,   0 Âµs
2017-09-26 00:12:40 UTC Syncing #4234806 46dbâ€¦5806     0 blk/s    0 tx/s   0 Mgas/s      0+    0 Qed  #4233783   18/25 peers      1 MiB chain   65 MiB db  0 bytes queue   11 KiB sync  RPC:  0 conn,  0 req/s,   0 Âµs
2017-09-26 00:12:45 UTC Syncing #4234806 46dbâ€¦5806     0 blk/s    0 tx/s   0 Mgas/s      0+    0 Qed  #4233783   19/25 peers    499 KiB chain   65 MiB db  0 bytes queue   11 KiB sync  RPC:  0 conn,  0 req/s,   0 Âµs
2017-09-26 00:12:55 UTC Syncing #4234806 46dbâ€¦5806     0 blk/s    0 tx/s   0 Mgas/s      0+    0 Qed  #4233783   20/25 peers      4 MiB chain   65 MiB db  0 bytes queue   11 KiB sync  RPC:  0 conn,  0 req/s,   0 Âµs
2017-09-26 00:13:00 UTC Syncing #4234806 46dbâ€¦5806     0 blk/s    0 tx/s   0 Mgas/s      0+    0 Qed  #4233783   21/25 peers      1 MiB chain   65 MiB db  0 bytes queue   11 KiB sync  RPC:  0 conn,  0 req/s,   0 Âµs
2017-09-26 00:13:10 UTC Syncing #4234806 46dbâ€¦5806     0 blk/s    0 tx/s   0 Mgas/s      0+    0 Qed  #4233783   22/25 peers      3 MiB chain   65 MiB db  0 bytes queue   11 KiB sync  RPC:  0 conn,  0 req/s,   0 Âµs
2017-09-26 00:13:25 UTC Syncing #4234806 46dbâ€¦5806     0 blk/s    0 tx/s   0 Mgas/s      0+    0 Qed  #4233783   19/25 peers      2 MiB chain   65 MiB db  0 bytes queue   11 KiB sync  RPC:  0 conn,  0 req/s,   0 Âµs
2017-09-26 00:13:35 UTC Syncing #4234806 46dbâ€¦5806     0 blk/s    0 tx/s   0 Mgas/s      0+    0 Qed  #4233783   22/25 peers      2 MiB chain   65 MiB db  0 bytes queue   11 KiB sync  RPC:  0 conn,  0 req/s,   0 Âµs
2017-09-26 00:13:45 UTC Syncing #4234806 46dbâ€¦5806     0 blk/s    0 tx/s   0 Mgas/s      0+    0 Qed  #4233783   22/25 peers      2 MiB chain   65 MiB db  0 bytes queue   11 KiB sync  RPC:  0 conn,  0 req/s,   0 Âµs
2017-09-26 00:14:00 UTC Syncing #4234806 46dbâ€¦5806     0 blk/s    0 tx/s   0 Mgas/s      0+    0 Qed  #4233783   21/25 peers      2 MiB chain   65 MiB db  0 bytes queue   11 KiB sync  RPC:  0 conn,  0 req/s,   0 Âµs
2017-09-26 00:14:10 UTC Syncing #4234806 46dbâ€¦5806     0 blk/s    0 tx/s   0 Mgas/s      0+    0 Qed  #4233783   22/25 peers      3 MiB chain   65 MiB db  0 bytes queue   11 KiB sync  RPC:  0 conn,  0 req/s,   0 Âµs
2017-09-26 00:14:20 UTC Syncing #4234806 46dbâ€¦5806     0 blk/s    0 tx/s   0 Mgas/s      0+    0 Qed  #4233783   24/25 peers      3 MiB chain   65 MiB db  0 bytes queue   11 KiB sync  RPC:  0 conn,  0 req/s,   0 Âµs
2017-09-26 00:14:25 UTC Syncing #4234806 46dbâ€¦5806     0 blk/s    0 tx/s   0 Mgas/s      0+    0 Qed  #4233783   23/25 peers      3 MiB chain   65 MiB db  0 bytes queue   11 KiB sync  RPC:  0 conn,  0 req/s,   0 Âµs
2017-09-26 00:14:35 UTC Syncing #4234806 46dbâ€¦5806     0 blk/s    0 tx/s   0 Mgas/s      0+    0 Qed  #4233783   24/25 peers    993 KiB chain   65 MiB db  0 bytes queue   11 KiB sync  RPC:  0 conn,  0 req/s,   0 Âµs
2017-09-26 00:14:50 UTC Syncing #4234806 46dbâ€¦5806     0 blk/s    0 tx/s   0 Mgas/s      0+    0 Qed  #4233783   21/25 peers    867 KiB chain   65 MiB db  0 bytes queue   11 KiB sync  RPC:  0 conn,  0 req/s,   0 Âµs
2017-09-26 00:15:00 UTC Syncing #4234806 46dbâ€¦5806     0 blk/s    0 tx/s   0 Mgas/s      0+    0 Qed  #4233783   23/25 peers    509 KiB chain   65 MiB db  0 bytes queue   11 KiB sync  RPC:  0 conn,  0 req/s,   0 Âµs
2017-09-26 00:15:10 UTC Syncing #4234806 46dbâ€¦5806     0 blk/s    0 tx/s   0 Mgas/s      0+    0 Qed  #4233783   21/25 peers    792 KiB chain   65 MiB db  0 bytes queue   11 KiB sync  RPC:  0 conn,  0 req/s,   0 Âµs
2017-09-26 00:15:20 UTC Syncing #4234806 46dbâ€¦5806     0 blk/s    0 tx/s   0 Mgas/s      0+    0 Qed  #4233783   22/25 peers    312 KiB chain   65 MiB db  0 bytes queue   11 KiB sync  RPC:  0 conn,  0 req/s,   0 Âµs'
```

It doesn't move forward even I restart.

**Comment by 5chdn** [comment] 2017-09-26 07:33
The interesting part is missing from the log. What happens before that? Right after you start? How is your client configured? Is this Foundation or Classic?

**Comment by hrishikeshio** [comment] 2017-09-26 07:50
Mine is stuck too. Its running default configuration on foundation chain.

**Comment by 5chdn** [comment] 2017-09-26 08:17
Are you on HDD or SSD?

**Comment by arkpar** [comment] 2017-09-26 08:27
@hrishikeshio could you try running with `-l sync=trace` and posting the log?

**Comment by hrishikeshio** [comment] 2017-09-26 08:39
@5chdn  Using SDD. Its stuck since 2+ hours. I restarted parity multiple times to make it work. I didn't provide whole log since it was repetitive.
@arkpar https://pastebin.com/MMFCx0mY

**Comment by miningpoolhub** [comment] 2017-09-28 06:14
Here's log from my stuck parity.

https://pastebin.com/XYkAsWrH
https://pastebin.com/MFgTKKZY
https://pastebin.com/qJDuECBN

I divided them due to pastebin's size limit.
This instance uses SSD.

**Comment by ctzjc** [comment] 2017-10-03 17:14
And they go silent....I have SAME issue

**Comment by arkpar** [comment] 2017-10-04 09:38
@miningpoolhub would it be possible for you to upload contents of `/home/xxxxx/.parity_stuck20170926/chains/ethereum/db/906a34e69aec8c0d` somewhere?

**Comment by arkpar** [comment] 2017-10-04 10:22
@miningpoolhub Also, If you have any older logs (around block 4234295) that would be helpful.

**Comment by miningpoolhub** [comment] 2017-10-04 14:07
It's about 20GB. Any suggestion for file transferring big files?
I don't have old logs currently. It's already truncated when I restarted parity.

**Comment by lexibrent** [comment] 2018-04-16 04:43
I am experiencing the same problem as the other people posting here. It syncs fine for about a day or so, then gets stuck until I restart Parity. I will collect logs for you.

**Comment by folsen** [comment] 2018-05-19 08:59
Closing as unreproducible, please re-open if you have sync trace logs available to be able to debug.

**Closed by folsen** 2018-05-19 08:59 UTC
Labels: F2-bug, M4-core, P2-asap

**Comment by zeroecco** [comment] 2018-12-28 17:22
hello! still having this issue. here is the debug log I have
```
Dec 28 17:18:04 parity-001 parity[2903]: 2018-12-28 17:18:04 UTC IO Worker #1 DEBUG sync  89 -> Dispatching packet: 2
Dec 28 17:18:04 parity-001 parity[2903]: 2018-12-28 17:18:04 UTC IO Worker #0 DEBUG sync  89 -> Dispatching packet: 2
Dec 28 17:18:04 parity-001 parity[2903]: 2018-12-28 17:18:04 UTC IO Worker #3 DEBUG sync  73 -> Dispatching packet: 2
Dec 28 17:18:04 parity-001 parity[2903]: 2018-12-28 17:18:04 UTC IO Worker #2 DEBUG sync  10 -> Dispatching packet: 2
Dec 28 17:18:04 parity-001 parity[2903]: 2018-12-28 17:18:04 UTC IO Worker #1 DEBUG sync  89 -> Dispatching packet: 2
Dec 28 17:18:04 parity-001 parity[2903]: 2018-12-28 17:18:04 UTC IO Worker #0 DEBUG sync  89 -> Dispatching packet: 2
Dec 28 17:18:04 parity-001 parity[2903]: 2018-12-28 17:18:04 UTC IO Worker #3 DEBUG sync  73 -> Dispatching packet: 2
Dec 28 17:18:04 parity-001 parity[2903]: 2018-12-28 17:18:04 UTC IO Worker #2 DEBUG sync  10 -> Dispatching packet: 2
Dec 28 17:18:04 parity-001 parity[2903]: 2018-12-28 17:18:04 UTC IO Worker #1 DEBUG sync  89 -> Dispatching packet: 2
Dec 28 17:18:04 parity-001 parity[2903]: 2018-12-28 17:18:04 UTC IO Worker #0 DEBUG sync  89 -> Dispatching packet: 2
Dec 28 17:18:04 parity-001 parity[2903]: 2018-12-28 17:18:04 UTC IO Worker #3 DEBUG sync  73 -> Dispatching packet: 2
Dec 28 17:18:04 parity-001 parity[2903]: 2018-12-28 17:18:04 UTC IO Worker #2 DEBUG sync  10 -> Dispatching packet: 2
Dec 28 17:18:04 parity-001 parity[2903]: 2018-12-28 17:18:04 UTC IO Worker #1 DEBUG sync  89 -> Dispatching packet: 2
Dec 28 17:18:04 parity-001 parity[2903]: 2018-12-28 17:18:04 UTC IO Worker #0 DEBUG sync  89 -> Dispatching packet: 2
Dec 28 17:18:04 parity-001 parity[2903]: 2018-12-28 17:18:04 UTC IO Worker #3 DEBUG sync  73 -> Dispatching packet: 2
Dec 28 17:18:04 parity-001 parity[2903]: 2018-12-28 17:18:04 UTC IO Worker #2 INFO import  Syncing #1512251 0xfc4a…12ab     0.00 blk/s    0.0 tx/s    0 Mgas/s      0+    0 Qed  #1512251   38/256 peers      7 MiB chain    4 GiB db  0 bytes queue  214 MiB sync  RPC:  0 conn,    0 req/s,    0 µs
```

**Comment by zeroecco** [comment] 2018-12-28 17:30
@joshua-mir no problem. I cleared the logs and have done as asked. I am just waiting for the condition to re-present itself now

**Comment by zeroecco** [comment] 2018-12-28 17:55
included a gist of the debug output. I filtered out `'Dispatching packet: 2'` as it made the debug too long to gist.
the gist:
https://gist.github.com/zeroecco/cd4d4ef224ffe386318cb32b579b74cb

**Comment by joshua-mir** [comment] 2018-12-28 18:00
Your sync isn't stuck anymore, I see the blocknumber increasing reliably in that gist.

**Comment by zeroecco** [comment] 2018-12-28 18:01
line 4286 is where it stops syncing

**Comment by joshua-mir** [comment] 2018-12-28 18:13
Ah I see. Could you please make a new issue regarding this with that gist attached? It's going to be quite helpful in debugging this.

For the short term this appears to be an issue in the way parity interacts with that specific peer. I don't know what a workaround would be other than to make sure you don't connect to it by using a host rule on your OS, or collecting some of the good peers manually and adding them to your reserved-peers, and then enabling reserved-only.

**Comment by zeroecco** [comment] 2018-12-28 18:18
sure thing: https://github.com/paritytech/parity-ethereum/issues/10116

Okie Dokie I will try to find a good parity peer list and use that
