### ISSUE TITLE
ETH/ETC sync stuck.

### ISSUE THREAD

**Issue by miningpoolhub** [paritytech/parity#7114] opened 2017-11-22 00:23 UTC
_Before filing a new issue, please **provide the following information**._

> I'm running:
> - **Which Parity version?**: Parity/v1.7.6-unstable-1953533-20171013/x86_64-linux-gnu/rustc1.19.0
> - **Which operating system?**: Ubuntu
> - **How installed?**: from source
> - **Are you fully synchronized?**: yes
> - **Did you try to restart the node?**: no

_Your issue description goes here below. Try to include **actual** vs. **expected behavior** and **steps to reproduce** the issue._

Ethereum classic chain sync stopped at some block.

Here's the log from stuck node.

```
2017-11-21 03:43:18 UTC   14/25 peers      2 MiB chain   66 MiB db  0 bytes queue   31 KiB sync  RPC:  0 conn,  2 req/s, 153 Âµs
2017-11-21 03:43:19 UTC Imported #4875133 4e7câ€¦109a (51 txs, 1.25 Mgas, 39.11 ms, 6.99 KiB)
2017-11-21 03:43:26 UTC Imported #4875134 e4b0â€¦713e (4 txs, 0.08 Mgas, 3.30 ms, 0.95 KiB)
2017-11-21 03:43:27 UTC Snapshot: 2514026 accounts 0 blocks 102586416 bytes
2017-11-21 03:43:37 UTC Snapshot: 2568275 accounts 0 blocks 106312615 bytes
2017-11-21 03:43:47 UTC Snapshot: 2664810 accounts 0 blocks 109747988 bytes
2017-11-21 03:43:48 UTC   14/25 peers      4 MiB chain   66 MiB db  0 bytes queue   31 KiB sync  RPC:  0 conn,  4 req/s, 144 Âµs
2017-11-21 03:43:52 UTC Reorg to #4875135 480câ€¦325e (e4b0â€¦713e #4875133 4e7câ€¦109a 4b25â€¦d1a5)
2017-11-21 03:43:52 UTC Imported #4875135 480câ€¦325e (0 txs, 0.00 Mgas, 2.60 ms, 1.03 KiB) + another 1 block(s) containing 4 tx(s)
2017-11-21 03:43:57 UTC Snapshot: 2853992 accounts 0 blocks 116626099 bytes
2017-11-21 03:44:07 UTC Snapshot: 2951279 accounts 0 blocks 120074091 bytes
2017-11-21 03:44:14 UTC Imported #4875136 9b59â€¦967c (1 txs, 0.04 Mgas, 4.60 ms, 0.70 KiB)
2017-11-21 03:44:17 UTC Snapshot: 3141617 accounts 0 blocks 126940964 bytes
2017-11-21 03:44:18 UTC   14/25 peers      4 MiB chain   66 MiB db  0 bytes queue   31 KiB sync  RPC:  0 conn,  7 req/s, 146 Âµs
2017-11-21 03:44:27 UTC Snapshot: 3216415 accounts 0 blocks 130514404 bytes
2017-11-21 03:44:34 UTC Stage 2 block verification failed for 6009â€¦1eaa: Block(MismatchedH256SealElement(Mismatch { expected: 45e6d65d1c6704b68c68751e91b8bb7de43dfe83f54f2512dfa71ebd104bf6ef, found: 1791d41f367d6891437cf37a741b752221ab49e5bac97a7469ef6fb8ea853dce }))
2017-11-21 03:44:37 UTC Snapshot: 3406635 accounts 0 blocks 137433604 bytes
2017-11-21 03:44:47 UTC Snapshot: 3592864 accounts 0 blocks 144300194 bytes
2017-11-21 03:44:53 UTC   10/25 peers      5 MiB chain   66 MiB db  0 bytes queue   19 KiB sync  RPC:  0 conn,  2 req/s, 107 Âµs
2017-11-21 03:44:57 UTC Snapshot: 3680624 accounts 0 blocks 147728839 bytes
2017-11-21 03:45:07 UTC Snapshot: 3867547 accounts 0 blocks 154617621 bytes
2017-11-21 03:45:17 UTC Snapshot: 3962015 accounts 0 blocks 158081275 bytes
2017-11-21 03:45:23 UTC   10/25 peers      6 MiB chain   66 MiB db  0 bytes queue   19 KiB sync  RPC:  0 conn,  2 req/s, 155 Âµs
2017-11-21 03:45:27 UTC Snapshot: 4049376 accounts 0 blocks 165270758 bytes
2017-11-21 03:45:37 UTC Snapshot: 4128798 accounts 0 blocks 168754736 bytes
2017-11-21 03:45:47 UTC Snapshot: 4225374 accounts 0 blocks 172204877 bytes
2017-11-21 03:45:57 UTC Snapshot: 4386265 accounts 0 blocks 179376245 bytes
2017-11-21 03:45:58 UTC    9/25 peers      5 MiB chain   66 MiB db  0 bytes queue   21 KiB sync  RPC:  0 conn,  3 req/s, 139 Âµs
2017-11-21 03:46:07 UTC Snapshot: 4562431 accounts 0 blocks 186324237 bytes
2017-11-21 03:46:17 UTC Snapshot: 4658203 accounts 0 blocks 189764617 bytes
2017-11-21 03:46:27 UTC Snapshot: 4811590 accounts 0 blocks 196950912 bytes
2017-11-21 03:46:33 UTC    5/25 peers      6 MiB chain   66 MiB db  0 bytes queue   21 KiB sync  RPC:  0 conn,  2 req/s, 155 Âµs
2017-11-21 03:46:37 UTC Snapshot: 4903470 accounts 0 blocks 200418497 bytes
2017-11-21 03:46:47 UTC Snapshot: 5019626 accounts 0 blocks 211017076 bytes
2017-11-21 03:46:57 UTC Snapshot: 5113205 accounts 0 blocks 214501796 bytes
2017-11-21 03:47:03 UTC    7/25 peers      6 MiB chain   66 MiB db  0 bytes queue   21 KiB sync  RPC:  0 conn,  2 req/s, 141 Âµs
2017-11-21 03:47:07 UTC Snapshot: 5306601 accounts 0 blocks 221391599 bytes
2017-11-21 03:47:17 UTC Snapshot: 5403929 accounts 0 blocks 224839623 bytes
2017-11-21 03:47:27 UTC Snapshot: 5584819 accounts 0 blocks 231835195 bytes
2017-11-21 03:47:33 UTC    7/25 peers      6 MiB chain   66 MiB db  0 bytes queue   19 KiB sync  RPC:  0 conn,  2 req/s, 141 Âµs
2017-11-21 03:47:37 UTC Snapshot: 5682571 accounts 0 blocks 235298814 bytes

````

There's other instance that ran correctly from other server.

```
2017-11-21 03:44:07 UTC Snapshot: 9949156 accounts 0 blocks 391165860 bytes
2017-11-21 03:44:13 UTC Imported #4875136 9b59â€¦967c (1 txs, 0.04 Mgas, 10.84 ms, 0.70 KiB)
2017-11-21 03:44:17 UTC Snapshot: 10139833 accounts 0 blocks 398108823 bytes
2017-11-21 03:44:27 UTC Snapshot: 10269026 accounts 0 blocks 405164452 bytes
2017-11-21 03:44:34 UTC Imported #4875137 6009â€¦1eaa (14 txs, 0.35 Mgas, 7.23 ms, 2.06 KiB)
2017-11-21 03:44:34 UTC   32/50 peers      6 MiB chain   67 MiB db  0 bytes queue   31 KiB sync  RPC:  0 conn,  2 req/s, 112 Âµs
2017-11-21 03:44:37 UTC Snapshot: 10443321 accounts 0 blocks 412231086 bytes
2017-11-21 03:44:41 UTC Imported #4875138 f78eâ€¦7aab (16 txs, 0.47 Mgas, 12.83 ms, 2.48 KiB)
2017-11-21 03:44:47 UTC Snapshot: 10636111 accounts 0 blocks 419154129 bytes
2017-11-21 03:44:57 UTC Snapshot: 10917113 accounts 0 blocks 429589384 bytes
2017-11-21 03:44:59 UTC Stage 1 block verification failed for 8dd2â€¦35bd: Ethkey(InvalidSignature)
2017-11-21 03:45:07 UTC Snapshot: 11014222 accounts 0 blocks 433045672 bytes
2017-11-21 03:45:07 UTC Imported #4875139 4cbbâ€¦7216 (7 txs, 0.22 Mgas, 17.46 ms, 1.57 KiB)
2017-11-21 03:45:09 UTC   27/50 peers      3 MiB chain   67 MiB db  0 bytes queue   31 KiB sync  RPC:  0 conn,  2 req/s, 112 Âµs
2017-11-21 03:45:17 UTC Snapshot: 11304859 accounts 0 blocks 443412810 bytes
2017-11-21 03:45:27 UTC Snapshot: 11498081 accounts 0 blocks 450347096 bytes
2017-11-21 03:45:29 UTC Imported #4875140 eab4â€¦98fe (6 txs, 0.15 Mgas, 4.46 ms, 1.70 KiB)
2017-11-21 03:45:37 UTC Snapshot: 11693070 accounts 0 blocks 457266238 bytes
2017-11-21 03:45:39 UTC   28/50 peers      4 MiB chain   67 MiB db  0 bytes queue   31 KiB sync  RPC:  0 conn,  2 req/s, 145 Âµs
2017-11-21 03:45:41 UTC Stage 1 block verification failed for 425dâ€¦9e0b: Ethkey(InvalidSignature)
2017-11-21 03:45:43 UTC Imported #4875141 7513â€¦c1d9 (15 txs, 0.44 Mgas, 9.77 ms, 2.71 KiB)
2017-11-21 03:45:47 UTC Snapshot: 11878286 accounts 0 blocks 464223993 bytes
2017-11-21 03:45:57 UTC Snapshot: 12069489 accounts 0 blocks 471148973 bytes

````

The problem is that ethereum chain also had same issue on this same machine.
I couldn't get the log from due to parity restart but same thing will happen if there's some attacker.
Nodes are working fine when I restart them. Reorg to longest chain automatically.

**Comment by 5chdn** [comment] 2017-11-22 10:13
Need some ETC consensus experts in here. friendly pinging @sorpaas @whilei @sjmackenzie @splix 

@miningpoolhub you changed the title to "ETH", does this also affect the _foundation_ chain?

**Comment by miningpoolhub** [comment] 2017-11-22 10:36
@5chdn Yeah. Same thing happened on ETH chain too.

**Comment by 5chdn** [comment] 2017-11-22 10:42
Can you please update to 1.7.9 or 1.8.3 and also share the ETH logs with us? Thanks!

**Comment by whilei** [comment] 2017-11-22 15:35
I have seen very similar behavior on geth, and have also very recently been working on it (https://github.com/ethereumproject/go-ethereum/issues/346). I'm not yet totally sure that it's the _same_ issue, but looks damn close. 

My hypothesis so far is geth imports block _h1_ as latest head block, but _h1_ will turn out to be an uncle. Then _h2_ won't get imported because _h2_'s parent hash won't match _h1_'s hash. And instead of handling a best-block uncle/head reorg in a timely way, it just goes on discarding block announcements until the peer is dropped.

I will follow up with some logs.

**Comment by miningpoolhub** [comment] 2017-11-24 13:44
@5chdn 
The correct chain was ran by v1.7.8 version and forked chain was ran by v1.7.6
I forgot restarting the parity on second machine.

I am a bit confused still because I don't understand why ETC chain forked too.
ETC was running on same parity version v1.7.6.

**Comment by miningpoolhub** [comment] 2017-11-26 09:25
v1.7.8 parity forked/stuck again.



```
2017-11-25 21:50:07 UTC   50/50 peers      6 MiB chain  348 MiB db  0 bytes queue   32 KiB sync  RPC:  0 conn,  5 req/s, 115 Âµs
2017-11-25 21:50:16 UTC Imported #4621763 f849â€¦054b (2 txs, 0.04 Mgas, 14.45 ms, 0.75 KiB)
2017-11-25 21:50:42 UTC   50/50 peers      6 MiB chain  348 MiB db  0 bytes queue   32 KiB sync  RPC:  0 conn,  3 req/s, 130 Âµs
2017-11-25 21:50:46 UTC Imported #4621764 c9ddâ€¦92d0 (172 txs, 6.69 Mgas, 87.08 ms, 30.86 KiB)
2017-11-25 21:50:52 UTC Imported #4621765 d3ffâ€¦1c7a (4 txs, 0.41 Mgas, 8.82 ms, 2.20 KiB)
2017-11-25 21:51:04 UTC Imported #4621766 a7c6â€¦a64f (120 txs, 6.69 Mgas, 82.70 ms, 23.13 KiB)
2017-11-25 21:51:07 UTC Imported #4621767 030câ€¦7d47 (135 txs, 6.70 Mgas, 149.86 ms, 33.82 KiB) + another 1 block(s) containing 119 tx(s)
2017-11-25 21:51:17 UTC   50/50 peers      6 MiB chain  349 MiB db  0 bytes queue   32 KiB sync  RPC:  0 conn,  4 req/s, 142 Âµs
2017-11-25 21:51:34 UTC Imported #4621768 2d07â€¦b48b (38 txs, 6.63 Mgas, 40.23 ms, 7.16 KiB)
2017-11-25 21:51:34 UTC Stage 2 block verification failed for 021aâ€¦ba6f: Block(MismatchedH256SealElement(Mismatch { expected: 704f42a7d5f6460c37adc415499e715cab64fd69daaca3c4fd2b78a92800681a, found: f43663728378ce22d89fca7e98e4188dec4a95bf7a4ff7f7374b03283bcb70d0 }))
2017-11-25 21:51:52 UTC   50/50 peers      6 MiB chain  349 MiB db  0 bytes queue   32 KiB sync  RPC:  0 conn,  2 req/s, 125 Âµs
2017-11-25 21:52:27 UTC   50/50 peers      6 MiB chain  349 MiB db  0 bytes queue   32 KiB sync  RPC:  0 conn,  4 req/s, 133 Âµs
2017-11-25 21:53:02 UTC   50/50 peers      6 MiB chain  350 MiB db  0 bytes queue   32 KiB sync  RPC:  0 conn,  2 req/s, 144 Âµs
2017-11-25 21:53:37 UTC   50/50 peers      6 MiB chain  350 MiB db  0 bytes queue   32 KiB sync  RPC:  0 conn,  4 req/s, 121 Âµs
2017-11-25 21:54:12 UTC   50/50 peers      6 MiB chain  350 MiB db  0 bytes queue   32 KiB sync  RPC:  0 conn,  1 req/s, 124 Âµs
2017-11-25 21:54:22 UTC Imported #4621769 ed1câ€¦658d (141 txs, 6.68 Mgas, 56.05 ms, 21.45 KiB)
2017-11-25 21:54:22 UTC Submitted block imported OK. #4621769: ed1cfb2772901a8603bf94c60e9534ee761bb626430529f89c93e3fcf00d658d
2017-11-25 21:54:47 UTC   50/50 peers      3 MiB chain  350 MiB db  0 bytes queue   32 KiB sync  RPC:  0 conn,  4 req/s, 141 Âµs
2017-11-25 21:55:10 UTC Reorg to #4621785 6d8aâ€¦85b0 (a7f2â€¦a445 #4621783 9704â€¦f329 539câ€¦32da)
2017-11-25 21:55:22 UTC   50/50 peers      3 MiB chain  350 MiB db  0 bytes queue   32 KiB sync  RPC:  0 conn,  5 req/s, 115 Âµs
2017-11-25 21:55:57 UTC   50/50 peers      3 MiB chain  350 MiB db  0 bytes queue   32 KiB sync  RPC:  0 conn,  5 req/s, 113 Âµs
2017-11-25 21:56:32 UTC   50/50 peers      3 MiB chain  351 MiB db  0 bytes queue   32 KiB sync  RPC:  0 conn,  4 req/s, 129 Âµs
2017-11-25 21:57:07 UTC   50/50 peers      3 MiB chain  351 MiB db  0 bytes queue   32 KiB sync  RPC:  0 conn,  5 req/s, 125 Âµs
2017-11-25 21:57:42 UTC   50/50 peers      3 MiB chain  351 MiB db  0 bytes queue   32 KiB sync  RPC:  0 conn,  4 req/s, 123 Âµs
2017-11-25 21:58:17 UTC   50/50 peers      5 MiB chain  351 MiB db  0 bytes queue   32 KiB sync  RPC:  0 conn,  4 req/s, 111 Âµs
2017-11-25 21:58:52 UTC   50/50 peers      5 MiB chain  352 MiB db  0 bytes queue   32 KiB sync  RPC:  0 conn,  4 req/s, 121 Âµs
2017-11-25 21:59:27 UTC   50/50 peers      5 MiB chain  352 MiB db  0 bytes queue   32 KiB sync  RPC:  0 conn,  4 req/s, 117 Âµs
2017-11-25 22:00:02 UTC   50/50 peers      5 MiB chain  353 MiB db  0 bytes queue   32 KiB sync  RPC:  0 conn,  4 req/s, 138 Âµs
2017-11-25 22:00:37 UTC   50/50 peers      5 MiB chain  353 MiB db  0 bytes queue   32 KiB sync  RPC:  0 conn,  4 req/s, 147 Âµs
2017-11-25 22:01:12 UTC   50/50 peers      5 MiB chain  353 MiB db  0 bytes queue   32 KiB sync  RPC:  0 conn,  4 req/s, 132 Âµs
2017-11-25 22:01:47 UTC   50/50 peers      5 MiB chain  353 MiB db  0 bytes queue   32 KiB sync  RPC:  0 conn,  4 req/s, 108 Âµs
2017-11-25 22:02:22 UTC   50/50 peers      5 MiB chain  353 MiB db  0 bytes queue   32 KiB sync  RPC:  0 conn,  4 req/s, 135 Âµs
2017-11-25 22:02:57 UTC   50/50 peers      5 MiB chain  354 MiB db  0 bytes queue   32 KiB sync  RPC:  0 conn,  4 req/s, 119 Âµs
2017-11-25 22:03:32 UTC   50/50 peers      5 MiB chain  354 MiB db  0 bytes queue   32 KiB sync  RPC:  0 conn,  4 req/s, 130 Âµs
2017-11-25 22:04:07 UTC   50/50 peers      5 MiB chain  354 MiB db  0 bytes queue   32 KiB sync  RPC:  0 conn,  4 req/s, 131 Âµs
2017-11-25 22:04:42 UTC   50/50 peers      5 MiB chain  354 MiB db  0 bytes queue   32 KiB sync  RPC:  0 conn,  4 req/s, 126 Âµs
2017-11-25 22:05:17 UTC   50/50 peers      5 MiB chain  354 MiB db  0 bytes queue   32 KiB sync  RPC:  0 conn,  4 req/s, 110 Âµs
2017-11-25 22:05:52 UTC   50/50 peers      5 MiB chain  355 MiB db  0 bytes queue   32 KiB sync  RPC:  0 conn,  4 req/s, 128 Âµs
2017-11-25 22:06:27 UTC   50/50 peers      5 MiB chain  356 MiB db  0 bytes queue   32 KiB sync  RPC:  0 conn,  4 req/s, 125 Âµs
2017-11-25 22:07:02 UTC   50/50 peers      6 MiB chain  356 MiB db  0 bytes queue   32 KiB sync  RPC:  0 conn,  4 req/s, 134 Âµs
2017-11-25 22:07:37 UTC   50/50 peers      6 MiB chain  357 MiB db  0 bytes queue   32 KiB sync  RPC:  0 conn,  5 req/s, 117 Âµs
2017-11-25 22:08:07 UTC   50/50 peers      6 MiB chain  358 MiB db  0 bytes queue   32 KiB sync  RPC:  0 conn,  5 req/s, 130 Âµs
2017-11-25 22:08:42 UTC   50/50 peers      6 MiB chain  357 MiB db  0 bytes queue   32 KiB sync  RPC:  0 conn,  5 req/s, 136 Âµs
2017-11-25 22:09:17 UTC   50/50 peers      6 MiB chain  357 MiB db  0 bytes queue   32 KiB sync  RPC:  0 conn,  5 req/s, 132 Âµs
2017-11-25 22:09:52 UTC   50/50 peers      6 MiB chain  357 MiB db  0 bytes queue   32 KiB sync  RPC:  0 conn,  4 req/s, 125 Âµs
```

**Comment by miningpoolhub** [comment] 2017-11-28 18:49
Here's another fork log from parity latest version. v1.7.9

```
2017-11-28 06:33:02 UTC Imported #4636228 86cfâ€¦d585 (248 txs, 6.72 Mgas, 274.78 ms, 31.97 KiB)
2017-11-28 06:33:35 UTC   50/50 peers      3 MiB chain  405 MiB db  0 bytes queue   32 KiB sync  RPC:  0 conn,  3 req/s, 184 Âµs
2017-11-28 06:33:51 UTC Imported #4636229 9439â€¦d1ed (38 txs, 0.83 Mgas, 36.15 ms, 4.81 KiB)
2017-11-28 06:34:10 UTC   50/50 peers      3 MiB chain  404 MiB db  0 bytes queue   32 KiB sync  RPC:  0 conn,  4 req/s, 151 Âµs
2017-11-28 06:34:15 UTC Imported #4636230 5f5bâ€¦82ea (198 txs, 6.70 Mgas, 251.29 ms, 27.45 KiB)
2017-11-28 06:34:37 UTC Imported #4636231 be09â€¦4bd2 (28 txs, 0.59 Mgas, 77.74 ms, 4.07 KiB)
2017-11-28 06:34:45 UTC   50/50 peers      6 MiB chain  404 MiB db  0 bytes queue   32 KiB sync  RPC:  0 conn,  4 req/s, 206 Âµs
2017-11-28 06:34:46 UTC Imported #4636232 0204â€¦34b0 (52 txs, 1.65 Mgas, 85.00 ms, 7.84 KiB) + another 1 block(s) containing 72 tx(s)
2017-11-28 06:35:13 UTC Imported #4636233 6a3eâ€¦e7b1 (160 txs, 6.69 Mgas, 265.01 ms, 25.80 KiB)
2017-11-28 06:35:13 UTC Stage 2 block verification failed for 0435â€¦240f: Block(MismatchedH256SealElement(Mismatch { expected: dd105ca7c2d1d55d8968cdf0527e6221fac5c4893a412242cbc0e1bb0c68d0de, found: a993845b5c65f343b3ee164c244ae824db8aca7fbe1fb34fb8912c10b93959cb }))
2017-11-28 06:35:20 UTC   50/50 peers      8 MiB chain  404 MiB db  0 bytes queue   32 KiB sync  RPC:  0 conn,  4 req/s, 142 Âµs
2017-11-28 06:35:55 UTC   50/50 peers     10 MiB chain  404 MiB db  0 bytes queue   32 KiB sync  RPC:  0 conn,  4 req/s, 182 Âµs
2017-11-28 06:36:30 UTC   50/50 peers      9 MiB chain  404 MiB db  0 bytes queue   32 KiB sync  RPC:  0 conn,  4 req/s, 153 Âµs
2017-11-28 06:37:05 UTC   50/50 peers      8 MiB chain  406 MiB db  0 bytes queue   32 KiB sync  RPC:  0 conn,  5 req/s, 185 Âµs
2017-11-28 06:37:32 UTC Imported #4636234 db60â€¦1f7f (147 txs, 6.68 Mgas, 221.08 ms, 27.34 KiB)
2017-11-28 06:37:32 UTC Submitted block imported OK. #4636234: db60dd75d827a573e52498f64a425da7895530e0856c502f8489e00c1bbc1f7f
2017-11-28 06:37:40 UTC   50/50 peers     10 MiB chain  407 MiB db  0 bytes queue   32 KiB sync  RPC:  0 conn,  5 req/s, 122 Âµs
2017-11-28 06:38:11 UTC   50/50 peers      6 MiB chain  408 MiB db  0 bytes queue   32 KiB sync  RPC:  0 conn,  4 req/s, 186 Âµs
2017-11-28 06:38:45 UTC   50/50 peers      7 MiB chain  408 MiB db  0 bytes queue   32 KiB sync  RPC:  0 conn,  4 req/s, 171 Âµs
2017-11-28 06:39:20 UTC   50/50 peers      5 MiB chain  408 MiB db  0 bytes queue   32 KiB sync  RPC:  0 conn,  4 req/s, 179 Âµs
2017-11-28 06:39:55 UTC   50/50 peers      9 MiB chain  409 MiB db  0 bytes queue   32 KiB sync  RPC:  0 conn,  5 req/s, 157 Âµs
2017-11-28 06:40:30 UTC   50/50 peers      8 MiB chain  408 MiB db  0 bytes queue   32 KiB sync  RPC:  0 conn,  5 req/s, 213 Âµs
2017-11-28 06:41:05 UTC   47/50 peers      9 MiB chain  408 MiB db  0 bytes queue   32 KiB sync  RPC:  0 conn,  4 req/s, 136 Âµs
2017-11-28 06:41:40 UTC   50/50 peers      5 MiB chain  408 MiB db  0 bytes queue   32 KiB sync  RPC:  0 conn,  6 req/s, 188 Âµs
2017-11-28 06:42:15 UTC   50/50 peers     10 MiB chain  407 MiB db  0 bytes queue   32 KiB sync  RPC:  0 conn,  4 req/s, 144 Âµs
2017-11-28 06:42:45 UTC   50/50 peers     14 MiB chain  407 MiB db  0 bytes queue   32 KiB sync  RPC:  0 conn,  4 req/s, 169 Âµs

```

I can easily recover its state by restarting.

**Comment by miningpoolhub** [comment] 2017-11-30 00:47
Sync stuck again today.

I found that
node runnong on "Intel(R) Xeon(R) CPU E5-2697 v4 @ 2.30GHz" runs fine.
node running on "Intel(R) Xeon(R) CPU E5-2680 v3 @ 2.50GHz" stuck time to time.

Seems like some hashing result is different on ES-2680.
Not sure but just guessing from the log.
Any idea about it?

**Comment by whilei** [comment] 2017-11-30 17:05
```
I1129 12:25:19.152918 p2p/server.go:587] Accepted conn 71.8.44.246:62686
I1129 12:25:19.314560 p2p/server.go:680] Added Peer a11dfd496b25c340 71.8.44.246:62686
I1129 12:25:19.314723 eth/handler.go:250] Peer a11dfd496b25c340 [eth/63]: peer connected [Parity/v1.7.0-beta-5f2cabd-20170727/x86_64-windows-msvc/rustc1.18.0]
I1129 12:25:19.458939 eth/downloader/downloader.go:1512] Quality of service: rtt 20s, conf 0.500, ttl 1m0s
I1129 12:25:19.459068 eth/peer.go:209] Peer a11dfd496b25c340 [eth/63] fetching 1 headers from #1920000, skipping 0 (reverse = false)
I1129 12:25:19.683631 eth/downloader/downloader.go:1482] Quality of service: rtt 20s, conf 0.750, ttl 1m0s
I1129 12:25:19.723993 eth/handler.go:192] Removing peer a11dfd496b25c340
I1129 12:25:19.724023 eth/handler.go:310] Peer a11dfd496b25c340 [eth/63]: message handling failed: known fork hash mismatch
I1129 12:25:19.724053 p2p/peer.go:180] Peer a11dfd496b25c340 71.8.44.246:62686: locally requested disconnect: Useless peer
I1129 12:25:19.724224 p2p/server.go:704] Removed Peer a11dfd496b25c340 71.8.44.246:62686 (Useless peer)
```
Taken @khelle's logs given at https://github.com/ethereumproject/go-ethereum/issues/346#issuecomment-347909624

**Comment by debris** [comment] 2018-05-19 09:40
> Going to close issue since it appears it was resolved with UDP6 ports being open.

@whilei issue seems to be a different one and resolved with changing udp settings https://github.com/ethereumproject/go-ethereum/issues/346#issuecomment-351892844 

> Seems like some hashing result is different on ES-2680.

This is extremely unlikely. I'm closing, cause this issue cannot be resolved without more details and/or more people experiencing the same problems. Please reopen if it still occurs and you can provide a scenario that allows us to reproduce it

**Closed by debris** 2018-05-19 09:40 UTC
Labels: F2-bug, M4-core, P2-asap
