### ISSUE TITLE
ERC20 tokens that are limited-time marketing promotions cannot be archived

### ISSUE THREAD

**Issue by ltfschoen** [paritytech/parity#7305] opened 2017-12-16 20:30 UTC
_Before filing a new issue, please **provide the following information**._

> I'm running:
>
> - **Which Parity version?**: v1.8.4-beta
* Note: same issue occurs with Parity v1.8.3-beta
> - **Which operating system?**: MacOS
* macOS Sierra 10.12.6
> - **How installed?**: Installer
* Downloaded https://parity-downloads-mirror.parity.io/v1.8.4/x86_64-apple-darwin/parity-1.8.4-macos-installer.pkg
* Validated checksum with `shasum -a 256 parity-1.8.4-macos-installer.pkg`
* Run parity-1.8.4-macos-installer.pkg
* Updating to latest Google Chrome Version 63.0.3239.108 (Official Build) (64-bit)
> - **Are you fully synchronized?**: yes
> - **Did you try to restart the node?**: yes
* Yes, I've restarted Parity, restarted Google Chrome, and emptied browser cache with hard reload

_Your issue description goes here below. Try to include **actual** vs. **expected behaviour** and **steps to reproduce** the issue._

**Actual Behaviour** 
Some tokens such as [INSP Token Symbol](https://etherscan.io/token/0x52903256dd18D85c2Dc4a6C999907c9793eA61E3) are just Promo tokens that provide a discount when investing in an ICO, but after the ICO has ended they may no longer serve any purpose, so whilst we may be transferred that token as an air drop, we as users may want to "hide" it from the Wallet view in the Accounts tab of the Parity Client manually ourselves after a certain date. Would adding a feature that allows users to toggle the state of whether certain tokens are visible or not be looked upon favourably by Parity developers and other users? 
Note that the INSP Token Symbol itself does not currently appear in the Parity Client anyway, but there may be other Promo tokens that do.

**Expected Behaviour** 
If your Ethereum address has a balance of any ERC20 tokens that are just representative of limited-time marketing promotions such as INSP, then in your Wallet view (of the Accounts tab in the Parity Client) it could not only display that ERC20 token Symbol, its corresponding icon, and the correct balance, which should all match details shown in the Token Tracker view of your account at Etherscan https://etherscan.io/address/<YOUR_ETHEREUM_ADDRESS>#tokentxns, but additionally also give the user an option in the user interface that allows them to "mask" that token (i.e. it could be as simple as a feature where you click a button that says "Choose Tokens to Archive", which then allows users to clicking the tokens they want to archive, and then as a result those tokens are show at the end of the list (or even in a separate list called "Token Archive" or similar.

**Steps to Reproduce**
N/A

**Comment by 5chdn** [comment] 2018-01-03 13:37
Duplicate of #6783

**Closed by 5chdn** 2018-01-03 13:37 UTC
Labels: M8-dapp, Z0-duplicate
