### ISSUE TITLE
Memory leak when running --pruning=archive with latest master

### ISSUE THREAD

**Issue by mtbitcoin** [paritytech/parity#3081] opened 2016-11-02 03:56 UTC
There is a Memory leak when running '--pruning=archive' with latest master

2016-11-01 20:56:06  Starting Parity/v1.4.0-unstable-a02a8d3-20161101/x86_64-windows-msvc/rustc1.12.0

**Comment by tomusdrw** [comment] 2016-11-02 08:07
Does it happen while syncing or when fully synced node is running for some time?

**Comment by mtbitcoin** [comment] 2016-11-02 08:57
Fully synched nodes running for some time. I've been able to consistently reproduce this on 4 different nodes. Removing the --pruning=archive on the same nodes meant no more memory leaks.  I recall we had this issue in the past too but it was fixed

**Comment by arkpar** [comment] 2016-11-02 09:31
@mtbitcoin What is the memory usage? How do you measure it?

**Comment by gavofyork** [comment] 2016-11-02 09:46
the period snapshot has taken my ram to around 6.5% of total (around 1GB) and left it at around 900MB.

**Comment by mtbitcoin** [comment] 2016-11-02 09:57
@arkpar on windows, task manager shows 99% ram utilized out of 30GB. Shutting parity down frees up more than 15Gb.

**Comment by arkpar** [comment] 2016-11-02 10:06
Most of that is cache which is freed automatically as soon as other program needs memory. Could you take note of "Peak working set" and "Memory (Private working set)" values for parity process in the details tab? If the columns are not visible you can enable them in the "View" menu.

**Comment by mtbitcoin** [comment] 2016-11-02 15:04
Cache was set to 1024 mb. Task manager showed ram utilized around 2-4gb which was normal. I don't have the peak and working sets at the moment because I am now running it without archive. But will try setting up one later

**Comment by mtbitcoin** [comment] 2016-11-07 11:44
@arkpar  These are the values, the memory leak is still present

Commit: 4,367,668 KB
Working Set: 3,911,564 KB
Shareable: 4768 KB
Private: 3,911,800 KB

**Comment by Shadowstep33** [comment] 2017-02-18 21:04
I am simply running parity with the --geth flag and I started it at night to finish syncing (about 500mb RAM usage) and when I woke up it is at 1.5GB

**Comment by 5chdn** [comment] 2017-04-11 07:54
Do you still experience this issue with 1.5 or 1.6?

**Comment by mtbitcoin** [comment] 2017-04-11 07:59
Yes,  issue still persists at least till ver 1.6.2.  Did not further test after that

**Comment by 5chdn** [comment] 2017-05-09 13:13
This issue is labelled with _bug_: The client fails to follow expected behavior; and is inactive for one month. It's neither assigned nor linked to a milestone.

@paritytech/core-devs Please, decide on a deadline and assign this ticket to a developer within 7 days or close it otherwise.

**Comment by keorn** [comment] 2017-07-31 18:44
@mtbitcoin is the issue still present?

**Comment by gaoxiangxyz** [comment] 2018-01-04 11:39
@keorn @5chdn The issue is still present on windows with SSD, task manager shows 99% ram utilized out of 64GB. The private working set of parity.exe process is only about 1GB. The current block number is about 2.5 million and sync is blocked when ram utilized reach to 99%.

config file is as below
```
[parity]
base_path = "E:\\eth\\parity\\mainnet"
db_path = "E:\\eth\\parity\\mainnet\\chains"
keys_path = "E:\\eth\\parity\\mainnet\\keys"
identity = "ws_mainnet"

[ui]
disable = true

[network]
no_warp = true

[ipc]
disable = true

[rpc]
apis = ["web3", "eth", "net", "parity", "traces", "rpc", "personal", "parity_set"]

[websockets]
disable = true

[secretstore]
disable = true

[ipfs]
disable = true

[footprint]
pruning = "archive"
tracing = "on"
db_compaction = "ssd"

[misc]
log_file = "E:\\eth\\parity\\mainnet.log"
color = false
```

**Comment by folsen** [comment] 2018-05-19 05:40
@Tbaut can we try to reproduce this on a windows setup somehow? If not, please close.

**Comment by Tbaut** [comment] 2018-05-23 10:08
I do not have access to an archive windows node right now. Due to the age of the issue, I'll close it.  We can reopen if it still happens on a recent release.

**Closed by Tbaut** 2018-05-23 10:08 UTC
Labels: F2-bug, M4-core, P2-asap
