### ISSUE TITLE
Unable to sync archive node from scratch because of  "Corruption: block checksum mismatch: expected 4234929713, got 629800586"

### ISSUE THREAD

**Issue by doetsch** [paritytech/parity#7545] opened 2018-01-12 10:22 UTC
_Before filing a new issue, please **provide the following information**._

> I'm running:
>
> - **Which Parity version?**: 1.8.6
> - **Which operating system?**: Linux
> - **How installed?**: via deb
> - **Are you fully synchronized?**: no
> - **Which network are you connected to?**: ethereum
> - **Did you try to restart the node?**: yes

_Your issue description goes here below. Try to include **actual** vs. **expected behavior** and **steps to reproduce** the issue._

I am trying to sync an archive node from scratch since the update to 1.8.6 did not allow me to use my old database (it just did nothing for hours). However, the new sync from scratch stops after about 20 hours at block 2678631 with error:

stack backtrace:
   0:     0x5630c8c922fc - <no info>

Thread 'Verifier #3' panicked at 'DB flush failed.: "Corruption: block checksum mismatch: expected 4234929713, got 629800586  in /foo/bar/db/906a34e69aec8c0d/archive/db/167419.sst offset 3193303 size 16290"', /checkout/src/libcore/result.rs:906

This is a bug. Please report it at:

    https://github.com/paritytech/parity/issues/new

Aborted

**Comment by 5chdn** [comment] 2018-01-16 10:30
Duplicate of #7334

**Closed by 5chdn** 2018-01-16 10:30 UTC
