### ISSUE TITLE
Parity drops transactions

### ISSUE THREAD

**Issue by GeRikz** [paritytech/parity#8733] opened 2018-05-29 21:57 UTC
I'm running:
*Which Parity version?**: 1.11.1
*Which operating system?**: centos 6
*How installed?**: bash <(curl https://get.parity.io -Lk)
*Are you fully synchronized?**: yes
*Which network are you connected to?**: ethereum
*Did you try to restart the node?**:  yes

Parity is droping all transactions with error
There are too many transactions in the queue. Your transaction was dropped due to limit. Try increasing the fee.
When i add --tx-queue-size 90000 in launch options transactions goes true but i lose all peers and peers are jumping from 1/25 to 4/25 and getting out of sync. If --tx-queue-size are removed then peers keeps above 23 but not letting transactions to chain. Im using 30gwei and 21,000 gas limit to send transactions

**Comment by Tbaut** [comment] 2018-05-30 10:36
This is a duplicate of #8679 A fix has been prepared and will be introduced in the next minor version.

**Closed by Tbaut** 2018-05-30 10:36 UTC
Labels: F3-annoyance, M4-core, Z7-duplicate
