### ISSUE TITLE
parity light client sync stuck

### ISSUE THREAD

**Issue by onpars** [paritytech/parity#6882] opened 2017-10-24 18:59 UTC
> I'm running:
>
> - **Parity version**: Parity 1.8.1-beta
> - **Operating system**:  Linux
> - **And installed**: deb

Initially I was using `parity --geth --light.` Since it is stuck now I am using `parity --geth --light --mode=active -lsync=trace`.

A new blockchain download. Behind NAT. Stuck at block 1977816. Initially, it was syncing quickly. Now it is stuck.Please advice.

```
2017-10-24 20:39:52  IO Worker #2 INFO import  Syncing #1977816 8970…716c     0 hdr/s  30060+    0 Qed  #1977816    7/50 peers   664 bytes cache 25 MiB queue  RPC:  0 conn, 33 req/s,  21 µs
2017-10-24 20:39:57  IO Worker #1 DEBUG sync  Maintaining sync (Rounds(Filling scaffold up to (2369374, 96fc31ef869051a534464fe006bfed6a4f7af4af12e15abddd2fbe06cc087139)))
2017-10-24 20:39:57  IO Worker #1 TRACE sync  Drained 128 headers to import
2017-10-24 20:39:57  IO Worker #1 TRACE sync  Drained 128 headers to import
2017-10-24 20:39:57  IO Worker #1 TRACE sync  Drained 128 headers to import
2017-10-24 20:39:57  IO Worker #1 TRACE sync  Drained 128 headers to import
2017-10-24 20:39:57  IO Worker #1 TRACE sync  Drained 128 headers to import
2017-10-24 20:39:57  IO Worker #1 TRACE sync  Drained 128 headers to import
2017-10-24 20:39:57  IO Worker #1 TRACE sync  Drained 128 headers to import
2017-10-24 20:39:57  IO Worker #1 TRACE sync  Drained 128 headers to import
2017-10-24 20:39:57  IO Worker #1 TRACE sync  Drained 128 headers to import
2017-10-24 20:39:57  IO Worker #1 TRACE sync  Drained 128 headers to import
2017-10-24 20:39:57  IO Worker #1 TRACE sync  Drained 128 headers to import
2017-10-24 20:39:57  IO Worker #1 TRACE sync  Drained 128 headers to import
2017-10-24 20:39:57  IO Worker #1 TRACE sync  Drained 128 headers to import
2017-10-24 20:39:57  IO Worker #1 TRACE sync  Drained 128 headers to import
2017-10-24 20:39:57  IO Worker #1 TRACE sync  Drained 128 headers to import
2017-10-24 20:39:57  IO Worker #1 TRACE sync  Drained 128 headers to import
2017-10-24 20:39:57  IO Worker #1 TRACE sync  Drained 128 headers to import
2017-10-24 20:39:57  IO Worker #1 TRACE sync  Drained 128 headers to import
2017-10-24 20:39:57  IO Worker #1 TRACE sync  Drained 128 headers to import
2017-10-24 20:39:57  IO Worker #1 TRACE sync  Drained 128 headers to import
2017-10-24 20:39:57  IO Worker #1 TRACE sync  Drained 128 headers to import
2017-10-24 20:39:57  IO Worker #1 TRACE sync  Drained 128 headers to import
2017-10-24 20:39:57  IO Worker #1 TRACE sync  Drained 128 headers to import
2017-10-24 20:39:57  IO Worker #1 TRACE sync  Drained 128 headers to import
2017-10-24 20:39:57  IO Worker #2 INFO import  Syncing #1977816 8970…716c     0 hdr/s  29944+    0 Qed  #1977816    6/50 peers   664 bytes cache 25 MiB queue  RPC:  0 conn, 19 req/s,  21 µs
2017-10-24 20:40:01  IO Worker #0 TRACE sync  Announcement from peer 70: new chain head (7c5cf5df284e3cd0761fa615b11d38fde700d557ebba12b6247949a601d39740, 4422247), reorg depth 1
2017-10-24 20:40:01  IO Worker #0 DEBUG sync  Maintaining sync (Rounds(Filling scaffold up to (2369374, 96fc31ef869051a534464fe006bfed6a4f7af4af12e15abddd2fbe06cc087139)))
2017-10-24 20:40:01  IO Worker #0 TRACE sync  Drained 128 headers to import
2017-10-24 20:40:01  IO Worker #0 TRACE sync  Drained 128 headers to import
2017-10-24 20:40:01  IO Worker #0 TRACE sync  Drained 128 headers to import
2017-10-24 20:40:01  IO Worker #0 TRACE sync  Drained 128 headers to import
2017-10-24 20:40:01  IO Worker #0 TRACE sync  Drained 128 headers to import
2017-10-24 20:40:01  IO Worker #0 TRACE sync  Drained 128 headers to import
2017-10-24 20:40:01  IO Worker #0 TRACE sync  Drained 128 headers to import
2017-10-24 20:40:01  IO Worker #0 TRACE sync  Drained 128 headers to import
2017-10-24 20:40:01  IO Worker #0 TRACE sync  Drained 128 headers to import
2017-10-24 20:40:01  IO Worker #0 TRACE sync  Drained 128 headers to import
2017-10-24 20:40:01  IO Worker #0 TRACE sync  Drained 128 headers to import
2017-10-24 20:40:01  IO Worker #0 TRACE sync  Drained 128 headers to import
2017-10-24 20:40:01  IO Worker #0 TRACE sync  Drained 128 headers to import
2017-10-24 20:40:01  IO Worker #0 TRACE sync  Drained 128 headers to import
2017-10-24 20:40:01  IO Worker #0 TRACE sync  Drained 128 headers to import
2017-10-24 20:40:01  IO Worker #0 TRACE sync  Drained 128 headers to import
2017-10-24 20:40:01  IO Worker #0 TRACE sync  Drained 128 headers to import
2017-10-24 20:40:01  IO Worker #0 TRACE sync  Drained 128 headers to import
2017-10-24 20:40:01  IO Worker #0 TRACE sync  Drained 128 headers to import
2017-10-24 20:40:01  IO Worker #0 TRACE sync  Drained 128 headers to import
2017-10-24 20:40:01  IO Worker #0 TRACE sync  Drained 128 headers to import
2017-10-24 20:40:01  IO Worker #0 TRACE sync  Drained 128 headers to import
2017-10-24 20:40:01  IO Worker #0 TRACE sync  Drained 128 headers to import
2017-10-24 20:40:01  IO Worker #0 TRACE sync  Drained 128 headers to import
2017-10-24 20:40:01  IO Worker #0 TRACE sync  Drained 128 headers to import
2017-10-24 20:40:01  IO Worker #0 TRACE sync  Drained 128 headers to import
2017-10-24 20:40:01  IO Worker #0 TRACE sync  Drained 128 headers to import
2017-10-24 20:40:01  IO Worker #3 TRACE sync  Announcement from peer 46: new chain head (7c5cf5df284e3cd0761fa615b11d38fde700d557ebba12b6247949a601d39740, 4422247), reorg depth 1
2017-10-24 20:40:01  IO Worker #3 DEBUG sync  Maintaining sync (Rounds(Filling scaffold up to (2369374, 96fc31ef869051a534464fe006bfed6a4f7af4af12e15abddd2fbe06cc087139)))
2017-10-24 20:40:01  IO Worker #3 TRACE sync  Drained 128 headers to import
2017-10-24 20:40:01  IO Worker #2 TRACE sync  Announcement from peer 64: new chain head (7c5cf5df284e3cd0761fa615b11d38fde700d557ebba12b6247949a601d39740, 4422247), reorg depth 1
2017-10-24 20:40:01  IO Worker #2 DEBUG sync  Maintaining sync (Rounds(Filling scaffold up to (2369374, 96fc31ef869051a534464fe006bfed6a4f7af4af12e15abddd2fbe06cc087139)))
2017-10-24 20:40:01  IO Worker #2 TRACE sync  Drained 128 headers to import
2017-10-24 20:40:01  IO Worker #2 TRACE sync  Drained 128 headers to import
2017-10-24 20:40:01  IO Worker #1 TRACE sync  Announcement from peer 27: new chain head (7c5cf5df284e3cd0761fa615b11d38fde700d557ebba12b6247949a601d39740, 4422247), reorg depth 1
2017-10-24 20:40:01  IO Worker #1 DEBUG sync  Maintaining sync (Rounds(Filling scaffold up to (2369374, 96fc31ef869051a534464fe006bfed6a4f7af4af12e15abddd2fbe06cc087139)))
2017-10-24 20:40:01  IO Worker #0 TRACE sync  Announcement from peer 10: new chain head (7c5cf5df284e3cd0761fa615b11d38fde700d557ebba12b6247949a601d39740, 4422247), reorg depth 1
2017-10-24 20:40:01  IO Worker #0 DEBUG sync  Maintaining sync (Rounds(Filling scaffold up to (2369374, 96fc31ef869051a534464fe006bfed6a4f7af4af12e15abddd2fbe06cc087139)))
2017-10-24 20:40:01  IO Worker #0 TRACE sync  Drained 128 headers to import
2017-10-24 20:40:01  IO Worker #0 TRACE sync  Drained 128 headers to import
2017-10-24 20:40:02  IO Worker #1 DEBUG sync  Maintaining sync (Rounds(Filling scaffold up to (2369374, 96fc31ef869051a534464fe006bfed6a4f7af4af12e15abddd2fbe06cc087139)))
2017-10-24 20:40:02  IO Worker #1 TRACE sync  Drained 128 headers to import
2017-10-24 20:40:02  IO Worker #1 TRACE sync  Drained 128 headers to import
2017-10-24 20:40:02  IO Worker #0 INFO import  Syncing #1977816 8970…716c     0 hdr/s  29988+    0 Qed  #1977816    6/50 peers   664 bytes cache 25 MiB queue  RPC:  0 conn, 34 req/s,  21 µs
2017-10-24 20:40:07  IO Worker #0 DEBUG sync  Maintaining sync (Rounds(Filling scaffold up to (2369374, 96fc31ef869051a534464fe006bfed6a4f7af4af12e15abddd2fbe06cc087139)))
2017-10-24 20:40:07  IO Worker #0 TRACE sync  Drained 128 headers to import
2017-10-24 20:40:07  IO Worker #0 TRACE sync  Drained 128 headers to import
2017-10-24 20:40:07  IO Worker #0 TRACE sync  Drained 128 headers to import
2017-10-24 20:40:07  IO Worker #0 TRACE sync  Drained 128 headers to import
2017-10-24 20:40:07  IO Worker #0 TRACE sync  Drained 128 headers to import
2017-10-24 20:40:07  IO Worker #0 TRACE sync  Drained 128 headers to import
2017-10-24 20:40:07  IO Worker #0 TRACE sync  Drained 128 headers to import
2017-10-24 20:40:07  IO Worker #0 TRACE sync  Drained 128 headers to import
2017-10-24 20:40:07  IO Worker #0 TRACE sync  Drained 128 headers to import
2017-10-24 20:40:07  IO Worker #0 TRACE sync  Drained 128 headers to import
2017-10-24 20:40:07  IO Worker #0 TRACE sync  Drained 128 headers to import
2017-10-24 20:40:07  IO Worker #0 TRACE sync  Drained 128 headers to import
2017-10-24 20:40:07  IO Worker #0 TRACE sync  Drained 128 headers to import
2017-10-24 20:40:07  IO Worker #0 TRACE sync  Drained 128 headers to import
2017-10-24 20:40:07  IO Worker #0 TRACE sync  Drained 128 headers to import
2017-10-24 20:40:07  IO Worker #0 TRACE sync  Drained 128 headers to import
2017-10-24 20:40:07  IO Worker #0 TRACE sync  Drained 128 headers to import
2017-10-24 20:40:07  IO Worker #0 TRACE sync  Drained 128 headers to import
2017-10-24 20:40:07  IO Worker #0 TRACE sync  Drained 128 headers to import
2017-10-24 20:40:07  IO Worker #0 TRACE sync  Drained 128 headers to import
2017-10-24 20:40:07  IO Worker #0 TRACE sync  Drained 128 headers to import
2017-10-24 20:40:07  IO Worker #0 TRACE sync  Drained 128 headers to import
2017-10-24 20:40:07  IO Worker #0 TRACE sync  Drained 128 headers to import
2017-10-24 20:40:07  IO Worker #0 TRACE sync  Drained 128 headers to import
2017-10-24 20:40:07  IO Worker #0 TRACE sync  Drained 128 headers to import
2017-10-24 20:40:07  IO Worker #0 TRACE sync  Drained 128 headers to import
2017-10-24 20:40:07  IO Worker #0 TRACE sync  Drained 128 headers to import
2017-10-24 20:40:07  IO Worker #0 TRACE sync  Drained 128 headers to import
2017-10-24 20:40:07  IO Worker #0 TRACE sync  Drained 128 headers to import
2017-10-24 20:40:07  IO Worker #0 TRACE sync  Drained 128 headers to import
2017-10-24 20:40:07  IO Worker #0 TRACE sync  Drained 128 headers to import
2017-10-24 20:40:07  IO Worker #0 TRACE sync  Drained 128 headers to import
2017-10-24 20:40:07  IO Worker #0 TRACE sync  Drained 128 headers to import
2017-10-24 20:40:07  IO Worker #0 TRACE sync  Drained 128 headers to import
2017-10-24 20:40:07  IO Worker #1 INFO import  Syncing #1977816 8970…716c     0 hdr/s  30019+    0 Qed  #1977816    6/50 peers   664 bytes cache 25 MiB queue  RPC:  0 conn, 20 req/s,  21 µs
2017-10-24 20:40:12  IO Worker #2 DEBUG sync  Maintaining sync (Rounds(Filling scaffold up to (2369374, 96fc31ef869051a534464fe006bfed6a4f7af4af12e15abddd2fbe06cc087139)))
2017-10-24 20:40:12  IO Worker #2 TRACE sync  Drained 128 headers to import
2017-10-24 20:40:12  IO Worker #2 TRACE sync  Drained 128 headers to import
2017-10-24 20:40:12  IO Worker #2 TRACE sync  Drained 128 headers to import
2017-10-24 20:40:12  IO Worker #2 TRACE sync  Drained 128 headers to import
2017-10-24 20:40:12  IO Worker #2 TRACE sync  Drained 128 headers to import
2017-10-24 20:40:12  IO Worker #2 TRACE sync  Drained 128 headers to import
2017-10-24 20:40:12  IO Worker #2 TRACE sync  Drained 128 headers to import
2017-10-24 20:40:12  IO Worker #2 TRACE sync  Drained 128 headers to import
2017-10-24 20:40:12  IO Worker #2 TRACE sync  Drained 128 headers to import
2017-10-24 20:40:12  IO Worker #2 TRACE sync  Drained 128 headers to import
2017-10-24 20:40:12  IO Worker #2 TRACE sync  Drained 128 headers to import
2017-10-24 20:40:12  IO Worker #2 TRACE sync  Drained 128 headers to import
2017-10-24 20:40:12  IO Worker #2 TRACE sync  Drained 128 headers to import
2017-10-24 20:40:12  IO Worker #2 TRACE sync  Drained 128 headers to import
2017-10-24 20:40:12  IO Worker #2 TRACE sync  Drained 128 headers to import
2017-10-24 20:40:12  IO Worker #2 TRACE sync  Drained 128 headers to import
2017-10-24 20:40:12  IO Worker #2 TRACE sync  Drained 128 headers to import
2017-10-24 20:40:12  IO Worker #2 TRACE sync  Drained 128 headers to import
2017-10-24 20:40:12  IO Worker #2 TRACE sync  Drained 128 headers to import
2017-10-24 20:40:12  IO Worker #2 TRACE sync  Drained 128 headers to import
2017-10-24 20:40:12  IO Worker #2 TRACE sync  Drained 128 headers to import
2017-10-24 20:40:12  IO Worker #2 TRACE sync  Drained 128 headers to import
2017-10-24 20:40:12  IO Worker #2 TRACE sync  Drained 128 headers to import
2017-10-24 20:40:12  IO Worker #2 TRACE sync  Drained 128 headers to import
2017-10-24 20:40:12  IO Worker #2 TRACE sync  Drained 128 headers to import
2017-10-24 20:40:12  IO Worker #2 TRACE sync  Drained 128 headers to import
2017-10-24 20:40:12  IO Worker #2 TRACE sync  Drained 128 headers to import
2017-10-24 20:40:12  IO Worker #2 TRACE sync  Drained 128 headers to import
2017-10-24 20:40:12  IO Worker #2 TRACE sync  Drained 128 headers to import
2017-10-24 20:40:12  IO Worker #2 TRACE sync  Drained 128 headers to import
2017-10-24 20:40:12  IO Worker #2 TRACE sync  Drained 128 headers to import
2017-10-24 20:40:12  IO Worker #2 TRACE sync  Drained 128 headers to import
2017-10-24 20:40:12  IO Worker #3 INFO import  Syncing #1977816 8970…716c     0 hdr/s  30001+    0 Qed  #1977816    6/50 peers   664 bytes cache 25 MiB queue  RPC:  0 conn, 34 req/s,  21 µs
```

Keep repeating that block number. Restart does not help.

**Comment by Office-Julia** [comment] 2017-10-28 06:40
Hello. Let me assist you with this issue. 
Could you please ask the following questions:
1. Have you uninstalled and installed Parity again?
2. What flags are you running Parity with?
3. Do you use any config file?
4. Is there anything in the logs?
5. Do you experience any connection problem? Are you connected to any peers?
6. What's your time? Is it synchronized? time.is

**Comment by Office-Julia** [comment] 2017-10-28 07:05
Also please note version 1.8.1 is not the latest one.
Our latest Beta release is 1.8.2,
and latest stable release is 1.7.8.
Please kindly let us know if you tried to install these versions and if the problem happens there again?

Reference: https://github.com/paritytech/parity/releases

**Comment by Office-Julia** [comment] 2017-10-28 08:34
@rphmeier do you have any ideas?

**Comment by onpars** [comment] 2017-10-28 13:54
> Have you uninstalled and installed Parity again?

No. It was a fresh installation.

> What flags are you running Parity with?

Only `--geth --light` as described in original post.

> Do you use any config file?

No.

> Is there anything in the logs?

Which log? Isn't above already the verbose log?

> Do you experience any connection problem?

No.

> Are you connected to any peers?

As per above's log it's `6/50 peers`.

> What's your time? Is it synchronized? time.is

Very synchronized. To exclude this issue, I am actually always running beforehand `sudo ntpdate -s time.nist.gov`.

> Also please note version 1.8.1 is not the latest one.

This bug report was with the latest beta at the time which was 4 days ago. 1.8.2 was only released 2 days ago.

**Comment by 5chdn** [comment] 2017-10-29 07:53
duplicate of #6319 

you probably need more peers serving the light protocol.

**Closed by 5chdn** 2017-10-29 07:53 UTC
Labels: M4-core, Z5-unconfirmed
