### ISSUE TITLE
panicked at 'DecodeError: RlpIsTooShort

### ISSUE THREAD

**Issue by bokkypoobah** [paritytech/parity#3669] opened 2016-11-29 13:48 UTC
I have just done a fresh sync using Parity/v1.5.0-unstable-54b656b-20161128/x86_64-macos/rustc1.13.0 with the parameter '--tracing on' and tried a trace_transaction on 0xc95d72edac6a17ad37d851ee767403969acec8c001fd3e3a00625e731aa39ecd , and Parity crashed with the following message:

    thread '<unnamed>' panicked at 'DecodeError: RlpIsTooShort, f90241f840f83ef83880f69479e56155e36e0ed205abf8b28074717cce8d9a3694d73026b0494d25427f3d1a7743babe1bddf8a035880d61997f05fb6280808001c10280c0f847f845f83c80f839944bb96091ee9d802ed039c4d1a5f6216f90f81b0194bacb710a72801f00615ff65ae1910478fb52ccf58846d8f867422ca80083010d888001c480c2808080c0f901b3f90105f8d980f8d694b5806ee8211626592310e0782933a626c78279fe948f9c2b5c291a43465bfc14ec430575f69fe9becd808302cddab8a4b61d27f6000000000000000000000000bb9bc244d798123fde783fcc1c72d3bb8c1894130000000000000000000000000000000000000000000000000de0b6b3a764000000000000000000000000000000000000000000000000000000000000000000600000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000001e780e58301473aa0000000000000000000000000000000000000000000000000000000000000000001c0f868f83c80f839948f9c2b5c291a43465bfc14ec430575f69fe9becd94bb9bc244d798123fde783fcc1c72d3bb8c189413880de0b6b3a76400008301f4c38001e680e482cf63a0000000000000000000000000000000000000000000000000000000000000000101c180f83ff380f194bb9bc244d798123fde783fcc1c72d3bb8c18941394807640a13483f8ac783c557fcdf27be11ea4ac7a8083016c838001c680c48213f98080c28080', util/rlp/src/rlpin.rs:120
    stack backtrace:
       1:        0x107480c48 - std::sys::backtrace::tracing::imp::write::h6f1d53a70916b90d
       2:        0x107486ddf - std::panicking::default_hook::{{closure}}::h137e876f7d3b5850
       3:        0x1074857e5 - std::panicking::default_hook::h0ac3811ec7cee78c
       4:        0x107485df6 - std::panicking::rust_panic_with_hook::hc303199e04562edf
       5:        0x107485c94 - std::panicking::begin_panic::h6ed03353807cf54d
       6:        0x107485bb2 - std::panicking::begin_panic_fmt::hc321cece241bb2f5
       7:        0x106f674dc - <ethcore::trace::db::TraceDB<T>>::traces::h5592036804cddf33
       8:        0x106f53cf6 - <ethcore::client::client::Client as ethcore::client::traits::BlockChainClient>::transaction_traces::hecdb9d7c977af290
       9:        0x10692ad0e - <jsonrpc_core::io::DelegateMethod<T, F> as jsonrpc_core::commander::MethodCommand>::execute::h1ac3a2b89496c347
      10:        0x107323243 - jsonrpc_core::commander::Commander::execute_method::h5b971ea2f7ee1de3
      11:        0x1073241ef - jsonrpc_core::request_handler::RequestHandler::handle_call::h082dd6345fe02cd6
      12:        0x1073237b5 - jsonrpc_core::request_handler::RequestHandler::handle_request::h26dbd3a45b6a845b
      13:        0x1073263a2 - jsonrpc_core::io::IoHandler::handle_request::h040e24e667f10582
      14:        0x10730498c - <jsonrpc_http_server::handler::ServerHandler as hyper::server::Handler<hyper::net::HttpStream>>::on_request_readable::hc7e90be5aa2a2b3b
      15:        0x1072fd6e9 - <hyper::http::conn::ConnInner<K, T, H>>::read::ha480e579ba4170b6
      16:        0x1072fe578 - <hyper::http::conn::ConnInner<K, T, H>>::read::ha480e579ba4170b6
      17:        0x1072fd5c1 - <hyper::http::conn::ConnInner<K, T, H>>::read::ha480e579ba4170b6
      18:        0x1072fb95c - <hyper::http::conn::ConnInner<K, T, H>>::on_readable::h006387df4ed1bdac
      19:        0x1072f9b55 - <hyper::http::conn::Conn<K, T, H>>::ready::h87963f9e4d2fb2bf
      20:        0x1072ee6e0 - <mio::event_loop::EventLoop<H>>::run_once::hd8826d41cd9f3821
      21:        0x1072f716f - drop::ha83ce868857a554b
      22:        0x1072ee02d - std::panicking::try::do_call::h5376ad9d00b74af5
      23:        0x10748739a - __rust_maybe_catch_panic
      24:        0x1072f78c6 - <F as alloc::boxed::FnBox<A>>::call_box::ha622049364175089
      25:        0x107484e94 - std::sys::thread::Thread::new::thread_start::h759e10bc4abc7e72
      26:     0x7fff89ca499c - _pthread_body
      27:     0x7fff89ca4919 - _pthread_start

I've seen some of the similar closed issues, but this crash seems to still be occurring.

**Comment by rphmeier** [comment] 2016-12-08 15:45
@debris Did trace format change at any point recently?

**Comment by arkpar** [comment] 2016-12-09 09:58
Can't reproduce on latest master (fresh sync):
```
curl -s -X POST -H "Content-Type: application/json" --data '{"jsonrpc":"2.0","method":"trace_transaction","params":["0xc95d72edac6a17ad37d851ee767403969acec8c001fd3e3a00625e731aa39ecd"],"id":74}' 127.0.0.1:8545
{"jsonrpc":"2.0","result":[{"action":{"callType":"call","from":"0xb5806ee8211626592310e0782933a626c78279fe","gas":"0x2cdda","input":"0xb61d27f6000000000000000000000000bb9bc244d798123fde783fcc1c72d3bb8c1894130000000000000000000000000000000000000000000000000de0b6b3a7640000000000000000000000000000000000000000000000000000000000000000006000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000","to":"0x8f9c2b5c291a43465bfc14ec430575f69fe9becd","value":"0x0"},"blockHash":"0x0181f86b1d87c613cd14d03eb908eea2ee33b1800632f0293c3402539ca9b16d","blockNumber":1431090,"result":{"gasUsed":"0x1473a","output":"0x0000000000000000000000000000000000000000000000000000000000000000"},"subtraces":1,"traceAddress":[],"transactionHash":"0xc95d72edac6a17ad37d851ee767403969acec8c001fd3e3a00625e731aa39ecd","transactionPosition":2,"type":"call"},{"action":{"callType":"call","from":"0x8f9c2b5c291a43465bfc14ec430575f69fe9becd","gas":"0x1f4c3","input":"0x","to":"0xbb9bc244d798123fde783fcc1c72d3bb8c189413","value":"0xde0b6b3a7640000"},"blockHash":"0x0181f86b1d87c613cd14d03eb908eea2ee33b1800632f0293c3402539ca9b16d","blockNumber":1431090,"result":{"gasUsed":"0xcf63","output":"0x0000000000000000000000000000000000000000000000000000000000000001"},"subtraces":1,"traceAddress":[0],"transactionHash":"0xc95d72edac6a17ad37d851ee767403969acec8c001fd3e3a00625e731aa39ecd","transactionPosition":2,"type":"call"},{"action":{"callType":"call","from":"0xbb9bc244d798123fde783fcc1c72d3bb8c189413","gas":"0x16c83","input":"0x","to":"0x807640a13483f8ac783c557fcdf27be11ea4ac7a","value":"0x0"},"blockHash":"0x0181f86b1d87c613cd14d03eb908eea2ee33b1800632f0293c3402539ca9b16d","blockNumber":1431090,"result":{"gasUsed":"0x13f9","output":"0x"},"subtraces":0,"traceAddress":[0,0],"transactionHash":"0xc95d72edac6a17ad37d851ee767403969acec8c001fd3e3a00625e731aa39ecd","transactionPosition":2,"type":"call"}],"id":74}
```

**Comment by debris** [comment] 2016-12-09 11:40
@rphmeier not in last 3-4 months

**Comment by splix** [comment] 2016-12-18 09:39
I have same error, but just for some of the transactions. 
For example for transaction 0xe68cd5463eb4c030135a99a2375a02f198bbd4c3243877930667e819ed2b316f:
```
thread '<unnamed>' panicked at 'DecodeError: RlpIsTooShort, f90ec1f841f83ff780f594fbe26da0e985087d28228defbdaa394713b0865f94a9bb482ac8ceae9dea58eb3fda24ca786d3c62b2871ad60eeedfaf00808001c480c2808080c0f844f842f83980f794c092825321c03c9928f7c9c4590aa0c6e068012c940a0940b6b833e5cade72aba776c7bc5459b0e39e89be48692f6b4116ee00808001c480c2808080c0f88ff846f83b80f838949892842c988e4df55fbcf18642dbe5bf1d36f9fe94bfc39b6f805a9e40e77291aff27aee3c96915bdd88334eadf6e303e800824a388001c680c4821fc28001c0f845f83b80f83894bfc39b6f805a9e40e77291aff27aee3c96915bdd94c0d332838f14ef42fcde1cf2518c427ddb67672988334eadf6e303e8008208fc8001c480c2808080c180f88ff846f83b80f83894a28b98dce3a9073a117b9381d72d5986969b126494bfc39b6f805a9e40e77291aff27aee3c96915bdd8810a86439c6797800824a388001c680c4821fc28001c0f845f83b80f83894bfc39b6f805a9e40e77291aff27aee3c96915bdd94c0d332838f14ef42fcde1cf2518c427ddb6767298810a86439c67978008208fc8001c480c2808080c180f891f847f83c80f839947271419d1c4240087171538dfc97c24b55aeccaa94bfc39b6f805a9e40e77291aff27aee3c96915bdd89030924dc7deace4800824a388001c680c4821fc28001c0f846f83c80f83994bfc39b6f805a9e40e77291aff27aee3c96915bdd94c0d332838f14ef42fcde1cf2518c427ddb67672989030924dc7deace48008208fc8001c480c2808080c180f848f846f83d80f83a94c0d332838f14ef42fcde1cf2518c427ddb67672994c3128a6b538812f9858d57748fc4f4b6c1e788e88902b5c0282441c700008304c40d8001c480c2808080c0f88ff846f83b80f83894cead16227592da269698e438c45b5fde5299305d94bfc39b6f805a9e40e77291aff27aee3c96915bdd8825e556fc23a77c00824a388001c680c4821fc28001c0f845f83b80f83894bfc39b6f805a9e40e77291aff27aee3c96915bdd94c0d332838f14ef42fcde1cf2518c427ddb6767298825e556fc23a77c008208fc8001c480c2808080c180f88ff846f83b80f838942f7535d6374284a1f1bf74b8d2e8ba0dcbe7b2f394bfc39b6f805a9e40e77291aff27aee3c96915bdd880f7e81083bf38c00824a388001c680c4821fc28001c0f845f83b80f83894bfc39b6f805a9e40e77291aff27aee3c96915bdd94c0d332838f14ef42fcde1cf2518c427ddb676729880f7e81083bf38c008208fc8001c480c2808080c180f88ff846f83b80f838942e87912e31f4ca2bc454b229691e604f567486df94bfc39b6f805a9e40e77291aff27aee3c96915bdd8820259a9ec1dd3c00824a388001c680c4821fc28001c0f845f83b80f83894bfc39b6f805a9e40e77291aff27aee3c96915bdd94c0d332838f14ef42fcde1cf2518c427ddb6767298820259a9ec1dd3c008208fc8001c480c2808080c180f891f847f83c80f839947ebc1560005e7d7be57fefb9db88af9f7f982a2994bfc39b6f805a9e40e77291aff27aee3c96915bdd8902f3c5f6d1cd446400824a388001c680c4821fc28001c0f846f83c80f83994bfc39b6f805a9e40e77291aff27aee3c96915bdd94c0d332838f14ef42fcde1cf2518c427ddb6767298902f3c5f6d1cd4464008208fc8001c480c2808080c180f88ff846f83b80f83894dab475b9365e3bc16ec045ab65af47950b8b785f94bfc39b6f805a9e40e77291aff27aee3c96915bdd882422f6a44702c000824a388001c680c4821fc28001c0f845f83b80f83894bfc39b6f805a9e40e77291aff27aee3c96915bdd94c0d332838f14ef42fcde1cf2518c427ddb676729882422f6a44702c0008208fc8001c480c2808080c180f88ff846f83b80f83894d4d3301f0bce322f3212fbb3069e5312f70f0d3794bfc39b6f805a9e40e77291aff27aee3c96915bdd883cb531eb5c8b1800824a388001c680c4821fc28001c0f845f83b80f83894bfc39b6f805a9e40e77291aff27aee3c96915bdd94c0d332838f14ef42fcde1cf2518c427ddb676729883cb531eb5c8b18008208fc8001c480c2808080c180f891f847f83c80f839940a0940b6b833e5cade72aba776c7bc5459b0e39e94bfc39b6f805a9e40e77291aff27aee3c96915bdd894348de76bfbe0eb000824a388001c680c4821fc28001c0f846f83c80f83994bfc39b6f805a9e40e77291aff27aee3c96915bdd94c0d332838f14ef42fcde1cf2518c427ddb676729894348de76bfbe0eb0008208fc8001c480c2808080c180f88ff846f83b80f838949decf6360a3614d83ef70401f4b8f73be024cc1194bfc39b6f805a9e40e77291aff27aee3c96915bdd8819f96f6c0c242c00824a388001c680c4821fc28001c0f845f83b80f83894bfc39b6f805a9e40e77291aff27aee3c96915bdd94c0d332838f14ef42fcde1cf2518c427ddb6767298819f96f6c0c242c008208fc8001c480c2808080c180f88ff846f83b80f83894f9e1d999efb5258c9f5a307dbb6c0596e1cb893394bfc39b6f805a9e40e77291aff27aee3c96915bdd885cd2e0d486ed6000824a388001c680c4821fc28001c0f845f83b80f83894bfc39b6f805a9e40e77291aff27aee3c96915bdd94c0d332838f14ef42fcde1cf2518c427ddb676729885cd2e0d486ed60008208fc8001c480c2808080c180f88ff846f83b80f838945924fa3b7c1b8b739e932939c631881ee4faeaf494bfc39b6f805a9e40e77291aff27aee3c96915bdd888ac40835d6d64800824a388001c680c4821fc28001c0f845f83b80f83894bfc39b6f805a9e40e77291aff27aee3c96915bdd94c0d332838f14ef42fcde1cf2518c427ddb676729888ac40835d6d648008208fc8001c480c2808080c180f88ff846f83b80f83894b6445f76243e2b9d19f963484ed182a20ef3abea94bfc39b6f805a9e40e77291aff27aee3c96915bdd88102b96c6fd229c00824a388001c680c4821fc28001c0f845f83b80f83894bfc39b6f805a9e40e77291aff27aee3c96915bdd94c0d332838f14ef42fcde1cf2518c427ddb67672988102b96c6fd229c008208fc8001c480c2808080c180f88ff846f83b80f83894bb069339b46bce1a464ce264781ea2b240ea24d594bfc39b6f805a9e40e77291aff27aee3c96915bdd88190927b660ca5c00824a388001c680c4821fc28001c0f845f83b80f83894bfc39b6f805a9e40e77291aff27aee3c96915bdd94c0d332838f14ef42fcde1cf2518c427ddb67672988190927b660ca5c008208fc8001c480c2808080c180f88ff846f83b80f8389408c46c2e15844956dda674cd0cf60af1409d7db094bfc39b6f805a9e40e77291aff27aee3c96915bdd88152d8f4f6a797800824a388001c680c4821fc28001c0f845f83b80f83894bfc39b6f805a9e40e77291aff27aee3c96915bdd94c0d332838f14ef42fcde1cf2518c427ddb67672988152d8f4f6a7978008208fc8001c480c2808080c180f847f845f83c80f839940608492b4172e822994064f885aeff489361a68494ff903b35d9e2fd1b2c091eaf08b7a5f24a60e3bf880dced4beb1e76c8083010d888001c480c2808080c0f8a6f8a4f87980f8769435a91fea24ccb8e641d24fe909028850c71cc54894e0b7927c4af23765cb51314a0e0521a9645f0e2a808301f58db844a9059cbb00000000000000000000000002bf4d673cba0dcf2cb54d576070f4d6d696b52200000000000000000000000000000000000000000000000000000004b06f9dca01e680e4826eeda0000000000000000000000000000000000000000000000000000000000000000180c0f847f845f83c80f83994026d9acb43f44b258ebcfae786f32ae8376f6f00949fd3a2d403e9392159b53e78f0b7546a7b58e11488018e61c950a2ac0083010d888001c480c2808080c0f885f883f85880f85594f4d7dfcb1dcef5494f8cea07330b7c3c9b1245f7949b35f7bf4d3fb2910ba5faf4edc8c02169f50919808302b1a8a4797af62780c7288eb4ee8df9a9f4650b592b8a0d5cf8d9354e3b1b5db388acb0d5ac1b6501e680e48203bca0000000000000000000000000000000000000000000000000000000000000000080c0f8a6f8a4f87980f876943599493ce65772cf93e98af1195ec0955dc9800294bb9bc244d798123fde783fcc1c72d3bb8c189413808301dd70b844095ea7b3000000000000000000000000bf4ed7b27f1d666546e30d74d50d173d20bca754000000000000000000000000000000000000000000000034dad7d63a85dc000001e680e48256d0a0000000000000000000000000000000000000000000000000000000000000000180c0f8c5f88cf83e80f83b945ce174e21ec9e29af1132c606f41305e2905f1db9427773f458cc4cb0ad812b2177f5c6f67ee0ca3878083037be08a9fa6a6e3302e3433383501f84880f8458202acb8400000000000000000000000000000000000000000000000000000000000000020000000000000000000000000000000000000000000000000000000000000000001c0f6f080ee9427773f458cc4cb0ad812b2177f5c6f67ee0ca38794000000000000000000000000000000000000000480038001c10280c180f847f845f83c80f83994b4429d1f0cd14c59a3bd5fccab765fa26f940f0f949f476535dc0af66456498889ca84906c9cabd0e388cbaf3b123480280083010d888001c480c2808080c0f84cf84af83f80f83c945ce174e21ec9e29af1132c606f41305e2905f1db9441ecb3249276f0b57a9af5b83aa6f0053cb611308083037b9c8b8b14724531332e3833363101c680c48214a28080c0f8c1f8bff8b980f8b694d05243e425bc786f266c84429697e41240890f049459c651bf22ef0504f6c88dc266aab365fee7ae6480831e2368b8847ec0f30d0000000000000000000000000000000000000000000000000000000000000020000000000000000000000000000000000000000000000000000000000000002e516d507132513763516d6771714c4e39766e557177794c46434e6663546f5a65654835426b47746975704e6b6b4200000000000000000000000000000000000001c10280c0f84cf84af83f80f83c945ce174e21ec9e29af1132c606f41305e2905f1db942e648b5c0beae84c26520efffa8a74b223a626098083037b9c8b8b1472453635342e30393701c680c48214a28080c0', util/rlp/src/rlpin.rs:120
stack backtrace:
   1:        0x1013854d8 - std::sys::backtrace::tracing::imp::write::h6f1d53a70916b90d
   2:        0x10138b88f - std::panicking::default_hook::{{closure}}::h137e876f7d3b5850
   3:        0x10138a295 - std::panicking::default_hook::h0ac3811ec7cee78c
   4:        0x10138a8a6 - std::panicking::rust_panic_with_hook::hc303199e04562edf
   5:        0x10138a744 - std::panicking::begin_panic::h6ed03353807cf54d
   6:        0x10138a662 - std::panicking::begin_panic_fmt::hc321cece241bb2f5
   7:        0x100e1a4bc - <ethcore::trace::db::TraceDB<T>>::traces::h955bd037f820680f
   8:        0x100e06a18 - <ethcore::client::client::Client as ethcore::client::traits::BlockChainClient>::transaction_traces::h8e64c61021a5066a
   9:        0x1007f286f - <ethcore_rpc::v1::impls::traces::TracesClient<C, M> as ethcore_rpc::v1::traits::traces::Traces>::transaction_traces::hc1292f141debd3f4
  10:        0x1007aaadc - <jsonrpc_core::io::DelegateMethod<T, F> as jsonrpc_core::commander::MethodCommand>::execute::h542a9682a0d86097
  11:        0x100fcfbde - <jsonrpc_core::io::IoHandler as jsonrpc_core::io::GenericIoHandler>::handle::he9a0d08e37d231f2
  12:        0x100fb1e50 - <hyper::server::message::Message<H, T> as hyper::http::conn::MessageHandler<T>>::on_decode::ha6b721b3726472fb
  13:        0x100fc858d - <hyper::http::conn::ConnInner<K, T, H>>::read::haa8491cee492fd59
  14:        0x100fc86ee - <hyper::http::conn::ConnInner<K, T, H>>::read::haa8491cee492fd59
  15:        0x100fc95a1 - <hyper::http::conn::ConnInner<K, T, H>>::read::haa8491cee492fd59
  16:        0x100fc4a94 - <hyper::http::conn::Conn<K, T, H>>::ready::h3349e73e6241d4ef
  17:        0x100fc1215 - <mio::deprecated::event_loop::EventLoop<H>>::io_process::ha73143c976f64ba0
  18:        0x100fb9172 - drop::h4a83cec586b1c731
  19:        0x100fb5f6d - std::panicking::try::do_call::hf56ce52ce2d9fecb
```

For most of transactions all works fine, but for some of them, like this one, it crashes. For example crashing for TheDAO Hack transaction 0x8471497131d77305416c760ebfed2b6d653c2066c51dac58c6551dcc7dfb3350

I'm using Parity/v1.5.0-unstable-3450538-20161216/x86_64-macos/rustc1.13.0 (fresh build from master [3450538])
State DB configuration: archive +Trace

Previously, with Parity 1.3.x all of this transactions were working without any issue.

**Comment by bokkypoobah** [comment] 2017-03-12 04:19
I just retested a fresh version of Parity (v1.7.0-unstable-3fe3353-20170311) using:

    curl -s -X POST -H "Content-Type: application/json" --data '{"jsonrpc":"2.0","method":"trace_transaction","params":["0xc95d72edac6a17ad37d851ee767403969acec8c001fd3e3a00625e731aa39ecd"],"id":74}' 127.0.0.1:8545

And I got the same error as follows:

    Iota:chains bok$ parity 
    2017-03-12 15:16:53  Starting Parity/v1.7.0-unstable-3fe3353-20170311/x86_64-macos/rustc1.15.1
    2017-03-12 15:16:53  State DB configuration: fast
    2017-03-12 15:16:53  Operating mode: active
    2017-03-12 15:16:53  Configured for Foundation using Ethash engine
    2017-03-12 15:16:54  Updated conversion rate to Ξ1 = US$21.64 (5501276000 wei/gas)
    2017-03-12 15:16:57  Public node URL: enode://d58e9d252f41f594617b389aeffffa6ad7933aefcdc98252a00f63624c13ae48e6b5ab9de66b71f361e34ca68dd5b19658e03b558884440fe453dd968ec52ba9@192.168.1.11:30303
    thread '<unnamed>' panicked at 'DecodeError: RlpIsTooShort, f90241f840f83ef83880f69479e56155e36e0ed205abf8b28074717cce8d9a3694d73026b0494d25427f3d1a7743babe1bddf8a035880d61997f05fb6280808001c10280c0f847f845f83c80f839944bb96091ee9d802ed039c4d1a5f6216f90f81b0194bacb710a72801f00615ff65ae1910478fb52ccf58846d8f867422ca80083010d888001c480c2808080c0f901b3f90105f8d980f8d694b5806ee8211626592310e0782933a626c78279fe948f9c2b5c291a43465bfc14ec430575f69fe9becd808302cddab8a4b61d27f6000000000000000000000000bb9bc244d798123fde783fcc1c72d3bb8c1894130000000000000000000000000000000000000000000000000de0b6b3a764000000000000000000000000000000000000000000000000000000000000000000600000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000001e780e58301473aa0000000000000000000000000000000000000000000000000000000000000000001c0f868f83c80f839948f9c2b5c291a43465bfc14ec430575f69fe9becd94bb9bc244d798123fde783fcc1c72d3bb8c189413880de0b6b3a76400008301f4c38001e680e482cf63a0000000000000000000000000000000000000000000000000000000000000000101c180f83ff380f194bb9bc244d798123fde783fcc1c72d3bb8c18941394807640a13483f8ac783c557fcdf27be11ea4ac7a8083016c838001c680c48213f98080c28080', /Users/bok/.cargo/git/checkouts/parity-6ba620efeffb2216/3fe3353/util/rlp/src/rlpin.rs:120
    stack backtrace:
       1:        0x10b83db5a - std::sys::imp::backtrace::tracing::imp::write::hd3b65cdfe843284c
       2:        0x10b84352f - std::panicking::default_hook::{{closure}}::hf2b7428652613d83
       3:        0x10b8431d7 - std::panicking::default_hook::h5da8f27db5582938
       4:        0x10b8439f6 - std::panicking::rust_panic_with_hook::hcef1e67c646c6802
       5:        0x10b843894 - std::panicking::begin_panic::hc2e8ca89533cd10d
       6:        0x10b8437b2 - std::panicking::begin_panic_fmt::h60990696c3c3a88d
       7:        0x10b300953 - <ethcore::trace::db::TraceDB<T>>::traces::h5ff8770b6fee27fe
       8:        0x10b2e5a22 - <ethcore::client::client::Client as ethcore::client::traits::BlockChainClient>::transaction_traces::h85f8122da27426bd
       9:        0x10abe83d9 - <ethcore_rpc::v1::impls::traces::TracesClient<C, M> as ethcore_rpc::v1::traits::traces::Traces>::transaction_traces::hca9c9778dad533be
      10:        0x10abd361c - <jsonrpc_macros::delegates::DelegateMethod<T, F> as jsonrpc_core::calls::RpcMethod<M>>::call::hebde1883d87da752
      11:        0x10ad1f5f8 - <jsonrpc_core::io::MetaIoHandler<T, S>>::handle_call::he64afe21b30bba65
      12:        0x10ad1fd79 - <jsonrpc_core::io::MetaIoHandler<T, S>>::handle_request::h36bbc6b975971d04
      13:        0x10ac04620 - <jsonrpc_http_server::handler::ServerHandler<M, S> as hyper::server::Handler<hyper::net::HttpStream>>::on_request_readable::h8c3805f63424ce25
      14:        0x10ad3e0cf - <hyper::http::conn::ConnInner<K, T, H>>::read::h79bbe6060dc1461d
      15:        0x10ad3e22d - <hyper::http::conn::ConnInner<K, T, H>>::read::h79bbe6060dc1461d
      16:        0x10ad3f67e - <hyper::http::conn::ConnInner<K, T, H>>::read::h79bbe6060dc1461d
      17:        0x10ad2530b - <hyper::http::conn::Conn<K, T, H>>::ready::hf37da3b551697a63
      18:        0x10ad11bd2 - <mio::deprecated::event_loop::EventLoop<H>>::io_process::h0f5c5c212e665927
      19:        0x10ace5ee2 - drop::h71e5c465be2a2c63
      20:        0x10ac54d3d - std::panicking::try::do_call::h868e91a29dfd315a
    Abort trap: 6

**Comment by tomusdrw** [comment] 2017-03-16 13:25
@bokkypoobah Was it after a freshly synced parity? Or did you use old database?

**Comment by bokkypoobah** [comment] 2017-03-16 13:28
Old database + update sync. Not a full fresh sync.

**Comment by bokkypoobah** [comment] 2017-03-25 23:29
2017-03-26 10:25:17  Starting Parity/v1.6.4-beta-1164193-20170322/x86_64-macos/rustc1.16.0
    ...
    thread '<unnamed>' panicked at 'DecodeError: RlpIsTooShort, f90241f840f83ef83880f69479e56155e36e0ed205abf8b28074717cce8d9a3694d73026b0494d25427f3d1a7743babe1bddf8a035880d61997f05fb6280808001c10280c0f847f845f83c80f839944bb96091ee9d802ed039c4d1a5f6216f90f81b0194bacb710a72801f00615ff65ae1910478fb52ccf58846d8f867422ca80083010d888001c480c2808080c0f901b3f90105f8d980f8d694b5806ee8211626592310e0782933a626c78279fe948f9c2b5c291a43465bfc14ec430575f69fe9becd808302cddab8a4b61d27f6000000000000000000000000bb9bc244d798123fde783fcc1c72d3bb8c1894130000000000000000000000000000000000000000000000000de0b6b3a764000000000000000000000000000000000000000000000000000000000000000000600000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000001e780e58301473aa0000000000000000000000000000000000000000000000000000000000000000001c0f868f83c80f839948f9c2b5c291a43465bfc14ec430575f69fe9becd94bb9bc244d798123fde783fcc1c72d3bb8c189413880de0b6b3a76400008301f4c38001e680e482cf63a0000000000000000000000000000000000000000000000000000000000000000101c180f83ff380f194bb9bc244d798123fde783fcc1c72d3bb8c18941394807640a13483f8ac783c557fcdf27be11ea4ac7a8083016c838001c680c48213f98080c28080', util/rlp/src/rlpin.rs:120
    stack backtrace:
       1:        0x105f29ffc - std::sys::imp::backtrace::tracing::imp::write::h21ca2762819c7ae8
       2:        0x105f2fade - std::panicking::default_hook::{{closure}}::h38f99a37d00bb19b
       3:        0x105f2f780 - std::panicking::default_hook::ha2186ee24b50729c
       4:        0x105f2ff97 - std::panicking::rust_panic_with_hook::h979db19ee91d2a53
       5:        0x105f2fe44 - std::panicking::begin_panic::h6a69f5b54391c64d
       6:        0x105f2fd62 - std::panicking::begin_panic_fmt::h9de2343580b3c2c4
       7:        0x1059fdaad - <ethcore::trace::db::TraceDB<T>>::traces::hcfa84ad87e7ed47d
       8:        0x1059e79a2 - <ethcore::client::client::Client as ethcore::client::traits::BlockChainClient>::transaction_traces::hd0b0ad19f8a8e357
       9:        0x1053092b9 - <ethcore_rpc::v1::impls::traces::TracesClient<C, M> as ethcore_rpc::v1::traits::traces::Traces>::transaction_traces::heb30edea85e0dd2f
      10:        0x1052da22c - <jsonrpc_macros::delegates::DelegateMethod<T, F> as jsonrpc_core::calls::RpcMethod<M>>::call::h6256a2764c592d14
      11:        0x105440df0 - <jsonrpc_core::io::MetaIoHandler<T, S>>::handle_call::hf0846c39dfd26c6a
      12:        0x105441589 - <jsonrpc_core::io::MetaIoHandler<T, S>>::handle_request::h4b356c31e76e5c50
      13:        0x105324b7d - <jsonrpc_http_server::handler::ServerHandler<M, S> as hyper::server::Handler<hyper::net::HttpStream>>::on_request_readable::h9a2ce29ac5f566e4
      14:        0x10545f702 - <hyper::http::conn::ConnInner<K, T, H>>::read::h23ccb0ce065cd78f
      15:        0x1054610be - <hyper::http::conn::ConnInner<K, T, H>>::read::h23ccb0ce065cd78f
      16:        0x105460b67 - <hyper::http::conn::ConnInner<K, T, H>>::read::h23ccb0ce065cd78f
      17:        0x105444e68 - <hyper::http::conn::Conn<K, T, H>>::ready::h374f78064d97f38e
      18:        0x105436b42 - <mio::deprecated::event_loop::EventLoop<H>>::run_once::h1a8b4de53cbc649f
      19:        0x1053fa0bb - drop::h4ec26ea726038c0e
      20:        0x10537305d - std::panicking::try::do_call::h27864fa88c03278f

**Comment by 5chdn** [comment] 2017-03-30 10:14
@bokkypoobah I'm doing a full sync +fatb +tracing now and try to reproduce this.

while digging through the old similar issues (e.g., #1704), it was suggested to remove and reimport the database. How old is your db? Does it still happen if you resync or reimport the chain with the current version?

    parity export blocks ./blocks.db
    rm -rf ~/.local/share/io.parity.ethereum/chains/ethereum/db/906a34e69aec8c0d/
    parity import ./blocks.db --tracing on

**Comment by bokkypoobah** [comment] 2017-04-01 10:42
@5chdn, I exported and imported as you suggested and Parity stopped crashing when issued with the same RPC command:

> Iota:chains bok$ curl -s -X POST -H "Content-Type: application/json" --data '{"jsonrpc":"2.0","method":"trace_transaction","params":["0xc95d72edac6a17ad37d851ee767403969acec8c001fd3e3a00625e731aa39ecd"],"id":74}' 127.0.0.1:8545
> {"jsonrpc":"2.0","result":[{"action":{"callType":"call","from":"0xb5806ee8211626592310e0782933a626c78279fe","gas":"0x2cdda","input":"0xb61d27f6000000000000000000000000bb9bc244d798123fde783fcc1c72d3bb8c1894130000000000000000000000000000000000000000000000000de0b6b3a7640000000000000000000000000000000000000000000000000000000000000000006000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000","to":"0x8f9c2b5c291a43465bfc14ec430575f69fe9becd","value":"0x0"},"blockHash":"0x0181f86b1d87c613cd14d03eb908eea2ee33b1800632f0293c3402539ca9b16d","blockNumber":1431090,"result":{"gasUsed":"0x1473a","output":"0x0000000000000000000000000000000000000000000000000000000000000000"},"subtraces":1,"traceAddress":[],"transactionHash":"0xc95d72edac6a17ad37d851ee767403969acec8c001fd3e3a00625e731aa39ecd","transactionPosition":2,"type":"call"},{"action":{"callType":"call","from":"0x8f9c2b5c291a43465bfc14ec430575f69fe9becd","gas":"0x1f4c3","input":"0x","to":"0xbb9bc244d798123fde783fcc1c72d3bb8c189413","value":"0xde0b6b3a7640000"},"blockHash":"0x0181f86b1d87c613cd14d03eb908eea2ee33b1800632f0293c3402539ca9b16d","blockNumber":1431090,"result":{"gasUsed":"0xcf63","output":"0x0000000000000000000000000000000000000000000000000000000000000001"},"subtraces":1,"traceAddress":[0],"transactionHash":"0xc95d72edac6a17ad37d851ee767403969acec8c001fd3e3a00625e731aa39ecd","transactionPosition":2,"type":"call"},{"action":{"callType":"call","from":"0xbb9bc244d798123fde783fcc1c72d3bb8c189413","gas":"0x16c83","input":"0x","to":"0x807640a13483f8ac783c557fcdf27be11ea4ac7a","value":"0x0"},"blockHash":"0x0181f86b1d87c613cd14d03eb908eea2ee33b1800632f0293c3402539ca9b16d","blockNumber":1431090,"result":{"gasUsed":"0x13f9","output":"0x"},"subtraces":0,"traceAddress":[0,0],"transactionHash":"0xc95d72edac6a17ad37d851ee767403969acec8c001fd3e3a00625e731aa39ecd","transactionPosition":2,"type":"call"}],"id":74}

Thanks! Happy for this issue to be closed.

**Comment by 5chdn** [comment] 2017-04-03 08:40
Glad this works. I know re-syncing the full chain takes weeks. 

Closing as dupe of #1704, exporting/importing as per [this comment https://github.com/paritytech/parity/issues/1704#issuecomment-235224503] helps fixing the tracedb.

**Closed by 5chdn** 2017-04-03 08:40 UTC
Labels: F1-panic, M4-core
