### ISSUE TITLE
Parity failed to start due to checksum issue

### ISSUE THREAD

**Issue by dinganc** [paritytech/parity#7591] opened 2018-01-16 21:44 UTC
_Before filing a new issue, please **provide the following information**._

> I'm running:
>
> - **Which Parity version?**: 1.8.6
> - **Which operating system?**: Windows
> - **How installed?**: via installer
> - **Are you fully synchronized?**: yes
> - **Which network are you connected to?**: ethereum 
> - **Did you try to restart the node?**: yes

_Your issue description goes here below. Try to include **actual** vs. **expected behavior** and **steps to reproduce** the issue._

actual:
stack backtrace:
   0:        0x140a172f2 - hid_error
   1:        0x140a177d3 - hid_error
   2:        0x14007e674 - <no info>
   3:        0x140b5ebc4 - hid_error
   4:        0x140b5ea39 - hid_error
   5:        0x140b5e912 - hid_error
   6:        0x140b5e880 - hid_error
   7:        0x140b67e5f - hid_error
   8:        0x1403fa1e1 - <no info>
   9:        0x1405c8f64 - <no info>
  10:        0x1404bee3c - <no info>
  11:        0x14056bbe5 - <no info>
  12:        0x13ffd50c3 - <no info>
  13:        0x13ffef8d7 - <no info>
  14:        0x13fff523a - <no info>
  15:        0x13fff8787 - <no info>
  16:        0x140b60052 - hid_error
  17:        0x140b5f3c2 - hid_error
  18:        0x140ec2b79 - hid_write
  19:         0x773a652d - BaseThreadInitThunk

Thread 'main' panicked at 'failed to update version: "Corruption: block checksum
 mismatch: expected 1802156008, got 3756168298  in E:\\Parity\\Ethereum\\chains\
\ethereum\\db\\906a34e69aec8c0d\\overlayrecent\\db/597004.sst offset 5842674 siz
e 707237"', src\libcore\result.rs:906

This is a bug. Please report it at:

    https://github.com/paritytech/parity/issues/new

expected:
parity to run

steps to reproduce the issue:
execute ptray.exe or parity.exe

**Comment by dinganc** [comment] 2018-01-16 21:45
Checked hard drive, tried both HDD and SDD

**Comment by 5chdn** [comment] 2018-01-17 11:56
Duplicate of #7334

**Closed by 5chdn** 2018-01-17 11:56 UTC
