### ISSUE TITLE
Discovering Ledger Nano S

### ISSUE THREAD

**Issue by Samyoul** [paritytech/parity#4889] opened 2017-03-13 22:02 UTC
I'm attempting access my Ledger Nano S via the Parity UI. I am unable to discover how I can do this.

**Specs:**

```
Parity : Parity//v1.6.2-beta-8a27211-20170311/x86_64-windows-msvc/rustc1.15.1
Ledger Nano S : Firmware 1.3.1
Ledger Nano S : Ethereum Application 1.0.8
```

Could someone be so kind as to point me in the right direction. Thank you.

Additional information:
Browser mode is deactiveated

**Comment by jacogr** [comment] 2017-03-14 07:21
The steps should be -

1. Plug it in & unlock it (Browser mode should be deactivated)
2. Enter the Ethereum app on the device
3. It should be auto-detected and show up in your accounts list within 5 seconds (colourful icon while connected, gray icon while disconnected)
4. Now you should be able to transact with the account anywhere you can use an account (signer will ask you to sign on the device itself)

I just checked mine, both the firmware & Ethereum application versions matches with yours. (Settings -> About, which is the latest versions of both, firmware with the new long passcode.) I had some issues when I just received mine at the end of Feb with detection, the Firmware version needed to be upgraded, however since you are on latest already, that is not an issue here.

Only difference between our setups as you have indicated is the Operating System version.

**Comment by arkpar** [comment] 2017-03-14 08:26
@Samyoul What's your windows version?

**Comment by Samyoul** [comment] 2017-03-14 11:03
>@Samyoul What's your windows version?

```
Windows 7 Home Premium
Service Pack 1
64 bit
```

> 1. Plug it in & unlock it (Browser mode should be deactivated)
> 2. Enter the Ethereum app on the device
> 3. It should be auto-detected and show up in your accounts list within 5 seconds (colourful icon while connected, gray icon while disconnected)
> 4. Now you should be able to transact with the account anywhere you can use an account (signer will ask you to sign on the device itself)

I've followed these steps, repeatedly, the Ledger Nano S device is not being detected by Parity on my machine. A few things that may be of note:

- I am able to connect to the Ledger Ethereum Chrome App with the device.
- I am also able to connect to myetherwallet.com when I activate browser mode.
- Contract data mode is active.

**Comment by jacogr** [comment] 2017-03-14 11:50
Ok, I switched on my contract data and the device is not detected anymore. Once I toggle it to "No" again, it shows up as being detected.

Could you just toggle on your side as a check to see if it does get picked up with it off? (Just want to rule out any other possibilities there.)

**Comment by LogvinovLeon** [comment] 2017-03-14 19:26
I had the same probem and fixed it by updating both the Firmware and the ETH Ledger App to the newest version.

**Comment by sant9ga** [comment] 2017-03-14 19:40
Doesn't work for me.
Latest firmware on Nano S, Parity 1.6.3, browser mode and contract data both deactivated.
Accessing Parity via latest Ffox, windows 8.1.

**Comment by Samyoul** [comment] 2017-03-14 19:44
>Could you just toggle on your side as a check to see if it does get picked up with it off? (Just want to rule out any other possibilities there.)

I can confirm that this does not resolve the issue for me.

**Comment by arkpar** [comment] 2017-03-14 20:06
@Samyoul could do the following?
1. Exit Parity, MEW, and all Ledger apps.
2. Connect Ledger Nano and start ethereum app.
3. Open command prompt
4. Execute `"C:\Program Files\Ethcore\Parity\parity.exe" -l hardware_wallet=trace`, copy or screenshot the output and post it.

**Comment by Samyoul** [comment] 2017-03-14 20:34
Ok. Output is as below:

```
$ "C:\Program Files\Ethcore\Parity\parity.exe" -l hardware_wallet=trace
2017-03-14 20:20:08 UTC main INFO parity::run  Starting Parity/v1.6.2-beta-8a27211-20170311/x86_64-windows-msvc/rustc1.15.1
2017-03-14 20:20:08 UTC main INFO parity::run  State DB configuration: fast
2017-03-14 20:20:08 UTC main INFO parity::run  Operating mode: passive
2017-03-14 20:20:09 UTC hw_wallet TRACE hardware_wallet::ledger  Checking device: HidDeviceInfo { path: "\\\\?\\hid#vid_2c97&pid_0001#7&31d9c9ac&0&0000#{4d1e55b2-f16f-11cf-88cb-001111000030}", vendor_id: 11415, product_id: 1, serial_number: Some("0001"), release_number: 512, manufacturer_string: Some("Ledger"), product_string: Some("Nano S"), usage_page: 65440, usage: 1, interface_number: -1 }
2017-03-14 20:20:09 UTC hw_wallet TRACE hardware_wallet::ledger  writing [0, 1, 1, 5, 0, 0, 0, 5, 224, 6, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]
2017-03-14 20:20:09 UTC hw_wallet TRACE hardware_wallet::ledger  read [1, 1, 5, 0, 0, 0, 6, 0, 1, 0, 8, 144, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]
2017-03-14 20:20:09 UTC hw_wallet DEBUG hardware_wallet::ledger  Read status 9000
2017-03-14 20:20:09 UTC hw_wallet TRACE hardware_wallet::ledger  writing [0, 1, 1, 5, 0, 0, 0, 22, 224, 2, 0, 0, 17, 4, 128, 0, 0, 44, 128, 0, 0, 60, 128, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]
2017-03-14 20:20:09 UTC main INFO ethcore::service  Configured for Foundation using Ethash engine
2017-03-14 20:20:09 UTC hw_wallet TRACE hardware_wallet::ledger  read [1, 1, 5, 0, 0, 0, 109, 65, 4, 222, 156, 101, 98, 162, 212, 151, 26, 128, 138, 60, 200, 178, 184, 125, 154, 61, 131, 154, 42, 13, 134, 85, 158, 79, 44, 18, 52, 115, 128, 40, 129, 249, 119, 130, 44, 20, 151, 245, 102, 88, 69, 197, 203, 239, 65, 84, 230, 39, 153, 7, 121, 214, 230, 103, 0]
2017-03-14 20:20:09 UTC hw_wallet TRACE hardware_wallet::ledger  read [1, 1, 5, 0, 1, 207, 231, 134, 243, 141, 149, 193, 121, 53, 40, 50, 97, 67, 67, 57, 55, 56, 55, 48, 48, 101, 53, 55, 102, 51, 53, 99, 50, 99, 102, 51, 65, 53, 69, 99, 101, 99, 99, 50, 48, 57, 53, 65, 70, 100, 56, 53, 69, 55, 57, 144, 0, 0, 0, 0, 0, 0, 0, 0, 0]
2017-03-14 20:20:09 UTC hw_wallet DEBUG hardware_wallet::ledger  Read status 9000
2017-03-14 20:20:09 UTC hw_wallet DEBUG hardware_wallet::ledger  Found device: Device { path: "\\\\?\\hid#vid_2c97&pid_0001#7&31d9c9ac&0&0000#{4d1e55b2-f16f-11cf-88cb-001111000030}", info: WalletInfo { name: "Nano S", manufacturer: "Ledger", serial: "0001", address: 2acc978700e57f35c2cf3a5ececc2095afd85e79 } }
2017-03-14 20:20:09 UTC hyper-client INFO miner  Updated conversion rate to Ξ1 = US$28.63 (4158142200 wei/gas)
2017-03-14 20:20:19 UTC IO Worker #0 INFO import  Syncing #3350522 39b7…edd7     0 blk/s    0 tx/s   0 Mgas/s      0+    0 Qed  #3350522    0/ 8/25 peers   131 MiB db   73 KiB chain  0 bytes queue   10 KiB sync  RPC:  0 conn,  0 req/s, 288 µs
2017-03-14 20:20:19 UTC IO Worker #1 INFO network  Public node URL: enode://d38a1a12f96897ccda71b7261a99d3ac017618a7f6320689af046036bd9e08b7b16be22a605ec547fbfef79100ba2c8b3c79a654f3c603d35cf703d95aeab340@127.0.0.1:30303
2017-03-14 20:20:26 UTC IO Worker #0 INFO import  Syncing #3350523 a6de…0147     0 blk/s    2 tx/s   0 Mgas/s    191+  198 Qed  #3350920    5/ 8/25 peers   131 MiB db   76 KiB chain    3 MiB queue    3 MiB sync  RPC:  0 conn,  0 req/s, 350 µs
2017-03-14 20:20:34 UTC IO Worker #2 INFO import  Syncing #3350542 a261…3863     2 blk/s   20 tx/s   1 Mgas/s      0+ 1569 Qed  #3352112    0/ 9/25 peers   131 MiB db   93 KiB chain   19 MiB queue  435 KiB sync  RPC:  0 conn,  0 req/s, 350 µs
```

I can / could see from that output that Parity can see the device.

So I opened the UI , but it the device didn't show. I waited for about a minute and the device appeared in the account list. I wonder if the issue was caused by some kind of latency on my machine.

**Comment by jacogr** [comment] 2017-03-14 21:06
@sant9ga Just looked through everything, there is a case where if you have already watched the address or added it to your addressbook, it won't be pulled in since it sees it as already existing. If this is the case, just "forget" it in your addressbook and it should be created when detected. (UI may need a refresh)

Will address this case, which may be what some people face. (Not sure if it fixes your issue, but may be worth checking)

**Comment by Samyoul** [comment] 2017-03-14 21:26
> @sant9ga Just looked through everything, there is a case where if you have already watched the address or added it to your addressbook, it won't be pulled in since it sees it as already existing. If this is the case, just "forget" it in your addressbook and it should be created when detected. (UI may need a refresh)
> 
> Will address this case, which may be what some people face. (Not sure if it fixes your issue, but may be worth checking)

Hmmm, this could have been the reason for my issue. I was watching my main Ledger Nano S in the addressbook.

**Comment by jacogr** [comment] 2017-03-14 21:34
Something we missed, obvious in retrospect. Will be fixed. 

Doesn't really explain why the delay in showing up for you, however digging through the code looking for possibilities brought that one up.

**Comment by sant9ga** [comment] 2017-03-22 19:33
I've removed the watch address from the contacts and it appears!
2 questions:
1) how to send tokens if the "contract data" mode should be disabled? Some error appears when trying to send DGD.
2) when I've tried to send just ether it got an error about insufficient funds.

**Comment by 5chdn** [comment] 2017-04-03 09:35
@sant9ga could you add more details about what issues you are experiencing?

@jacogr can this be closed now?

**Comment by 5chdn** [comment] 2017-04-04 10:44
@jacogr check this. https://www.reddit.com/r/EtherMining/comments/6377ym/the_problem_with_accounts_paritymist/

The same issue appears if you watch an account before importing it from geth. Is this also covered by #4912 ?

**Comment by 5chdn** [comment] 2017-05-10 11:54
This issue is labelled with _annoyance_: The client behaves within expectations, however this "expected behaviour" itself is at issue. It's neither assigned nor linked to any milestone.

@paritytech/ui-devs Please decide on a deadline and add an assignee within 7 days, thanks!

**Comment by arkpar** [comment] 2017-05-10 12:01
@sant9ga "Contract mode" should be enabled to send tokens. Everything else has been addressed I believe

**Closed by arkpar** 2017-05-10 12:01 UTC
Labels: F3-annoyance, M7-ui
