### ISSUE TITLE
Parity light chain stops syncing randomly

### ISSUE THREAD

**Issue by AyushyaChitransh** [paritytech/parity#6904] opened 2017-10-26 11:14 UTC
> I'm running:
>
> - **Parity version**: Parity/v1.8.0-beta-9882902-20171015/x86_64-linux-gnu/rustc1.20.0
> - **Operating system**: Linux
> - **And installed**: via one line installer

**Expected behavior** 

After starting light chain, I leave the server as it is, I revisit the server after a couple of hours to see the chain has synced.

**Actual Behavior**

The chain syncing stops after certain time. Number of peers is 50/50. It says that it is syncing but there is no increase in the block number. I restart the node to begin syncing again.

**steps to reproduce**
I start light chain by `parity --light --unsafe-expose --force-ui --public-node`

---

**Comment by Office-Julia** [comment] 2017-10-28 11:28
Maybe duplicate of 
https://github.com/paritytech/parity/issues/6882

@rphmeier what do you think?

**Comment by 5chdn** [comment] 2017-10-29 07:54
#6319 actually :)

**Closed by 5chdn** 2017-10-29 07:54 UTC
Labels: Z0-duplicate
