### ISSUE TITLE
Thread 'main' panicked

### ISSUE THREAD

**Issue by pgconlin** [paritytech/parity#7465] opened 2018-01-05 00:28 UTC
_Before filing a new issue, please **provide the following information**._

> I'm running:
>
> - **Which Parity version?**: v1.9.0-unstable-75f2921-20180103/x86_64-linux-gnu/rustc1.22.1
> - **Which operating system?**: Fedora 25 Linux
> - **How installed?**: from source
> - **Are you fully synchronized?**: no
> - **Did you try to restart the node?**: yes

_Your issue description goes here below. Try to include **actual** vs. **expected behavior** and **steps to reproduce** the issue._

Was running fine, stopped parity to adjust --max-peers= setting from 64 to 48, relaunched and got the below results.

2018-01-04 16:24:36  main INFO parity::run  Starting Parity/v1.9.0-unstable-75f2921-20180103/x86_64-linux-gnu/rustc1.22.1
2018-01-04 16:24:36  main INFO parity::run  Keys path /home/pgconlin/snap/parity/7019/.local/share/io.parity.ethereum/keys/Foundation
2018-01-04 16:24:36  main INFO parity::run  DB path /home/pgconlin/snap/parity/7019/.local/share/io.parity.ethereum/chains/ethereum/db/906a34e69aec8c0d
2018-01-04 16:24:36  main INFO parity::run  Path to dapps /home/pgconlin/snap/parity/7019/.local/share/io.parity.ethereum/dapps
2018-01-04 16:24:36  main INFO parity::run  State DB configuration: fast
2018-01-04 16:24:36  main INFO parity::run  Operating mode: active
2018-01-04 16:24:36  main DEBUG miner  minimal_gas_price: recalibrating...
2018-01-04 16:24:36  main INFO ethcore::service  Configured for Foundation using Ethash engine
2018-01-04 16:24:36   INFO miner  Updated conversion rate to Ξ1 = US$941.68 (126420456 wei/gas)
2018-01-04 16:24:36   DEBUG miner  minimal_gas_price: Got gas price! 126420456

====================

stack backtrace:
   0:     0x55c74b19551c - backtrace::backtrace::trace::hb833bdf29723cea6
   1:     0x55c74b195552 - backtrace::capture::Backtrace::new::h00ba4a65e8473ae3
   2:     0x55c74a5b9cb8 - panic_hook::panic_hook::h5268918cdba10500
   3:     0x55c74b1e9956 - std::panicking::rust_panic_with_hook
                        at /checkout/src/libstd/panicking.rs:578
   4:     0x55c74b1e97e4 - std::panicking::begin_panic<alloc::string::String>
                        at /checkout/src/libstd/panicking.rs:538
   5:     0x55c74b1e96e9 - std::panicking::begin_panic_fmt
                        at /checkout/src/libstd/panicking.rs:522
   6:     0x55c74b1e967a - std::panicking::rust_begin_panic
                        at /checkout/src/libstd/panicking.rs:498
   7:     0x55c74b222dd0 - core::panicking::panic_fmt
                        at /checkout/src/libcore/panicking.rs:71
   8:     0x55c74b222d06 - core::panicking::panic
                        at /checkout/src/libcore/panicking.rs:51
   9:     0x55c74ab6d1e0 - ethcore::blockchain::blockchain::BlockChain::new::h1b7f3f48ef92665b
  10:     0x55c74a9f38d8 - ethcore::client::client::Client::new::h1c0e9bb9b283a24b
  11:     0x55c74aa9e06b - ethcore::service::ClientService::start::h9182f406a1e8740e
  12:     0x55c74a48fd5c - parity::run::execute::hbeb22f77879a7cc3
  13:     0x55c74a4aac86 - parity::execute::h7c090f7d05b01a36
  14:     0x55c74a4b0a01 - parity::main_direct::hb6780805db12f624
  15:     0x55c74a4b4055 - parity::main::hfe501176d4a5972d
  16:     0x55c74b1f033b - panic_abort::__rust_maybe_catch_panic
                        at /checkout/src/libpanic_abort/lib.rs:38

Thread 'main' panicked at 'called `Option::unwrap()` on a `None` value', /checkout/src/libcore/option.rs:335

This is a bug. Please report it at:

    https://github.com/paritytech/parity/issues/new

**Comment by pgconlin** [comment] 2018-01-05 00:52
Ah well, looks like this was a case of --fast-and-loose working as expected.  However, according to parity's standard ctrl-c exit statements it looked like there was not an unclean exit.  Oh well.

**Comment by 5chdn** [comment] 2018-01-05 09:39
Duplicate of #7340

Yes, using _fast and loose_ is not a good idea.

**Closed by 5chdn** 2018-01-05 09:39 UTC
