### ISSUE TITLE
Thread 'IO Worker #1' panicked at 'DB flush failed.: Error(Msg("Corruption: block checksum mismatch: expected 3328599191, got 751106850  in /home/james/.local/share/io.parity.ethereum/chains/ethereum/db/906a34e69aec8c0d/overlayrecent/db/310415.sst offset 36308894 size 13789"), State { next_error: None, backtrace: None })', /checkout/src/libcore/result.rs:916

### ISSUE THREAD

**Issue by jamesray1** [paritytech/parity#8094] opened 2018-03-12 23:17 UTC
> I'm running:
>
> - **Which Parity version?**: version Parity/v1.10.0-unstable-9fec2142a-20180227/x86_64-linux-gnu/rustc1.24.0
> - **Which operating system?**: Linux
> - **How installed?**: not sure, it may have been via rustup, snap or source.
> - **Are you fully synchronized?**: no
> - **Which network are you connected to?**: ethereum
> - **Did you try to restart the node?**: yes, as well as following the syncing tips [here](https://github.com/paritytech/wiki/pull/32/files).

CLI output extract:
```
2018-03-13 09:45:10  Syncing #3186486 7465…5471    35 blk/s  273 tx/s  10 Mgas/s      0+ 4654 Qed  #3191142   49/128 peers   5 MiB chain 256 MiB db 41 MiB queue 11 MiB sync  RPC:  0 conn,  0 req/s,   0 µs
2018-03-13 09:45:24  DB corrupted: Corruption: block checksum mismatch: expected 3328599191, got 751106850  in /home/james/.local/share/io.parity.ethereum/chains/ethereum/db/906a34e69aec8c0d/overlayrecent/db/310415.sst offset 36308894 size 13789. Repair will be triggered on next restart
2018-03-13 09:45:24  DB corrupted: Corruption: block checksum mismatch: expected 3328599191, got 751106850  in /home/james/.local/share/io.parity.ethereum/chains/ethereum/db/906a34e69aec8c0d/overlayrecent/db/310415.sst offset 36308894 size 13789. Repair will be triggered on next restart
2018-03-13 09:45:24  DB corrupted: Corruption: block checksum mismatch: expected 3328599191, got 751106850  in /home/james/.local/share/io.parity.ethereum/chains/ethereum/db/906a34e69aec8c0d/overlayrecent/db/310415.sst offset 36308894 size 13789. Repair will be triggered on next restart
2018-03-13 09:45:24  DB corrupted: Corruption: block checksum mismatch: expected 3328599191, got 751106850  in /home/james/.local/share/io.parity.ethereum/chains/ethereum/db/906a34e69aec8c0d/overlayrecent/db/310415.sst offset 36308894 size 13789. Repair will be triggered on next restart

====================

stack backtrace:
   0:     0x555b60c27acc - backtrace::backtrace::trace::h9b029d0fdbfd6263
   1:     0x555b60c27172 - backtrace::capture::Backtrace::new::hc989ad19f674032e
   2:     0x555b600a0315 - panic_hook::panic_hook::h4ded59abfceb318d

Thread 'IO Worker #1' panicked at 'DB flush failed.: Error(Msg("Corruption: block checksum mismatch: expected 3328599191, got 751106850  in /home/james/.local/share/io.parity.ethereum/chains/ethereum/db/906a34e69aec8c0d/overlayrecent/db/310415.sst offset 36308894 size 13789"), State { next_error: None, backtrace: None })', /checkout/src/libcore/result.rs:916

This is a bug. Please report it at:

    https://github.com/paritytech/parity/issues/new


====================

stack backtrace:
   0:   [1]    18137 abort (core dumped)  ./parity --port 30304 --peers 128
```

**Comment by debris** [comment] 2018-03-13 10:25
Thanks for the report! I believe this is a duplicate of #7766

**Closed by debris** 2018-03-13 10:25 UTC

**Comment by 5chdn** [comment] 2018-03-23 11:39
Duplicate of #7748
