### ISSUE TITLE
hardware_wallet::ledger  Error reading device info: Ledger protocol error: Unexpected chunk header

### ISSUE THREAD

**Issue by XelionIO** [paritytech/parity#6373] opened 2017-08-24 17:47 UTC
> I'm running:
>
> - **Parity version**: 1.6.10
> - **Operating system**: Windows 10 Entreprise LTSB
> - **Ledger Firmware**: 1.3.1
> - **Ethereum App**: 1.0.17
> - **Type**: via installer

My Ledger is not detected by Parity.
I've used ``parity.exe" -l hardware_wallet=trace`` and the output is : 

```bash
C:\Program Files\Ethcore\Parity>parity.exe -l hardware_wallet=trace
2017-08-24 19:44:14  main INFO parity::run  Starting Parity/v1.6.10-stable-1a5b176-20170721/x86_64-windows-msvc/rustc1.18.0
2017-08-24 19:44:14  main INFO parity::run  State DB configuration: fast
2017-08-24 19:44:14  main INFO parity::run  Operating mode: passive
2017-08-24 19:44:15  main INFO ethcore::service  Configured for Foundation using Ethash engine
2017-08-24 19:44:15  hw_wallet TRACE hardware_wallet::ledger  Checking device: HidDeviceInfo { path: "\\\\?\\hid#vid_046d&pid_c07d&mi_01&col05#7&266e634d&0&0004#{4d1e55b2-f16f-11cf-88cb-001111000030}", vendor_id: 1133, product_id: 49277, serial_number: Some("108735673335"), release_number: 34818, manufacturer_string: Some("Logitech"), product_string: Some("Gaming Mouse G502"), usage_page: 65280, usage: 2, interface_number: 1 }
2017-08-24 19:44:15  hw_wallet TRACE hardware_wallet::ledger  Checking device: HidDeviceInfo { path: "\\\\?\\hid#vid_04d9&pid_0201&mi_00#7&1b91a0ce&0&0000#{4d1e55b2-f16f-11cf-88cb-001111000030}", vendor_id: 1241, product_id: 513, serial_number: None, release_number: 257, manufacturer_string: None, product_string: Some("USB-HID Keyboard"), usage_page: 1, usage: 6, interface_number: 0 }
2017-08-24 19:44:15  hw_wallet TRACE hardware_wallet::ledger  Checking device: HidDeviceInfo { path: "\\\\?\\hid#vid_046d&pid_0a5c&mi_03&col01#7&12dc7c76&0&0000#{4d1e55b2-f16f-11cf-88cb-001111000030}", vendor_id: 1133, product_id: 2652, serial_number: Some("00000000"), release_number: 4097, manufacturer_string: Some("Logitech"), product_string: Some("Logitech G633 Gaming Headset"), usage_page: 12, usage: 1, interface_number: 3 }
2017-08-24 19:44:15  hw_wallet TRACE hardware_wallet::ledger  Checking device: HidDeviceInfo { path: "\\\\?\\hid#vid_046d&pid_0a5c&mi_03&col02#7&12dc7c76&0&0001#{4d1e55b2-f16f-11cf-88cb-001111000030}", vendor_id: 1133, product_id: 2652, serial_number: Some("00000000"), release_number: 4097, manufacturer_string: Some("Logitech"), product_string: Some("Logitech G633 Gaming Headset"), usage_page: 11, usage: 1, interface_number: 3 }
2017-08-24 19:44:15  hw_wallet TRACE hardware_wallet::ledger  Checking device: HidDeviceInfo { path: "\\\\?\\hid#vid_046d&pid_c232#2&33191fed&0&0000#{4d1e55b2-f16f-11cf-88cb-001111000030}", vendor_id: 1133, product_id: 49714, serial_number: None, release_number: 1, manufacturer_string: None, product_string: None, usage_page: 1, usage: 6, interface_number: -1 }
2017-08-24 19:44:15  hw_wallet TRACE hardware_wallet::ledger  Checking device: HidDeviceInfo { path: "\\\\?\\hid#vid_046d&pid_c231#2&1dd8bfaf&0&0000#{4d1e55b2-f16f-11cf-88cb-001111000030}", vendor_id: 1133, product_id: 49713, serial_number: None, release_number: 1, manufacturer_string: None, product_string: None, usage_page: 1, usage: 2, interface_number: -1 }
2017-08-24 19:44:15  hw_wallet TRACE hardware_wallet::ledger  Checking device: HidDeviceInfo { path: "\\\\?\\hid#vid_04d9&pid_0201&mi_01#7&3ce1489&0&0000#{4d1e55b2-f16f-11cf-88cb-001111000030}", vendor_id: 1241, product_id: 513, serial_number: None, release_number: 257, manufacturer_string: None, product_string: Some("USB-HID Keyboard"), usage_page: 65280, usage: 1, interface_number: 1 }
2017-08-24 19:44:15  hw_wallet TRACE hardware_wallet::ledger  Checking device: HidDeviceInfo { path: "\\\\?\\hid#vid_046d&pid_0a5c&mi_03&col03#7&12dc7c76&0&0002#{4d1e55b2-f16f-11cf-88cb-001111000030}", vendor_id: 1133, product_id: 2652, serial_number: Some("00000000"), release_number: 4097, manufacturer_string: Some("Logitech"), product_string: Some("Logitech G633 Gaming Headset"), usage_page: 65347, usage: 514, interface_number: 3 }
2017-08-24 19:44:15  hw_wallet TRACE hardware_wallet::ledger  Checking device: HidDeviceInfo { path: "\\\\?\\hid#vid_04d9&pid_0201&mi_02&col01#7&27a5524b&0&0000#{4d1e55b2-f16f-11cf-88cb-001111000030}", vendor_id: 1241, product_id: 513, serial_number: None, release_number: 257, manufacturer_string: None, product_string: Some("USB-HID Keyboard"), usage_page: 1, usage: 128, interface_number: 2 }
2017-08-24 19:44:15  hw_wallet TRACE hardware_wallet::ledger  Checking device: HidDeviceInfo { path: "\\\\?\\hid#vid_04d9&pid_0201&mi_02&col02#7&27a5524b&0&0001#{4d1e55b2-f16f-11cf-88cb-001111000030}", vendor_id: 1241, product_id: 513, serial_number: None, release_number: 257, manufacturer_string: None, product_string: Some("USB-HID Keyboard"), usage_page: 12, usage: 1, interface_number: 2 }
2017-08-24 19:44:15  hw_wallet TRACE hardware_wallet::ledger  Checking device: HidDeviceInfo { path: "\\\\?\\hid#vid_046d&pid_c07d&mi_00#7&297258b&0&0000#{4d1e55b2-f16f-11cf-88cb-001111000030}", vendor_id: 1133, product_id: 49277, serial_number: Some("108735673335"), release_number: 34818, manufacturer_string: Some("Logitech"), product_string: Some("Gaming Mouse G502"), usage_page: 1, usage: 2, interface_number: 0 }
2017-08-24 19:44:15  hw_wallet TRACE hardware_wallet::ledger  Checking device: HidDeviceInfo { path: "\\\\?\\hid#vid_04d9&pid_0201&mi_02&col03#7&27a5524b&0&0002#{4d1e55b2-f16f-11cf-88cb-001111000030}", vendor_id: 1241, product_id: 513, serial_number: None, release_number: 257, manufacturer_string: None, product_string: Some("USB-HID Keyboard"), usage_page: 1, usage: 2, interface_number: 2 }
2017-08-24 19:44:15  hw_wallet TRACE hardware_wallet::ledger  Checking device: HidDeviceInfo { path: "\\\\?\\hid#vid_04d9&pid_0201&mi_02&col04#7&27a5524b&0&0003#{4d1e55b2-f16f-11cf-88cb-001111000030}", vendor_id: 1241, product_id: 513, serial_number: None, release_number: 257, manufacturer_string: None, product_string: Some("USB-HID Keyboard"), usage_page: 1, usage: 6, interface_number: 2 }
2017-08-24 19:44:15  hw_wallet TRACE hardware_wallet::ledger  Checking device: HidDeviceInfo { path: "\\\\?\\hid#vid_2c97&pid_0001#6&31d9c9ac&0&0000#{4d1e55b2-f16f-11cf-88cb-001111000030}", vendor_id: 11415, product_id: 1, serial_number: Some("0001"), release_number: 512, manufacturer_string: Some("Ledger"), product_string: Some("Nano S"), usage_page: 61904, usage: 1, interface_number: -1 }
2017-08-24 19:44:15  hw_wallet TRACE hardware_wallet::ledger  writing [0, 1, 1, 5, 0, 0, 0, 5, 224, 6, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]
2017-08-24 19:44:15  hw_wallet TRACE hardware_wallet::ledger  read [191, 0, 1, 141, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]
2017-08-24 19:44:15  hw_wallet DEBUG hardware_wallet::ledger  Error reading device info: Ledger protocol error: Unexpected chunk header
2017-08-24 19:44:15  hw_wallet TRACE hardware_wallet::ledger  Checking device: HidDeviceInfo { path: "\\\\?\\hid#vid_046d&pid_c07d&mi_01&col01#7&266e634d&0&0000#{4d1e55b2-f16f-11cf-88cb-001111000030}", vendor_id: 1133, product_id: 49277, serial_number: Some("108735673335"), release_number: 34818, manufacturer_string: Some("Logitech"), product_string: Some("Gaming Mouse G502"), usage_page: 1, usage: 6, interface_number: 1 }
2017-08-24 19:44:15  hw_wallet TRACE hardware_wallet::ledger  Checking device: HidDeviceInfo { path: "\\\\?\\hid#vid_046d&pid_c07d&mi_01&col02#7&266e634d&0&0001#{4d1e55b2-f16f-11cf-88cb-001111000030}", vendor_id: 1133, product_id: 49277, serial_number: Some("108735673335"), release_number: 34818, manufacturer_string: Some("Logitech"), product_string: Some("Gaming Mouse G502"), usage_page: 12, usage: 1, interface_number: 1 }
2017-08-24 19:44:15  hw_wallet TRACE hardware_wallet::ledger  Checking device: HidDeviceInfo { path: "\\\\?\\hid#vid_046d&pid_c07d&mi_01&col03#7&266e634d&0&0002#{4d1e55b2-f16f-11cf-88cb-001111000030}", vendor_id: 1133, product_id: 49277, serial_number: Some("108735673335"), release_number: 34818, manufacturer_string: Some("Logitech"), product_string: Some("Gaming Mouse G502"), usage_page: 1, usage: 128, interface_number: 1 }
2017-08-24 19:44:15  hw_wallet TRACE hardware_wallet::ledger  Checking device: HidDeviceInfo { path: "\\\\?\\hid#vid_046d&pid_c07d&mi_01&col04#7&266e634d&0&0003#{4d1e55b2-f16f-11cf-88cb-001111000030}", vendor_id: 1133, product_id: 49277, serial_number: Some("108735673335"), release_number: 34818, manufacturer_string: Some("Logitech"), product_string: Some("Gaming Mouse G502"), usage_page: 65280, usage: 1, interface_number: 1 }
2017-08-24 19:44:15  hw_wallet TRACE hardware_wallet::ledger  Checking device: HidDeviceInfo { path: "\\\\?\\hid#vid_0d8c&pid_0134&mi_02#7&25395a90&0&0000#{4d1e55b2-f16f-11cf-88cb-001111000030}", vendor_id: 3468, product_id: 308, serial_number: None, release_number: 256, manufacturer_string: Some("BIRD UM1"), product_string: Some("BIRD UM1"), usage_page: 12, usage: 1, interface_number: 2 }
2017-08-24 19:44:15  hyper-client INFO miner  Updated conversion rate to Ξ1 = US$322.4 (369254400 wei/gas)
Client service error: Client(Database("Error converting string"))
```

https://pastebin.com/J6Azek8W

**Comment by MicahZoltu** [comment] 2017-08-24 18:28
@XelionIO Make sure you have the Ethereum app open on the ledger and in settings within the Ledger ethereum app you have _disabled_ browser support.

**Comment by XelionIO** [comment] 2017-08-24 18:38
@MicahZoltu I've done that but same problem and same error.

**Comment by arkpar** [comment] 2017-08-25 14:23
@XelionIO Are you sure you have browser support disabled in Ethereum app settings? Try restarting the device after you've disabled it

**Comment by XelionIO** [comment] 2017-08-25 20:33
@arkpar I've upgraded Parity to 1.7.0-beta and disabled browser support in the Ethereum App. Even after complete reboot, same error :/

**Comment by folsen** [comment] 2017-08-30 09:50
I've had an issue with my Ledger that stemmed from a bug in the Ethereum app on the Ledger itself. What version of the Ethereum app on your device are you running (it's shown under About when you go into the app)?

**Comment by 5chdn** [comment] 2017-08-30 10:34
> What version of the Ethereum app on your device are you running (it's shown under About when you go into the app)?

From the first post:

- Ledger Firmware: 1.3.1
- Ethereum App: 1.0.17

**Comment by XelionIO** [comment] 2017-10-10 14:23
Quick update : 

I'm running : 
    Parity version: 1.7.1
    Operating system: Windows 10 Pro
    Ledger Firmware: 1.3.1
    Ethereum App: 1.0.18
    Type: via installer

Same error : 
`C:\Program Files\Parity\Parity>parity.exe -l hardware_wallet=trace
2017-10-10 16:21:58  main INFO parity::run  Starting Parity/v1.7.3-beta-d097956-20171009/x86_64-windows-msvc/rustc1.20.0
2017-10-10 16:21:58  main INFO parity::run  Keys path C:\Users\NKI-SYSADMIN\AppData\Roaming\Parity\Ethereum\keys\Foundation
2017-10-10 16:21:58  main INFO parity::run  DB path C:\Users\NKI-SYSADMIN\AppData\Local\Parity\Ethereum\chains\ethereum\db\906a34e69aec8c0d
2017-10-10 16:21:58  main INFO parity::run  Path to dapps C:\Users\NKI-SYSADMIN\AppData\Roaming\Parity\Ethereum\dapps
2017-10-10 16:21:58  main INFO parity::run  State DB configuration: fast
2017-10-10 16:21:58  main INFO parity::run  Operating mode: passive
2017-10-10 16:21:59  main INFO ethcore::service  Configured for Foundation using Ethash engine
2017-10-10 16:21:59  hw_wallet TRACE hardware_wallet::ledger  Checking device: HidDeviceInfo { path: "\\\\?\\hid#vid_03f0&pid_094a#6&42fcab3&0&0000#{4d1e55b2-f16f-11cf-88cb-001111000030}", vendor_id: 1008, product_id: 2378, serial_number: None, release_number: 256, manufacturer_string: Some("PixArt"), product_string: Some("HP USB Optical Mouse"), usage_page: 1, usage: 2, interface_number: -1 }
2017-10-10 16:21:59  hw_wallet TRACE hardware_wallet::ledger  Checking device: HidDeviceInfo { path: "\\\\?\\hid#vid_04d9&pid_a0cd&mi_01&col01#7&3a25fca4&0&0000#{4d1e55b2-f16f-11cf-88cb-001111000030}", vendor_id: 1241, product_id: 41165, serial_number: None, release_number: 261, manufacturer_string: None, product_string: Some("USB Keyboard"), usage_page: 1, usage: 6, interface_number: 1 }
2017-10-10 16:21:59  hw_wallet TRACE hardware_wallet::ledger  Checking device: HidDeviceInfo { path: "\\\\?\\hid#vid_04d9&pid_a0cd&mi_01&col02#7&3a25fca4&0&0001#{4d1e55b2-f16f-11cf-88cb-001111000030}", vendor_id: 1241, product_id: 41165, serial_number: None, release_number: 261, manufacturer_string: None, product_string: Some("USB Keyboard"), usage_page: 1, usage: 128, interface_number: 1 }
2017-10-10 16:21:59  hw_wallet TRACE hardware_wallet::ledger  Checking device: HidDeviceInfo { path: "\\\\?\\hid#vid_04d9&pid_a0cd&mi_00#7&11bb4edb&0&0000#{4d1e55b2-f16f-11cf-88cb-001111000030}", vendor_id: 1241, product_id: 41165, serial_number: None, release_number: 261, manufacturer_string: None, product_string: Some("USB Keyboard"), usage_page: 1, usage: 6, interface_number: 0 }
2017-10-10 16:21:59  hw_wallet TRACE hardware_wallet::ledger  Checking device: HidDeviceInfo { path: "\\\\?\\hid#vid_04d9&pid_a0cd&mi_01&col03#7&3a25fca4&0&0002#{4d1e55b2-f16f-11cf-88cb-001111000030}", vendor_id: 1241, product_id: 41165, serial_number: None, release_number: 261, manufacturer_string: None, product_string: Some("USB Keyboard"), usage_page: 12, usage: 1, interface_number: 1 }
2017-10-10 16:21:59  hw_wallet TRACE hardware_wallet::ledger  Checking device: HidDeviceInfo { path: "\\\\?\\hid#vid_04d9&pid_a0cd&mi_01&col04#7&3a25fca4&0&0003#{4d1e55b2-f16f-11cf-88cb-001111000030}", vendor_id: 1241, product_id: 41165, serial_number: None, release_number: 261, manufacturer_string: None, product_string: Some("USB Keyboard"), usage_page: 65280, usage: 1, interface_number: 1 }
2017-10-10 16:21:59  hw_wallet TRACE hardware_wallet::ledger  Checking device: HidDeviceInfo { path: "\\\\?\\hid#vid_04d9&pid_a0cd&mi_01&col05#7&3a25fca4&0&0004#{4d1e55b2-f16f-11cf-88cb-001111000030}", vendor_id: 1241, product_id: 41165, serial_number: None, release_number: 261, manufacturer_string: None, product_string: Some("USB Keyboard"), usage_page: 65281, usage: 1, interface_number: 1 }
2017-10-10 16:21:59  hw_wallet TRACE hardware_wallet::ledger  Checking device: HidDeviceInfo { path: "\\\\?\\hid#vid_2c97&pid_0001#7&31d9c9ac&0&0000#{4d1e55b2-f16f-11cf-88cb-001111000030}", vendor_id: 11415, product_id: 1, serial_number: Some("0001"), release_number: 512, manufacturer_string: Some("Ledger"), product_string: Some("Nano S"), usage_page: 61904, usage: 1, interface_number: -1 }
2017-10-10 16:21:59  hw_wallet TRACE hardware_wallet::ledger  writing [0, 1, 1, 5, 0, 0, 0, 5, 224, 6, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]
2017-10-10 16:21:59  hw_wallet TRACE hardware_wallet::ledger  read [255, 255, 255, 255, 134, 0, 17, 68, 184, 253, 212, 208, 80, 61, 239, 121, 93, 51, 121, 2, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]
2017-10-10 16:21:59  hw_wallet DEBUG hardware_wallet::ledger  Error reading device info: Ledger protocol error: Unexpected chunk header
2017-10-10 16:21:59  hw_wallet TRACE hardware_wallet::ledger  Checking device: HidDeviceInfo { path: "\\\\?\\hid#vid_0d8c&pid_0014&mi_03#8&79f1e3e&0&0000#{4d1e55b2-f16f-11cf-88cb-001111000030}", vendor_id: 3468, product_id: 20, serial_number: None, release_number: 256, manufacturer_string: Some("C-Media Electronics Inc."), product_string: Some("USB Audio Device"), usage_page: 12, usage: 1, interface_number: 3 }
2017-10-10 16:21:59  hw_wallet TRACE hardware_wallet::ledger  Checking device: HidDeviceInfo { path: "\\\\?\\hid#vid_04d9&pid_a0cd&mi_02#7&26f5e066&0&0000#{4d1e55b2-f16f-11cf-88cb-001111000030}", vendor_id: 1241, product_id: 41165, serial_number: None, release_number: 261, manufacturer_string: None, product_string: Some("USB Keyboard"), usage_page: 65280, usage: 65280, interface_number: 2 }
2017-10-10 16:21:59  hyper-client INFO miner  Updated conversion rate to Ξ1 = US$302.80 (393155940 wei/gas)
Client service error: Client(Database("Error converting string"))`

**Comment by arkpar** [comment] 2017-10-10 14:53
@XelionIO Please also make sure ledger chrome app is not running.

**Comment by XelionIO** [comment] 2017-10-10 14:54
@arkpar No it doesn't run

**Comment by debris** [comment] 2018-03-20 03:15
@niklasad1 do you think we can close this issue?

**Comment by niklasad1** [comment] 2018-03-20 07:51
@debris I don't think so because [update_devices](https://github.com/paritytech/parity/blob/master/hw/src/ledger.rs#L120) haven't been changed so it will iterate through all devices and only add ledger devices to the list. That looks ok according to the trace but response looks strange but it is worth testing for sure!

My guesses are:
1. Ledger is in the wrong state or has some hardware/software issues
2. HidApi tries to write to the wrong device and gets unexpected header

**Comment by niklasad1** [comment] 2018-03-20 08:13
@XelionIO Hey, do you think you re-run this on [parity 1.9.4](https://github.com/paritytech/parity/releases/tag/v1.9.4) and provide the logs? 

If that doesn't work can you try plugging out all USB devices except `Ledger` and provide the logs? 

Thanks

**Comment by XelionIO** [comment] 2018-03-20 12:49
@niklasad1 I've moved to Arch linux in the meantime and my Ledger is working great with parity now, even tough i have the issue #7786 too.

**Comment by niklasad1** [comment] 2018-03-26 14:46
I'm closing this because the responses are not even on the same channel and I can't reproduce this.

**Closed by niklasad1** 2018-03-26 14:46 UTC
Labels: F2-bug, M4-core, P5-sometimesoon
