### ISSUE TITLE
DB corrupted

### ISSUE THREAD

**Issue by SJablonska** [paritytech/parity#7851] opened 2018-02-09 23:22 UTC
_Before filing a new issue, please **provide the following information**._

> I'm running:
>
> - **Which Parity version?**: 1.9.2
> - **Which operating system?**: Linux (Debian Stretch)
> - **How installed?**: binaries
> - **Are you fully synchronized?**: no (stopped at #5048532)
> - **Which network are you connected to?**: ethereum
> - **Did you try to restart the node?**: yes

DB corrupted: Corruption: block checksum mismatch: expected 2046883650, got 2199761626  in /media/veracrypt2/cryptos/parity/chains/ethereum/db/906a34e69aec8c0d/overlayrecent/db/099975.sst offset 63011146 size 13755. Repair will be triggered on next restart

====================

stack backtrace:
   0:     0x55fd674c928c - <no info>

Thread 'main' panicked at 'failed to update version: Error(Msg("Corruption: block checksum mismatch: expected 2046883650, got 2199761626  in /media/veracrypt2/cryptos/parity/chains/ethereum/db/906a34e69aec8c0d/overlayrecent/db/099975.sst offset 63011146 size 13755"), State { next_error: None, backtrace: None })', /checkout/src/libcore/result.rs:906

**Comment by 5chdn** [comment] 2018-02-12 13:46
Duplicate of #7334

**Comment by 5chdn** [comment] 2018-02-12 13:47
#7766 sorry

**Closed by 5chdn** 2018-02-12 13:46 UTC
