### ISSUE TITLE
Panic at unix/time.rs

### ISSUE THREAD

**Issue by Pzixel** [paritytech/parity#9061] opened 2018-07-06 15:03 UTC
> I'm running:
>
> - **Which Parity version?**: 1.10.6
> - **Which operating system?**: Linux
> - **How installed?**: docker
> - **Are you fully synchronized?**: yes
> - **Which network are you connected to?**: ethereum
> - **Did you try to restart the node?**: no

At some moment node just died. I'm not sure if it's reproducable, but before he died he asked me to create an issue with logs:

```
2018-07-06 11:25:51 UTC Verifier #1 INFO import  Imported #223831 7fa9…a413 (17 txs, 16.80 Mgas, 5359.10 ms, 26.89 KiB)
2018-07-06 11:25:51 UTC IO Worker #1 DEBUG txqueue  Imported transaction to current: 3e8af498ce116ed9e1d12ef103336aaf41328a18b79355c651473167af534551
2018-07-06 11:25:51 UTC IO Worker #1 DEBUG txqueue  status: TransactionQueueStatus { pending: 952, future: 0 }
2018-07-06 11:25:51 UTC IO Worker #1 DEBUG txqueue  Imported transaction to current: f73d3e49372244ded080cea835a0cc7ddef8e1f55b7fa75f944ce3af6e8dbd79
2018-07-06 11:25:51 UTC IO Worker #1 DEBUG txqueue  status: TransactionQueueStatus { pending: 953, future: 0 }
2018-07-06 11:25:51 UTC IO Worker #1 DEBUG txqueue  Imported transaction to current: dae0e9c4c49e85cbd63e2b49358ea199f98a598c618159e91b1bcb767aefaf18
2018-07-06 11:25:51 UTC IO Worker #1 DEBUG txqueue  status: TransactionQueueStatus { pending: 954, future: 0 }
2018-07-06 11:25:51 UTC IO Worker #1 DEBUG txqueue  Imported transaction to current: 3f07c84f6eed07475bef4db23e7af54c4743e5839c87faf8989691d8d714140f
2018-07-06 11:25:51 UTC IO Worker #1 DEBUG txqueue  status: TransactionQueueStatus { pending: 955, future: 0 }
2018-07-06 11:25:54 UTC IO Worker #3 DEBUG txqueue  Imported transaction to current: da2dd2f0807384a60fc31447c3e84d8b9f300e222b5fe62da343fcb46867f794
2018-07-06 11:25:54 UTC IO Worker #3 DEBUG txqueue  status: TransactionQueueStatus { pending: 956, future: 0 }
2018-07-06 11:25:54 UTC IO Worker #3 DEBUG txqueue  Imported transaction to current: 873b0f86e3e1fcafd1faad380277a8d9c48f78c3c224c45d65ece5ee25e2de3c
2018-07-06 11:25:54 UTC IO Worker #3 DEBUG txqueue  status: TransactionQueueStatus { pending: 957, future: 0 }
2018-07-06 11:25:54 UTC IO Worker #3 DEBUG txqueue  Imported transaction to current: 8153cabaea264abd33a5cd711b43a1f182b2ab67eb7b095329eba731c5c3a101
2018-07-06 11:25:54 UTC IO Worker #3 DEBUG txqueue  status: TransactionQueueStatus { pending: 958, future: 0 }
2018-07-06 11:26:05 UTC IO Worker #0 DEBUG txqueue  Imported transaction to current: 68efdcbf1940f060dad6d9d747ddf365651bd6bb5156e4e55cd5c357299f647c
2018-07-06 11:26:06 UTC IO Worker #0 DEBUG txqueue  status: TransactionQueueStatus { pending: 959, future: 0 }                                                                                                                                
2018-07-06 11:26:09 UTC IO Worker #1 INFO import     5/25 peers      6 MiB chain  103 MiB db  0 bytes queue  202 KiB sync  RPC:  0 conn,  0 req/s, 47480 µs                                                                                   
2018-07-06 11:27:03 UTC IO Worker #2 INFO import     5/25 peers      6 MiB chain  103 MiB db  0 bytes queue  202 KiB sync  RPC:  0 conn,  0 req/s, 47480 µs                                                                                   
2018-07-06 11:27:03 UTC IO Worker #1 INFO import     5/25 peers      6 MiB chain  103 MiB db  0 bytes queue  202 KiB sync  RPC:  0 conn,  0 req/s, 47480 µs                                                                                   
2018-07-06 11:27:04 UTC IO Worker #3 INFO import     5/25 peers      6 MiB chain  103 MiB db  0 bytes queue  202 KiB sync  RPC:  0 conn,  0 req/s, 47480 µs                                                                                   
2018-07-06 11:27:04 UTC IO Worker #0 INFO import     5/25 peers      6 MiB chain  103 MiB db  0 bytes queue  202 KiB sync  RPC:  0 conn,  0 req/s, 47480 µs                                                                                   
2018-07-06 11:27:36 UTC IO Worker #1 INFO import     4/25 peers      6 MiB chain  103 MiB db  0 bytes queue  202 KiB sync  RPC:  0 conn,  0 req/s, 47480 µs                                                                                   

====================

stack backtrace:
   0:     0x56173ce30e0c - <no info>
   1:     0x56173ce2f5f2 - <no info>
   2:     0x56173c46d2ca - <no info>

Thread '<unnamed>' panicked at 'other was less than the current instant', libstd/sys/unix/time.rs:292

This is a bug. Please report it at:

    https://github.com/paritytech/parity/issues/new
```

**Comment by Tbaut** [comment] 2018-07-09 11:11
Thanks for the report. It's a duplicate of https://github.com/paritytech/parity/issues/8444

**Closed by Tbaut** 2018-07-09 11:11 UTC
