### ISSUE TITLE
Change eth_sign to expect the user to prepend the message, not Parity.

### ISSUE THREAD

**Issue by MicahZoltu** [paritytech/parity#5431] opened 2017-04-07 22:42 UTC
Since https://github.com/paritytech/parity/issues/4459 was "fixed", Parity has begun prepending the message passed to `eth_sign` with `\x19Ethereum Signed Message:\n`.  This leads to incredibly confusing behavior for the developer since the expectation is that when one callse `eth_sign(address, message)` Parity will sign `message` with the private key associated with `address`.  However, this is _not_ the behavior that actually occurs.

I recognize that this was added as a security feature to prevent dApps from getting valid transactions signed by Parity, but I think this is the wrong solution to the problem from a developer ergonomics perspective.  Instead, `eth_sign` should expect `message` to already have the magic string prependended to it.  If the magic string was not prepended, then `eth_sign` should return an error to the user clearly stating that they must prepend the `eth_sign` request with the magic string.  With this change, the system is still secure against dApps signing transactions, but it also makes it very clear to the developer (and future readers of that code) what exactly is being signed.

I just spent quite a bit of time troubleshooting why the signature I was getting back from Parity wasn't the signature I expected, only to find out that it is because Parity was not signing the message I sent it, it was signing a _different_ message.

If this issue is rejected for whatever reason, then the [documentation](https://github.com/paritytech/parity/wiki/JSONRPC-eth-module#eth_sign) should be updated to be _really_ clear about what is happening here.

On a side note, I would like to better understand the actual risks that `eth_sign` presents.  It seems that if a dApp wants a transaction signed, it can just call `eth_signTransaction`.  It is unclear to me how making `eth_sign` sign an enveloped message is really solving anything?

**Comment by tomusdrw** [comment] 2017-04-10 07:42
The reason the message is prepended is to protect your private key from [chosen-plaintext attack](https://en.wikipedia.org/wiki/Chosen-plaintext_attack).
As you noticed signing arbitrary transactions can be achieved via `eth_signTransaction`.

Documentation needs to be updated for sure, the behaviour of the message not containing the prepended text was implemented to keep it compatible with geth.

**Comment by MicahZoltu** [comment] 2017-04-10 16:41
I'm guessing since this is designed to be geth compatible there is no hope in getting it changed?

Is there some other method that can be used that will allow me to use Parity to sign a message (without a prefix)?

It seems like this attack vector only applies to unlocked accounts, and if you are running an untrusted dApp with an unlocked account they can already steal everything from you so allowing for arbitrary signing isn't really increasing attack surface area meaningfully.

Out of curiosity: are there any known chosen-plaintext attacks against ECDSA, or is it a theoretical attack (not yet discovered but not provably impossible).

**Comment by rphmeier** [comment] 2017-04-10 16:46
@MicahZoltu I think something close was was added in #5423

**Comment by MicahZoltu** [comment] 2017-04-10 16:53
Hmm, not quite what I was looking for.  In particular, I would never give my passphrase to an untrusted dApp, but with Parity's signer I would not hesitate to let a dApp submit whatever signing requests it wanted (because I have to manually approve each).  Also, I would want to be able to sign any arbitrary byte array.  It is unclear if that call supports that (it says "hashed message").  I suspect it does but the documentation is unclear.

**Comment by fumecow** [comment] 2017-04-21 18:19
Parity is also returning the signature in (v,r,s) order instead of (r,s,v).  I made a diagram illustrating the differences with the way eth_sign works currently for the three clients we typically use:

![signature generation validation](https://cloud.githubusercontent.com/assets/27297969/25290819/c62aed94-268c-11e7-96d4-5c30bcebf51d.png)

**Comment by MicahZoltu** [comment] 2017-04-21 18:29
@fumecow That is probably worth of its own issue.  That is a pretty significant compatibility difference between Geth/Parity.

**Comment by fumecow** [comment] 2017-04-21 18:29
I will create a new issue then.  Thanks...

**Comment by 5chdn** [comment] 2017-05-10 11:59
This issue is labelled with _annoyance_: The client behaves within expectations, however this "expected behaviour" itself is at issue. It's neither assigned nor linked to any milestone.

@paritytech/core-devs Please decide on a deadline and add an assignee within 7 days, thanks!

**Comment by 5chdn** [comment] 2017-05-15 10:45
Related: #5490

**Comment by debris** [comment] 2018-05-19 06:06
Closing, cause this behaviour has been 'standarized' and is the same in both parity and get.

**Closed by debris** 2018-05-19 06:06 UTC
Labels: F3-annoyance, F5-documentation, M6-rpcapi, P7-nicetohave
