### ISSUE TITLE
Allow community editing of wiki

### ISSUE THREAD

**Issue by HaleTom** [paritytech/parity#6603] opened 2017-09-28 15:05 UTC
I would like to update the page:

https://github.com/paritytech/parity/wiki/FAQ:-Backup,-Restore,-and-Files

To say to stop parity before removing the database.

Could the wiki be community editable?

What about using https://readthedocs.org/ ?

**Comment by 5chdn** [comment] 2017-09-28 19:03
Duplicate of #6585

**Comment by 5chdn** [comment] 2017-09-28 19:03
Working on something. Stay tuned.

**Closed by 5chdn** 2017-09-28 19:03 UTC
Labels: Z0-duplicate

**Comment by HaleTom** [comment] 2017-09-29 05:46
@5chdn Sorry, my workflow on this sucked to not catch that issue already raised!!

Thanks!

**Comment by 5chdn** [comment] 2017-09-29 09:31
Meanwhile just write here what you want to add to the wiki, I can pass this through.

**Comment by HaleTom** [comment] 2017-11-04 15:58
The change would be to add:

`Stop parity, then`

before the text `[E]xecute parity db kill.`

**Comment by 5chdn** [comment] 2017-11-04 17:03
Updated, thanks
