### ISSUE TITLE
PIP: use persistent peer IDs to avoid request credit cheating

### ISSUE THREAD

**Issue by rphmeier** [paritytech/parity#3744] opened 2016-12-08 13:37 UTC

**Comment by rphmeier** [comment] 2016-12-12 15:21
Actually this might be considered as a protocol-level bug: current buffer amount should be broadcasted optionally with the handshake (None -> assume maximum) so that peers who accidentally disconnect and reconnect won't be confused when their requests are denied.

**Comment by rphmeier** [comment] 2016-12-19 17:13
Can be coupled with a "registration" system to discourage changing of network key, but this is something for further on.

**Comment by 5chdn** [comment] 2017-05-10 10:25
This issue is labelled with _annoyance_: The client behaves within expectations, however this "expected behaviour" itself is at issue. It's inactive since last year, neither assigned nor linked to any milestone.

@paritytech/core-devs Please, decide within 7 days on a deadline and add an assignee or close it otherwise. Thanks.

**Comment by rphmeier** [comment] 2017-05-10 10:27
Hard to say what the deadline will be since it depends how far into light client avenues we explore. This enhancement will only be useful upon integrating micropayments into the light client protocol.

**Comment by 5chdn** [comment] 2017-05-10 10:33
Ok, if this is rather an enhancement, I'm fine with tracking and prioritizing it in the _light client_ project dashboard. Thanks :)

**Comment by 5chdn** [comment] 2018-02-12 10:40
Is this relevant for PIP?

**Comment by rphmeier** [comment] 2018-02-12 15:12
yes, still is

**Comment by folsen** [comment] 2018-05-19 05:50
Closing this because while it's still relevant, it's probably not something we will work on in the next 6-12 months. Getting light clients used is step 1 which is still pretty far off, then finding some incentive structure that makes sense is step 2, and as part of that this would be relevant. It should be considered at the right time when we're working on step 2.

**Closed by folsen** 2018-05-19 05:50 UTC
Labels: F8-enhancement, M4-core, P7-nicetohave
