### ISSUE TITLE
Feature Request: evm_increaseTime for --chain dev

### ISSUE THREAD

**Issue by simon-jentzsch** [paritytech/parity#6282] opened 2017-08-11 06:43 UTC
We are using the `parity --chain dev`for testing our code, which works very well. But there are a lot of tests, where the contract depend on time. Here we would need a way to manually jump forward in time by increaseing the current blocktime. testrpc implemented this with `evm_increaseTime` . It would be great, if parity (only in dev-mode) would allow this as well.

**Comment by travs** [comment] 2017-09-18 09:35
@5chdn 
is this a duplicate of #5022 ?

**Comment by 5chdn** [comment] 2017-09-18 09:37
Yes, thanks.

**Closed by 5chdn** 2017-09-18 09:37 UTC
Labels: F8-enhancement, M6-rpcapi, P7-nicetohave
