### ISSUE TITLE
Crash on fresh sync

### ISSUE THREAD

**Issue by emocanu** [paritytech/parity#8110] opened 2018-03-13 19:51 UTC
_Before filing a new issue, please **provide the following information**._

> I'm running:
>
> - **Which Parity version?**: v1.9.4-beta-6f21a32b2-20180228
> - **Which operating system?**: Windows
> - **How installed?**: via binaries
> - **Are you fully synchronized?**: no
> - **Which network are you connected to?**: ethereum
> - **Did you try to restart the node?**: no

_Your issue description goes here below. Try to include **actual** vs. **expected behavior** and **steps to reproduce** the issue._

I expect parity to sync the Ethereum blockchain without crashing.
Here is the command line and the output (parity194.exe is the renamed parity.exe):

> parity194 -d c:\parity_data\base\ --db-path c:\parity_data\db_chains\
2018-03-13 16:07:30  Starting Parity/v1.9.4-beta-6f21a32b2-20180228/x86_64-windows-msvc/rustc1.24.0
2018-03-13 16:07:30  Keys path c:\parity_data\base\\keys\Foundation
2018-03-13 16:07:30  DB path c:\parity_data\db_chains\ethereum\db\906a34e69aec8c0d
2018-03-13 16:07:30  Path to dapps c:\parity_data\base\\dapps
2018-03-13 16:07:30  State DB configuration: fast
2018-03-13 16:07:30  Operating mode: active
2018-03-13 16:07:31  Configured for Foundation using Ethash engine
2018-03-13 16:07:31  Multi-threaded server is not available on Windows. Falling back to single thread.
2018-03-13 16:07:31  Multi-threaded server is not available on Windows. Falling back to single thread.
2018-03-13 16:07:31  Updated conversion rate to Ξ1 = US$687.94 (173049420 wei/gas)
2018-03-13 16:07:37  Public node URL: enode://6e2cf42736d8b54224ee16625ffcd77ccebe9f327475d1bd2e381cf670aee5aa1f569c90ed4957b4412b8a97affbf2f458928b830ed0acf72a86f52bdb80484d@127.0.0.1:30303
2018-03-13 16:07:41  Syncing snapshot 0/1078        #0    1/25 peers      8 KiB chain    3 MiB db  0 bytes queue   10 KiB sync  RPC:  0 conn,  0 req/s,   0 µs
2018-03-13 16:07:51  Syncing snapshot 2/1078        #0    1/25 peers      8 KiB chain    3 MiB db  0 bytes queue   10 KiB sync  RPC:  0 conn,  0 req/s,   0 µs
2018-03-13 16:08:00  Blocked connection from http://home.web3.site:8180 using invalid token.
2018-03-13 16:08:01  Syncing snapshot 3/1078        #0    1/25 peers      8 KiB chain    3 MiB db  0 bytes queue   10 KiB sync  RPC:  1 conn, 36 req/s,  86 µs
2018-03-13 16:08:11  Syncing snapshot 6/1078        #0    1/25 peers      8 KiB chain    3 MiB db  0 bytes queue   10 KiB sync  RPC:  1 conn,  1 req/s,  84 µs
2018-03-13 16:08:21  Syncing snapshot 8/1078        #0    2/25 peers      8 KiB chain    3 MiB db  0 bytes queue   10 KiB sync  RPC:  1 conn,  1 req/s,  84 µs
2018-03-13 16:08:31  Syncing snapshot 13/1078        #0    4/25 peers      8 KiB chain    3 MiB db  0 bytes queue   10 KiB sync  RPC:  1 conn,  2 req/s,  95 µs
2018-03-13 16:08:41  Syncing snapshot 18/1078        #0    4/25 peers      8 KiB chain    3 MiB db  0 bytes queue   10 KiB sync  RPC:  1 conn,  1 req/s,  77 µs
2018-03-13 16:08:51  Syncing snapshot 22/1078        #0    4/25 peers      8 KiB chain    3 MiB db  0 bytes queue   10 KiB sync  RPC:  0 conn,  0 req/s,  82 µs
2018-03-13 16:09:01  Syncing snapshot 26/1078        #0    4/25 peers      8 KiB chain    3 MiB db  0 bytes queue   10 KiB sync  RPC:  0 conn,  0 req/s,  82 µs
2018-03-13 16:09:11  Syncing snapshot 28/1078        #0    4/25 peers      8 KiB chain    3 MiB db  0 bytes queue   10 KiB sync  RPC:  0 conn,  0 req/s,  82 µs
2018-03-13 16:09:21  Syncing snapshot 35/1078        #0    5/25 peers      8 KiB chain    3 MiB db  0 bytes queue   10 KiB sync  RPC:  0 conn,  0 req/s,  82 µs
2018-03-13 16:09:31  Syncing snapshot 41/1078        #0    5/25 peers      8 KiB chain    3 MiB db  0 bytes queue   10 KiB sync  RPC:  0 conn,  0 req/s,  82 µs
2018-03-13 16:09:41  Syncing snapshot 44/1078        #0    5/25 peers      8 KiB chain    3 MiB db  0 bytes queue   10 KiB sync  RPC:  0 conn,  0 req/s,  82 µs
2018-03-13 16:09:51  Syncing snapshot 49/1078        #0    8/25 peers      8 KiB chain    3 MiB db  0 bytes queue   10 KiB sync  RPC:  0 conn,  0 req/s,  82 µs
2018-03-13 16:10:01  Syncing snapshot 51/1078        #0    8/25 peers      8 KiB chain    3 MiB db  0 bytes queue   10 KiB sync  RPC:  0 conn,  0 req/s,  82 µs
2018-03-13 16:10:11  Syncing snapshot 53/1078        #0    9/25 peers      8 KiB chain    3 MiB db  0 bytes queue   10 KiB sync  RPC:  0 conn,  0 req/s,  82 µs
2018-03-13 16:10:21  Syncing snapshot 55/1078        #0    9/25 peers      8 KiB chain    3 MiB db  0 bytes queue   10 KiB sync  RPC:  0 conn,  0 req/s,  82 µs
2018-03-13 16:10:31  Syncing snapshot 59/1078        #0   10/25 peers      8 KiB chain    3 MiB db  0 bytes queue   10 KiB sync  RPC:  0 conn,  0 req/s,  82 µs
2018-03-13 16:10:41  Syncing snapshot 65/1078        #0    9/25 peers      8 KiB chain    3 MiB db  0 bytes queue   10 KiB sync  RPC:  0 conn,  0 req/s,  82 µs
2018-03-13 16:10:51  Syncing snapshot 67/1078        #0   12/25 peers      8 KiB chain    3 MiB db  0 bytes queue   10 KiB sync  RPC:  0 conn,  0 req/s,  82 µs
2018-03-13 16:11:01  Syncing snapshot 69/1078        #0   12/25 peers      8 KiB chain    3 MiB db  0 bytes queue   10 KiB sync  RPC:  0 conn,  0 req/s,  82 µs
2018-03-13 16:11:11  Syncing snapshot 70/1078        #0   13/25 peers      8 KiB chain    3 MiB db  0 bytes queue   10 KiB sync  RPC:  0 conn,  0 req/s,  82 µs
2018-03-13 16:11:21  Syncing snapshot 76/1078        #0   13/25 peers      8 KiB chain    3 MiB db  0 bytes queue   10 KiB sync  RPC:  0 conn,  0 req/s,  82 µs
2018-03-13 16:11:31  Syncing snapshot 82/1078        #0   13/25 peers      8 KiB chain    3 MiB db  0 bytes queue   10 KiB sync  RPC:  0 conn,  0 req/s,  82 µs
2018-03-13 16:11:36  Syncing snapshot 84/1078        #0   14/25 peers      8 KiB chain    3 MiB db  0 bytes queue   10 KiB sync  RPC:  0 conn,  0 req/s,  82 µs
2018-03-13 16:11:41  Syncing snapshot 85/1078        #0   14/25 peers      8 KiB chain    3 MiB db  0 bytes queue   10 KiB sync  RPC:  0 conn,  0 req/s,  82 µs
2018-03-13 16:11:46  Syncing snapshot 86/1078        #0   15/25 peers      8 KiB chain    3 MiB db  0 bytes queue   10 KiB sync  RPC:  0 conn,  0 req/s,  82 µs
2018-03-13 16:11:51  Syncing snapshot 88/1078        #0   15/25 peers      8 KiB chain    3 MiB db  0 bytes queue   10 KiB sync  RPC:  0 conn,  0 req/s,  82 µs
2018-03-13 16:11:56  Syncing snapshot 90/1078        #0   15/25 peers      8 KiB chain    3 MiB db  0 bytes queue   10 KiB sync  RPC:  0 conn,  0 req/s,  82 µs
2018-03-13 16:12:01  Syncing snapshot 94/1078        #0   16/25 peers      8 KiB chain    3 MiB db  0 bytes queue   10 KiB sync  RPC:  0 conn,  0 req/s,  82 µs
2018-03-13 16:12:06  Syncing snapshot 98/1078        #0   16/25 peers      8 KiB chain    3 MiB db  0 bytes queue   10 KiB sync  RPC:  0 conn,  0 req/s,  82 µs
2018-03-13 16:12:11  Syncing snapshot 98/1078        #0   16/25 peers      8 KiB chain    3 MiB db  0 bytes queue   10 KiB sync  RPC:  0 conn,  0 req/s,  82 µs
2018-03-13 16:12:21  Syncing snapshot 103/1078        #0   16/25 peers      8 KiB chain    3 MiB db  0 bytes queue   10 KiB sync  RPC:  0 conn,  0 req/s,  82 µs
2018-03-13 16:12:26  Syncing snapshot 107/1078        #0   16/25 peers      8 KiB chain    3 MiB db  0 bytes queue   10 KiB sync  RPC:  0 conn,  0 req/s,  82 µs
2018-03-13 16:12:31  Syncing snapshot 107/1078        #0   16/25 peers      8 KiB chain    3 MiB db  0 bytes queue   10 KiB sync  RPC:  0 conn,  0 req/s,  82 µs
2018-03-13 16:12:36  Syncing snapshot 109/1078        #0   16/25 peers      8 KiB chain    3 MiB db  0 bytes queue   10 KiB sync  RPC:  0 conn,  0 req/s,  82 µs
2018-03-13 16:12:41  Syncing snapshot 112/1078        #0   17/25 peers      8 KiB chain    3 MiB db  0 bytes queue   10 KiB sync  RPC:  0 conn,  0 req/s,  82 µs
2018-03-13 16:12:46  Syncing snapshot 115/1078        #0   17/25 peers      8 KiB chain    3 MiB db  0 bytes queue   10 KiB sync  RPC:  0 conn,  0 req/s,  82 µs
2018-03-13 16:12:51  Syncing snapshot 120/1078        #0   18/25 peers      8 KiB chain    3 MiB db  0 bytes queue   10 KiB sync  RPC:  0 conn,  0 req/s,  82 µs
2018-03-13 16:12:56  Syncing snapshot 122/1078        #0   18/25 peers      8 KiB chain    3 MiB db  0 bytes queue   10 KiB sync  RPC:  0 conn,  0 req/s,  82 µs
2018-03-13 16:13:01  Syncing snapshot 126/1078        #0   19/25 peers      8 KiB chain    3 MiB db  0 bytes queue   10 KiB sync  RPC:  0 conn,  0 req/s,  82 µs
2018-03-13 16:13:06  Syncing snapshot 129/1078        #0   18/25 peers      8 KiB chain    3 MiB db  0 bytes queue   10 KiB sync  RPC:  0 conn,  0 req/s,  82 µs
2018-03-13 16:13:16  Syncing snapshot 133/1078        #0   18/25 peers      8 KiB chain    3 MiB db  0 bytes queue   10 KiB sync  RPC:  0 conn,  0 req/s,  82 µs
2018-03-13 16:13:21  Syncing snapshot 135/1078        #0   19/25 peers      8 KiB chain    3 MiB db  0 bytes queue   10 KiB sync  RPC:  0 conn,  0 req/s,  82 µs
2018-03-13 16:13:26  Syncing snapshot 136/1078        #0   19/25 peers      8 KiB chain    3 MiB db  0 bytes queue   10 KiB sync  RPC:  0 conn,  0 req/s,  82 µs
2018-03-13 16:13:31  Syncing snapshot 137/1078        #0   19/25 peers      8 KiB chain    3 MiB db  0 bytes queue   10 KiB sync  RPC:  0 conn,  0 req/s,  82 µs
2018-03-13 16:13:36  Syncing snapshot 139/1078        #0   20/25 peers      8 KiB chain    3 MiB db  0 bytes queue   10 KiB sync  RPC:  0 conn,  0 req/s,  82 µs
2018-03-13 16:13:41  Syncing snapshot 142/1078        #0   20/25 peers      8 KiB chain    3 MiB db  0 bytes queue   10 KiB sync  RPC:  0 conn,  0 req/s,  82 µs
2018-03-13 16:13:46  Syncing snapshot 145/1078        #0   21/25 peers      8 KiB chain    3 MiB db  0 bytes queue   10 KiB sync  RPC:  0 conn,  0 req/s,  82 µs
2018-03-13 16:13:51  Syncing snapshot 148/1078        #0   21/25 peers      8 KiB chain    3 MiB db  0 bytes queue   10 KiB sync  RPC:  0 conn,  0 req/s,  82 µs
2018-03-13 16:13:56  Syncing snapshot 150/1078        #0   21/25 peers      8 KiB chain    3 MiB db  0 bytes queue   10 KiB sync  RPC:  0 conn,  0 req/s,  82 µs
2018-03-13 16:14:01  Syncing snapshot 152/1078        #0   21/25 peers      8 KiB chain    3 MiB db  0 bytes queue   10 KiB sync  RPC:  0 conn,  0 req/s,  82 µs
2018-03-13 16:14:06  Syncing snapshot 156/1078        #0   21/25 peers      8 KiB chain    3 MiB db  0 bytes queue   10 KiB sync  RPC:  0 conn,  0 req/s,  82 µs
2018-03-13 16:14:11  Syncing snapshot 156/1078        #0   21/25 peers      8 KiB chain    3 MiB db  0 bytes queue   10 KiB sync  RPC:  0 conn,  0 req/s,  82 µs
2018-03-13 16:14:21  Syncing snapshot 159/1078        #0   21/25 peers      8 KiB chain    3 MiB db  0 bytes queue   10 KiB sync  RPC:  0 conn,  0 req/s,  82 µs
2018-03-13 16:14:26  Syncing snapshot 162/1078        #0   21/25 peers      8 KiB chain    3 MiB db  0 bytes queue   10 KiB sync  RPC:  0 conn,  0 req/s,  82 µs
2018-03-13 16:14:31  Syncing snapshot 164/1078        #0   21/25 peers      8 KiB chain    3 MiB db  0 bytes queue   10 KiB sync  RPC:  0 conn,  0 req/s,  82 µs
2018-03-13 16:14:36  Syncing snapshot 167/1078        #0   21/25 peers      8 KiB chain    3 MiB db  0 bytes queue   10 KiB sync  RPC:  0 conn,  0 req/s,  82 µs
2018-03-13 16:14:41  Syncing snapshot 170/1078        #0   21/25 peers      8 KiB chain    3 MiB db  0 bytes queue   10 KiB sync  RPC:  0 conn,  0 req/s,  82 µs
2018-03-13 16:14:46  Syncing snapshot 174/1078        #0   22/25 peers      8 KiB chain    3 MiB db  0 bytes queue   10 KiB sync  RPC:  0 conn,  0 req/s,  82 µs
2018-03-13 16:14:51  Syncing snapshot 176/1078        #0   22/25 peers      8 KiB chain    3 MiB db  0 bytes queue   10 KiB sync  RPC:  0 conn,  0 req/s,  82 µs
2018-03-13 16:14:56  Syncing snapshot 177/1078        #0   22/25 peers      8 KiB chain    3 MiB db  0 bytes queue   10 KiB sync  RPC:  0 conn,  0 req/s,  82 µs
2018-03-13 16:15:01  Syncing snapshot 180/1078        #0   22/25 peers      8 KiB chain    3 MiB db  0 bytes queue   10 KiB sync  RPC:  0 conn,  0 req/s,  82 µs
2018-03-13 16:15:05  DB corrupted: Corruption: block checksum mismatch: expected 2180620424, got 1761345003  in c:\parity_data\db_chains\ethereum\db\906a34e69aec8c0d\snapshot\restoration\db/000799.sst offset 21306324 size 3449. Repair will be triggered on next restart
2018-03-13 16:15:05  Encountered error during state restoration: Corruption: block checksum mismatch: expected 2180620424, got 1761345003  in c:\parity_data\db_chains\ethereum\db\906a34e69aec8c0d\snapshot\restoration\db/000799.sst offset 21306324 size 3449
2018-03-13 16:15:05  DB corrupted: Corruption: block checksum mismatch: expected 2180620424, got 1761345003  in c:\parity_data\db_chains\ethereum\db\906a34e69aec8c0d\snapshot\restoration\db/000799.sst offset 21306324 size 3449. Repair will be triggered on next restart
2018-03-13 16:15:06  Syncing       #0 d4e5…8fa3     0 blk/s    0 tx/s   0 Mgas/s      0+    0 Qed        #0   22/25 peers      8 KiB chain    3 MiB db  0 bytes queue   10 KiB sync  RPC:  0 conn,  0 req/s,  82 µs
2018-03-13 16:15:16  Syncing     #508 ef8a…1a72    51 blk/s    0 tx/s   0 Mgas/s      0+    0 Qed      #508   21/25 peers    520 KiB chain    8 MiB db  0 bytes queue   30 MiB sync  RPC:  0 conn,  0 req/s,  82 µs
2018-03-13 16:15:26  Syncing    #1778 7000…9c21   126 blk/s    0 tx/s   0 Mgas/s      0+    0 Qed     #1778   17/25 peers      2 MiB chain   11 MiB db  0 bytes queue   31 MiB sync  RPC:  0 conn,  0 req/s,  82 µs
2018-03-13 16:15:32  Syncing    #1975 a27b…c20e    38 blk/s    0 tx/s   0 Mgas/s  26933+ 2555 Qed    #34417   19/25 peers      2 MiB chain   12 MiB db   44 MiB queue   12 MiB sync  RPC:  0 conn,  0 req/s,  82 µs
2018-03-13 16:15:42  Syncing    #2771 3a18…419d    80 blk/s    0 tx/s   0 Mgas/s  19716+11920 Qed    #34417   21/25 peers      3 MiB chain   14 MiB db   47 MiB queue   12 MiB sync  RPC:  0 conn,  0 req/s,  82 µs
2018-03-13 16:15:47  Syncing    #3211 645c…e8d1    86 blk/s    0 tx/s   0 Mgas/s  14500+16695 Qed    #34417   22/25 peers      3 MiB chain   20 MiB db   47 MiB queue   12 MiB sync  RPC:  0 conn,  0 req/s,  82 µs
2018-03-13 16:15:52  Syncing    #3623 9707…4843    81 blk/s    0 tx/s   0 Mgas/s   9402+21369 Qed    #34417   22/25 peers      3 MiB chain   21 MiB db   46 MiB queue   12 MiB sync  RPC:  0 conn,  0 req/s,  82 µs
2018-03-13 16:16:02  Syncing   #15899 18d1…669c  1237 blk/s    0 tx/s   0 Mgas/s   3562+15417 Qed    #34925   19/25 peers      7 MiB chain   63 MiB db   28 MiB queue   19 MiB sync  RPC:  0 conn,  0 req/s,  82 µs
2018-03-13 16:16:12  Syncing   #35179 2b4c…aecb  1952 blk/s    0 tx/s   0 Mgas/s      0+    0 Qed    #35179   21/25 peers    0 bytes chain   69 MiB db  0 bytes queue   32 MiB sync  RPC:  0 conn,  0 req/s,  82 µs
2018-03-13 16:16:22  Syncing   #35696 1ae4…11fc    52 blk/s    0 tx/s   0 Mgas/s  28230+ 4893 Qed    #68843   21/25 peers    321 KiB chain   69 MiB db   51 MiB queue   12 MiB sync  RPC:  0 conn,  0 req/s,  82 µs
2018-03-13 16:16:27  Syncing   #36132 ce0c…887b    86 blk/s    0 tx/s   0 Mgas/s  23119+ 9578 Qed    #68843   23/25 peers    614 KiB chain   69 MiB db   51 MiB queue   12 MiB sync  RPC:  0 conn,  0 req/s,  82 µs
2018-03-13 16:16:32  Syncing   #36596 76b1…78e1    92 blk/s    0 tx/s   0 Mgas/s  17070+15155 Qed    #68843   23/25 peers    720 KiB chain   69 MiB db   53 MiB queue   12 MiB sync  RPC:  0 conn,  0 req/s,  82 µs
2018-03-13 16:16:37  Syncing   #37092 3b0a…084a    98 blk/s    0 tx/s   0 Mgas/s  10511+21219 Qed    #68843   23/25 peers      1 MiB chain   69 MiB db   55 MiB queue   12 MiB sync  RPC:  0 conn,  0 req/s,  82 µs
2018-03-13 16:16:47  Syncing   #47386 2308…e859  1029 blk/s   53 tx/s   1 Mgas/s      0+21459 Qed    #68843   23/25 peers      7 MiB chain   69 MiB db   43 MiB queue   12 MiB sync  RPC:  0 conn,  0 req/s,  82 µs
2018-03-13 16:16:57  Syncing   #55592 543e…95a6   816 blk/s  416 tx/s  40 Mgas/s   2524+22257 Qed    #80391   22/25 peers      6 MiB chain   67 MiB db   49 MiB queue   15 MiB sync  RPC:  0 conn,  0 req/s,  82 µs
2018-03-13 16:17:02  Syncing   #62801 f144…774b  1441 blk/s  383 tx/s  11 Mgas/s      0+17587 Qed    #80391   23/25 peers    0 bytes chain   68 MiB db   37 MiB queue   15 MiB sync  RPC:  0 conn,  0 req/s,  82 µs
2018-03-13 16:17:12  Syncing   #79158 de13…2b2a  1644 blk/s  981 tx/s  32 Mgas/s      0+ 3014 Qed    #82170   23/25 peers      6 MiB chain   68 MiB db    6 MiB queue   26 MiB sync  RPC:  0 conn,  0 req/s,  82 µs
2018-03-13 16:17:22  Syncing   #85536 0a6a…6425   633 blk/s  402 tx/s  10 Mgas/s  16235+ 3443 Qed   #105236   20/25 peers      4 MiB chain   68 MiB db   32 MiB queue   13 MiB sync  RPC:  0 conn,  0 req/s,  82 µs
2018-03-13 16:17:27  Syncing   #89908 1031…b781   871 blk/s  434 tx/s  11 Mgas/s  15776+ 3916 Qed   #109620   19/25 peers      5 MiB chain   68 MiB db   32 MiB queue   12 MiB sync  RPC:  0 conn,  0 req/s,  82 µs
2018-03-13 16:17:32  Syncing   #90426 b929…ead2   104 blk/s   34 tx/s   0 Mgas/s  11480+ 9738 Qed   #111665   20/25 peers      6 MiB chain   68 MiB db   37 MiB queue   14 MiB sync  RPC:  0 conn,  0 req/s,  82 µs
2018-03-13 16:17:38  Syncing   #90938 abd4…61be   102 blk/s   27 tx/s   0 Mgas/s   5642+15646 Qed   #117128   22/25 peers      6 MiB chain   68 MiB db   40 MiB queue   14 MiB sync  RPC:  0 conn,  0 req/s,  82 µs
2018-03-13 16:17:48  Syncing   #99332 ef07…d67c   881 blk/s  355 tx/s   9 Mgas/s      0+17798 Qed   #117128   22/25 peers      5 MiB chain   69 MiB db   36 MiB queue   15 MiB sync  RPC:  0 conn,  0 req/s,  82 µs
2018-03-13 16:17:53  Syncing  #107194 28c3…8a8a  1566 blk/s  821 tx/s  21 Mgas/s   4794+13112 Qed   #125122   23/25 peers      5 MiB chain   69 MiB db   35 MiB queue   14 MiB sync  RPC:  0 conn,  0 req/s,  82 µs
2018-03-13 16:18:03  Syncing  #116050 00e3…5c0b   891 blk/s  512 tx/s  14 Mgas/s      0+10971 Qed   #127021   23/25 peers      6 MiB chain   69 MiB db   23 MiB queue   20 MiB sync  RPC:  0 conn,  0 req/s,  82 µs
2018-03-13 16:18:13  Syncing  #127221 1274…f683  1125 blk/s  845 tx/s  22 Mgas/s   6727+ 1431 Qed   #135403   23/25 peers      2 MiB chain   69 MiB db   14 MiB queue   18 MiB sync  RPC:  0 conn,  0 req/s,  82 µs
2018-03-13 16:18:23  Syncing  #128204 7fac…9637    97 blk/s   17 tx/s   0 Mgas/s   6369+13381 Qed   #147976   19/25 peers      2 MiB chain   69 MiB db   40 MiB queue   12 MiB sync  RPC:  0 conn,  0 req/s,  82 µs
2018-03-13 16:18:28  Syncing  #128684 5e5a…31a7    95 blk/s  190 tx/s   4 Mgas/s      0+19287 Qed   #147976   21/25 peers      2 MiB chain   69 MiB db   43 MiB queue   12 MiB sync  RPC:  0 conn,  0 req/s,  82 µs
2018-03-13 16:18:38  Syncing  #139246 47ab…b8a1  1050 blk/s  793 tx/s  20 Mgas/s    347+13957 Qed   #153564   22/25 peers      3 MiB chain   69 MiB db   33 MiB queue   16 MiB sync  RPC:  0 conn,  0 req/s,  82 µs
2018-03-13 16:18:42  DB corrupted: Corruption: block checksum mismatch: expected 1770441022, got 3688434136  in c:\parity_data\db_chains\ethereum\db\906a34e69aec8c0d\overlayrecent\db/002168.sst offset 5411316 size 7274. Repair will be triggered on next restart
2018-03-13 16:18:42  DB corrupted: Corruption: block checksum mismatch: expected 1770441022, got 3688434136  in c:\parity_data\db_chains\ethereum\db\906a34e69aec8c0d\overlayrecent\db/002168.sst offset 5411316 size 7274. Repair will be triggered on next restart
2018-03-13 16:18:42  DB corrupted: Corruption: block checksum mismatch: expected 1770441022, got 3688434136  in c:\parity_data\db_chains\ethereum\db\906a34e69aec8c0d\overlayrecent\db/002168.sst offset 5411316 size 7274. Repair will be triggered on next restart
2018-03-13 16:18:42  DB corrupted: Corruption: block checksum mismatch: expected 1770441022, got 3688434136  in c:\parity_data\db_chains\ethereum\db\906a34e69aec8c0d\overlayrecent\db/002168.sst offset 5411316 size 7274. Repair will be triggered on next restart

====================

stack backtrace:
   0:        0x1403a4b03 - hid_error
   1:        0x1403a42e3 - hid_error
   2:        0x13fa94b4d - <no info>
   3:        0x1403c6214 - hid_error
   4:        0x1403c6071 - hid_error
   5:        0x1403c5f52 - hid_error
   6:        0x1403c5eca - hid_error
   7:        0x1403ddb8d - hid_error
   8:        0x13fd4e089 - <no info>
   9:        0x13fd1acd9 - <no info>
  10:        0x13fd981ef - <no info>
  11:        0x13fe74404 - <no info>
  12:        0x13fe74caa - <no info>
  13:        0x1403daad2 - hid_error
  14:        0x13fe50b41 - <no info>
  15:        0x1403c876c - hid_error
  16:        0x1403b0597 - hid_error
  17:         0x770b59cd - BaseThreadInitThunk

Thread 'IO Worker #0' panicked at 'DB flush failed.: Error(Msg("Corruption: block checksum mismatch: expected 1770441022, got 3688434136  in c:\\parity_data\\db_chains\\ethereum\\db\\906a34e69aec8c0d\\overlayrecent\\db/002168.sst offset 5411316 size 7274"), State { next_error: None, backtrace: None })', src\libcore\result.rs:916

This is a bug. Please report it at:

    https://github.com/paritytech/parity/issues/new

====================

stack backtrace:
   0:        0x1403a4b03 - hid_error
   1:        0x1403a42e3 - hid_error
   2:        0x13fa94b4d - <no info>
   3:        0x1403c6214 - hid_error
   4:        0x1403c6071 - hid_error
   5:        0x1403c5f52 - hid_error
   6:        0x1403c5eca - hid_error
   7:        0x1403ddb8d - hid_error
   8:        0x13fd4e089 - <no info>
   9:        0x13fd1acd9 - <no info>
  10:        0x13fd981ef - <no info>
  11:        0x13fe74404 - <no info>
  12:        0x13fe74caa - <no info>
  13:        0x1403daad2 - hid_error
  14:        0x13fe50b41 - <no info>
  15:        0x1403c876c - hid_error
  16:        0x1403b0597 - hid_error
  17:         0x770b59cd - BaseThreadInitThunk

Thread 'IO Worker #3' panicked at 'DB flush failed.: Error(Msg("Corruption: block checksum mismatch: expected 1770441022, got 3688434136  in c:\\parity_data\\db_chains\\ethereum\\db\\906a34e69aec8c0d\\overlayrecent\\db/002168.sst offset 5411316 size 7274"), State { next_error: None, backtrace: None })', src\libcore\result.rs:916

This is a bug. Please report it at:

    https://github.com/paritytech/parity/issues/new

====================

stack backtrace:
   0:        0x1403a4b03 - hid_error
   1:        0x1403a42e3 - hid_error
   2:        0x13fa94b4d - <no info>
   3:        0x1403c6214 - hid_error
   4:        0x1403c6071 - hid_error
   5:        0x1403c5f52 - hid_error
   6:        0x1403c5eca - hid_error
   7:        0x1403ddb8d - hid_error
   8:        0x13fd4e089 - <no info>
   9:        0x13fd1acd9 - <no info>
  10:        0x13fd981ef - <no info>
  11:        0x13fe74404 - <no info>
  12:        0x13fe74caa - <no info>
  13:        0x1403daad2 - hid_error
  14:        0x13fe50b41 - <no info>
  15:        0x1403c876c - hid_error
  16:        0x1403b0597 - hid_error
  17:         0x770b59cd - BaseThreadInitThunk

Thread 'IO Worker #2' panicked at 'DB flush failed.: Error(Msg("Corruption: block checksum mismatch: expected 1770441022, got 3688434136  in c:\\parity_data\\db_chains\\ethereum\\db\\906a34e69aec8c0d\\overlayrecent\\db/002168.sst offset 5411316 size 7274"), State { next_error: None, backtrace: None })', src\libcore\result.rs:916

This is a bug. Please report it at:

    https://github.com/paritytech/parity/issues/new

====================

stack backtrace:
   0:        0x1403a4b03 - hid_error
   1:        0x1403a42e3 - hid_error
   2:        0x13fa94b4d - <no info>
   3:        0x1403c6214 - hid_error
   4:        0x1403c6071 - hid_error
   5:        0x1403c5f52 - hid_error
   6:        0x1403c5eca - hid_error
   7:        0x1403ddb8d - hid_error
   8:        0x13fd4e089 - <no info>
   9:        0x13fd1acd9 - <no info>
  10:        0x13fd981ef - <no info>
  11:        0x13fe74404 - <no info>
  12:        0x13fe74caa - <no info>
  13:        0x1403daad2 - hid_error
  14:        0x13fe50b41 - <no info>
  15:        0x1403c876c - hid_error
  16:        0x1403b0597 - hid_error
  17:         0x770b59cd - BaseThreadInitThunk

Thread 'IO Worker #1' panicked at 'DB flush failed.: Error(Msg("Corruption: block checksum mismatch: expected 1770441022, got 3688434136  in c:\\parity_data\\db_chains\\ethereum\\db\\906a34e69aec8c0d\\overlayrecent\\db/002168.sst offset 5411316 size 7274"), State { next_error: None, backtrace: None })', src\libcore\result.rs:916

This is a bug. Please report it at:

    https://github.com/paritytech/parity/issues/new

**Comment by 5chdn** [comment] 2018-03-23 10:31
Duplicate of #7748

**Closed by 5chdn** 2018-03-23 10:31 UTC
