### ISSUE TITLE
Core dump when calling eth_sendRawTransaction over RPC

### ISSUE THREAD

**Issue by dukejones** [paritytech/parity#7747] opened 2018-01-30 22:55 UTC
Parity/v1.8.7-stable-e322fd8-20180124/x86_64-linux-gnu/rustc1.23.0
Ubuntu 16.04.3
Binary installation
synced
Ropsten
yes

parity --chain=ropsten --jsonrpc-interface all --jsonrpc-cors all --ui-interface all --ws-interface all --ws-origins all

```golang

	conn, err := rpc.Dial("ws://165.227.xxx.xxx:8546") // ip changed to protect the innocent
	if err != nil {
		log.Fatalf("Failed to connect to the Ethereum client: %v", err)
	}
	var result string
	if err := conn.Call(&result, "eth_sendRawTransaction", rlp); err != nil {
		log.Fatalf("Failed to call eth_sendRawTransaction: %v", err)
	}
	log.Println(result)
```

RLP ends up looking like: f8880384ee6b28008307a120940f54d1617ecb696e267db81a1956c2437325478580a4d3c9cc2600000000000000000000000000000000000000000000000000000000000003e829a0d2b12ac65b9a1f1ce061b6018439cf0c36a003b45b3c4eb398e2d43daacba3eea026bd4c3e91a71d72a4822ba1928ca9d46830c600fa40a36953ee99b1e658bdca

====================

stack backtrace:
   0:     0x558edea36e0c - <no info>

Thread '<unnamed>' panicked at 'byte index 2 is not a char boundary; it is inside '�' (bytes 0..3) of `����k(�� �T�a~�in&}�V�Cs%G������&�)�ұ*�[��a��9�
                                                                                                                                                      6��[<N����=�ˣ��&�L>��r��+�����h0��@�iS�X��`', /checkout/src/libcore/str/mod.rs:2235

**Comment by dukejones** [comment] 2018-01-30 22:57
Same thing with http://xxx:8545

**Comment by dukejones** [comment] 2018-01-30 22:58
RLP transaction works when manually posted to https://ropsten.etherscan.io/pushTx

**Comment by sorpaas** [comment] 2018-04-04 10:29
Are there more info on the raw transaction RLP posted? I tried v1.8.7 on Ropsten but cannot reproduce the bug.

```
$ http localhost:8545 jsonrpc=2.0 id=1 method=eth_sendRawTransaction params:='["0xf8880384ee6b28008307a120940f54d1617ecb696e267db81a1956c2437325478580a4d3c9cc2600000000000000000000000000000000000000000000000000000000000003e829a0d2b12ac65b9a1f1ce061b6018439cf0c36a003b45b3c4eb398e2d43daacba3eea026bd4c3e91a71d72a4822ba1928ca9d46830c600fa40a36953ee99b1e658bdca"]'
HTTP/1.1 200 OK
Content-Type: application/json
Date: Wed, 04 Apr 2018 10:25:44 GMT
Transfer-Encoding: chunked

{
    "error": {
        "code": -32010, 
        "message": "Invalid chain id."
    }, 
    "id": 1, 
    "jsonrpc": "2.0"
}
```

**Comment by folsen** [comment] 2018-05-21 03:08
Closing as unreproducible, please reopen if you can reproduce.

**Closed by folsen** 2018-05-21 03:08 UTC
Labels: F1-panic, M6-rpcapi, P5-sometimesoon
