### ISSUE TITLE
Registry dApp external links are broken.

### ISSUE THREAD

**Issue by MicahZoltu** [paritytech/parity#5377] opened 2017-04-02 18:44 UTC
When using the Registry dApp inside Parity UI, if you do a lookup and then click on the result it tries to send you to etherscan.io.  However, the link it results in is incorrect as it has two protocols (the second missing the `:`).

Example: Lookup `Zoltu` then click and it tries to take you to:
`https://https//etherscan.io/address/0x00730819b8b1f47022a9a40c6cc55b8014c4c2da`

**Comment by 5chdn** [comment] 2017-04-03 07:40
duplicate of #4941 and should be fixed in #4984 with 52c81fe4eeed111d5f6e1ce6debcafa2960f6e0d

which version are you using?

**Closed by 5chdn** 2017-04-03 07:40 UTC
Labels: F2-bug, M7-ui
