### ISSUE TITLE
Syncing #3714708 takes very long

### ISSUE THREAD

**Issue by ng0177** [paritytech/parity#7330] opened 2017-12-19 06:07 UTC
[th6mas@freckle ~]$ parity
2017-12-19 06:37:55  Starting Parity/v1.9.0-unstable-5cb53ddd8-20171218/x86_64-linux-gnu/rustc1.21.0
2017-12-19 06:37:55  Keys path /home/th6mas/.local/share/io.parity.ethereum/keys/Foundation
2017-12-19 06:37:55  DB path /home/th6mas/.local/share/io.parity.ethereum/chains/ethereum/db/906a34e69aec8c0d
2017-12-19 06:37:55  Path to dapps /home/th6mas/.local/share/io.parity.ethereum/dapps
2017-12-19 06:37:55  State DB configuration: fast
2017-12-19 06:37:55  Operating mode: active
2017-12-19 06:37:55  Configured for Foundation using Ethash engine
2017-12-19 06:37:56  Updated conversion rate to Ξ1 = US$819.31 (145302290 wei/gas)
2017-12-19 06:38:02  Public node URL: enode://a1e265e136bbe2b4abe2eb85e638c1a6bf88194adfb0588ecd4d0805e22b410b2d5e3a8364b3d06f5aef28af4536576eaf655f8880976391a409b660a73d7b90@192.168.0.10:30303
2017-12-19 06:38:07  Syncing #3708414 00e7…7e19     0 blk/s    3 tx/s   0 Mgas/s      3+   18 Qed  #3708447    2/25 peers   86 KiB chain 60 MiB db 436 KiB queue 354 KiB sync  RPC:  0 conn,  0 req/s,   0 µs
2017-12-19 06:38:17  Syncing #3709297 f3d5…53a5    88 blk/s 2266 tx/s  95 Mgas/s      0+  548 Qed  #3709847    3/25 peers   4 MiB chain 65 MiB db 12 MiB queue 849 KiB sync  RPC:  0 conn,  0 req/s,   0 µs
2017-12-19 06:38:27  Syncing #3710062 27e2…18a4    76 blk/s 1836 tx/s  88 Mgas/s      0+ 1860 Qed  #3711923    3/25 peers   7 MiB chain 69 MiB db 38 MiB queue 951 KiB sync  RPC:  0 conn,  0 req/s,   0 µs
2017-12-19 06:38:33  Syncing #3710505 c7fa…9d85    84 blk/s 2373 tx/s  99 Mgas/s      0+ 1970 Qed  #3712477    3/25 peers   7 MiB chain 70 MiB db 40 MiB queue 808 KiB sync  RPC:  0 conn,  0 req/s,   0 µs
2017-12-19 06:38:42  Syncing #3711462 ad2d…80d1    97 blk/s 2049 tx/s 104 Mgas/s      0+ 1395 Qed  #3712858    4/25 peers   7 MiB chain 73 MiB db 30 MiB queue 3 MiB sync  RPC:  0 conn,  0 req/s,   0 µs
2017-12-19 06:38:52  Syncing #3712167 627b…9a95    70 blk/s 1850 tx/s  93 Mgas/s      0+  687 Qed  #3712858    4/25 peers   7 MiB chain 75 MiB db 14 MiB queue 16 MiB sync  RPC:  0 conn,  0 req/s,   0 µs
2017-12-19 06:39:02  Syncing #3712858 bb95…f90e    69 blk/s 1376 tx/s  89 Mgas/s      0+    0 Qed  #3712858    4/25 peers   8 MiB chain 77 MiB db 0 bytes queue 30 MiB sync  RPC:  0 conn,  0 req/s,   0 µs
2017-12-19 06:39:08  Stage 2 block verification failed for cd67…67dd: Block(MismatchedH256SealElement(Mismatch { expected: 18ecdf3adfe716cca3d770926056534127b228dc24e9e9ae74c15861f402b260, found: 5d5dce57e26031c09ae8630d39739f34e91df7147282dd41258383798f6fb2c6 }))
2017-12-19 06:39:13  Syncing #3713369 aded…fe6d    49 blk/s  912 tx/s  65 Mgas/s   1900+ 1335 Qed  #3720986    5/25 peers   7 MiB chain 78 MiB db 46 MiB queue 4 MiB sync  RPC:  0 conn,  0 req/s,   0 µs
2017-12-19 06:39:22  Syncing #3714198 a857…174b    86 blk/s 2164 tx/s 103 Mgas/s      0+  507 Qed  #3713960    4/25 peers   7 MiB chain 77 MiB db 10 MiB queue 227 KiB sync  RPC:  0 conn,  0 req/s,   0 µs
2017-12-19 06:39:32  Syncing #3714708 1b5e…e012    51 blk/s 1233 tx/s  50 Mgas/s      0+    0 Qed  #3715943    6/25 peers   8 MiB chain 78 MiB db 0 bytes queue 5 MiB sync  RPC:  0 conn,  0 req/s,   0 µs
2017-12-19 06:39:42  Syncing #3714708 1b5e…e012     0 blk/s    0 tx/s   0 Mgas/s      0+    0 Qed  #3719156    6/25 peers   5 MiB chain 78 MiB db 0 bytes queue 5 MiB sync  RPC:  0 conn,  0 req/s,   0 µs
2017-12-19 06:39:52  Syncing #3714708 1b5e…e012     0 blk/s    0 tx/s   0 Mgas/s      0+    0 Qed  #3719998    2/25 peers   5 MiB chain 78 MiB db 0 bytes queue 6 MiB sync  RPC:  0 conn,  0 req/s,   0 µs
2017-12-19 06:40:22     1/25 peers   5 MiB chain 78 MiB db 0 bytes queue 1 MiB sync  RPC:  0 conn,  0 req/s,   0 µs
2017-12-19 06:40:32  Syncing #3714708 1b5e…e012     0 blk/s    0 tx/s   0 Mgas/s      0+    0 Qed  #3720987    1/25 peers   6 MiB chain 78 MiB db 0 bytes queue 1 MiB sync  RPC:  0 conn,  0 req/s,   0 µs
2017-12-19 06:40:42  Syncing #3714708 1b5e…e012     0 blk/s    0 tx/s   0 Mgas/s      0+    0 Qed  #3720984    1/25 peers   4 MiB chain 78 MiB db 0 bytes queue 1 MiB sync  RPC:  0 conn,  0 req/s,   0 µs
2017-12-19 06:41:07  Syncing #3714708 1b5e…e012     0 blk/s    0 tx/s   0 Mgas/s      0+    0 Qed  #3720982    1/25 peers   4 MiB chain 78 MiB db 0 bytes queue 1 MiB sync  RPC:  0 conn,  0 req/s,   0 µs
2017-12-19 06:41:17  Syncing #3714708 1b5e…e012     0 blk/s    0 tx/s   0 Mgas/s      0+    0 Qed  #3720979    2/25 peers   5 MiB chain 78 MiB db 0 bytes queue 1 MiB sync  RPC:  0 conn,  0 req/s,   0 µs
2017-12-19 06:41:27  Syncing #3714708 1b5e…e012     0 blk/s    0 tx/s   0 Mgas/s      0+    0 Qed  #3720979    2/25 peers   7 MiB chain 78 MiB db 0 bytes queue 1 MiB sync  RPC:  0 conn,  0 req/s,   0 µs
2017-12-19 06:41:37  Syncing #3714708 1b5e…e012     0 blk/s    0 tx/s   0 Mgas/s      0+    0 Qed  #3720979    2/25 peers   7 MiB chain 78 MiB db 0 bytes queue 1 MiB sync  RPC:  0 conn,  0 req/s,   0 µs
2017-12-19 06:42:07     3/25 peers   5 MiB chain 78 MiB db 0 bytes queue 1 MiB sync  RPC:  0 conn,  0 req/s,   0 µs
2017-12-19 06:42:38     1/25 peers   5 MiB chain 78 MiB db 0 bytes queue 1 MiB sync  RPC:  0 conn,  0 req/s,   0 µs
2017-12-19 06:42:48  Syncing #3714708 1b5e…e012     0 blk/s    0 tx/s   0 Mgas/s      0+    0 Qed  #3721090    2/25 peers   4 MiB chain 78 MiB db 0 bytes queue 1 MiB sync  RPC:  0 conn,  0 req/s,   0 µs
2017-12-19 06:42:58  Syncing #3714708 1b5e…e012     0 blk/s    0 tx/s   0 Mgas/s      0+    0 Qed  #3721090    2/25 peers   4 MiB chain 78 MiB db 0 bytes queue 1 MiB sync  RPC:  0 conn,  0 req/s,   0 µs
2017-12-19 06:43:23  Syncing #3714708 1b5e…e012     0 blk/s    0 tx/s   0 Mgas/s      0+    0 Qed  #3721090    4/25 peers   4 MiB chain 78 MiB db 0 bytes queue 1 MiB sync  RPC:  0 conn,  0 req/s,   0 µs
2017-12-19 06:43:53     1/25 peers   5 MiB chain 78 MiB db 0 bytes queue 1 MiB sync  RPC:  0 conn,  0 req/s,   0 µs
2017-12-19 06:44:23     1/25 peers   5 MiB chain 78 MiB db 0 bytes queue 1 MiB sync  RPC:  0 conn,  0 req/s,   0 µs
2017-12-19 06:44:53     1/25 peers   5 MiB chain 78 MiB db 0 bytes queue 1 MiB sync  RPC:  0 conn,  0 req/s,   0 µs
2017-12-19 06:45:13  Syncing #3714708 1b5e…e012     0 blk/s    0 tx/s   0 Mgas/s      0+    0 Qed  #3721090    1/25 peers   6 MiB chain 78 MiB db 0 bytes queue 1 MiB sync  RPC:  0 conn,  0 req/s,   0 µs
2017-12-19 06:45:43     2/25 peers   5 MiB chain 78 MiB db 0 bytes queue 1 MiB sync  RPC:  0 conn,  0 req/s,   0 µs
2017-12-19 06:46:13  Syncing #3714708 1b5e…e012     0 blk/s    0 tx/s   0 Mgas/s      0+    0 Qed  #3721090    4/25 peers   5 MiB chain 78 MiB db 0 bytes queue 1 MiB sync  RPC:  0 conn,  0 req/s,   0 µs
2017-12-19 06:46:43     2/25 peers   5 MiB chain 78 MiB db 0 bytes queue 1 MiB sync  RPC:  0 conn,  0 req/s,   0 µs
2017-12-19 06:47:08  Syncing #3714708 1b5e…e012     0 blk/s    0 tx/s   0 Mgas/s      0+    0 Qed  #3721090    3/25 peers   5 MiB chain 78 MiB db 0 bytes queue 1 MiB sync  RPC:  0 conn,  0 req/s,   0 µs
2017-12-19 06:47:18  Syncing #3714708 1b5e…e012     0 blk/s    0 tx/s   0 Mgas/s      0+    0 Qed  #3721090    3/25 peers   5 MiB chain 78 MiB db 0 bytes queue 1 MiB sync  RPC:  0 conn,  0 req/s,   0 µs
2017-12-19 06:47:43  Syncing #3714708 1b5e…e012     0 blk/s    0 tx/s   0 Mgas/s      0+    0 Qed  #3721090    3/25 peers   5 MiB chain 78 MiB db 0 bytes queue 1 MiB sync  RPC:  0 conn,  0 req/s,   0 µs
2017-12-19 06:47:53  Syncing #3714708 1b5e…e012     0 blk/s    0 tx/s   0 Mgas/s      0+    0 Qed  #3721090    3/25 peers   6 MiB chain 78 MiB db 0 bytes queue 1 MiB sync  RPC:  0 conn,  0 req/s,   0 µs
2017-12-19 06:48:03  Syncing #3714708 1b5e…e012     0 blk/s    0 tx/s   0 Mgas/s      0+    0 Qed  #3721090    3/25 peers   6 MiB chain 78 MiB db 0 bytes queue 1 MiB sync  RPC:  0 conn,  0 req/s,   0 µs
2017-12-19 06:48:13  Syncing #3714708 1b5e…e012     0 blk/s    0 tx/s   0 Mgas/s      0+    0 Qed  #3721090    3/25 peers   6 MiB chain 78 MiB db 0 bytes queue 1 MiB sync  RPC:  0 conn,  0 req/s,   0 µs
2017-12-19 06:48:23  Syncing #3714708 1b5e…e012     0 blk/s    0 tx/s   0 Mgas/s      0+    0 Qed  #3721090    4/25 peers   6 MiB chain 78 MiB db 0 bytes queue 1 MiB sync  RPC:  0 conn,  0 req/s,   0 µs
2017-12-19 06:48:53     2/25 peers   6 MiB chain 78 MiB db 0 bytes queue 1 MiB sync  RPC:  0 conn,  0 req/s,   0 µs
2017-12-19 06:49:28     3/25 peers   5 MiB chain 78 MiB db 0 bytes queue 1 MiB sync  RPC:  0 conn,  0 req/s,   0 µs
2017-12-19 06:50:03     3/25 peers   5 MiB chain 78 MiB db 0 bytes queue 1 MiB sync  RPC:  0 conn,  0 req/s,   0 µs
2017-12-19 06:50:23  Syncing #3714708 1b5e…e012     0 blk/s    0 tx/s   0 Mgas/s      0+    0 Qed  #3721090    5/25 peers   5 MiB chain 78 MiB db 0 bytes queue 1 MiB sync  RPC:  0 conn,  0 req/s,   0 µs
2017-12-19 06:50:53     4/25 peers   5 MiB chain 78 MiB db 0 bytes queue 1 MiB sync  RPC:  0 conn,  0 req/s,   0 µs
2017-12-19 06:51:23     4/25 peers   5 MiB chain 78 MiB db 0 bytes queue 1 MiB sync  RPC:  0 conn,  0 req/s,   0 µs
2017-12-19 06:51:53     4/25 peers   5 MiB chain 78 MiB db 0 bytes queue 1 MiB sync  RPC:  0 conn,  0 req/s,   0 µs
2017-12-19 06:52:28     4/25 peers   6 MiB chain 78 MiB db 0 bytes queue 1 MiB sync  RPC:  0 conn,  0 req/s,   0 µs
2017-12-19 06:53:03     3/25 peers   6 MiB chain 78 MiB db 0 bytes queue 1 MiB sync  RPC:  0 conn,  0 req/s,   0 µs
2017-12-19 06:53:18  Syncing #3714708 1b5e…e012     0 blk/s    0 tx/s   0 Mgas/s      0+    0 Qed  #3721090    4/25 peers   6 MiB chain 78 MiB db 0 bytes queue 1 MiB sync  RPC:  0 conn,  0 req/s,   0 µs
2017-12-19 06:53:43  Syncing #3714708 1b5e…e012     0 blk/s    0 tx/s   0 Mgas/s      0+    0 Qed  #3721090    5/25 peers   7 MiB chain 78 MiB db 0 bytes queue 1 MiB sync  RPC:  0 conn,  0 req/s,   0 µs
2017-12-19 06:53:53  Syncing #3714708 1b5e…e012     0 blk/s    0 tx/s   0 Mgas/s      0+    0 Qed  #3721090    5/25 peers   7 MiB chain 78 MiB db 0 bytes queue 1 MiB sync  RPC:  0 conn,  0 req/s,   0 µs
2017-12-19 06:54:03  Syncing #3714708 1b5e…e012     0 blk/s    0 tx/s   0 Mgas/s      0+    0 Qed  #3721090    6/25 peers   6 MiB chain 78 MiB db 0 bytes queue 1 MiB sync  RPC:  0 conn,  0 req/s,   0 µs
2017-12-19 06:54:13  Syncing #3714708 1b5e…e012     0 blk/s    0 tx/s   0 Mgas/s      0+    0 Qed  #3721090    4/25 peers   6 MiB chain 78 MiB db 0 bytes queue 1 MiB sync  RPC:  0 conn,  0 req/s,   0 µs
2017-12-19 06:54:23  Syncing #3714708 1b5e…e012     0 blk/s    0 tx/s   0 Mgas/s      0+    0 Qed  #3721090    4/25 peers   6 MiB chain 78 MiB db 0 bytes queue 1 MiB sync  RPC:  0 conn,  0 req/s,   0 µs
2017-12-19 06:54:33  Syncing #3714708 1b5e…e012     0 blk/s    0 tx/s   0 Mgas/s      0+    0 Qed  #3721090    4/25 peers   6 MiB chain 78 MiB db 0 bytes queue 1 MiB sync  RPC:  0 conn,  0 req/s,   0 µs
2017-12-19 06:54:43  Syncing #3714708 1b5e…e012     0 blk/s    0 tx/s   0 Mgas/s      0+    0 Qed  #3721090    5/25 peers   6 MiB chain 78 MiB db 0 bytes queue 1 MiB sync  RPC:  0 conn,  0 req/s,   0 µs
2017-12-19 06:54:53  Syncing #3714708 1b5e…e012     0 blk/s    0 tx/s   0 Mgas/s      0+    0 Qed  #3721090    5/25 peers   5 MiB chain 78 MiB db 0 bytes queue 1 MiB sync  RPC:  0 conn,  0 req/s,   0 µs
2017-12-19 06:55:08  Syncing #3714708 1b5e…e012     0 blk/s    0 tx/s   0 Mgas/s      0+    0 Qed  #3721090    6/25 peers   5 MiB chain 78 MiB db 0 bytes queue 1 MiB sync  RPC:  0 conn,  0 req/s,   0 µs
2017-12-19 06:55:18  Syncing #3714708 1b5e…e012     0 blk/s    0 tx/s   0 Mgas/s      0+    0 Qed  #3721090    6/25 peers   5 MiB chain 78 MiB db 0 bytes queue 1 MiB sync  RPC:  0 conn,  0 req/s,   0 µs
2017-12-19 06:55:28  Syncing #3714708 1b5e…e012     0 blk/s    0 tx/s   0 Mgas/s      0+    0 Qed  #3721090    5/25 peers   6 MiB chain 78 MiB db 0 bytes queue 1 MiB sync  RPC:  0 conn,  0 req/s,   0 µs
2017-12-19 06:55:58     5/25 peers   6 MiB chain 78 MiB db 0 bytes queue 1 MiB sync  RPC:  0 conn,  0 req/s,   0 µs
2017-12-19 06:56:07  Syncing #3714708 1b5e…e012     0 blk/s    0 tx/s   0 Mgas/s      0+    0 Qed  #3721090    6/25 peers   6 MiB chain 78 MiB db 0 bytes queue 1 MiB sync  RPC:  0 conn,  0 req/s,   0 µs
2017-12-19 06:56:18  Syncing #3714708 1b5e…e012     0 blk/s    0 tx/s   0 Mgas/s      0+    0 Qed  #3721090    6/25 peers   6 MiB chain 78 MiB db 0 bytes queue 1 MiB sync  RPC:  0 conn,  0 req/s,   0 µs
2017-12-19 06:56:28  Syncing #3714708 1b5e…e012     0 blk/s    0 tx/s   0 Mgas/s      0+    0 Qed  #3721090    6/25 peers   6 MiB chain 78 MiB db 0 bytes queue 1 MiB sync  RPC:  0 conn,  0 req/s,   0 µs
2017-12-19 06:56:58     4/25 peers   6 MiB chain 78 MiB db 0 bytes queue 1 MiB sync  RPC:  0 conn,  0 req/s,   0 µs
2017-12-19 06:57:33     6/25 peers   5 MiB chain 78 MiB db 0 bytes queue 1 MiB sync  RPC:  0 conn,  0 req/s,   0 µs
2017-12-19 06:58:08     6/25 peers   5 MiB chain 78 MiB db 0 bytes queue 1 MiB sync  RPC:  0 conn,  0 req/s,   0 µs
2017-12-19 06:58:18  Syncing #3714708 1b5e…e012     0 blk/s    0 tx/s   0 Mgas/s      0+    0 Qed  #3721090    8/25 peers   6 MiB chain 78 MiB db 0 bytes queue 1 MiB sync  RPC:  0 conn,  0 req/s,   0 µs
2017-12-19 06:58:28  Syncing #3714708 1b5e…e012     0 blk/s    0 tx/s   0 Mgas/s      0+    0 Qed  #3721090    8/25 peers   6 MiB chain 78 MiB db 0 bytes queue 1 MiB sync  RPC:  0 conn,  0 req/s,   0 µs
2017-12-19 06:58:53  Syncing #3714708 1b5e…e012     0 blk/s    0 tx/s   0 Mgas/s      0+    0 Qed  #3721090    7/25 peers   6 MiB chain 78 MiB db 0 bytes queue 1 MiB sync  RPC:  0 conn,  0 req/s,   0 µs
2017-12-19 06:59:03  Syncing #3714708 1b5e…e012     0 blk/s    0 tx/s   0 Mgas/s      0+    0 Qed  #3721090    8/25 peers   6 MiB chain 78 MiB db 0 bytes queue 1 MiB sync  RPC:  0 conn,  0 req/s,   0 µs
2017-12-19 06:59:28  Syncing #3714708 1b5e…e012     0 blk/s    0 tx/s   0 Mgas/s      0+    0 Qed  #3721090    4/25 peers   5 MiB chain 78 MiB db 0 bytes queue 1 MiB sync  RPC:  0 conn,  0 req/s,   0 µs
2017-12-19 06:59:38  Syncing #3714708 1b5e…e012     0 blk/s    0 tx/s   0 Mgas/s      0+    0 Qed  #3721090    6/25 peers   7 MiB chain 78 MiB db 0 bytes queue 1 MiB sync  RPC:  0 conn,  0 req/s,   0 µs
2017-12-19 07:00:03  Syncing #3714708 1b5e…e012     0 blk/s    0 tx/s   0 Mgas/s      0+    0 Qed  #3721090    6/25 peers   5 MiB chain 78 MiB db 0 bytes queue 1 MiB sync  RPC:  0 conn,  0 req/s,   0 µs
2017-12-19 07:00:13  Syncing #3714708 1b5e…e012     0 blk/s    0 tx/s   0 Mgas/s      0+    0 Qed  #3721090    6/25 peers   6 MiB chain 78 MiB db 0 bytes queue 1 MiB sync  RPC:  0 conn,  0 req/s,   0 µs
2017-12-19 07:00:23  Syncing #3714708 1b5e…e012     0 blk/s    0 tx/s   0 Mgas/s      0+    0 Qed  #3721090    6/25 peers   6 MiB chain 78 MiB db 0 bytes queue 1 MiB sync  RPC:  0 conn,  0 req/s,   0 µs
2017-12-19 07:00:53     8/25 peers   6 MiB chain 78 MiB db 0 bytes queue 1 MiB sync  RPC:  0 conn,  0 req/s,   0 µs
2017-12-19 07:01:28  Syncing #3714708 1b5e…e012     0 blk/s    0 tx/s   0 Mgas/s      0+    0 Qed  #3721090    6/25 peers   6 MiB chain 78 MiB db 0 bytes queue 1 MiB sync  RPC:  0 conn,  0 req/s,   0 µs
2017-12-19 07:01:43  Syncing #3714708 1b5e…e012     0 blk/s    0 tx/s   0 Mgas/s      0+    0 Qed  #3721090    5/25 peers   6 MiB chain 78 MiB db 0 bytes queue 1 MiB sync  RPC:  0 conn,  0 req/s,   0 µs
2017-12-19 07:02:03  Syncing #3714708 1b5e…e012     0 blk/s    0 tx/s   0 Mgas/s      0+    0 Qed  #3721090    7/25 peers   7 MiB chain 78 MiB db 0 bytes queue 1 MiB sync  RPC:  0 conn,  0 req/s,   0 µs
2017-12-19 07:02:13  Syncing #3714708 1b5e…e012     0 blk/s    0 tx/s   0 Mgas/s      0+    0 Qed  #3721090    7/25 peers   6 MiB chain 78 MiB db 0 bytes queue 11 MiB sync  RPC:  0 conn,  0 req/s,   0 µs
2017-12-19 07:02:32  Syncing #3714708 1b5e…e012     0 blk/s    0 tx/s   0 Mgas/s      0+    0 Qed  #3721090    5/25 peers   6 MiB chain 78 MiB db 0 bytes queue 18 MiB sync  RPC:  0 conn,  0 req/s,   0 µs
2017-12-19 07:03:03     5/25 peers   7 MiB chain 78 MiB db 0 bytes queue 18 MiB sync  RPC:  0 conn,  0 req/s,   0 µs
2017-12-19 07:03:18  Syncing #3714708 1b5e…e012     0 blk/s    0 tx/s   0 Mgas/s      0+    0 Qed  #3721090    5/25 peers   6 MiB chain 78 MiB db 0 bytes queue 18 MiB sync  RPC:  0 conn,  0 req/s,   0 µs
2017-12-19 07:03:28  Syncing #3714708 1b5e…e012     0 blk/s    0 tx/s   0 Mgas/s      0+    0 Qed  #3721090    7/25 peers   4 MiB chain 78 MiB db 0 bytes queue 18 MiB sync  RPC:  0 conn,  0 req/s,   0 µs
2017-12-19 07:03:38  Syncing #3714708 1b5e…e012     0 blk/s    0 tx/s   0 Mgas/s      0+    0 Qed  #3721090    6/25 peers   5 MiB chain 78 MiB db 0 bytes queue 20 MiB sync  RPC:  0 conn,  0 req/s,   0 µs
2017-12-19 07:04:08     4/25 peers   6 MiB chain 78 MiB db 0 bytes queue 18 MiB sync  RPC:  0 conn,  0 req/s,   0 µs
2017-12-19 07:04:38     5/25 peers   5 MiB chain 78 MiB db 0 bytes queue 18 MiB sync  RPC:  0 conn,  0 req/s,   0 µs
2017-12-19 07:05:08     4/25 peers   6 MiB chain 78 MiB db 0 bytes queue 18 MiB sync  RPC:  0 conn,  0 req/s,   0 µs
2017-12-19 07:05:18  Syncing #3714708 1b5e…e012     0 blk/s    0 tx/s   0 Mgas/s      0+    0 Qed  #3721090    5/25 peers   6 MiB chain 78 MiB db 0 bytes queue 18 MiB sync  RPC:  0 conn,  0 req/s,   0 µs
2017-12-19 07:05:48     4/25 peers   6 MiB chain 78 MiB db 0 bytes queue 18 MiB sync  RPC:  0 conn,  0 req/s,   0 µs
2017-12-19 07:06:18     5/25 peers   6 MiB chain 78 MiB db 0 bytes queue 18 MiB sync  RPC:  0 conn,  0 req/s,   0 µs
2017-12-19 07:06:43  Syncing #3714708 1b5e…e012     0 blk/s    0 tx/s   0 Mgas/s      0+    0 Qed  #3721090    6/25 peers   6 MiB chain 78 MiB db 0 bytes queue 18 MiB sync  RPC:  0 conn,  0 req/s,   0 µs
2017-12-19 07:06:53  Syncing #3714708 1b5e…e012     0 blk/s    0 tx/s   0 Mgas/s      0+    0 Qed  #3721090    6/25 peers   6 MiB chain 78 MiB db 0 bytes queue 18 MiB sync  RPC:  0 conn,  0 req/s,   0 µs

I use Fedora 27 and 

[th6mas@freckle ~]$ parity --version
Parity
  version Parity/v1.9.0-unstable-5cb53ddd8-20171218/x86_64-linux-gnu/rustc1.21.0
Copyright 2015, 2016, 2017 Parity Technologies (UK) Ltd
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>.
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.

By Wood/Paronyan/Kotewicz/Drwięga/Volf
   Habermeier/Czaban/Greeff/Gotchac/Redmann

**Comment by 5chdn** [comment] 2018-01-02 14:32
Are you on SSD or HDD?

**Comment by ng0177** [comment] 2018-01-02 15:26
on SSD. Thanks.

**Comment by 5chdn** [comment] 2018-01-02 15:38
Duplicate of #6372 

You could try to remove your `nodes.json` and increase the number of `--snapshot-peers` to trigger a warp-sync.

**Closed by 5chdn** 2018-01-02 15:38 UTC
Labels: M4-core, Z0-question
