### ISSUE TITLE
Error installing 1.7.2 with one-line installer on Ubuntu 17.04

### ISSUE THREAD

**Issue by sandakersmann** [paritytech/parity#6547] opened 2017-09-18 23:07 UTC
Hi. I'm trying to install Parity 1.7.2 with one-line installer on Ubuntu 17.04. 
I'm currently running 1.7.0. I get this in the terminal:

`~$ bash <(curl https://get.parity.io -Lk)    `

`  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current    `

`                                 Dload  Upload   Total   Spent    Left  Speed    `

`100   170    0   170    0     0    491      0 --:--:-- --:--:-- --:--:--   492    `

`100  2990  100  2990    0     0   4578      0 --:--:-- --:--:-- --:--:--  4578    `

`Release selected is: beta    `

`  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current    `

`                                 Dload  Upload   Total   Spent    Left  Speed    `

`  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0    `

`basename: missing operand    `

`Try 'basename --help' for more information.    `

`Existing version of parity: 1.7.0 is newer than the version you attempting to install: `

**Comment by drobsarma** [comment] 2017-09-19 00:33
Similar Issue on 16.04 freshly installed

**Comment by ddorgan** [comment] 2017-09-19 01:56
Can you please retry now.

**Comment by AyushyaChitransh** [comment] 2017-09-19 04:25
I am on 16.04

    ~$ bash <(curl https://get.parity.io -Lk)

It works and I was able to upgrade to `version Parity/v1.7.2-beta-9f47909-20170918/x86_64-linux-gnu/rustc1.19.0`

**Comment by 5chdn** [comment] 2017-09-19 07:46
Duplicate of #6548

**Closed by 5chdn** 2017-09-19 07:46 UTC
Labels: M1-ci, M2-installer, P2-asap, Z0-duplicate

**Comment by sandakersmann** [comment] 2017-09-19 17:15
Yes, works now :)
